### ISSUE TITLE
Jenkins build server: Update Openfire to latest 3.10.2 build

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1001]

**Comment by ACueva** [comment]
@elinz I believe you already did this?

**Comment by ACueva** [comment]
Reassigning back to myself to:

- [ ] Update 3rd party installation folder with latest installer
- [ ] Update installation guide if necessary

**Comment by elinz** [comment]
@ACueva I've updated the installation guide to reflect new install dialogs. Same content; different look. At a future release I may just delete these screenshots so they aren't version dependent. I will close this issue.
