### ISSUE TITLE
Nuclear Santa Cruz .csv file needs copyright permissions for the images 

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1006]
The Nuclear Santa Cruz .csv contains list of locations of nuclear facilities and a network path to annotated "images" of these locations.  We should have a filled out G-141 for the location data, even if it is made up data. We should also have copyright information for all the images.

It looks like they are actually screenshots of some imagery that we may or may not own. If they are just screenshots from imagery we own, we still need to have a G-141 for each image, saying we own proper permissions on that data.

csv file in question is found here
https://nsec.esri.com/arcgis/home/item.html?id=235473b232be4414b27ecaaf08fe3e4d
photos are currently stored here
\\nsec\SolutionsWeb\Resources\Photos\PlacesOfInterest
g-141 can be found here
https://esri.app.box.com/files/0/f/3453468100/1/f_28927966718

 we can work together to get this figured out if you have any questions, i assigned to you @MaryClawson because i was under the impression that you created this csv

**Comment by karlterrey** [comment]
I will check on this with legal. 
No G-141 should be needed though for fictitious data in a cvs file that Esri made up. It just needs to be clearly noted as fictitious data for demonstration purposes.

**Comment by dfoll** [comment]
@karlterrey ... thanks for paying attention to this... how about the other issue, are there any shortcuts we can utilize about the photos... i believe (but need to confirm) that they are just screenshots from imagery we already own

**Comment by karlterrey** [comment]
That's what I am checking with legal.

**Comment by karlterrey** [comment]
@dfoll That's what I am checking with legal.

**Comment by dfoll** [comment]
@karlterrey cool, thanks... guess i misread your first comment

**Comment by karlterrey** [comment]
@dfoll No need for a G-141 for the csv. The photographs do need source citation and if necessary permissions. I am not sure who obtained the Getty image in there but we need to know if we can use it, where we got it from, when etc. Most of the photos are imagery images. We need those sources noted, i.e. what imagery is it. Need to make sure it is clearly noted as fictitious data, especially any image annotations.

**Comment by karlterrey** [comment]
@dfoll No need for a G-141 for the csv. The photographs do need source citation and if necessary permissions. I am not sure who obtained the Getty image in there but we need to know if we can use it, where we got it from, when etc. Most of the photos are imagery images. We need those sources noted, i.e. what imagery is it. Need to make sure it is clearly noted as fictitious data, especially any image annotations.

**Comment by csmoore** [comment]
When @HeatherEisan (and Carolyn before her) did this for the solutions icon images, she created some [very thorough attribution docs](https://github.com/Esri/solutions-symbology-data/tree/master/documentation) - I'm not sure if this is how you want to do or standardize on this - but wanted to make sure you were aware of that approach. 

Note: For images you get off of Flickr you usually see a variant of Creative Commons license. For images Getty freely shares, they have their own "Open Content" language which seems to be Getty's own particular way of sharing images ["without restrictions"](http://www.getty.edu/about/opencontentfaq.html)

**Comment by MaryClawson** [comment]
The imagery used in for the annotated imagery graphics was screen captured from the ArcGIS Online Imagery Basemap.  Annotation was added using PowerPoint.  All of the annotations related to potential nuclear facilities are all fictions.  All are annotated with a disclaimer that they are for Demonstration Only and that Annotations are notional.  A read-me file has been added to \\nsec\SolutionsWeb\Resources\Photos\PlacesOfInterest
