### ISSUE TITLE
Natural Color Landsat not available from portal

### ISSUE THREAD

**Issue by MaryClawson** [Esri/ops-server-config#1008]
Natural Color Landsat is listed as service in [dev server], however, I am not able to add it to a map-- error message occurs.

**Comment by elinz** [comment]
@MaryClawson This is a browser specific issue related to a problem with the SSL public key on the online server. If you use another browser such as IE, this service can be added to your web map.

**Comment by elinz** [comment]
@MaryClawson I have reported this issue to the imagery/raster dev team so they can redirect the issue to the appropriate ArcGIS Online support team.

**Comment by MaryClawson** [comment]
@elinz  Thanks, it opens when I use IE, but not Chrome.

**Comment by jrweakland** [comment]
@MaryClawson - Please close this issue if appropriate.

**Comment by conklinbd** [comment]
This issue does not seem to be something we need to address for the Ops Server release.
Changing the milestone to after next.

**Comment by elinz** [comment]
Tested 15 December 2015; I can add the online true color/natural color imagery service in web map using Chrome: https://imagery.arcgisonline.com/ArcGIS/rest/services/LandsatGLS/NaturalColor/ImageServer

Closing issue.
