### ISSUE TITLE
Install ArcGIS for Maritime: Server extension on Ops Server with publically releasable NOAA charts

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1009]
So that this can be demoed with out an internet connection.  It's a very simple install. 

NOAA ENC data can be found here: http://www.nauticalcharts.noaa.gov/mcd/enc/download_agreement.htm.  If there is any permisisons issue with us including it on the Ops Server, then I recommend installing the Maritime extension on Server anyway, and we can allow users to download the data themselves and then manually copy it to the proper folder (the service just checks a folder for data on startup and generates an index).

@jfrygeo , do any of your demos, web maps, etc reference the external NOAA ENC Online service?

**Comment by jfrygeo** [comment]
That's a great idea. I will write some documentation and provide NOAA charts on the OpsServer. @conklinbd

**Comment by jfrygeo** [comment]
Maritime Chart Server will not be installed on this OpsServer - however, the executable and ENC data are provided in the Maritime Operations folder for this opsserver build.

**Comment by elinz** [comment]
Clarification: Maritime Chart Server software and ENC data is being provided in this release as part of the Demos and Scripts.

@jfrygeo Let me know when you have provided whatever documentation/instructions in the Demos and Scripts folder and I will close this issue.

**Comment by jfrygeo** [comment]
Eric,

I assume the documentation is in the executable. I am not sure where there is any documentation. I have the executables and data in the Maritime Operations folder.

Regards,
John

**Comment by elinz** [comment]
@jfrygeo I'm referring to the install instructions; this must exist somewhere.

**Comment by jfrygeo** [comment]
I will hunt this down from the MCS team.

**Comment by elinz** [comment]
@jfrygeo Thanks.

**Comment by jfrygeo** [comment]
Added portal items for:
<li>Mapping and Charting Solution for Server Installation Guide
<ln>https://server.arcgis.com/en/documentation/install/mapping-charting-solution/latest/welcome-to-the-mapping-and-charting-solutions-for-server-install-guide.htm
<li>Maritime Chart Server Sample Application
<ln>http://nsdemo.esri.com/WAB4MCS/
<li>Maritime Chart Server Web Application Widgets-Github
<ln>https://github.com/Esri/maritimechartservice-sample-viewer
