### ISSUE TITLE
Publish Urban Mission Rehearsal Web Scene to Ops Server

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1010]
This is a very useful 3D demo for presentations. Can we include it on the Ops Server, or a similar 3D urban web scene?

**Comment by conklinbd** [comment]
@NatalieCampos is this something you have done?

**Comment by NatalieCampos** [comment]
This was done on past servers but not the current NSEC.  All current work for UMR has been on the documenting and creating of versions for the CE project.  I will work with Jimmy and Lorraine to get this done prior to cutoff.

**Comment by conklinbd** [comment]
Thanks @NatalieCampos

**Comment by NatalieCampos** [comment]
The UMR webscene has been published.  The portal item summary and description remain the same as the previous AFMIEDEV portal item.  @jrweakland  Can you please review for release?

https://nsec.esri.com/arcgis/home/item.html?id=5f5e48f2cf48451b9fb8e5cecd7979b0

**Comment by kerryrobinson** [comment]
Thanks Natalie!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by jrweakland** [comment]
@NatalieCampos - reviewed and sent to the release team. 
@lfunkhouser - added to the ReleaseReview group on nsec.
@kerryrobinson - please close this issue when appropriate.

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review. id:5f5e48f2cf48451b9fb8e5cecd7979b0

**Comment by conklinbd** [comment]
Not sure why this issue was assigned to @kerryrobinson.
Reassigned to @lfunkhouser

**Comment by lfunkhouser** [comment]
@jrweakland Are the Access and Use Constraints accurate?  There is no military imagery present.

**Comment by karlterrey** [comment]
@lfunkhouser @jrweakland I edited the Access and Use Constraints as there are no military images present. That portion is only used if military photographs are used.

**Comment by karlterrey** [comment]
@jrweakland We should have a note in the description that the 3D visualizations are fictitious, assuming that they are fictitious. Or extruded based on whatever imagery source was used.

**Comment by jrweakland** [comment]
@karlterrey and @lfunkhouser - i have added the following sentence to the portal item description. <b>These 2D and 3D procedural rules and heights are based on best estimates of the local conditions and should not be construed as fact.</b>

Please let me know if this statement meets you intent.

**Comment by karlterrey** [comment]
@jrweakland Perfect

**Comment by lfunkhouser** [comment]
@jrweakland The portal description does not include the statement. Maybe it didn't save..

**Comment by jrweakland** [comment]
@lfunkhouser - updated with the sentence. please confirm and close issue.

**Comment by karlterrey** [comment]
@jrweakland @lfunkhouser Verified as fixed. Closing this.

**Comment by conklinbd** [comment]
I am reopening this issue. The issue was that that this scene needs to be released because @kerryrobinson needed it for her Map Journal presentation. This is a showstopper.

**Comment by lfunkhouser** [comment]
Released by ReleasedIntelligence
