### ISSUE TITLE
Including Military Operations feeds in latest Ops Server?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1011]
Are there any plans to include Military Operations feeds (Friendly, Hostile, Situation Report, Intel Reports, etc) in the Fall 2015 release of Ops Server?   This is a key aspect of the current Ops Server release that I use in every presentation.   GeoEvent services, geofences, dashboards, etc.

I don't see it currently on NSEC.

**Comment by conklinbd** [comment]
@jrweakland @pHill5136

**Comment by jrweakland** [comment]
@kerryrobinson - My understanding is that @pHill5136  is creating GEE feeds for folks in the DCRO. These feeds should be included in the upcoming release of the Ops Server.

**Comment by kerryrobinson** [comment]
@jrweakland @pHill5136 @ScottCecilio   -  OK, I now see that there are updates being made to FriendlyOperations and HostileOperations over Monterrey.   There are are also still features over Afghanistan/Iran as well.  Should they be deleted?

 I don't see any situation reporting except for ISR Mission Reports and SPOT reports.  Are there any plans to include reports, sensor tracks, NAI/TAIs etc?

**Comment by jrweakland** [comment]
@kerryrobinson - @pHill5136 is adding more services as we speak.

**Comment by conklinbd** [comment]
@phill5136 are you  making any more changes to the number of geoevent services? If not then please close this issue.
