### ISSUE TITLE
Event definitions for Geomessages contain errors

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1013]
There are an extremely large number of errors with the event definitions for the geomessages on the server. This is filling the log with errors which will make it really difficult for customers and distributors to figure out if their geoevent configuration is working. 

We need to correct the event definitions to include all the required fields.

**Comment by conklinbd** [comment]
Should be able to be fixed by next Friday.

**Comment by pHill5136** [comment]
@elinz @conklinbd Added fields to trackrep and created position_report event def. Will wait some  time and see if these kind of messages stop filling up the logs.

**Comment by conklinbd** [comment]
Based on the number of messages +1million that have processed without error I am closing this issue.
