### ISSUE TITLE
"New Geography" feature service located on external server

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1015]
The NewGeography feature service (id: 9b789a22ffdd44549bd47d973929dd47) is not located on our development server. According to portal item description, this is a temp service until the foundation services have been updated. 

This service is not working. Is this service still needed?

**Comment by conklinbd** [comment]
I had not planned on maintaining this service. If someone else wants to publish it that is fine with me.
@nfeuerstein or @jrweakland ?

**Comment by conklinbd** [comment]
I am assuming this isn't need.
