### ISSUE TITLE
Web Map "Maritime Domain Awareness Dashboard" references service from NOAA that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1016]
Web map 995d354c59694c01bbd1ff877441526a "Maritime Domain Awareness Dashboard" references URL http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs that can be found.

**Comment by jrweakland** [comment]
@jfrygeo - it is located here by chance?

https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast

**Comment by jfrygeo** [comment]
Services updated to reflect new NOAA REST Urls
