### ISSUE TITLE
WMS service item "Near Real-Time Observations NOAA nowCOAST WMS" references service from NOAA that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1017]
WMS service item 6cc00b9f0afd4ea9ac5b859dda0fd253 "Near Real-Time Observations NOAA nowCOAST WMS" references the following URL from NOAA that does not exist:

http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs  

Accessing this URL generates the following error:
Not Found
The requested URL /wms/com.esri.wms.Esrimap/obs was not found on this server.

**Comment by jrweakland** [comment]
@jfrygeo - is it located here by chance?

https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast

**Comment by jfrygeo** [comment]
Jim,

NOAA just fielded a new nowcoast app and the urls have changed. They now have rest endpoints too. I will look to update this tomorrow.

Regards,
John

Sent from my iPhone

On Sep 28, 2015, at 5:45 PM, Jim Weakland <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://github.com/jfrygeo> - is it located here by chance?

https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast

**Comment by jfrygeo** [comment]
Service updated to:
<ln>https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/obs_meteocean_insitu_sfc_time/MapServer
<li>https://nsec.esri.com/arcgis/home/item.html?id=4fba403aa63b41b982c48af3043843d5
