### ISSUE TITLE
Web Map "ObservationsMap" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1018]
Item id 3ca2b8e0e7eb4f8893143c11b00e42fc references the following services/layers that do not exist:
NationalIntelligence/ObservationReports/FeatureServer/0 

This service only contains a single layer "SaluteReports" layer id 1.

**Comment by topowright** [comment]
@elinz fixed

**Comment by elinz** [comment]
@topowright Layer 0 still does not exist.

**Comment by conklinbd** [comment]
Observation report Layer 0 exists. Closing.
