### ISSUE TITLE
Web Map "ClustersTest" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1019]
Item id 519b87631e984e9c8b09ed93b86085d0 references the following services/layers that do not exist:
NationalIntelligence/ObservationReports/FeatureServer/0

This service only contains a single layer "SaluteReports" layer id 1.

**Comment by topowright** [comment]
@elinz fixed

**Comment by elinz** [comment]
@topowright This web map does not exist anymore. Was it your intent to fix this issue by just deleting the web map?

**Comment by conklinbd** [comment]
Verifying that was the intended fix.
