### ISSUE TITLE
Share HostileOperations to DemoReview

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1020]
@jrweakland HostileOperations service needs to be shared to DemoReview

**Comment by jrweakland** [comment]
@pHill5136 - these portal items will not be shared with the Demo Review Group until the items have the: Title, Summary, Description, Access and Use Constraints, and Credits fields completely filled out. You are also missing all of the proper tags. Why is there an unknown unit in the thumbnail for a hostile service?

https://nsec.esri.com/arcgis/home/item.html?id=e51a4c093b644a7f9cd12faf7df95da6

https://nsec.esri.com/arcgis/home/item.html?id=0750cc5ebd3b473184dbd428c3861134

**Comment by pHill5136** [comment]
Updated metadata on services

**Comment by jrweakland** [comment]
Shared with the Demo Review group - https://nsec.esri.com/arcgis/home/item.html?id=e51a4c093b644a7f9cd12faf7df95da6

**Comment by jrweakland** [comment]
Shared with the Demo Review group - https://nsec.esri.com/arcgis/home/item.html?id=0750cc5ebd3b473184dbd428c3861134

**Comment by jrweakland** [comment]
Closing issue. Changed owner to me and placed in FinalReview folder.
