### ISSUE TITLE
FriendlyOperations Share to DemoReview

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1021]
@jrweakland FriendlyOperations service needs to be shared to Demo Review

**Comment by jrweakland** [comment]
@pHill5136 - these portal items will not be shared with the Demo Review Group until the items have the: Title, Summary, Description, Access and Use Constraints, and Credits fields completely filled out. You are also missing all of the proper tags.

https://nsec.esri.com/arcgis/home/item.html?id=6a33688d4bb6493aba882b86d934c4ce

https://nsec.esri.com/arcgis/home/item.html?id=e377b17ba01241ea80e74e75323e1776

**Comment by pHill5136** [comment]
updated metadata on services

**Comment by jrweakland** [comment]
Shared with Demo Review Group - https://nsec.esri.com/arcgis/home/item.html?id=6a33688d4bb6493aba882b86d934c4ce

**Comment by jrweakland** [comment]
Shared with Demo Review Group - https://nsec.esri.com/arcgis/home/item.html?id=e377b17ba01241ea80e74e75323e1776

**Comment by jrweakland** [comment]
Closing issue. Changed owner to me and placed in FinalReview folder.
