### ISSUE TITLE
IntelReports Share to Demo Review

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1022]
@jrweakland Intel Reports service needs to be shared to demo Review group

**Comment by jrweakland** [comment]
@pHill5136 - these portal items will not be shared with the Demo Review Group until the items have the: Title, Summary, Description, Access and Use Constraints, and Credits fields completely filled out. You are also missing all of the proper tags.

https://nsec.esri.com/arcgis/home/item.html?id=60d9c717ebd64314bb1764bd5ea5c96b

https://nsec.esri.com/arcgis/home/item.html?id=b1ab24b97f9f4bd4925d2a5f0b792fce

You named this intel reports and the layers are mission reports and incident reports. Is this correct?

**Comment by pHill5136** [comment]
updated metadata on services

**Comment by jrweakland** [comment]
Shared with Demo review group - https://nsec.esri.com/arcgis/home/item.html?id=60d9c717ebd64314bb1764bd5ea5c96b

**Comment by jrweakland** [comment]
Shared with Demo Review group - https://nsec.esri.com/arcgis/home/item.html?id=b1ab24b97f9f4bd4925d2a5f0b792fce

**Comment by jrweakland** [comment]
Closing issue. Changed owner to me and placed in my final review folder.
