### ISSUE TITLE
Share ObservationReports to DemoReview

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1023]
@jrweakland ObservationReports Service needs to be shared with DemoReview group

**Comment by jrweakland** [comment]
@pHill5136 and @topowright - these portal items will not be shared with the Demo Review Group until the items have the: Title, Summary, Description, Access and Use Constraints, and Credits fields completely filled out. You are also missing thumbnails and all of the proper tags.

There are two map image layers with the same name but different dates (this needs to be resolved):

https://nsec.esri.com/arcgis/home/item.html?id=940093ddd52a4170b8025f58698e55d4
https://nsec.esri.com/arcgis/home/item.html?id=36834c8db03c43df92bf2ef230d958ce

Feature layer: https://nsec.esri.com/arcgis/home/item.html?id=d518e58360304d26a1dc4ab78aa45e29

**Comment by conklinbd** [comment]
@phill5136 this needs to be resolved today.

**Comment by pHill5136** [comment]
@topowright we need to get this fixed today. I believe you created these.

**Comment by topowright** [comment]
@pHill5136 fixed

**Comment by pHill5136** [comment]
Lyle did these yesterday

**Comment by conklinbd** [comment]
This looks like it should be reassigned to @jrweakland to verify change fix.

**Comment by jrweakland** [comment]
@topowright is fixing some issue with the portal items. he will let me know when i can attempt to send the items to demo review.

**Comment by jrweakland** [comment]
This webmap id:1e607ce98b6241baa05e53f8171638de
and this feature service id:12919c56d6a8446985a18d173f0f66f1
are relying on this being resolved.

**Comment by elinz** [comment]
All, please ignore this isssue. I am fixing this issue.

**Comment by elinz** [comment]
See issue #1207
