### ISSUE TITLE
Share ObservationReportsML to DemoReview

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1024]
@jrweakland ObservationReportsML Service needs to be shared with DemoReview group

**Comment by jrweakland** [comment]
@pHill5136 and @topowright - these portal items will not be shared with the Demo Review Group until the items have the: Title, Summary, Description, Access and Use Constraints, and Credits fields completely filled out. You are also missing thumbnails.

https://nsec.esri.com/arcgis/home/item.html?id=bff0a7b237e946b385bc7223d8af5ae4

https://nsec.esri.com/arcgis/home/item.html?id=e1786c4738b54473982b7f0b85453643

**Comment by conklinbd** [comment]
@phill5136 this needs to be resolved today.

**Comment by pHill5136** [comment]
@topowright This one needs to get updated too.

**Comment by topowright** [comment]
@pHill5136 These items have been updated

**Comment by pHill5136** [comment]
Lyle did these yesterday

**Comment by conklinbd** [comment]
Also reassigning to @jrweakland

**Comment by jrweakland** [comment]
Reviewed and shared with demo review.

**Comment by jrweakland** [comment]
@topowright is fixing some issue with this service. he will let me know when i can attempt to release the items again.

**Comment by conklinbd** [comment]
@topowright please provide an update on the status of this issue.

**Comment by topowright** [comment]
@conklinbd I have shared these items to Demo Review

**Comment by conklinbd** [comment]
#1212 depends on this issue

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review and release

id:e1786c4738b54473982b7f0b85453643
id:bff0a7b237e946b385bc7223d8af5ae4

**Comment by lfunkhouser** [comment]
Items released by Demo Intelligence

**Comment by conklinbd** [comment]
I verified, since the GEE issue depends on this one.
