### ISSUE TITLE
Web Map "SALUTE Reports" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1025]
Item id 1e607ce98b6241baa05e53f8171638de references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/ObservationReports/FeatureServer/0

This service only contains a single layer "SaluteReports" layer id 1.

**Comment by ACueva** [comment]
@nfeuerstein fixed this issue.  Duplicate issue as: https://github.com/Esri/ops-server-config/issues/1077
