### ISSUE TITLE
Web Map "Crowd Source reporter test map" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1026]
Item id:cb423c99205c4c53a999852b960bdccb references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/ObservationReports/FeatureServer/0

This service only contains a single layer "SaluteReports" layer id 1.

**Comment by conklinbd** [comment]
Based on the lack of activity on this item. I am going to delete the item at 1100 today. If you think this is in error please respond by then.  Items like this cause us problems in QA/QC and have the potential to cause other problems as individuals reuse this content in their demo's/presentations.

**Comment by conklinbd** [comment]
Deleted @phil7277 .

Back to @elinz to verify.

**Comment by elinz** [comment]
Verified that web map in question was deleted. Closing issue.
