### ISSUE TITLE
Web Map "Operations Center- SALUTE Reports" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1027]
Item id:67eb8bf42ecd4bd3b20677fdc788c903 references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/ObservationReports/FeatureServer/0

This service only contains a single layer "SaluteReports" layer id 1.

**Comment by conklinbd** [comment]
Based on the lack of activity on this item. I am going to delete the item at 1100 today. If you think this is in error please respond by then.  Items like this cause us problems in QA/QC and have the potential to cause other problems as individuals reuse this content in their demo's/presentations.

**Comment by conklinbd** [comment]
Deleted @phil7277 

Back to @elinz  to verify.

**Comment by elinz** [comment]
Verified web map in question was deleted. Closing issue.
