### ISSUE TITLE
Service "ObservationsReports/FeatureServer" missing a layer

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1028]
Service d518e58360304d26a1dc4ab78aa45e29 ObservationReports used to have a layer 0, now it only has layer 1 "SaluteReports". Many web maps references layer 0.

**Comment by topowright** [comment]
@elinz Do i need to republish this item to get the item layer to change?

**Comment by elinz** [comment]
@topowright yes you will need to republish.

**Comment by topowright** [comment]
@elinz This has been fixed

**Comment by conklinbd** [comment]
I can verify that the only layer is layer 0. I am closing this issue.
