### ISSUE TITLE
Briefing Book

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1030]
_From @joebayles on September 28, 2015 18:14_

https://nsec.esri.com/arcgis/home/item.html?id=db3f367dcfca4cc7b28ca288c0037323

- [x] No Summary
- [x] No Credits
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#125_

**Comment by conklinbd** [comment]
Updated from AGOL version. Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
