### ISSUE TITLE
Topographic Map

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1031]
_From @joebayles on September 28, 2015 18:15_

https://nsec.esri.com/arcgis/home/item.html?id=4c42ae61d0ab4cca8d4662bc6fff1041

- [x] No Summary
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#126_

**Comment by conklinbd** [comment]
Fixed with content from AGOL. Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
