### ISSUE TITLE
Terrain

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1032]
_From @joebayles on September 28, 2015 18:15_

https://nsec.esri.com/arcgis/home/item.html?id=fab65a596f9e409499c1fb2368f00227

- [x] Title?
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#127_

**Comment by conklinbd** [comment]
Fixed with AGOL content back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
