### ISSUE TITLE
Visibility and Range

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1033]
_From @joebayles on September 28, 2015 18:16_

https://nsec.esri.com/arcgis/home/item.html?id=b686d980cd5b497a95f95d8571c0826f
- [x] No Summary
- [x] Description needs to be complete
- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#128_

**Comment by nfeuerstein** [comment]
Done.
