### ISSUE TITLE
Distance to Assets

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1034]
_From @joebayles on September 28, 2015 18:16_

https://nsec.esri.com/arcgis/home/item.html?id=b0ec3983ee124cacac139140f1e85c7c

- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#129_

**Comment by conklinbd** [comment]
This item is owned by @nfeuerstein but you have assigned the issue to @jrweakland. Also labeled with Intel team. Which is it @joebayles.

**Comment by joebayles** [comment]
@conklinbd feel free to edit this issue however you see fit.

![image](https://cloud.githubusercontent.com/assets/5016557/10225520/0b28cd74-6818-11e5-9dfc-542eb581d959.png)

**Comment by nfeuerstein** [comment]
@conklinbd I assigned it to @jrweakland because I thought he would know more about it.  My team has not had anything to do with the planning, development of the template, or the solutions page documentation for it.  I thought @jrweakland would be the best to answer any questions.

**Comment by joebayles** [comment]
I can move the item to @jrweakland if you wish.

**Comment by nfeuerstein** [comment]
@joebayles I think it was just under my name because I wanted to make sure we had it on NSEC for UC.

**Comment by joebayles** [comment]
Fixed the issues.
