### ISSUE TITLE
Line of Sight

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1035]
_From @joebayles on September 28, 2015 18:19_

https://nsec.esri.com/arcgis/home/item.html?id=bdb59e3de7904449aa92acb329873b4b

- [ ] Delete?

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#130_

**Comment by jrweakland** [comment]
@joebayles - changed https://nsec.esri.com/arcgis/home/item.html?id=bdb59e3de7904449aa92acb329873b4b to Demo Review group.

@kgonzago - in the future, we will want to move this from Vermont to the Monterey, CA area and release to the Try it Live experience as discussed when you were in CA in 09/2015.

**Comment by joebayles** [comment]
:+1:

**Comment by kgonzago** [comment]
@jrweakland noted.
