### ISSUE TITLE
Time Aware (New)

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1036]
_From @joebayles on September 28, 2015 18:20_

https://nsec.esri.com/arcgis/home/item.html?id=a8284006eb504022afce6e2c3f02f39b

- [x] Title?
- [x] Summary?
- [x] No Access and Use Constraints
- [x] No Credits

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#131_

**Comment by conklinbd** [comment]
Updated based on AGOL item. Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
