### ISSUE TITLE
Boundary and Places

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1037]
_From @joebayles on September 28, 2015 18:36_

https://nsec.esri.com/arcgis/home/item.html?id=0aeb3e0a856d42b78995186408937f0a

- [x] Title?
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#132_

**Comment by conklinbd** [comment]
Fixed from AGOL Item. Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
