### ISSUE TITLE
Imagery

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1038]
_From @joebayles on September 28, 2015 18:37_

https://nsec.esri.com/arcgis/home/item.html?id=55a20dc19f2e47c8ad3b0a38eca94671

- [x] Title?
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#133_

**Comment by conklinbd** [comment]
Fixed based on AGOL. Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
