### ISSUE TITLE
Light Grey Canvas Labels

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1039]
_From @joebayles on September 28, 2015 18:38_

https://nsec.esri.com/arcgis/home/item.html?id=0d395746832342ea9505f8d318654c3e

- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#134_

**Comment by conklinbd** [comment]
Updated from AGOL item.
Back at you @joebayles
