### ISSUE TITLE
Light Grey Canvas

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1040]
_From @joebayles on September 28, 2015 18:39_

https://nsec.esri.com/arcgis/home/item.html?id=2970eaa4e2f44559a0c3cca33fe5dde1

- [x] Title?
- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#135_

**Comment by conklinbd** [comment]
Fixed from AGOL item. 
Back at you @joebayles
