### ISSUE TITLE
Dark Grey Canvas Labels

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1041]
_From @joebayles on September 28, 2015 18:40_

https://nsec.esri.com/arcgis/home/item.html?id=cc19b6a12c83475a830d2e8060783d47

- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#136_

**Comment by conklinbd** [comment]
Fixed from AGOL item.
Back at you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
