### ISSUE TITLE
Dark Grey Canvas

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1042]
_From @joebayles on September 28, 2015 18:40_

https://nsec.esri.com/arcgis/home/item.html?id=030a8ec8848f4c5ab4fafb890977eee1

- [x] Title?
- [x] No Access and Use Constraints
- [x] Credits?
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#137_

**Comment by conklinbd** [comment]
Updated by copying content from AGOL for this basemap including updating the title to be similar to the AGOL Basemap.

**Comment by conklinbd** [comment]
Back to you @joebayles

**Comment by joebayles** [comment]
Released to ReleasedOpsServer
