### ISSUE TITLE
Oceans

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1043]
_From @joebayles on September 28, 2015 18:41_

https://nsec.esri.com/arcgis/home/item.html?id=0384031089ba4f48bf86ca7f1dd4a63c

- [x] Title?
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

_Copied from original issue: ArcGIS/mil-intel-desktop-solutions-templates#138_

**Comment by conklinbd** [comment]
Fixed from AGOL item. Back at you @joebayles
