### ISSUE TITLE
Service "Military//NGASubregions.MapServer.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1044]
Service "Military//NGASubregions.MapServer" is associated with a portal item (523a2ef1f7b64237bc73c75cd7fe0ab4; FeatureServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by jfrygeo** [comment]
https://nsec.esri.com/arcgis/home/item.html?id=537802eca0814e5185a3dfd36e06d6bd (NGASubregions) is for
https://nsec.esri.com/ags/rest/services/Military/NGASubregions/MapServer

https://nsec.esri.com/arcgis/home/item.html?id=bee2ec5acb7e4c3f9a37c4b37406f8da points to 
https://nsec.esri.com/ags/rest/services/Military/NGASubregions/FeatureServer

Services work.

**Comment by jfrygeo** [comment]
Could be from using Esri Maps for Office - as that will create hosted features?

**Comment by elinz** [comment]
@jfrygeo No, this is not a hosted service; if it was the service would be located in the "Hosted" folder. The services may work, but this doesn't mean that the service "infrastructure" is correct. 

According to the service json information (shown below) the feature service should be pointing to the item 523a2ef1f7b64237bc73c75cd7fe0ab4. On a federated server you simply can't manually create a portal item and point it to a service url. While the service will draw, the service won't be associated with the portal item and therefore there will be ownership and access/sharing issues.
Portal properties:	{"isHosted":false,"portalItems":[{"itemID":"537802eca0814e5185a3dfd36e06d6bd","type":"MapServer"},{"itemID":"523a2ef1f7b64237bc73c75cd7fe0ab4","type":"FeatureServer"}]}

I will edit the service and correctly point it to this item.

**Comment by elinz** [comment]
@jfrygeo I corrected the service json. Closing issue.
