### ISSUE TITLE
Service "NationalIntelligence//OptimizedHotSpot.GPServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1046]
Service "NationalIntelligence//OptimizedHotSpot.GPServer" is associated with a portal item (b6d9ed696c184925ae200c71d4955885; GPServer) that does not exist.

@nfeuerstein @jrweakland Is this a military or intelligence team service? Thanks.

**Comment by conklinbd** [comment]
I created an item for this and shared to the Intel QA/QC group.
This item should be released since I think it is tied to the Ebola demo. If the Ebola demo is not being released then this item can wait until next release.

@nfeuerstein

**Comment by nfeuerstein** [comment]
The GP Service looks generically useful, perhaps for demo'ing Web AppBuilder.  Releasing.
