### ISSUE TITLE
Service "Military//PiracyBySubregion2009to2013.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1047]
ERROR: Service "Military//PiracyBySubregion2009to2013.MapServer" is associated with a portal item (ee4dabc9a8d24fc2bf1e9a1888a394d5; MapServer) that does not exist.

ERROR: Service "Military//PiracyBySubregion2009to2013.MapServer" is associated with a portal item (7d6f11fdf5bf41af9f76cb5b9f67629c; FeatureServer) that does not exist.

@jfrygeo Both the feature and map service portal item do not exist. Was this a service you were intentionally trying to delete? Let me know and I will delete this service.

**Comment by jfrygeo** [comment]
? they exist here: https://nsec.esri.com/arcgis/home/item.html?id=765c051ab7d14139bd8dc8857ed2e435

https://nsec.esri.com/arcgis/home/item.html?id=c33c98003a41459499e2b06978336f87

**Comment by jfrygeo** [comment]
I would delete those old items if possible

**Comment by elinz** [comment]
@jfrygeo The ids don't match because these portal items were not created correctly. When you create the service on a federated server, the portal items are automatically created. However, in this case, the portal items were deleted (which you shouldn't do for a non-hosted service). Then the portal items were manually re-created, which means that the service isn't actually associated with these portal items and therefore the service is "owner-less" and all the access and sharing can't be set on this service. 

These old items don't actually exist, but the service json actually references these missing items.

Is this service still needed?

**Comment by jfrygeo** [comment]
This service is needed. Delete the old items and reference this portal item with the PiracyBySubregion2009to2013.MapServer map service....

**Comment by elinz** [comment]
No need to delete old items as these didn't exist. I edited the service json to reference the map service and feature service items listed above. Closing issue.
