### ISSUE TITLE
Places of Interest

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1048]
https://nsec.esri.com/arcgis/home/item.html?id=dc98d111dc164933a13b20542db9fdcd

- [ ] Title?
- [ ] Summary should not be a definition of the concept, but a summary of the item.
- [ ] Delete Protection Disabled

**Comment by nfeuerstein** [comment]
I disagree with the definition of "summary" - there are already properties that are autopopulated that tell you that this item is a feature service.  A real world summary would explain the relevance of the item, not the metadata.
