### ISSUE TITLE
Owner of service definition item "CountryBoundaries" is not the same as the associated hosted service item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1051]
@nfeuerstein @sschwoppe  Service Definition item a1956f5df1d34a1fbe8c58e3b5e0b1b4("CountryBoundaries") must be owned by the same owner as the associated hosted service item 086c5358415e4a948764385685240cb7 ("Country Boundaries") - Hosted/CountryBoundaries/FeatureServer otherwise issues are encountered when setting up an Ops Server.

**Comment by conklinbd** [comment]
Changed owner to @nfeuerstein

**Comment by elinz** [comment]
Verified this issue was fixed. Closing issue.
