### ISSUE TITLE
Owner of service definition item "eboladistricts/FeatureServer" is not the same as the associated hosted service item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1052]
@nfeuerstein @sschwoppe Service Definition item df9de5d54c7045808ffb374fc4dea1a9("eboladistricts") must be owned by the same owner as the associated hosted service item b8966bd015e64a6d9576a57573c9610e("Districts in West Africa with reported  Ebola outbreaks") - Hosted/eboladistricts/FeatureServer otherwise issues are encountered when setting up an Ops Server.

**Comment by conklinbd** [comment]
Changed owner to @nfeuerstein

**Comment by elinz** [comment]
Verified this issue was fixed. Closing issue.
