### ISSUE TITLE
Owner of service definition item "ebolaoutbreaks" is not the same as the associated hosted service item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1054]
@nfeuerstein @sschwoppe Service Definition item 6df2cb73dd1d41c6a79e55c6fa0b15d7 ("ebolaoutbreaks") must be owned by the same owner as the associated hosted service item 8592ab25641446a0829964daf45a5548 ("Ebola Outbreaks") - Hosted/ebolaoutbreaks/FeatureServer otherwise issues are encountered when setting up an Ops Server.

**Comment by conklinbd** [comment]
Changed owner to @nfeuerstein

**Comment by elinz** [comment]
Verified this issue was fixed. Closing issue.
