### ISSUE TITLE
Owner of service definition item "liberiabordercrossings" is not the same as the associated hosted service item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1055]
@nfeuerstein @sschwoppe Service Definition item 24fe6e4a95a848beb8d869806955da83 ("liberiabordercrossings") must be owned by the same owner as the associated hosted service item 629ec8df73d1416291d4c1f18da77cc8 ("Liberia Border Crossings") - Hosted/liberiabordercrossings/FeatureServer otherwise issues are encountered when setting up an Ops Server.

**Comment by conklinbd** [comment]
Changed owner to @nfeuerstein

**Comment by elinz** [comment]
Verified issue was fixed. Closing issue.
