### ISSUE TITLE
Streets

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1057]
https://nsec.esri.com/arcgis/home/item.html?id=39644e963b6541d8b9424b3ae0ee3512

- [x] Title?
- [x] No Summary
- [x] Description is light
- [x] No Access and Use Constraints
- [x] Delete Protection Disabled

**Comment by conklinbd** [comment]
Pulled from AGOL Service item. Back at you @joebayles

**Comment by lfunkhouser** [comment]
While this is pulled from AGOL service item, http://www.arcgis.com/home/item.html?id=d8855ee4d3d74413babfb0f41203b168, there is no documentation that states this is where this item came from.  Couldn't we just reuse the access and use constraints that they use and reuse some information from where the data came from?  

For more details, it directs you to, World Street Map: http://www.arcgis.com/home/item.html?id=3b93337983e9436f8db950e38a8629af, which then gives a link to the data sources in the map service, Contributors for the World Street Map: http://help.arcgis.com/en/communitymaps/pdf/WorldStreetsMap_Contributors.pdf 

At the very least, should we add the pdf to Box, https://esri.app.box.com/files/0/f/3453468100/Data_Permissions?

**Comment by conklinbd** [comment]
I reused the access and use constraints from the item. I think a live link is a much better idea then a static doc. These constraints are what the AGOL team wants us to use and enforce.

**Comment by ACueva** [comment]
@conklinbd - I don't see any access and use constraints on the item.
![9-29-2015 4-11-22 pm](https://cloud.githubusercontent.com/assets/3093940/10180723/c416156c-66c4-11e5-86ea-f6adba0af74a.png)

**Comment by joebayles** [comment]
Not sure why this was all checked off, nothing has been changed. If you're saying that they are good how they are, then we can just release all of these items.

**Comment by conklinbd** [comment]
@joebayles I edited the item, but it looks like someone else must have had the item open for editing and my edits were overwritten. I have reverted the changes back to what I had from AGOL.
The main things I fixed were:
Changed the Title so it doesn't include the word basemap. 
Updated the description
Included the correct credits and tags.
