### ISSUE TITLE
SALUTE Reporting

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1059]
https://nsec.esri.com/arcgis/home/item.html?id=895d6bffcd1a4d829d30601b6cfa1f97

- [x] Title (Maybe SALUTE Report GeoForm?)
- [x] Summary needs more
- [x] Description needs more
- [x] Delete Protection Disabled

**Comment by nfeuerstein** [comment]
I dont think the description needs more, everything else is good.
