### ISSUE TITLE
National Security Basemaps Gallery

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1060]
https://nsec.esri.com/arcgis/home/item.html?id=51cf9070de1c49b68f8f0daae80d7bd6

- [ ] No Access and Use Constraints
- [x] Delete Protection Disabled

**Comment by conklinbd** [comment]
@joebayles I am not sure I understand why an application needs access and use constraints. This is data related and apps do not have data. 

AGOL does not have access and use constraints on apps.

**Comment by joebayles** [comment]
Agreed.
