### ISSUE TITLE
Military Aspects of Weather 2.0

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1061]
- [ ] Release Notes inside of Tools/MST_Install folder. "ArcGIS 10.2 is preferred", we are shipping this template as a 10.3 template.
- [ ] Tools/scratch folder.  Are these files necessary or can we cleanup this folder prior to zipping?
- [ ] It appears we are using 3rd party tools for this template.  Do you know if we are able to distribute these 3rd party tools and if so what licensing agreement we need to cite? i.e. gnu, Apache, etc.?
- [ ] MAOWTools.tbx appears to have some broken scripts.

![9-29-2015 8-53-24 am](https://cloud.githubusercontent.com/assets/3093940/10169797/99ceb986-6687-11e5-8493-c1957924f5d5.png)

**Comment by ACueva** [comment]
@jrweakland FYI

**Comment by conklinbd** [comment]
@ACueva shouldn't this be logged in the desktop template repository?
https://github.com/ArcGIS/mil-intel-desktop-solutions-templates/issues

**Comment by ACueva** [comment]
@conklinbd - This template will go out with the Ops Server release, this is why any issue affecting the ops server release is being logged against the Ops Server repo.  It's your call though.

**Comment by conklinbd** [comment]
Template issue should be on the template site. All released templates ship with the Ops Server but we won't hold up a release waiting for a template to ship.

**Comment by ACueva** [comment]
This issue was moved to ArcGIS/mil-intel-desktop-solutions-templates#139
