### ISSUE TITLE
Camps

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1062]
https://nsec.esri.com/arcgis/home/item.html?id=1b5ee365f46f417593e2e62eefbf776a

- [x] Title needs to be more specific
- [x] Description needs to be more specific
- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

https://nsec.esri.com/arcgis/home/item.html?id=621106f10a85416495445fc44e562edc

- [x] Title needs to be more specific
- [x] Description needs to be more specific
- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

https://nsec.esri.com/arcgis/home/item.html?id=f96cbe75893b48139d8ec3c96ef9bd50

- [x] Title needs to be more specific
- [x] Description needs to be more specific
- [x] No Access and Use Constraints
- [x] No Credits
- [x] Delete Protection Disabled

**Comment by nfeuerstein** [comment]
Found the permissions, here: \\disldb\Development\Commercial\OPSServerReleases\2014_Q4_10.3Final\DemoAndScripts\Intel\PredictiveAnalysisDemos\RefugeeCamps\Documents 

Updated the item properties.

**Comment by joebayles** [comment]
Verified

**Comment by joebayles** [comment]
>The camp locations are notional and were created for demo purposes only.

@nfeuerstein does that mean these should be in Demo Review, not Release Review? If not, then suggest you add "The information presented in this template or demonstration is based on standard Esri Commercial off-the-Shelf (COTS) technologies and commercial data."
