### ISSUE TITLE
SALUTE Reports fails to load

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1077]
When you try to access the SALUTE Reports Web Map on our development server it fails to load.
I believe the issue is related to the underlying service.  The service is looking for Layer 0 which does not exist.

https://SERVERNAME/ags/rest/services/NationalIntelligence/ObservationReports/FeatureServer/0

**Comment by nfeuerstein** [comment]
Switched out the feature service for the SALUTE Reports.  Map now loads.
