### ISSUE TITLE
Salute Reporting Geoform fails to load

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1078]
https://SERVERNAME/arcgis/home/item.html?id=895d6bffcd1a4d829d30601b6cfa1f97

Error is the following:

![9-28-2015 9-03-50 pm](https://cloud.githubusercontent.com/assets/3093940/10196931/2c95e6be-674a-11e5-9d24-91fd696f789f.png)

**Comment by nfeuerstein** [comment]
Switched out the SALUTE feature service in the web map and tested that app loads.
