### ISSUE TITLE
WMS service "Meteorological Service of Environment Canada" does not draw

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1081]
WMS service 5a27e3777f4c49a0b0a439353fb547a8 "Meteorological Service of Environment Canada" which references the following URL does not draw:
http://geo.weather.gc.ca/geomet/?lang=E

This item is shared with a demo review group so it's meant to be included in this 2015 Q4 release.

**Comment by jrweakland** [comment]
@elinz - please try this instead and let me know.

http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities

**Comment by jfrygeo** [comment]
It could be because of http was changed to https?

Sent from my iPhone

On Sep 30, 2015, at 12:00 PM, Jim Weakland <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1081<https://github.com/Esri/ops-server-config/issues/1081> to @jfrygeo<https://github.com/jfrygeo>.

**Comment by elinz** [comment]
@jfrygeo No. As @jrweakland stated above it's an issue with the URL getting truncated when the item was created. I'll need to update the URL through code to be http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities as state previously.

**Comment by jrweakland** [comment]
Steps to reproduce:
1. My Content -> Add Item -> From the web -> OGC (WMS) -> http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities -> It truncates the URL and does not allow you to select all of the layers be deselecting and reselecting the checkbox next to Layers
2. From a new map -> Add -> Add Layer from Web -> A WMS OGC Web Service -> http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities -> Add Layer -> all layers from the WMS come in and are visible.

**Comment by jfrygeo** [comment]
Okay. Does this fix issue?

Sent from my iPhone

On Sep 30, 2015, at 12:17 PM, Jim Weakland <notifications@github.com<mailto:notifications@github.com>> wrote:


Steps to reproduce:
1. My Content -> Add Item -> From the web -> OGC (WMS) -> http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities -> It truncates the URL and does not allow you to select all of the layers be deselecting and reselecting the checkbox next to Layers
2. From a new map -> Add -> Add Layer from Web -> A WMS OGC Web Service -> http://geo.weather.gc.ca/geomet/?lang=E&SERVICE=WMS&REQUEST=GetCapabilities -> Add Layer -> all layers from the WMS come in and are visible.

**Comment by elinz** [comment]
@jfrygeo No. As stated previously this needs to be fixed by editing the URL in the portal item json. I will take care of this.

**Comment by elinz** [comment]
@jfrygeo Actually, looks like this WMS service item was incorrectly created. You can set the WMS map server url to the get capabilities URL.

**Comment by jfrygeo** [comment]
So just add the WMS again?

**Comment by jrweakland** [comment]
yes. the wms service not the wms get capabilities url

**Comment by jfrygeo** [comment]
I don't have that item in my content anymore

**Comment by jfrygeo** [comment]
looks like its good. https://nsec.esri.com/arcgis/home/item.html?id=5a27e3777f4c49a0b0a439353fb547a8

**Comment by elinz** [comment]
@jfrygeo This service item does not work correctly. while the item will open in a web map it only contains about 30% of the layers that it should. Looks like this is an issue with portal. You will have to delete this WMS service item and then edit all the web maps that reference this item and manually add all the layers you need. Looks like the only web map that references this service item is: 995d354c59694c01bbd1ff877441526a ("Maritime Domain Awareness").

**Comment by jfrygeo** [comment]
I really only need requests for a few of the layers, you are saying I need to request to have all the layers?

**Comment by elinz** [comment]
@jfrygeo No that's not what I'm saying. What I'm saying is that it looks like there is a bug and you can reference the WMS URL in the WMS service item. Edit the web map that references this service and just add the layers that you really need. Also delete this WMS service item since it's not working correctly.

**Comment by jfrygeo** [comment]
Got it fixed as an item with the layers needed. Located in

Maritime Domain Awareness Dashboard
 https://nsec.esri.com/arcgis/home/webmap/viewer.html?webmap=995d354c59694c01bbd1ff877441526a

As item. https://nsec.esri.com/arcgis/home/item.html?id=14808ff0a2f94601a02711d78f824ae9

Seems to work fine? No?

**Comment by jfrygeo** [comment]
works 
![maritimedomainawarenessdashboardweather](https://cloud.githubusercontent.com/assets/5074686/10207710/bce64a3a-6793-11e5-8155-4ae0a5d777dc.PNG)

**Comment by elinz** [comment]
I just opened the item https://nsec.esri.com/arcgis/home/item.html?id=14808ff0a2f94601a02711d78f824ae9 and no data draws.

I just opened the item https://nsec.esri.com/arcgis/home/webmap/viewer.html?webmap=995d354c59694c01bbd1ff877441526a and the data doesn't draw and the legend has broken...links
![image](https://cloud.githubusercontent.com/assets/4635490/10207738/2da49404-6783-11e5-97b3-d66954a72b2b.png)

**Comment by jfrygeo** [comment]
hmmm, opens for me...

**Comment by elinz** [comment]
Yes, the items open, but the data does not draw.

**Comment by jfrygeo** [comment]
I waited about 10-15 seconds though

**Comment by elinz** [comment]
I waited longer then that.

**Comment by jfrygeo** [comment]
I am closer to Canada, I guess? The service shows instantaneously for me when using the Operations Dashboard, and the webmap. It could be that the model layer you had chosen contained no data at this time. I tend to use:
<li>RDPS.ETA - Total Precipitation Rate (m/s)
<li>RDPS.ETA - Total Cloud Cover

**Comment by elinz** [comment]
I do see some data drawing from the service item but it's extremely slow. Also I now see data drawing in the Maritime Domain Awareness web map and the legend is drawing.

**Comment by conklinbd** [comment]
Seems like this issue is good to close.
