### ISSUE TITLE
EM: Shelter Locator not working with portal

### ISSUE THREAD

**Issue by jessnoo** [Esri/ops-server-config#1082]
@conklinbd the first symptom seems to be that the application is looking in arcgis.com for basemap items.

the app is here: \\nsec\SolutionsWeb\Apps\EmergencyManagement\ShelterLocator 

i can walk through the basic configuration and first set of issues when you get a minute. thank you!

**Comment by conklinbd** [comment]
@jessnoo I think I have this figured out.
The primary issue was in ShelterLocator\js\library\coreLibrary\widgetLoader.js

Line 200 uses esriUtils.getItem() without first setting the arcgisurl. 

I added a line esriUtils.arcgisUrl = appGlobals.configData.PortalAPIURL + 'content/items/'
This sets the arcgisUrl to be used for retrieving the item.

There may be other places in the code this should have been set globally but I didn't look into it too far. 

Additionally, we had changed the name of the group owner for the basemap group so I updated the owner property.

**Comment by conklinbd** [comment]
I also noticed there were many references hard coded as http://

I changed these to // to make them protocol agnostic. Since we use https:// for everything http:// resources fail to load.

**Comment by conklinbd** [comment]
I also changed the javascript api to use the api hosted on the portal instead of js.arcgis.com.

**Comment by jessnoo** [comment]
woot! @conklinbd 

couple things i've noticed:
- basemap switcher gets stuck on the imagery service

- the legend at the bottom is stuck on Loading... 
![image](https://cloud.githubusercontent.com/assets/6181441/10206207/8bf86250-677a-11e5-9e61-6ed391510162.png)

- can we try enabling the routing capability --- update enabled in this block to true ... 

 DrivingDirectionSettings: {
            GetDirections: false,
            RouteServiceURL: "http://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",
            RouteColor: "0,0,225",
            RouteWidth: 6,
            Transparency: "0.5",
            RouteUnit: "MILES"
        },


@NikkiGolding

**Comment by conklinbd** [comment]
@jessnoo for the driving directions it appears that we need an AGOL account to use the routing service (error is that token is required). I think the solution to this would be to add the routing service to the portal and store credentials with the item. I have enabled directions but not performed that step.

**Comment by conklinbd** [comment]
For the ....Loading... issue, it looks like it is trying to find the Map Service endpoint for EmergencyShelters. Since this is a hosted service there is no Map Service endpoint. This is where the legend comes from...I assume.

**Comment by conklinbd** [comment]
@jessnoo is this still an issue? Do we need to keep debuging this app?

**Comment by jessnoo** [comment]
@conklinbd I think we need to call it for this release. I'm not sure what's causing the basemap and legend issues.

**Comment by conklinbd** [comment]
Ok. Verified and closed
