### ISSUE TITLE
"What is Web GIS?" Story Map not quite done, but consider for TEM Release

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1084]
I've submitted a story map 'What is Web GIS?' to the Demo Review group.  This is a Map Series story map made up of a bunch of Map Journal story maps, web maps and web apps.  All of these have been submitted to the Demo Review group. 

This originally pointed to content on my own older Ops Server and I have been in the process of pointing it to content on NSEC. I intended to finish that work this week but the internet connection from my hotel room in Germany has not been great and I've not been able to do so.   I will continue to slowly make updates but will miss the 3pm deadline today. I will also populate the item data for each of the items.

I think this is a valuable presentation to have on the Ops Server so hope it will make the release.

Here is the content that was shared with the Demo Review group today:
![image](https://cloud.githubusercontent.com/assets/3383476/10204984/011776e0-67bf-11e5-92ce-513256f90109.png)

I also need to share the PPT that created the slides for the story map but need to wait for a more stable internet connection to do so.  I should also copy this to the DemosAndScripts folder but not sure which subfolder it should go into since it isn't solution-specific.  Should I create a new folder?

Hopefully all of this makes sense, let me know if there are any questions/comments.  Unless I hear otherwise I will comment here when the Story Map is done.

**Comment by conklinbd** [comment]
@kerryrobinson I think this can make it on the release still. Please push to get these updates on the Portal content done ASAP.

For the new Demo, go ahead and make a folder for Global NS team.

**Comment by conklinbd** [comment]
@kerryrobinson can assign to me to review for release when she is ready.

**Comment by kerryrobinson** [comment]
@conklinbd , Thanks, another issue I have is that I'm not sure if the content I'm pointing to will make it onto the final release or not, so that will need to be checked during your review.

**Comment by conklinbd** [comment]
@kerryrobinson should I be waiting to review the content until you are done...or is the stuff you shared to demo review completely ready for release?

**Comment by kerryrobinson** [comment]
I think it'll be best to wait until it is all done, although if you want to take an initial look now and suggest anything I need to fix generally speaking (item details, etc) that is fine too.  Because this is different than other content on the Ops Server I'm not sure the best way to share and describe it.  The main app is the What is Web GIS story map (https://nsec.esri.com/arcgis/apps/MapSeries/index.html?appid=faef542a74e141398c05c43379a67004), everything else is referenced by that app.

I should be able to finish it up tonight, I'll let you know as soon as it's done.

**Comment by kerryrobinson** [comment]
@conklinbd  OK, all of the content is done for this. You can go ahead and review.

**Comment by conklinbd** [comment]
I am going to reassign items as I release them. I am creating a new user called DemoNationalSecurity for content owned by the Global National Security Team.

**Comment by conklinbd** [comment]
Ok. I finished releasing the content from your WebGISStoryMap Folder.
Many items were missing descriptions. I created a generic description for those items from your high level document and linked it back to that presentation. 

For thumbnails that were missing I just used the generic thumbnail from your presentation. 

I added tags, credits and delete protection to each item.

**Comment by kerryrobinson** [comment]
Thanks @conklinbd looks good .  Should the main story map be shared with any group so that it'll be discoverable?  Featured Maps and Apps or create a new group for Platform Demos or something similar?

**Comment by conklinbd** [comment]
I will add to Featured Maps and Apps. Good idea.

**Comment by pshowalter** [comment]
On the "What is Web GIS?" app, Web Maps tab, "Web Map" frame.  Typo "mashi" should be "mash".

[Web Map](https://nsec.esri.com/arcgis/apps/MapSeries/index.html?appid=faef542a74e141398c05c43379a67004)
Web Maps **mashi** up information from distributed sources, but they also allow you to configure an application-ready information product.

**Comment by kerryrobinson** [comment]
@pshowalter  good catch!

@conklinbd can you go ahead and fix the spelling mistake in this Map Journal?  id:47a2a3b4659b41c08e6029353eb7b272

**Comment by kerryrobinson** [comment]
I'm going to open a new issue for the spelling mistake since this one is closed.
