### ISSUE TITLE
Cannot Publish GP Services

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1085]
Not able to publish GP Services to OpsServer. Took the necessary steps to uninstall and reinstall Desktop (ArcMap) and ran into the same issue. This has only been tested on one machine.

**Comment by elinz** [comment]
@topowright What if any error messages did you receive when you attempted to publish the GP service?

**Comment by jrweakland** [comment]
@topowright - please set the proper labels, milestone, and assignee when you create an issue in the repo.

**Comment by topowright** [comment]
I feel it is important to include an application that shows the Incident Analysis Tools in the web using the incident data over the new geography. This would include the following items that would need to be included: 

GP Tools: 
Cluster Analysis
CLBLOC 
Incident Hot Spots
Incident Hot Spots by Area
Percent Change
Web map for base data display to include: 
Incidents , Roads and Districts

**Comment by topowright** [comment]
@elinz No messages, but I do have my error reports from desktop if that helps.

**Comment by elinz** [comment]
@topowright Please include the error information.

**Comment by conklinbd** [comment]
@topowright is this an issue you need resolved for the Ops Server release?

**Comment by topowright** [comment]
@elinz @nfeuerstein The issue was due to the GP tools being ran in ArcGIS Pro previously to me trying to publish these tools with ArcMap. I have been able to download a fresh cut of the tools and published one of the GP tools using the Incident data over Cali. I will now finish publishing  the rest of these items.
