### ISSUE TITLE
Time Span Analysis

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1087]
https://nsec.esri.com/arcgis/home/item.html?id=bbf4a2e6efba41fcb5579e7c6d81f3fc

- [x] Does this require a specific version of Esri Maps for Office?
- [x] Does the phrase "All scenario data was provided by the Sonoma County Sheriff Department and has been aggregated to intersection center points." belong in the Description, or Access and Use Constraints?
- [x] Do you mean:

>Through Time Span Analysis, or aoristic analysis, we can calculate the probability that an event occurred at a location within given temporal parameters and assign this temporal probability weight to the incident.

__or__

>Through aoristic or time span analysis, we can calculate the probability that an event will occur based on the fact that it occurred at a location within given temporal parameters, and assign this temporal probability weight to the incident.

**Comment by nfeuerstein** [comment]
No specific version - as long as publishing a map is supported in all newer versions we'll be good in the future as well.  The algorithms are basic Excel functions.
