### ISSUE TITLE
Duplicate ISR Mission Reports web maps

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1088]
@ScottCecilio @jrweakland @nfeuerstein 
Appears we have a duplicate item, ISR Mission Reports Web Map
ISR Mission Reports from Aerial Assets id=d1d694ff35d34f29b1b16b54a72e0e4f
ISR Mission Reports - Land Operations id=6da870dbe58743f6b8037f05a6d98102

I confirmed with Scott C that the latter is used for the Land Ops demo. Do we still want to release (demo user) the ISR Mission Reports from Aerial Assets too?

Assigning to @nfeuerstein since the one in question was shared by her.

**Comment by nfeuerstein** [comment]
It looks like they are both owned by DemoMilitary now, is this still an issue?  For what its worth, The Aerial Assets one was created by @phil7277 in support of the ISR Demo.  @phil7277 might be able to better explain the differences.

**Comment by phil7277** [comment]
@nfeuerstein, The original webmap was created to power the GEOFORM (ISR Mission Report) and the ISR Dashboard. @ScottCecilio  created a new one for the Land OPS demo calling the same feature layer which powers another GEOFORM he creates and a browser based dashboard.

**Comment by conklinbd** [comment]
@lfunkhouser Does this answer your question?

**Comment by lfunkhouser** [comment]
@conklinbd Yes. We will have some ISR Mission Reports items released by Demo Military and some released by Demo Intelligence.
