### ISSUE TITLE
Mission Report (Feature Layer) description is for web map

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1089]
@ScottCecilio The description for "Mission Report (Feature Layer) id:d78f22ee0b5e454588b9a0883cfd8d22" indicates that this is a web map and not a feature service. Can you update?

**Comment by ScottCecilio** [comment]
I do not own this anymore,  can you reassign so I can provide clarification?

**Comment by conklinbd** [comment]
I do not see this item any more. Is this issue still valid @ScottCecilio or @lfunkhouser

**Comment by ScottCecilio** [comment]
https://nsec.esri.com/arcgis/home/item.html?id=b0d5bd4b97d34882adfbae9def6cc309

I need a feature service for Land Operations and not map service.  As long as the feature servic, https://nsec.esri.com/arcgis/home/item.html?id=d78f22ee0b5e454588b9a0883cfd8d22, then I will be good to go.

**Comment by conklinbd** [comment]
Item id:d78f22ee0b5e454588b9a0883cfd8d22 was not released yet. 
@lfunkhouser this item is shared with demo review.

**Comment by conklinbd** [comment]
#1212 depends on this issue

**Comment by lfunkhouser** [comment]
Released by Demo Military

**Comment by conklinbd** [comment]
Verified
