### ISSUE TITLE
Service "Hosted//Ebola_Outbreak.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1093]
ERROR: Service "Hosted//Ebola_Outbreak.MapServer" is associated with a portal item (cf99f0d389464018b1054df2e7a789cc; MapServer) that does not exist.

Was this service meant to be deleted?

**Comment by conklinbd** [comment]
Based on the lack of activity associated with this issue, I will delete the service.

**Comment by conklinbd** [comment]
Service deleted @elinz.

**Comment by elinz** [comment]
Verified that service no longer exists. Closing issue.
