### ISSUE TITLE
Service "Test//ClusterAnalysisFSInput.GPServer" is associated with a portal item that does not exist.

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1094]
Service "Test//ClusterAnalysisFSInput.GPServer" is associated with a portal item (9c28c57d804f4df1babc8db52e9e3856; GPServer) that does not exist.

Was this service meant to be deleted?

**Comment by conklinbd** [comment]
@nfeuerstein I will delete this service today at 1100.

**Comment by nfeuerstein** [comment]
@conklinbd @elinz I would assume anything in 'test' can be deleted.

**Comment by elinz** [comment]
@nfeuerstein you would hope you could assume this, however, people are releasing content that references services in the "test" folder.

**Comment by conklinbd** [comment]
I have deleted the Cluster Analysis GP Service and associate Map Service Output.

**Comment by conklinbd** [comment]
To @elinz  to verify.

**Comment by elinz** [comment]
@conklinbd GP service Test//ClusterAnalysisFSInput.GPServer still exists as well as the related MapServer.

**Comment by elinz** [comment]
@conklinbd I'll go ahead and delete these services.

**Comment by elinz** [comment]
Fixed and verified. Closing issue.
