### ISSUE TITLE
Sudan Displaced Persons Camps

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1095]
id=b10809ff4307417190eae99e855f81a4

- [x] Description and Summary are the same
- [ ] Needs Legal Review... Is scenario data notional, or from somewhere?
- [X] Delete Protection Disabled

**Comment by karlterrey** [comment]
@nfeuerstein @sschwoppe The Story Map needs photos credits for each photo put on Box. Some photos need to be cited in the ap as well.

**Comment by conklinbd** [comment]
Based on discussion it seems like we have permission but we need to ensure the citation is present.

**Comment by conklinbd** [comment]
The item is current owned by @nfeuerstein but this issue is assigned to @sschwoppe who is fixing this item?

**Comment by nfeuerstein** [comment]
I'll do it.  @karlterrey it looked to me like all images in the app were cited.  I'll update the credits on box, but can you point out the photos in the app that weren't cited?

**Comment by karlterrey** [comment]
@nfeuerstein Sure thing. 
On the Home Section the Main Stage Photo has to be specifically credited - 'Robert Stansfield/Department for International Development'
On Section Four the Photo needs to be specifically credited- 'Robert Stansfield/Department for International Development'

**Comment by nfeuerstein** [comment]
Updated the photo credits in the story map.
