### ISSUE TITLE
Service Definition item (RoadClosures) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1096]
Hosted service RoadClosures/FeatureServer no longer exists, but associated service definition item exists
id: 8df4f2e5b7de4665b048c938473db9af type: Service Definition

**Comment by conklinbd** [comment]
@jessnoo This was probably an artifact of the publishing issue. You should just delete that service definition from your account.

**Comment by jessnoo** [comment]
yep -- will do. thank you!

**Comment by jessnoo** [comment]
@elinz the roadclosures service definition has been deleted.

**Comment by elinz** [comment]
Verified that service definition was deleted. Closing issue.
