### ISSUE TITLE
All the basemap Web Map are owned by ReleasedIntel, should be owned by ReleasedOpsServer

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1097]

**Comment by lfunkhouser** [comment]
Changed owner from ReleasedIntel to ReleasedOpsServer for the following basemap web maps;
Imagery Basemap
Dark Grey Canvas
Imagery Reference Basemap
Oceans Basemap
Terrain Basemap
Topographic Basemap
Light Grey Canvas Basemap
Streets Basemap

**Comment by elinz** [comment]
Verified fixed. Closing issue.
