### ISSUE TITLE
Web Map "Monterey Airport (Overview)" being released as demo content references a test service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1098]
Web Map "Monterey Airport (Overview)" (e9afca99ffa14bf0b064df6631210f60) references service item "SIGINT" (24dc0dce9c6949a889e516725757cbf0) and service was published to test folder (Test/SIGINT/FeatureServer/0).

If the SIGINT feature service is really needed in this web map then the service has to be published to a non-test folder and item has to go through release or demo workflow.

**Comment by elinz** [comment]
FYI: This web map is consumed by multiple web apps or operation views.

**Comment by jrweakland** [comment]
@ScottCecilio - You will need to get the SIGINT service out of the test folder on into the Military folder for the service to be published. This needs to happen today. Be aware that moving the service might "break" the items that are consuming the service.

**Comment by conklinbd** [comment]
Based on the fact that the symbology for this service is not good, all of the example I could find of this service are not good I decided to remove this service from the web map and saved with the layer removed. I am deleting the test service.

**Comment by conklinbd** [comment]
@elinz let me know if any other released content depended on this service. I will fix that item by removing the layer.

**Comment by elinz** [comment]
e9afca99ffa14bf0b064df6631210f60: Verified that layer was removed from this web map. No other released or going to be released consume this layer. Closing issue.

**Comment by ScottCecilio** [comment]
I use this layer in my Dashboard for Land Ops.  Should I just publish this today?
