### ISSUE TITLE
Country Boundaries needs Access and use constraints

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1099]
@nfeuerstein Country Boundaries service need Access and Use Constraints.  @karlterrey can help with wording for those services for demo purposes only; however, we still need to cite where we got the data.

- [ ] Country Boundaries Feature Layer id:086c5358415e4a948764385685240cb7
- [ ] CountryBoundaries id:a1956f5df1d34a1fbe8c58e3b5e0b1b4

**Comment by conklinbd** [comment]
@nfeuerstein @jrweakland @karlterrey @sschwoppe @lfunkhouser @elinz 
Based on the review from legal I am going to delete all Ebola content at 1100 today.

**Comment by conklinbd** [comment]
I deleted this item.
