### ISSUE TITLE
Districts in West Africa with reported Ebola outbreaks needs Access and Use Constraints

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1100]
Districts in West Africa with reported Ebola outbreaks id=b8966bd015e64a6d9576a57573c9610e needs Access and Use Constraints

@karlterrey can help with demo content wording; however, we still need to cite data

**Comment by conklinbd** [comment]
@nfeuerstein @jrweakland @karlterrey @sschwoppe @lfunkhouser @elinz 
Based on the review from legal I am going to delete all Ebola content at 1100 today.

**Comment by conklinbd** [comment]
I deleted this item.
