### ISSUE TITLE
Ebola Healthcare Facilities in West Africe needs Access and Use Constraints

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1101]
Ebola Healthcare Facilities in West Africa id=d1a00d57cea2458a887d3a6b4052952b needs Access and Use Constraints

@karlterrey can help with demo content wording; however, we still need to cite data

**Comment by jrweakland** [comment]
I have sent @karlterrey a quick look document with metadata and access and use constraints for this service. We shall see what legal has to say about it.

**Comment by conklinbd** [comment]
I have deleted all ebola related content.
