### ISSUE TITLE
Ebola Outbreaks portal items need more information

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1102]
Ebola Outbreaks items are missing Access and Use Constraints.  These items are planned to be released under different users. If the Web Map and Web App are released under the "Released" owner, the Feature Layer that is used by them will need to be released under "Released" owner, but will be released as a "Demo" owner. I've combined the following portal items into the same issue because they will most likely have the same Access and Use Constraints. These Ebola Outbreaks items need more information:

**Ebola Outbreaks feature service id:8592ab25641446a0829964daf45a5548**
- [ ] Access and Use Constraints
- [ ] Item is identified to be released under a Demo owner, please check to see if this should be a Released owner instead
- Note: The summary and description are the same and should be modified; however, that will not hold up the release.

**Ebola Outbreaks in West Africa (DEMO) id:f7026a1e91814f1caa1fac5a5ee656fa**
- [ ] Access and Use Constraints
- [ ] Item will be released as a "Released" owner, please check to see if this should be a "Demo" owner instead
- Note: The summary and description are the same for this Web Mapping Application and should be modified; however, that will not hold up the release.

**Ebola Outbreaks in West Africa (DEMO) id:934c8c749bff49248a3eb23512793281**
- [ ] Description
- [ ] Access and Use Constraints
- [ ] Item will be released as a "Released" owner, please check to see if this should be a "Demo" owner instead

**Comment by conklinbd** [comment]
@nfeuerstein @jrweakland @karlterrey @sschwoppe @lfunkhouser @elinz 
Based on the review from legal I am going to delete all Ebola content at 1100 today.

**Comment by conklinbd** [comment]
I deleted this item.
