### ISSUE TITLE
Diversity And Ethnicity Web Map

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1105]
https://nsec.esri.com/arcgis/home/item.html?id=3d262ec7abdb4dbd925d7d9f37bd6e2d

- [x] Title: Uppercase A, maybe a more specific title?
- [x] Summary: Misspelled "block"
- [x] Description:

This web __map__ summarizes racial and ethnic diversity in a __multi-scale__ map by country, tract __,__ and block group. The Diversity Index shows the likelihood that two persons chosen at random from the same area, belong to different race or ethnic groups. The index ranges from 0 (no diversity) to 100 (complete diversity). The pop-up is configured to include the following information for each geography level:_(Hard Return Here)_
 - Diversity Index (Expressed as a percentage in the pop-up)
 - Population counts by race and ethnicity

The data shown is from Esri's Updated Demographic estimates using Census 2010 geographies. The map adds increasing __levels__ of detail as you zoom in, from country, to tract, to block group data.

A census block is a component of a block group identified by a four-digit code. Blocks are small in area, in general, especially in cities. However, blocks in rural or remote areas may cover hundreds of square miles. A block code that starts with a zero indicates a water-only block. A block group is a collection of one or more blocks and a statistical division of a census tract identified by a one-digit code. Block groups do not cross census tract or country boundaries. In general, a block group is comprised of 600 to 3,000 residents. A zero block group code indicates a water-only __block group__. Census tracts are small statistical subdivisions of a county, with 1,200 to 8,000 residents typically. The boundaries are usually delineated by local committees and do not cross county or state lines. Tracts are identified by a six-digit code, with an implied decimal between the fourth and fifth digit. ~~This service is for testing and demonstration purposes only. The service and its data may not be used for commercial or operational purposes.~~

- [x] Share with Demo Review
- [x] Enable Delete Protection

**Comment by nfeuerstein** [comment]
@joebayles - the demographics team wanted the statement: "This service is for testing and demonstration purposes only.  The service and its data may not be used for commercial or operational purposes" added to the service description.  Why'd you cross it out?

**Comment by nfeuerstein** [comment]
@joebayles nevermind.  Its in the access and use constraints. :)
