### ISSUE TITLE
Jenkins build server: modify to extract content for demo and released accounts only

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1106]
In the Jenkins build process, modify calls to PortalContentExtract.py and GetSDFiles.py to only extract and get sd files for the following portal accounts:

DemoEManagement,DemoIntelligence,DemoLGovt,DemoMilitary,DemoNationalSecurity,DemoParksGardens,DemoSGovt,DemoUtilities,ReleasedEManagement,ReleasedIntelligence,ReleasedLGovt,ReleasedMilitary,ReleasedOpsServer,ReleasedParksGardens,ReleasedSGovt,ReleasedUtilities

Need to modify these calls for today's build.

**Comment by ACueva** [comment]
added following code in settings.xml:

```
<property name="build.users.toextract" value="DemoEManagement,DemoIntelligence,DemoLGovt,DemoMilitary,DemoNationalSecurity,DemoParksGardens,DemoSGovt,DemoUtilities,ReleasedEManagement,ReleasedIntelligence,ReleasedLGovt,ReleasedMilitary,ReleasedOpsServer,ReleasedParksGardens,ReleasedSGovt,ReleasedUtilities"/>
<echo message="Build users = ${build.users.toextract}"/>
```

The following code in build.xml:

```
<exec dir="${install.location.ops-server-config}\Publish\Portal\portalpy" executable="${build.python.environment}/python.exe">
    <arg line="${install.location.ops-server-config}\Publish\Portal\PortalContentExtract.py ${build.ArcGISPortal.url} ${build.ArcGISPortal.adminuser} ${build.ArcGISPortal.adminpassword} ${build.ArcGISPortal.extract.Folder} ${build.users.toextract}"/>
    </exec>
```

Verified in this build that code is functioning:
http://servername:8080/job/Ops%20Server%20Release%20Builder/54/console

**Comment by elinz** [comment]
@ACueva Reopening. Examined OpsServerBuilds\Archive\20151002_0955\OPSServerInstall\Server\ServiceDefinitions folder and no SD files were copied so can't tell if GetSDFiles.py execution was modified to copy just these users. Thanks.

**Comment by elinz** [comment]
@ACueva Manually extracting sd files for released and demo users 10/5 08:50 so testing can continue.

**Comment by elinz** [comment]
@ACueva Do not extract portal content or SD files for those Demo and Released accounts which do not own content.

@lfunkhouser FYI.

**Comment by elinz** [comment]
@conklinbd @ACueva @lfunkhouser I assuming we shouldn't copy any templates for domains we won't have portal content for? i.e. local government, parks and gardens, etc.

**Comment by conklinbd** [comment]
We should copy all templates.

**Comment by ACueva** [comment]
CopySD build script modified to include ${build.users.toextract} variable.
