### ISSUE TITLE
Web map "Road Closures" references an external basemap 

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1109]
Web map "Road Closures" (id: d40a0fe45fdb4b809a0536e2e9ad7b5c) is referencing an ArcGIS online basemap https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer.

Typically, If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also. I don't know in the case of Emergency Management content for this release...this may be by design.

**Comment by jessnoo** [comment]
Hi @elinz is this similar to #1110 ?

**Comment by elinz** [comment]
@jessnoo Yes, I see @conklinbd comment that all EM content will use AGOL basemaps. I'm closing this issue.
