### ISSUE TITLE
Web map "Evacuation Zones Map" references an external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1110]
Web map "Evacuation Zones Map" (id: 287ed95406db4d2f9a1700587267c1f0) is referencing an ArcGIS online basemap:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer   

Typically, if the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also. I don't know in the case of Emergency Management content for this release...this may be by design.

**Comment by jessnoo** [comment]
@elinz Yep, @conklinbd and I discussed this yesterday. Because the basemaps on the nsec server aren't cached to level of our sample data, we agreed to use the online basemaps for Emergency Management.

The regions that we would need more detailed cache are for Virginia Beach area and Naperville.

**Comment by conklinbd** [comment]
@elinz all EM content will use AGOL basemaps for this release.
