### ISSUE TITLE
Map service item "Military/MissionReport" needs to be moved into the Demo Review process

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1112]
@ScottCecilio @jrweakland The service Military/MissionReport has both a feature service and a map service. The feature service item d78f22ee0b5e454588b9a0883cfd8d22 has been shared with the Demo Review group. The map service item b0d5bd4b97d34882adfbae9def6cc309 (which was assigned to @ScottCecilio a few minutes ago) needs to have it's summary, description, etc edited and shared with the Demo Review group.

**Comment by jrweakland** [comment]
Ready for verification.

**Comment by elinz** [comment]
Verified. Closing issue.
