### ISSUE TITLE
Review File based data for permissions

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1113]
Ensure that all file based data have sufficient data permissions

**Comment by lfunkhouser** [comment]
@karlterrey Is this complete?

**Comment by karlterrey** [comment]
@lfunkhouser Yes this is not complete.

**Comment by joebayles** [comment]
Assigning to @jrweakland and @karlterrey to complete together.

**Comment by jrweakland** [comment]
Completed on 09/12/2016
