### ISSUE TITLE
Geofence Sync Rule names should follow naming conventions

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1118]
@jfrygeo Need to change geofence names and synch names to follow naming conventions. Probably want to append MaritimeOps_ to the beginning of names.

**Comment by jfrygeo** [comment]
About to board a plane. Does this need to get fixed before deadline?

John

Sent from my iPhone

On Oct 2, 2015, at 4:08 PM, Patrick Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #1118<https://github.com/Esri/ops-server-config/issues/1118> to @jfrygeo<https://github.com/jfrygeo>.

**Comment by pHill5136** [comment]
By next friday.

**Comment by pHill5136** [comment]
John I changed the name for the synchronization. Closing issue.
