### ISSUE TITLE
ArcGIS Predictive Analysis Tool - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1119]
@ircampbell @kAilshie @rbernstein  check email reminder for details of what goes where.

**Comment by kAilshie** [comment]
@BobBooth  @rbernstein I believe @ircampbell has all this content and this issue should be assigned to him.  However, I do not know if he is a member of the defense group to be able to update assignee and/or labels because I was not a member before today.
