### ISSUE TITLE
  Edit New issue Geofence Sync Rule names should follow naming conventions

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1120]
@helyx-rterry @abrowning80 Need to change your geofence synchronizations for opsserver release. Most are just numbers. Probably want to have Sustainment_, AirOps_ etc. appended to the beginning of the names.

**Comment by abrowning80** [comment]
@pHill5136 - Patrick, you are almost certainly looking at some seriously legacy stuff so please don't act on it and wait for us to send updated versions of both Sustainment and Air Operations. Note your point re geofences we will amend any erroneous fences. Will export Sustainment and Air Ops out of GEE and send to you either in this sprint or next.

**Comment by jrweakland** [comment]
@abrowning80 and @helyx-rterry - this needs to be fixed before this friday 10/09/2015

**Comment by pHill5136** [comment]
@helix-rterry @abrowning80 @conklinbd @jrweakland  I chanced names for these, but I noticed the fences point to the sample cities service on default. If these are not needed please delete synchronizations by Friday or if they are needed point them to the proper service. 

Thanks -P

**Comment by pHill5136** [comment]
@helix-rterry @abrowning80 @conklinbd @jrweakland Okay just saw previous response. Is it safe to just delete?

**Comment by abrowning80** [comment]
@pHill5136 @helyx-rterry yes it is fine just to delete them as we will send over the new updated version when they are ready to replace these.

**Comment by pHill5136** [comment]
@jrweakland @helyx-rterry @abrowning80 I deleted these. And closing.
