### ISSUE TITLE
ArcGIS for the Military: Maritime Operations: An Overview - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1121]
@jfrygeo check email reminder for details of what goes where.

**Comment by jfrygeo** [comment]
Trying to get video from http://geochannel.esri.com/index.cfm?event=video.view&channelId=38&videoId=5456 and be able to clip into segments, but may be this is only Esri Internal.

**Comment by jfrygeo** [comment]
Published link to http://geochannel.esri.com/index.cfm?event=video.view&channelId=38&videoId=5456 for the Maritime Operations at 2015 UC.

**Comment by jfrygeo** [comment]
Copied PPT and PDF for the presentation to: \\disldb\OpsServerStaging\2015_Q4\Resources\2015UCPresentations\ArcGIS for the Military_Maritime Operations_An Overview

**Comment by jfrygeo** [comment]
Documentation Added for "ArcGISPro_RasterFunctions_SeaState"
<ln>\\disldb\OpsServerStaging\2015_Q4\DemoAndScripts\Military\MaritimeOperations\ArcGISPro_RasterFunctions_SeaState\Documents

Video added for "ArcGISPro_RasterFunctions_SeaState"
<ln> \\disldb\OpsServerStaging\2015_Q4\Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\\SeaStatesAnalysisRasterFunctions.mp4

**Comment by jfrygeo** [comment]
Documentation Added for "Maritime Decision Aid Template"
<li>\disldb\OpsServerStaging\2015_Q4\DemoAndScripts\Military\MaritimeOperations\MaritimeDecisionAidTemplate\Documents

Video added for "Maritime Decision Aid Template"
<li>\disldb\OpsServerStaging\2015_Q4\Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\MaritimeDecisionAidTemplate.mp4

**Comment by jfrygeo** [comment]
Documentation Added for "Esri Maps for Office - Piracy"
<li>\\disldb\OpsServerStaging\2015_Q4\DemoAndScripts\Military\MaritimeOperations\EsriMapsForOffice_Piracy\Documents

Video added for "Esri Maps for Office - Piracy"
<li> \disldb\OpsServerStaging\2015_Q4\Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\EsriMapsForOffice_AntiShippingActivityMessages.mp4

**Comment by BobBooth** [comment]
@jfrygeo - thanks!
We're trying to keep the machine path names out of this, will be deleting them from your comments.

**Comment by jfrygeo** [comment]
Documentation Added for "Maritime Chart Server"
<li> DemoAndScripts\Military\MaritimeOperations\MaritimeChartServer\Documents

Video added for "Maritime Chart Server"
<li> Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\MaritimeChartServer.mp4

**Comment by jfrygeo** [comment]
Documentation Added for "Web AppBuilder Maritime Threat Tools"
<li>DemoAndScripts\Military\MaritimeOperations\WebAppBuilder_MaritimeThreatTools\Documents

Video added for "Web AppBuilder Maritime Threat Tools"
<li>Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\Web_AppBuilder_MaritimeThreatTools.mp4

**Comment by jfrygeo** [comment]
Documentation Added for "Portal GeoForm - Maritime Contacts"
<li> DemoAndScripts\Military\MaritimeOperations\PortalGeoForm_MaritimeContacts\Documents

Video added for "Portal GeoForm - Maritime Contacts"
<li> Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\PortalGeoForm_MaritimeContacts.mp4

**Comment by jfrygeo** [comment]
Documentation Added for "Operations Dashboard - Maritime Domain Awareness"
<li> DemoAndScripts\Military\MaritimeOperations\OperationsDashboard_MaritimeDomainAwareness\Documents

Video added for "Operations Dashboard - Maritime Domain Awareness"
<li> Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\OperationsDashboard_MaritimeDomainAwareness

**Comment by jfrygeo** [comment]
Documentation Added for "Predictive Analysis Tools - Panga Boats"
<li> DemoAndScripts\Military\MaritimeOperations\PredictiveAnalysis_Panga_Drugs\Documents\Maritime\Documents

Video added for "Predictive Analysis Tools - Panga Boats"
<li>Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\PredictiveAnalysisTools_Panga.mp4

**Comment by jfrygeo** [comment]
Added Demo Key word document here: 
<li> DemoAndScripts\Military\MaritimeOperations\2015_AFM-MO_TEM.docx

**Comment by jfrygeo** [comment]
@BobBooth please verify and close issue

**Comment by BobBooth** [comment]
@jfrygeo - Contents verified, thanks!
