### ISSUE TITLE
Esri Defense Mapping: Enterprise Production Management - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1123]
Tagging myself as Greg doesn't seem to have an account.

**Comment by conklinbd** [comment]
@BobBooth not sure why this is on our list. We don't normally release Defense Mapping with Ops Server.

**Comment by BobBooth** [comment]
@conklinbd - it was on the list I got from @jrweakland 
Happy to close if not relevant.
