### ISSUE TITLE
ArcGIS for the Military: Sustainment and Logistics - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1124]
@joebayles  check email reminder for details of what goes where.

**Comment by joebayles** [comment]
@abrowning80 you should upload your stuff before we close this issue.

**Comment by abrowning80** [comment]
@joebayles What stuff did you want me to post up?  At UC you said that you were quite happy to do the videos so have not kept any of the stuff I used.

**Comment by joebayles** [comment]
@BobBooth uploaded what I can.

**Comment by BobBooth** [comment]
Verified content is there.
