### ISSUE TITLE
Using ArcGIS to Manage Military Bases and Facilities - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1125]
@jfrygeo check email reminder for details of what goes where.

**Comment by jfrygeo** [comment]
Videos and links are here: 
<ln>"\\disldb\OpsServerStaging\2015_Q4\Resources\Videos\2015 UC Demo Theater Managing Bases and Facilities"

Powerpoint is here: \\disldb\OpsServerStaging\2015_Q4\Resources\2015UCPresentations\2015UC_ManagingBasesAndFacilitiesDemoTheater.pptx @BobBooth

**Comment by BobBooth** [comment]
@jfrygeo - Thanks! Closing.
