### ISSUE TITLE
Analyzing Maritime Weather - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1126]
@jfrygeo  check email reminder for details of what goes where.

**Comment by jfrygeo** [comment]
PPT is here 
<li> \\disldb\OpsServerStaging\2015_Q4\Resources\2015UCPresentations\2015UC_AnalyzingMaritimeWeatherDemoTheater.pdf

Video for  Sea States Analysis with Raster functions is here:
<li> \\disldb\OpsServerStaging\2015_Q4\Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations  

(Demonstration is used in both presentations).

@BobBooth - please verify and close comment

**Comment by BobBooth** [comment]
Verified, closing.
