### ISSUE TITLE
ArcGIS for the Military: Domestic Operations: An Overview - post PPT & video for Ops Server release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1127]
@joebayles check email reminder for details of what goes where.

**Comment by joebayles** [comment]
Done, to @BobBooth to verify.

**Comment by joebayles** [comment]
@abrowning80 You should upload your stuff before we close this issue.

**Comment by abrowning80** [comment]
@joebayles What stuff did you want me to post up?  At UC you said that you were quite happy to do the videos so have not kept any of the stuff I used.

**Comment by BobBooth** [comment]
@joebayles - what is the title? I don't see anything with "Domestic Operations" in the title.
Is there a corresponding video?

**Comment by joebayles** [comment]
@BobBooth I've uploaded what I can.
