### ISSUE TITLE
Geocoding Services

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1128]
id=9206d989a1614f049dfc23149d6f39f7

- [x] Supported Countries: What does that mean? I have a feeling that verbiage came from http://www.arcgis.com/home/item.html?id=305f2e55e67f4389bef269669fc2e284, but not sure. If so, please add the rest of it for clarification.

id=470692fb1bee417abed4fe48a826eb84
- [x] Supported Countries: What does that mean? I have a feeling that verbiage came from http://www.arcgis.com/home/item.html?id=305f2e55e67f4389bef269669fc2e284, but not sure. If so, please add the rest of it for clarification.

**Comment by nfeuerstein** [comment]
Updated descriptions.
