### ISSUE TITLE
ArcGIS for Intelligence: An Overview - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1129]
for Ops Server release
Deadline 9Oct
see email for post location
@sschwoppe @nfeuerstein

**Comment by elinz** [comment]
@CraigCleveland Please verify if this task still needs to be completed and this current release. Content cutoff for portal/server content is 13 Sept. Cutoff for DemoAndScripts and Resource content is 16 Sept.

**Comment by CraigCleveland** [comment]
@elinz - confirming that to the best of my knowledge this task still needs to be completed.  Candidly I have no window into the status of this at all.  Sorry...

**Comment by joebayles** [comment]
Closing because this is old.
