### ISSUE TITLE
Hosted service MonterreyAirportCompoundMap_WFL/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1131]
@ScottCecilio Can you republish this service using ArcGIS Pro before 16:00 deadline?

**Comment by ScottCecilio** [comment]
That's a no.

**Comment by ScottCecilio** [comment]
This service has been republished:

https://nsec.esri.com/ags/rest/services/Hosted/MonterreyAirportCompoundMap_WFL/FeatureServer

Please verify and close

**Comment by elinz** [comment]
Verified that Service Definition item for the hosted feature service in question does exist. Closing issue.
