### ISSUE TITLE
MAoW file based data needs data permissions

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1134]
The following data is missing data permissions in the data folder on the portal:
- [x] Data in the ClimateData folder
- [x] Data in the NetCDFData folder
- [x] Climate geodatabases in the Geodatabase folder
- [x] OperationalWeather geodatabase in the Geodatabase folder

Please also create a folder for MAoW on Box and file copies.

**Comment by jrweakland** [comment]
Data permissions are located on the data folder and on Box.

**Comment by lfunkhouser** [comment]
@karlterrey Assigning to you to test it it meets your critera

**Comment by karlterrey** [comment]
@lfunkhouser @jrweakland fix as assigned. Closing this.
