### ISSUE TITLE
Forecast Adversary Methods Using ArcGIS PA Tools - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1135]
for Ops Server release
Deadline 9Oct
see email for post location

@ircampbell

**Comment by elinz** [comment]
Did this need to be completed for this current release?

**Comment by dfoll** [comment]
i would just close this. it's been a year and it hasn't been done, so i don't have much confidence it get ever getting done

**Comment by joebayles** [comment]
Closing because this is old.
