### ISSUE TITLE
Discern Activities of Interest Through Real-Time Analysis and Periodic Analysis - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1137]
for Ops Server release
Deadline 9Oct
see email for post location

@nfeuerstein

**Comment by conklinbd** [comment]
Slides have been copied. For video do you mean the technical workshop video?
@dfoll.

**Comment by conklinbd** [comment]
I will not have time to make a video so I am closing this.
