### ISSUE TITLE
DerivedLayers file based data needs data permissions

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1139]
There is a Predictive Analysis.gdb in the Data folder on portal. It is missing the data sources. 
Please create a folder on Box and file copies there too.

**Comment by dfoll** [comment]
@kAilshie

**Comment by dfoll** [comment]
@ircampbell said folder is here...
\\nsecdata\Data\DerivedLayers

please add permissions information there.... when you are done, reassign to me, and i will get it also moved to the appropriate place on box

**Comment by ircampbell** [comment]
https://esri.app.box.com/files/0/f/4883213041/DerivedLayers

@karlterrey Karl, let me know if you need any further information.  Hopefully I put everything in the correct locations.  Thanks.

**Comment by karlterrey** [comment]
Verified and closed.
