### ISSUE TITLE
ArcGIS Predictive Analysis Tools - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1140]
for Ops Server release
Deadline 9Oct
see email for post location
@rbernstein @kAilshie

**Comment by kAilshie** [comment]
@dfoll I think this is a duplicate of #1119

**Comment by dfoll** [comment]
pretty much... we will fix that up next... not sure why the previous one got entered

**Comment by ircampbell** [comment]
Video, script, and slides have been added here.... 
•	Videos and scripts: \\disldb\OpsServerStaging\2015_Q4\Resources\Videos
•	Presentation here: \\disldb\OpsServerStaging\2015_Q4\Resources\2015UCPresentations

**Comment by ircampbell** [comment]
@dfoll Please verify and close

**Comment by dfoll** [comment]
@ircampbell thanks
