### ISSUE TITLE
A Geospatial Approach to Cyber Security - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1141]
for Ops Server release
Deadline 9Oct
see email for post location

**Comment by ScottCecilio** [comment]
This is now owned by Darren Baird.

**Comment by conklinbd** [comment]
This is a duplicate of #1117. This wasn't presented at UC so we don't need to distribute it.

**Comment by conklinbd** [comment]
This will not be released with this release.
