### ISSUE TITLE
Adapting a Template to Your Organization - needs slides and videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1142]
for Ops Server release
Deadline 9Oct
see email for post location
@phil7277

**Comment by topowright** [comment]
@dfoll I am not sure what this presentation was covering so I have moved the milestone version after next.

**Comment by dfoll** [comment]
@topowright who was it that did this presentation at uc... i just had you assigned because your name was on it for the list i saw

**Comment by dfoll** [comment]
this workshop never actually happened at uc15
