### ISSUE TITLE
Using Rasters to Measure Impact of Weather on Military Operations - needs videos posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1143]
for Ops Server release
Deadline 9Oct
see email for post location

**Comment by abrowning80** [comment]
Hi Derek,  appear to have been very efficient and have deleted the email.  Can you post the location here please, thanks

**Comment by abrowning80** [comment]
This has been done please can you close the issue. Thanks

**Comment by elinz** [comment]
@dfoll Can you please verify that this task was completed and close if completed? Thank you.

**Comment by joebayles** [comment]
Closing because this is old.
