### ISSUE TITLE
Intelligence Support to Operations - needs video posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1146]
for Ops Server release
Deadline 9Oct
see email for post location
@ScottCecilio

**Comment by ScottCecilio** [comment]
There was no video from UC created and I posted the Land Operations video in the location which covers the Intelligence Support to Operations demonstration.  Please review and close.

**Comment by ScottCecilio** [comment]
@dfoll @phil7277 I created a video for Land Operations and have posted it.  I talked to @jrweakland and discussed with the the possibility of just making an additional copy for ISOP.  We both agreed that since these two videos would almost be identical it did not make sense to post them both.

**Comment by elinz** [comment]
@dfoll Can you please verify if this issue was fixed or requires more work? Thank you.
