### ISSUE TITLE
Discover Imagery Relevant to Your Mission – needs slides and video posted

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1147]
for Ops Server release
Deadline 9Oct
see email for post location

**Comment by NatalieCampos** [comment]
The slides have been posted.

**Comment by NatalieCampos** [comment]
The current version of the Discovery App needs to be rebuilt with different styling before I can make the video.  This will keep the video consitent with the demo/released version.

**Comment by NatalieCampos** [comment]
Video has been posed to \\disldb\OpsServerStaging\2015_Q4\Resources\Videos\ImageDiscovery
