### ISSUE TITLE
OperationalLayers / Incidents file based data needs data permissions

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1148]
The Data folder on the portal contains an OperationalLayers folder. In this is an Incidents folder. The incidents.gdb contains a SIGACTS file with data in it but no data permissions. If it is fictitious please note that.

**Comment by dfoll** [comment]
@jrweakland i went to look at this data.... this is incident data... it looks like someone moved the points as a whole data set from their original geographic location and just dumped them on monterey... some are floating out in the ocean. This same set of data was moved by the intel team and effort was put into making the incidents line up with something that may be more realistic. My very strong suspicion is that this data was moved from it's original geographic location and nothing was ever done with it. The data that moved by our team is located at 
\\nsecdata\Data\FoundationOverlays\IncidentData\Monterey_Incidents.gdb
i would vote that we just totally blow away the incident data located at 
\\nsecdata\Data\OperationalLayers\Incidents\Incidents.gdb\SigActs 
don't want to do that though without confirming that it's not being used (hopefully it is not, i just would like confirmation)

**Comment by dfoll** [comment]
@karlterrey this issue can be closed... the data in question that did not have permissions has been deleted... the entire "incidents" folder has been blown away

**Comment by karlterrey** [comment]
Verified as fixed and closed
