### ISSUE TITLE
EM: Story Map Journal Question

### ISSUE THREAD

**Issue by jessnoo** [Esri/ops-server-config#1151]
Hi guys -- Is there a special technique you use to get embedded images into Story Map Journals or Briefing Books on the OPS server?

@conklinbd 

something like this: 

![image](https://cloud.githubusercontent.com/assets/6181441/10256327/5a3a5e6c-6905-11e5-8be8-a2842479f62d.png)

**Comment by conklinbd** [comment]
@jessnoo Just put them in a folder on SolutionsWeb\Resources  and then use the URL to the image to embed the photo in the story map.

**Comment by jessnoo** [comment]
Thanks @conklinbd this worked!
