### ISSUE TITLE
FoundationOverlays / AdminBoundaries needs sources cited

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1153]
The Data folder on the portal contains a folder FoundationOverlays. In this is an AdminBoundaries folder containing a  .gdb. The data sources need to be completed and if fictitious that should be noted.

**Comment by dfoll** [comment]
@karlterrey this one was a simple fix... we had the permissions (through the demographics data) just needed documented according for "AdminBoundaries" ... please check and make sure everything is now legit

**Comment by karlterrey** [comment]
Verified and closed
