### ISSUE TITLE
FoundationOverlays / ChangeDetection file on Data needs data permissions

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1154]
The FoundationOverlays folder in the Data folder on the portal contains a folder ChangeDetection. In this is a ChangeDetection .gdb. The data sources and permissions need to be completed.
Also the data permissions need need to be put on Box.

**Comment by ScottCecilio** [comment]
@karlterrey @nfeuerstein If this is the .gdb that I created was created by myself using USDA NAIP Data.  The permissions from this are already added at the following locations:

\\disldb\OpsServerStaging\2015_Q4\DemoAndScripts\Military\LandOperations\Permissions

https://esri.box.com/s/djp97vhaiej2ejn24umjnkjcafucgxs0

**Comment by karlterrey** [comment]
Verified as fixed
