### ISSUE TITLE
FoundationOverlays / Elevation in Data folder needs data permissions on Box

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1155]
The Data folder on the portal contains a folder FoundationOverlays. In that is a folder Elevation. In this is an Elevation Sources spreadsheet containing data permissions. This needs to be placed on Box as well.

**Comment by dfoll** [comment]
i have moved the spreadsheet elevationsources.xlsx over to box

**Comment by karlterrey** [comment]
Verified and closed
