### ISSUE TITLE
FoundationOverlays / Hydrography needs data sources

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1156]
The Data folder on the portal contains a FoundationOverlays folder. In this is a Hydrography folder. All the data needs source information and permissions if necessary. 
Please also create a folder for Hydrography on Box and file data permissions if necessary.

**Comment by karlterrey** [comment]
@nfeuerstein We can't release this unless we know the data source.

**Comment by nfeuerstein** [comment]
The zip files in that Hydropgraphy folder aren't used in any services, so I removed it.
