### ISSUE TITLE
FoundationOverlays / Networks contains data permissions but no data

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1159]
In the Data folder on portal is a FoundationOverlays folder. It contains some data permissions but no data.

**Comment by dfoll** [comment]
@nfeuerstein please weigh on this... i am certain that @mfunk collected this data and originally built the services, but i believe we scrapped those services... they at least do not exist as services on portal anymore

**Comment by nfeuerstein** [comment]
@dfoll @mfunk did a lot of good work on some road and rail networks, but they were scrapped in favor of using TDS road and rail data.  We can probably delete the permissions since there are no services or data that need those permissions anymore.

**Comment by karlterrey** [comment]
Verified permissions have been removed and issue closed.
