### ISSUE TITLE
FoundationOverlays / OperationalImagery needs data permissions put on Box

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1161]
In the Data folder on portal is a FoundationalOverlays folder. In this is an OperationalImagery folder. The data permissions needs to be put on Box.

**Comment by dfoll** [comment]
just a note for the followers of this issue... the spreadsheet is there, but i did not move it, because it is not complete, it currently is only filled out for the landsat.... other data sources, as far as a i can see have not been added to it yet @nfeuerstein @Nekillims

**Comment by dfoll** [comment]
previous comment was nonsense, the spreadsheet was opening up and only showing the last two entries in the spreadsheet.... i didn't realize the other permissions were above them in the part of the table not showing... spreadsheet is moved over.to box. @karlterrey you can verify and close

**Comment by karlterrey** [comment]
Verified as fixed. Closed.
