### ISSUE TITLE
FoundationOverlays / Weather needs data permissions 

### ISSUE THREAD

**Issue by karlterrey** [Esri/ops-server-config#1163]
In the Data folder on portal is an FoundationalOverlays folder. In this is a Weather folder. The data needs source information and data permissions.
This also needs to be put on Box.

**Comment by karlterrey** [comment]
@nfeuerstein We cant release this without data permissions or source info

**Comment by nfeuerstein** [comment]
The zip files containing data in that folder are not used in any services so I removed them.
