### ISSUE TITLE
Illicit Drug Grows

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1166]
id=a4c628fc4aa04a05ad30fd32613df340

- [x] If this is a demo item only, change the sharing to Demo Review instead of Release Review

__or__

- [ ] If this is a release item, elaborate in the description to be more specific (where, how, how is the information presented, etc.)

id=f6e165bf688c46daa06048fed1fb43e9

- [x] The description makes mention of filtering and summarizing, but I don't see that functionality when I View the Application.
![image](https://cloud.githubusercontent.com/assets/5016557/10288574/793e688a-6b4e-11e5-970f-ad228f7f60db.png)

**Comment by nfeuerstein** [comment]
Fixed it.

**Comment by joebayles** [comment]
Count and Summary work fine, but now it doesn't summarize by plant (that I can see). Pop-ups now just list count and sum.

**Comment by conklinbd** [comment]
This item has been released already. I am closing this issue.
