### ISSUE TITLE
Image Discovery web app text color is unreadable in IE

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1167]
The text for the metadata and buttons for images is white and unreadable for the Image Discovery web map in Internet Explorer id=7fdb5ddd53a54766ae8641cb8c4609da 

The following is displayed after selecting an area
![image](https://cloud.githubusercontent.com/assets/3800729/10288636/f4670152-6b4e-11e5-8e55-e2774382d944.png)

Clicking on a button and highlighting the text displays the information:
![image](https://cloud.githubusercontent.com/assets/3800729/10290112/131b88ae-6b57-11e5-8c6c-8819c025abea.png)

**Comment by conklinbd** [comment]
My impression is that this is a issue associated with this theme and CSS/Styling conflicts.
Maybe we should use a different theme.

**Comment by nfeuerstein** [comment]
I'm building another app now with a different theme.

**Comment by nfeuerstein** [comment]
I used a different theme and redeployed the app.  The styling seems to be more cohesive now.
