### ISSUE TITLE
Military Released Web Map includes unreleased service

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1173]
Web Map id:995d354c59694c01bbd1ff877441526a includes unreleased maritime boundary service. 
id:bf3cca6ca1bb45dd903e3df969156bd0

Currently owned by Jim

Most likely this service is in process of being released.

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review.

**Comment by lfunkhouser** [comment]
@jrweakland Released under owner DemoMilitary

**Comment by jrweakland** [comment]
Verified and closing.
