### ISSUE TITLE
Web Map includes unreleased service

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1175]
Web Map id:e9afca99ffa14bf0b064df6631210f60 includes unreleased service. dd6abcdbdca54ef993c5f2504cb35c57 Monterey Airport Compound Map.

Owned by Scott C. 
I believe this service was in process of getting replaced.

**Comment by ScottCecilio** [comment]
This was a temp map that I believe has now been deleted.  Please verify.

**Comment by conklinbd** [comment]
@ScottCecilio the map had id:e9afca99ffa14bf0b064df6631210f60. 
This map still exists. 

The service id:dd6abcdbdca54ef993c5f2504cb35c57 also still exists and is owned by your user.

Tip: You can search for these items by copying and pasting the id:guid into the search box on the portal.

**Comment by ScottCecilio** [comment]
This Web Map is awaiting release

**Comment by jrweakland** [comment]
@ScottCecilio - please provide id # of the map and I will review and forward for release.

**Comment by conklinbd** [comment]
This is the id of the service:  dd6abcdbdca54ef993c5f2504cb35c57 
Please review @jrweakland

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review and release.

**Comment by lfunkhouser** [comment]
Hosted service released by DemoMilitary
@ScottCecilio @jrweakland Is this the associated service definition for this hosted service: id:e227db9837eb461fac3de8624aff748f

**Comment by lfunkhouser** [comment]
Also released service definition by DemoMilitary

**Comment by ScottCecilio** [comment]
Is this ok to close now?

**Comment by conklinbd** [comment]
As soon as @jrweakland verifies.

**Comment by conklinbd** [comment]
Sorry. I just realized I created this issue. I assigned this to me to verify.

**Comment by conklinbd** [comment]
@ScottCecilio this service has been released and it looks good. 
@elinz The Web Map still references the old ID  19c1d72c36b34f10b25f5fa098ee076c this needs to be changed to dd6abcdbdca54ef993c5f2504cb35c57.

Can you change this or do you want me to hack the text data of the item?

**Comment by jrweakland** [comment]
@conklinbd - verified and ready for you to close.

**Comment by elinz** [comment]
@conklinbd I'll update the item data through code.

**Comment by elinz** [comment]
I've updated the web map e9afca99ffa14bf0b064df6631210f60 data by replacing 19c1d72c36b34f10b25f5fa098ee076c  with dd6abcdbdca54ef993c5f2504cb35c57

@lfunkhouser The service definition item for this service is e227db9837eb461fac3de8624aff748f.

Closing issue.
