### ISSUE TITLE
Services needs to be released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1177]
The FriendlyOperations service is not released but it is referenced in several released web maps.
id: e377b17ba01241ea80e74e75323e1776
The HosileOperations service is not released but it is referenced in several released web maps.
id: e51a4c093b644a7f9cd12faf7df95da6

**Comment by jrweakland** [comment]
@lfunkhouser - these are ready for your review.

**Comment by lfunkhouser** [comment]
@jrweakland Both items are released under owner DemoMilitary

**Comment by jrweakland** [comment]
Verified and closing
