### ISSUE TITLE
Maritime Collector App uses unreleased web map

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1178]
Web App Maritime Contact Collector uses an unreleased web map. Maritime Contacts Web Map for Geoform or ArcGIS for Collector
Owned by John id:e49682575da9423f9eaa221f8bb1278a

Also uses Maritime Contact service id:371ff339a8e9412d98f7a5030592df7e

Both need to be released

**Comment by lfunkhouser** [comment]
@jfrygeo Are the additional credits to be cited besides Esri for this web map?

**Comment by lfunkhouser** [comment]
Both have been released under owner DemoMilitary

**Comment by conklinbd** [comment]
Verified.
