### ISSUE TITLE
Access and Use Constraints for Esri data in Basic Diversity Demographics

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1180]
@karlterrey Can you take a look at the Access and Use Constraints for Basic Diversity Demographics id=28ab6e3f1f924c259282133706fd778e?  This data is a subset of Esri data and we need to clearly communicate that it isn't for use outside of Esri, Inc and Esri distributors. Can you suggest some wording?

**Comment by karlterrey** [comment]
@nfeuerstein where did this data come from? If it is from the Tapestry Team  we will need some documentation that we can use it and what restrictions we have. Mary C put up permissions on Box for the 2011/2016 demographic data that included email authorization. That would be a good model to work from.

**Comment by nfeuerstein** [comment]
@karlterrey this service was created from the same data Mary compiled permissions for.  @MaryClawson can you please update the "access and use contraints" for the demographic services to capture the permissions as provided by the Esri Demographics team.

**Comment by lfunkhouser** [comment]
@karlterrey @MaryClawson Nothing in the Access and Use constraints tells you what Esri people should do. Can there be something added like "For Esri Inc and Distributors" or something of the like?

**Comment by karlterrey** [comment]
@lfunkhouser @MaryClawson  If the data is the data provided by the Esri Demographics Team and covered by their permission document on Box then it is for public consumption.

**Comment by MaryClawson** [comment]
Fixed.  Ready for review.  @lfunkhouser
