### ISSUE TITLE
HostileOperations have units in Afghanistan

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1181]
@jrweakland Should there be hostile forces in Afghanistan and an unknown unit in the map?id=0750cc5ebd3b473184dbd428c3861134

If the Afghanistan data is going to remain in the map service, the extent of the item should be over Monterey, CA since that is what the item summary and description state.

**Comment by jrweakland** [comment]
@pHill5136 or @ScottCecilio - do you have a need for units in afghanistan? I do not recall that we still have a need for units and control measures there.

**Comment by pHill5136** [comment]
@jrweakland @ScottCecilio  This is just a copy of the old service used for gee. The Afghan troops are legacy. I can delete.

**Comment by jrweakland** [comment]
@pHill5136 @ScottCecilio - I have noticed that the installations, units, and equipment layers have unknown symbology. The SIGINT TRack does not have proper symbol with the layer. That layer is using single symbol.

**Comment by pHill5136** [comment]
Removed unknown symbology from layers

**Comment by pHill5136** [comment]
Sigint symbology restored.

**Comment by pHill5136** [comment]
@ScottCecilio Scott I fixed these.

**Comment by jrweakland** [comment]
Verified. @lfunkhouser

**Comment by lfunkhouser** [comment]
Verified as fixed.
Released by DemoMilitary
