### ISSUE TITLE
FriendlyOperations has units and control measures in Afghanistan

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1182]
FriendlyOperations id=6a33688d4bb6493aba882b86d934c4ce has units and control measures in Afghanistan as well as Monterey. If the units in Afghanistan support a specific demo, the description should be updated to explain this.

**Comment by jrweakland** [comment]
@pHill5136 or @ScottCecilio - do you have a need for units in afghanistan? I do not recall that we still have a need for units and control measures there.

**Comment by pHill5136** [comment]
These are leftover from the old server. I will delete.

**Comment by jrweakland** [comment]
@pHill5136 @ScottCecilio - this item also has unknown installations and equipment in the symbology. Any reason why?

**Comment by pHill5136** [comment]
removed unknown symbology.

**Comment by jrweakland** [comment]
Verified. @lfunkhouser

**Comment by lfunkhouser** [comment]
verified as fixed
