### ISSUE TITLE
GeoEvent cannot see ObservationReports layers

### ISSUE THREAD

**Issue by pHill5136** [Esri/ops-server-config#1185]
@topowright @jrweakland Usually this happens when the feature service is shared to publicly accessible share (i.e. Everyone) and the map service is not shared publicly.

**Comment by topowright** [comment]
@pHill5136 @jrweakland The feature layer item is missing. Republishing the service now.

**Comment by topowright** [comment]
@pHill5136 I have confirmed that both layers are shared with everyone.
