### ISSUE TITLE
Will NationalIntelligence/GNISNames/GeocodeServer service be released for TEM2015 release?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1186]
"GNIS Geocoding" Geocoding Service item 55f0d69ba58040adbe2655b932be4bac is shared with "Release Review" group. Will this item/service be released in time for the TEM2015 release? Just want to make sure because if it's not going to be released I need to remove instructions for configuring this geocoding service in the Ops Server Installation Guide. Thanks.

**Comment by lfunkhouser** [comment]
Released by Released OpsServer

**Comment by elinz** [comment]
Verified that this service item is now owned by ReleasedOpsServer and verified that the associated .sd file was extracted when extracting those services owned by ReleasedOpsServer. Closing issue.
