### ISSUE TITLE
Release NationalIntelligence/WorldElevationCache/ImageServer service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1187]
@nfeuerstein @lfunkhouser We need this service so that we can configure the portal to use a local elevation service. As of 06 Oct 2015 09:13 Pacific this item 91c91cea61da45b5a9f2b6ff337b8093 is not shared with the "Release Review" group.

**Comment by nfeuerstein** [comment]
@elinz this service was not shared with the Intel QA/QC group.  @NatalieCampos created this service and on 9/10 I sent an email asking if it was ready to be released/could be shared with the QA/QC group.  @NatalieCampos can this service be released?

**Comment by NatalieCampos** [comment]
Yes.

**Comment by nfeuerstein** [comment]
@NatalieCampos - is this Access and Use Contraints for that service correct?  It reads: "The information presented in this service is based on standard Esri Commercial off-the-Shelf (COTS) technologies and commercial data. Any scenario data is notional.  The locations of these events are approximate. The threat assigned to these events are notional. Use of military imagery does not imply or constitute endorsement, sponsorship, or affiliation of Esri, its products, or services by the U.S. Department of Defense."

**Comment by elinz** [comment]
@nfeuerstein @lfunkhouser FYI. At the end of the release process this service should be owned by "ReleasedOpsServer".

**Comment by NatalieCampos** [comment]
The Access Use/Constraints was copied out of OneNote.  Do you want it edited?

**Comment by nfeuerstein** [comment]
Is it correct?   Are there locations of events that are approximated?  Are there threats assigned to events?  Is there military imagery used?

**Comment by NatalieCampos** [comment]
The access use and constraints have been corrected/edited.

**Comment by nfeuerstein** [comment]
@lfunkhouser Item now shared with Release Review group.

**Comment by elinz** [comment]
@nfeuerstein @NatalieCampos In the Access Use/Constraints it states "Any scenario data is notional." Does this statement apply here? All the elevation data is real, correct? Or are we adding this statement to all of our content? Thanks.

**Comment by nfeuerstein** [comment]
@elinz The elevation data is all real; however, any scenario it is used in is notional as none of the data we provide via the ops server is to be used in an operational way.

**Comment by conklinbd** [comment]
This looks like it should be assigned to @lfunkhouser since it is in release review. Reminder that this content should be released to Released OpsServer account.

**Comment by lfunkhouser** [comment]
Issue #1250 needs to be fixed before this can be released

**Comment by lfunkhouser** [comment]
Assigning to @ACueva to release after he tests the new service

**Comment by ACueva** [comment]
Service has been tested, appears to be working properly now. id=daeab256eb5d4e0e82929874ea35365e
I have changed ownership to ReleasedOpsServer
