### ISSUE TITLE
Mosaic Dataset "OperationalImagery.gdb\Declassified" does not contain any records

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1188]
The data server contains the following empty mosaic dataset:
data\FoundationOverlays\OperationalImagery\OperationalImagery.gdb\Declassified

The data server also contains two related images, but these images do not have a defined spatial reference:
data\FoundationOverlays\OperationalImagery\Declassified

I don't believe there is an image service associated with this mosaic dataset and the underlying data seems like it's not close to be released.

Can the mosaic dataset and imagery be deleted or moved off the data server so it's not included in the TEM2015 release?

**Comment by nfeuerstein** [comment]
I deleted what I could.  The folders are currently open elsewhere so I wasn't able to delete everything.

**Comment by conklinbd** [comment]
Assigning to @elinz to complete the delete.

**Comment by elinz** [comment]
@nfeuerstein Just check the GDB [FILESERVER]\data\FoundationOverlays\OperationalImagery\OperationalImagery.gdb. It's no longer accessible as a file geodatabase...now interpreted as a folder. Do we happen to have a back up of this file geodatabase anywhere?

**Comment by conklinbd** [comment]
Same with this. We just need to delete it.

**Comment by elinz** [comment]
@conklinbd @nfeuerstein There were actually mosaic datasets contained in the OperationalImagery.gdb that contained records. Did we not need to keep these populated mosaic datasets?

**Comment by nfeuerstein** [comment]
Nope, we didn't.  Its moved off the ops server.
