### ISSUE TITLE
Mosaic Dataset "OperationalImagery.gdb\OrbView3" does not contain any records

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1189]
The data server contains the following empty mosaic dataset:
data\FoundationOverlays\OperationalImagery\OperationalImagery.gdb\OrbView3

The data server does contain related images:
data\FoundationOverlays\OperationalImagery\OrbView3

Are there any services using this data? Is this data being used for the ImageDiscovery app?

If this data and empty mosaic dataset are not being used for anything can it be deleted or removed to another server so it's not included in the TEM2015 release?

**Comment by nfeuerstein** [comment]
Tried to delete it but "the action can't be completed because the file is open in another program."

**Comment by conklinbd** [comment]
Assigned to @elinz to complete the delete.

**Comment by elinz** [comment]
@nfeuerstein Just check the GDB [FILESERVER]\data\FoundationOverlays\OperationalImagery\OperationalImagery.gdb. It's no longer accessible as a file geodatabase...now interpreted as a folder. Do we happen to have a back up of this file geodatabase anywhere?

@conklinbd Do you know of anyway to recover the fgdb?

**Comment by conklinbd** [comment]
Not sure why we need to restore it. This task was to delete the GDB.

**Comment by elinz** [comment]
@conklinbd The task was to delete a specific mosaic dataset in the file geodatabase. There were other mosaic datasets in this file geodatabase which were populated.

**Comment by nfeuerstein** [comment]
I've asked around and as far as anyone is concerned, this data and the mosaic datasets weren't being used.  Its was a good idea that wasn't carried out for various reasons.  I moved the folder to the data storage location that will no ship with the ops server.  As far as I can tell, NAIP and Landsat (from AGOL) are the only image services currently being used on the Ops Server
