### ISSUE TITLE
Mosaic Dataset "OperationalImagery.gdb\SIRC" does not contain any records

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1190]
The data server contains the following empty mosaic dataset:
data\FoundationOverlays\OperationalImagery\OperationalImagery.gdb\SIRC

The data server does contain related images:
data\FoundationOverlays\OperationalImagery\SIRC (but ArcMap can't read any of these images)

Are there any services using this data? Is this data being used for the ImageDiscovery app?

If this data and empty mosaic dataset are not being used for anything can it be deleted or removed to another server so it's not included in the TEM2015 release?

**Comment by nfeuerstein** [comment]
Deleted.
