### ISSUE TITLE
Drug Grows data outside AOI

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1192]
Illicit Drug Grows notional data was created outside the AOI. When you zoom in once using the basemaps on the Ops Server, you get the following: 

![image](https://cloud.githubusercontent.com/assets/3800729/10315626/42b16f34-6c10-11e5-8dc2-1bae3237c74e.png)

Suggestion is to modify the data to be within the AOI.

**Comment by nfeuerstein** [comment]
The forest extends outside the AOI.  It works fine at smaller scales which is how it was demo'd...or, if larger scales are needed, we can point to an AGOL basemap.
