### ISSUE TITLE
Mission Reports for Land Operations

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/ops-server-config#1195]
This feature service has had all items within it deleted.  This needs to have items in it or I need to be able to access a similar Feature Service for the Land Operations demonstration.  I can only find similar map services.

https://nsec.esri.com/ags/rest/services/Military/MissionReport/FeatureServer/0

Is this due to the GEE simulations?

**Comment by pHill5136** [comment]
I think GeoEvent deleted the features. I have a layer for mission reports https://nsec.esri.com:6443/arcgis/rest/services/Military/IntelReports/FeatureServer/0. Also will try to restore these.

**Comment by pHill5136** [comment]
@ScottCecilio @jrweakland I restored these features to the original feature class

**Comment by ScottCecilio** [comment]
I just checked the original feature service and it is empty.
https://nsec.esri.com/arcgis/home/item.html?id=d78f22ee0b5e454588b9a0883cfd8d22

**Comment by conklinbd** [comment]
@ScottCecilio and @pHill5136 why are you referencing this service via this url?
https://nsec.esri.com:6443/arcgis/rest/services/Military/IntelReports/FeatureServer/0

That is not the correct url. The correct url is:
https://nsec.esri.com/ags/rest/services/Military/IntelReports/FeatureServer/0
We do not want to bypass the web adapter when using these services.

**Comment by pHill5136** [comment]
@ScottCecilio Added attachments to https://nsec.esri.com/ags/rest/services/Military/IntelReports/FeatureServer/0

**Comment by conklinbd** [comment]
#1212 depends on this issue

**Comment by pHill5136** [comment]
@conklinbd @elinz Everything except the Hosted service used by the sustainment has been submitted for release -- added to military demo review. I have submitted an issue for aidan re the sustainment stuff. I suspect those services will need to be deleted from geoevent.

**Comment by pHill5136** [comment]
@ScottCecilio @conklinbd @elinz I have been trying to track down why features are being deleted from https://<server>/arcgis/home/item.html?id=d78f22ee0b5e454588b9a0883cfd8d22. Currently the LandOps-Mission reports service is pointing to https://<server>/ags/rest/services/Military/IntelReports/FeatureServer/0 and not deleting features. I have verified that no other GEE service in GEE is pointing to that service. The features are still being deleted so I suspect someone has a local copy of GEE pointing to that service that is deleting the features. If we can track down that I think I can restore the features and point to the original service.

**Comment by pHill5136** [comment]
@abrowning80 @helyx-rterry @ScottCecilio @conklinbd I am trying to track down an GEE output that is connected to the Military/MissionReport feature service. The errant output is deleting all of the features in the service. The current opsserver GEE instance is no longer connected to this service, but the features are still being deleted. I suspect someone exported the config and the connection to the redlands opsserver imported over. Older versions of the config prior to 10/7 may have this output.  
The output service is called LandOps-MissionReport-Out or mission-reports-out depending on when the config was exported and had delete old features set to delete from the timeontarget field. Did anyone at helyx export the config from gee recently?

**Comment by pHill5136** [comment]
@elinz @conklinbd 
To resolve this issue, we will be replacing and deleting ags/rest/services/Military/MissionReport/FeatureServer/0 with 
ags/rest/services/Military/IntelReports/FeatureServer/0

**Comment by conklinbd** [comment]
We will need to update the following content:
- [ ] id:d1d694ff35d34f29b1b16b54a72e0e4f   "ISR Mission Reports"       
- [ ] id:4ab19d716e4442daaacf006fdeb52677   "Mission Report"   Web Mapping App

**Comment by conklinbd** [comment]
The web app didn't have any references to the layer.

**Comment by conklinbd** [comment]
I am going to delete the service now

**Comment by conklinbd** [comment]
@elinz I didn't delete this service yet because I realized some other content in the release review process might be pointing to it. I will delete after the next report.

**Comment by conklinbd** [comment]
This item was deleted and replaced as instructed by @pHill5136. Assigning to @pHill5136 to verify.

**Comment by conklinbd** [comment]
I am closing this since it has been verified via other issues.
