### ISSUE TITLE
ArcGIS for the Military: Analyzing Environmental Impact on Operations - needs videos posted for Ops Server Release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1196]
@mfunk @jfrygeo - check email reminder for details of what goes where.

**Comment by mfunk** [comment]
@jrweakland any idea where Erik left his MAoT stuff he used for his demos? I'll need to rework it to do a video.

**Comment by jfrygeo** [comment]
Not sure. Maybe Scott Cecilio was working on it?

**Comment by jfrygeo** [comment]
video for weather stuff posted in the below locations:
<li><b>Sea State Raster Functions -</b>"..\Resources\Videos\2015 UC ArcGIS for the Military - Maritime Operations\ArcGISPro_SeaStatesAnalysisRasterFunctions.mp4"

<li><b>Military Aspects of Weather Version 1 </b> .\Resources\Videos\2015 Analyzing Maritime Weather\AnalyzingMaritimeWeather_MAOWV1.mp4

**Comment by BobBooth** [comment]
@jfrygeo - Thanks, I confirm they are there.
