### ISSUE TITLE
Creating Overlays for Military Operations - needs videos posted for Ops Server Release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1200]
@rbernstein - check email reminder for details of what goes where.

**Comment by elinz** [comment]
@BobBooth @jrweakland Moving this issue to next milestone since we are past the deadline for this release.

**Comment by jrweakland** [comment]
i am closing this issue since we are closing out NSEC server and that this video can be posted to esri videos online or posted to the next version of the ops server.
