### ISSUE TITLE
ArcGIS for the Military: MIL-STD-2525D Joint Military Symbology - needs videos posted for Ops Server Release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1203]
@abouffard - check email reminder for details of what goes where.

**Comment by jrweakland** [comment]
@abouffard  - I add the video I made for 2525D in 10.4 Server. @rbernstein is still on the hook for the demo with Pro and the military overlay from the demo theater.

**Comment by jrweakland** [comment]
@BobBooth - Closing this issue since the portal portion of the demo is posted to the folder.
