### ISSUE TITLE
MAoW - needs videos posted for Ops Server Release

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1204]
@abrowning80 - check email reminder for details of what goes where.

**Comment by abrowning80** [comment]
Hi. Milestone next does that mean to be done for this Friday as per the email or is this to be done for the next release of ops server? Am trying to get them done for this release.

**Comment by BobBooth** [comment]
Yes, target data is the Friday, for this release.

**Comment by abrowning80** [comment]
@BobBooth this was done can you now close the issue, thanks

**Comment by BobBooth** [comment]
I confirm that the videos are on the share.
