### ISSUE TITLE
GeoEvent Server contains message simulator files in multiple locations

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1205]
Geoevent server contains messages in the following two locations:
C:\MessageSimulator\Messages
C:\OpsServer\GeoEventData\MontereySimulations

A couple of the files are duplicated.

Messages should only be contained in the folder C:\MessageSimulator\Messages or its subfolder "GeoEventSimulator"

- C:\MessageSimulator\Messages: Should only contain messages run by the MessageSimulator (i.e. ArcGISQtMessageSimulator.exe).
- C:\MessageSimulator\Messages\GeoEventSimulator: Should only contain messages run by the Geoevent out of the box simulator.

Any demo scripts that reference message paths may have to be edited to reflect correct path.

**Comment by jrweakland** [comment]
@pHill5136 - please clean up the files and then reassign the issue to @elinz for verification.

**Comment by pHill5136** [comment]
The simulation in C:\OpsServer\GeoEventData\MontereySimulations is already in the C:\MessageSimulator\Messages folder. Deleting the former.

**Comment by conklinbd** [comment]
I will verify the GeoEvent issues while I review the overall geoevent content

**Comment by conklinbd** [comment]
Verify that this has been removed from C:\OpsServer.
