### ISSUE TITLE
Development GeoEvent configuration has an unneeded folder data store (i.e "AFMData")?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1206]
@jrweakland @pHill5136 Imported the GeoEvent xml configuration from our development geoevent server into a clean Geoevent server and import threw error that AFMData (C:\data) folder does not exist. 

I've checked the GeoEvent xml configuration file and searched for the label/name "AFMData" and it's only referenced in the data store section of the xml configuration. AFMData was a data store that was used in the past, but believe is no longer necessary as the "OpsServerData" data store is now used.

Please confirm if "AFMData" data store is no longer necessary and delete if necessary.

**Comment by pHill5136** [comment]
Removed file datasdtore afmdata

**Comment by conklinbd** [comment]
I will verify while I review the overall GeoEvent content.

**Comment by conklinbd** [comment]
Verified that AFMData is removed.
