### ISSUE TITLE
TEM2015 Test 01: GEE output service "MarkLogic-AddObservationFsOut" does not exist after GEE config import

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1207]
@jrweakland @pHill5136 Imported development geoevent configuration into TEM2015 test server and the "MarkLogic-AddObservationFsOut" output service does not exist.

**Comment by conklinbd** [comment]
@pHill5136 if this service isn't going to be released, we should delete the output.

**Comment by elinz** [comment]
@jrweakland @pHill5136 Investigated further. The ObservationReports service was not created on the Test server because the incorrect/invalid portal items were released for this service.

According to the ArcGIS Server service json the NationalIntelligence/ObservationReports service is associated with the following GUIDs:
{"itemID":"36834c8db03c43df92bf2ef230d958ce","type":"MapServer"}
{"itemID":"d518e58360304d26a1dc4ab78aa45e29","type":"FeatureServer"}

The issues are:
- The map service item associated with this service 36834c8db03c43df92bf2ef230d958ce does not exist.
- The feature service item associated with this service d518e58360304d26a1dc4ab78aa45e29 was not released (this item is shared with the "Demo Review" group.
- The invalid item 12919c56d6a8446985a18d173f0f66f1 was released. Secondary issue, this item is owned by ReleasedIntelligence, but the correct feature service item d518e58360304d26a1dc4ab78aa45e29 is shared with the "Demo Review" group so should the service be released to a demo or released account.

Please see me and I can assist in fixing this.

**Comment by pHill5136** [comment]
@conklinbd @topowright @jrweakland The dependent layer exists in the service, but geoevent cannot see it. It can see the service just not the layer. Typically this happens when the feature service is shared to a public group but the corresponding map service is still in a private group.
Jim can you check the status of the ObservationReports Map Server. Last I heard it was in DemoReview. I cant find it on the portal.

**Comment by elinz** [comment]
@conklinbd @topowright @jrweakland @pHill5136 There is no associated map service item for this service so access can't be controlled. The only users who can see this are admins.

I will fix this by editing the service json so feature service will point to portal item 12919c56d6a8446985a18d173f0f66f1  that was released to ReleaseIntelligence. I will manually create the map service portal item and edit the service json to point to this new portal item. I will set all summary, description, etc to match the feature service and also release as ReleasedIntelligence.

**Comment by elinz** [comment]
Fixed issues with the ObservationReports service. Will verify this issue when we create the final ops server build and deploy to test machine.

**Comment by conklinbd** [comment]
@elinz can we just close this one? I would prefer to close and then just look for test issues later if you want to remember to verify.

**Comment by elinz** [comment]
@conklinbd Sure. I'll close it.
