### ISSUE TITLE
NAIP Image services is used by released content

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1208]
NAIP Image Service ID:ca7d6030cb3e4f7d9131c661d432c0c8
Is used by released content but is not released. 

@NatalieCampos is going to republish to fix the other NAIP issues then we need to get this released (at least to demo review. 

@nfeuerstein let me know if you have any issue with this. I will push this through to demo release.

**Comment by conklinbd** [comment]
@NatalieCampos I reassigned to you so you can overwrite the service. Reassign back to me after you overwrite.

**Comment by nfeuerstein** [comment]
@conklinbd Sounds good.

**Comment by NatalieCampos** [comment]
The following change were made to the  NAIP mosaic dataset:
- The mosaic was rebuilt to include original NAIP imagery
- The clipped images were removed from gdb
-The  gdb was renamed to  remove the clip reference 
- The portal description was added to the mosaic dataset item description
- The portal description was added to the SD 
- Unnecessary gdb tables were  removed

The portal item can be returned to @conklinbd.

**Comment by conklinbd** [comment]
@NatalieCampos I am not seeing any time/date information in this service. 
The previous service had time/date info and could be used with the time slider app. 

This is needed for the release.

**Comment by NatalieCampos** [comment]
@conklinbd the image Year has been added.  Please let me know if this will suffice.

**Comment by conklinbd** [comment]
I am reviewing. Reminder - reassign the issue if it is someone else's turn.

**Comment by conklinbd** [comment]
I have review the service and it has been succesfully republished.
The service has not released but I added to issue #1219 
So this one can be closed.
