### ISSUE TITLE
TWI Content used in released content. 

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1209]
This was owned by our TWI Soldier so Looking for assistance to get this released. 
No Description, bad title etc..

- [x] id:1861307746174ca5914713795d19ec7c Tile Layer - Monterey Bay Area of Operations 
- [x] id:8833db468b34457496a9f2b358417d09 Tile Layer - Cover
- [x] id:773d718010da4a63b86dec6ee2cdeaa6 Tile Layer Drop_Zone_Analysis
- [x] id:b9ef7590b9c9440c87ce17c448b38b53 Tile Layer HMMWV_CCM
 

is used in a web map but not released.

**Comment by conklinbd** [comment]
@jrweakland this is the complete list for TWI.

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review and release.

The service definitions are for these items are:

Area of Operations - id:b2ca6123b7194a53a2dd029f1cbc5ed3
Cover - id:37daf91d910a45acaf68c7dd25e3e01e
Cross-Country Movement (HMMWV) - id:bf6e7bee41bd497d90861d705c82393b
Drop Zones - id:5282f627f2ad47fdb30f162b9fb648f7

**Comment by lfunkhouser** [comment]
Items and service definitions released by Demo Military
