### ISSUE TITLE
Points of Interest used in Released Web Map but not released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1210]
id:3A56228feb2f684aaa9db108f588666fc7

Point of Interest Map Service used in the released web maps. Need to be released for demo purposes at least.
Content is in release review so assigning to @lfunkhouser.

**Comment by lfunkhouser** [comment]
id:56228feb2f684aaa9db108f588666fc7 
@nfeuerstein This item is in Release Review - is this supposed to be released as released content or demo content?

**Comment by conklinbd** [comment]
If @nfeuerstein had it in release review I would assume it is for release.

**Comment by nfeuerstein** [comment]
@lfunkhouser It was in release review prior to there being a demo review group.  I went through and reshared a bunch of items to the correct group but apparently missed this one.  I'll go through again.  To be clear, it is for demo review, the symbols are awful but the data is good.

**Comment by lfunkhouser** [comment]
Thanks for clarifying @nfeuerstein 
Fixed typo "maybe" to "may be" in description
Released by Demo Intelligence
Updated extent of portal item to AOI so basemaps are available
Back at you @conklinbd

**Comment by Nekillims** [comment]
Agree on the symbols.  There was no standard set that I could use to support this range of objects, so I mixed and matched to try to get something somewhat consistent- sort of like international map/road signs.  Something for improvement in a future release.

**Comment by conklinbd** [comment]
Verified released. I am guessing my original id was a typo. I will have to retest a couple of apps to be certain.
