### ISSUE TITLE
Piracy by Subregion 2009to2013 Feature Service released by corresponding Map Service not released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1211]
id:c33c98003a41459499e2b06978336f87.
Piracy by Subregion 2009to2013 Map Service item also needs to be released if the feature service item is released.

**Comment by elinz** [comment]
NOTE: the associated feature service owned by "DemoMilitary" so release map service item to same owner.

**Comment by jfrygeo** [comment]
@jrweakland - fixed description of https://nsec.esri.com/arcgis/home/item.html?id=c33c98003a41459499e2b06978336f87 and shared to "demo review" group. Please release under "DemoMilitary" group.

**Comment by conklinbd** [comment]
Updated comment to remove internal server name.

**Comment by conklinbd** [comment]
@jfrygeo and @jrweakland since the associated item was already released with the same info I released this item.
