### ISSUE TITLE
Verify all resources referenced in Geoevent configuration are released

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1212]

**Comment by conklinbd** [comment]
The following GeoEvent Outputs will need to be deleted if their associated item is not released:

- [ ] SR_MovementsUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_ConvoySatatusUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_CrossingPointsUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_DOSCriticalUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_DOSOpsIntensityUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_MEELAlertsUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_MOVASSESSREPUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map
- [ ] SR_PODSUpdate Uses id:998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map 
- [ ] MarkLogic-ObservationsFsPollIn Uses id:e1786c4738b54473982b7f0b85453643 NationalIntel/ObservationReportsML
- [ ] LandOPs-MissionReports-Out Uses id:d78f22ee0b5e454588b9a0883cfd8d22 ServiceName Military/MissionReport (Map Service released but not FS)
- [ ] MarkLogic-AddObservationFsOut uses id:5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc NationalIntelligence/ObservationReports
- [ ] MarkLogic-UpdateObservationsFsOut uses id:5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc NationalIntelligence/ObservationReports

**Comment by conklinbd** [comment]
998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map Links to issue #1233

**Comment by pHill5136** [comment]
@elinz All service dependencies except 998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map Links to issue #1233 have been submitted to Military Demo Review group. I checked with @ACueva  that these were shared to the proper groups to be copied to the opserver release. 

I have submitted an issue #1241 to @abrowning80 to let me know if the last service needs to be released. I suspect that it will not be required and once I get confirmation I will delete the geoevent items dependent on it.

**Comment by pHill5136** [comment]
@elinz @conklinbd Since sustainment services depending on  998c767c6af34ff197e73b25b77c80fa ServiceName Hosted/Map are all outputs not used in geoevent services I'll be deleting.

**Comment by pHill5136** [comment]
@elinz @conklnbd All GEE output dependencies are shared to Military Demo Review and will be released.

**Comment by conklinbd** [comment]
Verified
