### ISSUE TITLE
Distance From Water Map Service Needs to be Released

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1214]
Map Service id:002451cd86134f7fa8b9394174142242 needs to be released. This service is being used by web map id:6214c50aa89b43a0ac842ac2bb1ba7eb   "Distance From Water". 

This is a ReleaseIntelligence portal item.

@nfeuerstein - I just updated the items that needed to be resolved for this item.

**Comment by lfunkhouser** [comment]
@jrweakland Is the data permission label indicating that we need additional data permissions for this item?

**Comment by lfunkhouser** [comment]
Released by ReleasedIntelligence

**Comment by jrweakland** [comment]
@lfunkhouser - I am unsure of the answer. I copied the access and use constraints from the web map (id:6214c50aa89b43a0ac842ac2bb1ba7eb) that consumes this service. @nfeuerstein - do you know the answer?

**Comment by nfeuerstein** [comment]
The Distance From raster (and the original water feature data) was all Esri owned, according to the permissions documented for the Sudan demo in 2014.

**Comment by lfunkhouser** [comment]
Released by Released Intelligence
