### ISSUE TITLE
Tsunami Hits Monterey Coast not released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1215]
id:d863515930c7412682678d7298544bf3 Briefing Book Tsunami Hits Monterey Coast
This item is being used in released content from National Security team.

@kerryrobinson just FYI.
@MaryClawson this item is owned by you. I think it looks good enough for a demo release at least.

**Comment by MaryClawson** [comment]
This briefing book is in the ArcGIS for Intelligence (QA/QC) group and shared with everyone.  Natalie has it for release? @nfeuerstein

**Comment by nfeuerstein** [comment]
@conklinbd @MaryClawson @lfunkhouser Breifing book has been removed and added to the Demo Review Group (as well as supporting web maps).

**Comment by lfunkhouser** [comment]
@nfeuerstein @MaryClawson Is it OK to have "Mary Clawson" in this Briefing Book or should it say "Esri"?

**Comment by lfunkhouser** [comment]
Fixed issue. Changed name to Esri. Released by Demo Intelligence.

**Comment by conklinbd** [comment]
Verified
