### ISSUE TITLE
ISIL March Accross Iraq not released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1216]
id:387bfd7f9d204139b7201da2472ec8e8
This Map Journal is being used in content produced by the National Security Team.

@kerryrobinson FYI.

Content looks good if we have appropriate permissions. 
@CraigCleveland

**Comment by CraigCleveland** [comment]
@conklinbd @kerryrobinson I spoke directly to the Esri Media team on this one as they were the original authors to clarify the licensing.  We (Esri) created it at the request of Mashable and were using their license to access the AP images and text.  So although fine to use in a public setting we do not necessarily have the rights to copy the images/text and package them up for redistribution.  I made the suggestion to @nfeuerstein that we could recreate the product using similar images from Wikimedia, and with our own text for a future release.

**Comment by kerryrobinson** [comment]
OK, thanks Craig, that sounds fine.  For my What is Web GIS app (which is a Map Series story map) I just need to reference another story map or briefing book on the Ops Server that is a good example. 

Maybe the Incident Briefing Book (https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/BriefingBook/?bookId=735dc51d834e4afb8d8e059bfeb64053) is a good one since it is released?

@conklinbd just let me know how I can now udpate my story map to reflect this change.

**Comment by conklinbd** [comment]
@kerryrobinson can you remind me which item id uses this map journal?

**Comment by kerryrobinson** [comment]
@conklinbd id:a0944c6a2b4f4847863af010461c24a5

**Comment by conklinbd** [comment]
Item reassigned. Assign back to me when it is ready to release.

**Comment by kerryrobinson** [comment]
Unfortunately the Incident Briefing story map is a map journal just like the one i'm embedding it into so it doesn't look great. But there are no other released story maps that I can choose so I've gone ahead and made the changes. 

Reassigning to Ben to release.

**Comment by conklinbd** [comment]
@kerryrobinson I agree this doesn't look good. If I have a few minutes I might recreate the old AAR story map that we had for Afghanistan. At least we have data permissions for that.

**Comment by kerryrobinson** [comment]
@conklinbd I was thinking the same thing. The map tour is a good one to show, so the AAR would be great.

**Comment by conklinbd** [comment]
Ok. I created a Story Map id:932fd43122d24c28ad408ef4b9387746.
This item and the web map id:13a6ba5d51b1467983cfb3bf0e96b78b will need to be released. 

I have updated this Journal and Reassigned back to my user. 

@lfunkhouser can you review and release the Story Map and Web Map. I made it quickly so please check it out.

**Comment by kerryrobinson** [comment]
@conklinbd I just took a quick look, the description for the Story Map (mainstage) will need to change from talking about an Incident Report to an After Action Report.
![image](https://cloud.githubusercontent.com/assets/3383476/10352631/395fbef2-6d48-11e5-9240-60deb80b23c6.png)

**Comment by conklinbd** [comment]
Ok. I fixed that.

**Comment by conklinbd** [comment]
I am realizing that this issue has gotten to be large. I am moving the release issue to a separate item.
I am closing this item, unless you see any additional errors @kerryrobinson then you can reopen.
