### ISSUE TITLE
TEM2015 Test 01: GEE output service "MarkLogic-ObservationsFsPollIn" does not start

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1217]
This input service won't start because it references a service that does not exist NationalIntelligence\ObservationReportsML\0 (feature service).

NOT SURE WHY WE NEED two ObservationReports services.

The service on the dev server references the following portal items which are not released:
{"itemID":"bff0a7b237e946b385bc7223d8af5ae4","type":"MapServer"}
{"itemID":"e1786c4738b54473982b7f0b85453643","type":"FeatureServer"}

**Comment by topowright** [comment]
@elinz @conklinbd The feature layer was a missing in portal. I republished the service and shared the item with everyone. Confirmed the GEE output service is now populating features to the feature service. 

We do not have a way to directly access content from Mark Logic. We need to replicate their data to allow us to show the content in platform applications. We adding content to Mark Logic we do this also by pushing content through GEE, which is the reason why we have two services.

**Comment by conklinbd** [comment]
I will verify this.

**Comment by conklinbd** [comment]
The service now exists. Understand reason for the 2 services. 
This item still needs to be released.

**Comment by conklinbd** [comment]
#1212 depends on this issue
