### ISSUE TITLE
Can't find item mentioned in Map Journal 

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1218]
Can't find an item referenced in the map journal. Journal ID:5cd903df8c234d9584f77bad9be47222
Missing Item ID:
@kerryrobinson 
{
title: "<p><strong><span style="font-size:22px">Maritime Charts</span></strong></p> ",
content: "<p><span style="font-size:12px">Vector nautical charts can be served as as a query-able GeoServices REST services or OGC Web Map Services.&nbsp; These services support dynamic querying on the rich data contained within ENCs in order to assist with planning and maritime domain awareness operations.&nbsp; Users can publish services that display S-57 products such as AML, ENC, and IENC based on their respective S-52 presentation library implementations.&nbsp; Since the data can be queried, applications can be built that allow for analytical capabilities such as search, location calculation, performing measurements of distance and area, and feature identification and attribute display.&nbsp; In addition, the technology includes S-63 decryption capabilities to produce and serve read-only caches of encrypted ENC datasets.</span></p> ",
contentActions: [ ],
creaDate: 1443089481930,
pubDate: 1443089481930,
status: "PUBLISHED",
media: {
type: "webpage",
webpage: {
url: "https://nsec.esri.com/arcgis/apps/webappviewer/index.html?id=755f187c59054f7a96ed28d533ca9069",
type: "webpage",
display: "stretch",
unload: false
}
}
},

**Comment by kerryrobinson** [comment]
OK, I guess that app is gone. Instead this one can be referenced in the Map Journal: http://nsdemo.esri.com/WAB4MCS/. 

Do I need to make the change? I don't have permission and don't think I can login as DemoNationalSecurity.

**Comment by conklinbd** [comment]
Reassigned item id:5cd903df8c234d9584f77bad9be47222 to @kerryrobinson to fix.
Reassign back to me to release.

**Comment by kerryrobinson** [comment]
I couldn't use http://nsdemo.esri.com/WAB4MCS/ because it isn't served over HTTPS.  Modified instead to use id:8a141ff5bc8b451f98880e4726112b14.

**Comment by conklinbd** [comment]
Reassigned item back to release.
