### ISSUE TITLE
Item not released NAIP over Time

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1219]
id:c725e126a53b4fbab72157dd77c0c29d
Not released but used in content from National Security Demo.
@kerryrobinson FYI..

**Comment by kerryrobinson** [comment]
This or any other time-enabled map will do. This was the best one I could find at the time.

**Comment by pshowalter** [comment]
I don't see any image change when running hitting the play button.   This app is part of "What is Web GIS?" on ["Operational Data" in the "Time Aware Data - Imagery over Time" section.](https://nsec.esri.com/arcgis/apps/MapSeries/index.html?appid=faef542a74e141398c05c43379a67004)

Running straight out of NSEC Portal does not seem to work either?  
Tested with Chrome and FF.
[Portal Web App](https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/time-aware-template-master/?appid=c725e126a53b4fbab72157dd77c0c29d)

**Comment by kerryrobinson** [comment]
@pshowalter The NAIP Over Time app was working last week, although it took some time to refresh.  It does not seem to be working now so I'm not sure what has changed. 

Do we know of any other time-enabled map that is released on the Ops Server?

**Comment by conklinbd** [comment]
@NatalieCampos Just republished this service. We must have lost the time enabled properties.
I will review a fix. No need to replace this.

**Comment by conklinbd** [comment]
This app is now functioning, however the web map that the app is using is not released.
Map = id:43774ea0de014514917b2167691b494e
Service = ca7d6030cb3e4f7d9131c661d432c0c8

Assigned to @nfeuerstein to release the app and the service

**Comment by nfeuerstein** [comment]
The web map, the app, and the image service are now shared with Demo Review:
App =c725e126a53b4fbab72157dd77c0c29d
Map = 43774ea0de014514917b2167691b494e
Service = ca7d6030cb3e4f7d9131c661d432c0c8

**Comment by lfunkhouser** [comment]
Access and Use Constraints are misleading.  It states "none"; however the link takes you to the USDA disclaimer that states "The Originator asks to be credited in derived products". USDA is cited in the credits. Should the Access and Use Constraints contain this statement, "The information presented in this template or demonstration is based on standard Esri Commercial off-the-Shelf (COTS) technologies and commercial data. All scenario data is notional." instead of "None"?  @karlterrey What do you advise?

**Comment by karlterrey** [comment]
@lfunkhouser @nfeuerstein Credit the sources in the Description with a text notation of where the data came from. 
In Access and Use Constraints say... "The information presented in this template or demonstration is based on standard Esri Commercial off-the-Shelf (COTS) technologies and commercial data. Any scenario data is notional".
Keep the Credits as they are.
We have the NAIP permission on Box already.

**Comment by lfunkhouser** [comment]
Assigning to @karlterrey to update access and use constraints

**Comment by karlterrey** [comment]
@lfunkhouser Updated Access and Use Constraints and Description.

**Comment by lfunkhouser** [comment]
All items released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified.
