### ISSUE TITLE
Item not Released Elevation View of Police Station

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1220]
Id:c6ffb9f409174948b6d0687eb8fcbfb5
The application Elevation View of Police Station and Businesses Destroyed is not released. 

This is great app and part of the Demo for National Security. 
@kerryrobinson FYI..

@MaryClawson Please release.

**Comment by MaryClawson** [comment]
The item is in the ArcGIS for Intelligence (QA/QC) group and is shared with Everyone.  Up to Natalie to release? @nfeuerstein

**Comment by nfeuerstein** [comment]
Web Map and app: ad9aeca906314d40ad1acfeebd97d8c0 and c6ffb9f409174948b6d0687eb8fcbfb5 reviewed and shared with Demo Review Group.

**Comment by lfunkhouser** [comment]
Modified web map item. Changed "template or demonstration" in Access and Use Constraints to "web map"; Enabled delete protection
Released both items by Demo Intelligence.
@conklinbd back to you

**Comment by conklinbd** [comment]
Verified this item has been released.
