### ISSUE TITLE
Mosaic Dataset CA_CC_Lidar.gdb\s_CA_CC_2010_DSM references incorrect paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1222]
Mosaic Dataset data\FoundationOverlays\Elevation\MosaicDatasets\CA_CC_Lidar.gdb\s_CA_CC_2010_DSM contains paths with local C:\OpsServer\Data instead of UNC path to \\_FILESERVER_\Data

**Comment by NatalieCampos** [comment]
@elinz I have fixed the mosaic dataset paths. to nsecdata. I am concerned however,  as I have fixed the paths to this mosaic an other mosaics repeatedly.  I am confused about how the paths keep reverting to some other location.  Could the build or extract process be overwriting paths?

![image](https://cloud.githubusercontent.com/assets/5116835/10327541/4b6c0b96-6c5d-11e5-943f-3705d8e19822.png)

**Comment by elinz** [comment]
@NatalieCampos Please do not include server names or domain account names in GitHub issues.

**Comment by elinz** [comment]
The build process does not alter the paths in mosaic datasets located in the "data" folder. We only modify mosaic datasets copied to the build folder. @ACueva Please confirm.

**Comment by conklinbd** [comment]
I think this should be assigned to @elinz to verify that this issue has been resolved.

**Comment by elinz** [comment]
@NatalieCampos I've deleted the screen shot from previous comment as it contained server names and domain account names.

**Comment by elinz** [comment]
Verified fixed. Closing issue.
