### ISSUE TITLE
Crowdsource Reporter: Can't edit configuration

### ISSUE THREAD

**Issue by jessnoo** [Esri/ops-server-config#1223]
@conklinbd it seems like i'm not able to edit crowdsource reporter configs after hitting 'publish' from the  'make gallery application' dialog. and my configuration looks a little ugly with the default color scheme -- 

id=e8bdbc493782458dad67680cfeb26d6a

thanks for any guidance you can offer -- i may have missed something somewhere --

**Comment by jessnoo** [comment]
same for Crowdsource Manager -- https://nsec.esri.com/arcgis/home/item.html?id=659efff073634843900b22378b585e4c

**Comment by conklinbd** [comment]
@jessnoo I have not been able to figure out how to make these apps configurable. Do you know if anyone on the team has tested this with Portal?

**Comment by jessnoo** [comment]
@conklinbd - @allisonmuise and I got together and looked through everything. 

1) needed to fill out the configuration Parameters section of the templates' item details pages  (this came from the git hub repos -- configuration-panel.js in the resources folder for the apps)

2) removed the 'arcgis' from the path to the code used by the templates. This 'arcgis' was resulting in /arcgis/arcgis in the template path causing 500 errors when accessing the config and app.

**Comment by conklinbd** [comment]
Verified the config option is now available.
