### ISSUE TITLE
Add document links for latest versions of templates

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1224]
Adding document links as portal items to direct user to location of templates on Ops Server.
Add the 10.3/Pro 1.1 version document links for the templates included on Ops Server

Military
- [x] Beach Landing
- [x] Clearing Operations
- [x] Compound Map
- [x] Distance  to Assets
- [x] Engagement Area
- [x] GeoMessageSimulator
- [ ] ~~Helicopter Landing Zone~~
- [ ] ~~Incident Analysis~~
- [x] Lodgment Planning
- [x] Observation Post
- [x] Range Dome Analysis
- [x] Squad Leader
- [x] Urban Mission Rehearsal
- [x] Vehicle Check Point
- [x] Vehicle Commander
- [x] Visibility and Range

Intelligence
- [x] Geonames Locator
- [x] Image Discovery
- [x] Image Observables
- [x] National Security Basemaps
- [x] Predictive Analysis Tools
- [x] Solutions Geoprocessing Toolbox

**Comment by joebayles** [comment]
Crossed out Helicopter Landing Zone and Incident Analysis because they will not get created.

**Comment by dfoll** [comment]
finished all mine @lfunkhouser  you can close after they are satisfactory.

**Comment by lfunkhouser** [comment]
verified as fixed.
