### ISSUE TITLE
Crowdsource Manager and Reporter are both owned by DemoIntelligence

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1225]
Crowdsource Manager and Crowdsource Reporter apps are both owned by demo Intelligence.
These apps are core apps used by multiple solutions so I am reassigning to OpsServer.

**Comment by conklinbd** [comment]
Fixed. @lfunkhouser just to make sure there are no issues with this.

**Comment by lfunkhouser** [comment]
No issues @conklinbd . Verified as fixed. Closing.
