### ISSUE TITLE
Diversity and Ethnicity web map needs clearer Access and Use Constraints

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1227]
Similar to #1180 

@karlterrey @MaryClawson @nfeuerstein The Access and Use Constraints wording in the Diversity and Ethnicity web map (id:3d262ec7abdb4dbd925d7d9f37bd6e2d) doesn't make it clear what Esri people should do. Can we add something like for "Esri Inc and Esri Distributors" or something of the like.

**Comment by MaryClawson** [comment]
Fixed.  Ready for review. @lfunkhouser

**Comment by lfunkhouser** [comment]
Verified as fixed. Unshared with Demo Review group and released by DemoIntelligence
