### ISSUE TITLE
Operations Center Reports (Crowd Source) uses group that is not released. 

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1228]
Item ID:29013195a6aa480c8bc3d1c34dbea5f0 is using the group id:a1bddbe62d4b46ad9a04dc24024bc55d which has not been released.

Also, need to ensure that the content of this group itself is released. 
Many items in the group still show ownership of @phil7277 and @ScottCecilio

**Comment by phil7277** [comment]
All items have been shared with the review team. The IIR Webmap (id=e0b736a2364442348441744937ae757c), and spot report webmap for collector (id=73bbdb629ebd471e88ac66c164d6fa40)  has been shared to the ArcGIS for Intelligence (QA/QC) group for review. DemoMilitary already owns item Maritime Contacts Web Map for Geoform or ArcGIS for Collector (id=e49682575da9423f9eaa221f8bb1278a). The ISR Mission Report webmap is owned by @ScottCecilio and has been shared by Scott with the Demo Review group. The Operations Center Report Group is public. Is there anything further we need to do to share this group for release? @ScottCecilio  will be helping me resolve any issues to ensure this makes release.

**Comment by conklinbd** [comment]
I have changed the owner of the group to DemoMilitary. The other items will need to be released for this issue to be closed. I am assigning this issue to Lorraine so she can review and release the individual items.

**Comment by lfunkhouser** [comment]
id:e0b736a2364442348441744937ae757c released by DemoIntelligence
id:73bbdb629ebd471e88ac66c164d6fa40 released by DemoIntelligence
ISR Mission Reports - Land Operations web map id:6da870dbe58743f6b8037f05a6d98102 released by DemoMilitary
ISR Mission Reports web map id:d1d694ff35d34f29b1b16b54a72e0e4f released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified that the group and all items have been released.
