### ISSUE TITLE
Manage Health and Safety Reports uses unreleased group

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1229]
The App Manage Health and Safety reports uses the group id:26b24f69605a47ea94f76988ec6d6a55 which has not been released.

Health and Safety Reports id:659efff073634843900b22378b585e4c has been released. 
I believe this is the same group also used by the Reporter app Health and Safety Reports.

**Comment by jessnoo** [comment]
updated owner to Released EManagement.

**Comment by conklinbd** [comment]
Verified Released.
