### ISSUE TITLE
Jenkins build server: Need to relocate "Downloads" folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1230]
The current Downloads folder is 116 GB; way too large to expect all users to copy to their Ops Servers. We need the templates to be an optional install so we need to relocate the Downloads folder out of the SolutionsWeb folder.

@ACueva Let's discuss where this should be copied. The decision may be based on if portal items for the templates are included in the ops server release.

**Comment by ACueva** [comment]
@lfunkhouser FYI

**Comment by lfunkhouser** [comment]
@elinz Document links will be created as portal items. These document links should point to the file location of the latest template on the Ops Server

**Comment by elinz** [comment]
@lfunkhouser Correct. The URLs in the document links can still point to the SolutionsWeb\Downloads location. And the install guide will still instruct users that they CAN copy the Downloads folder from the external drive to the IIS SolutionsWeb folder, however this would be optional due to the size of the downloads (there will be users who won't have enough system space). Because of the large size of the Downloads folder I don't want the Downloads folder to exist in the SolutionsWeb folder on the external drive because this is optional.

**Comment by elinz** [comment]
@lfunkhouser Actually now that I think about it, these portal items won't be extracted because they are owned by Template users. We are only extracting Demo and Released users. Do Template users also need to be extracted?

**Comment by ACueva** [comment]
Items will be copied to \OPSServerInstall\Downloads folder.
To verify next build.

**Comment by ACueva** [comment]
Verified.
