### ISSUE TITLE
Delete the GeoEventSimulator.exe that is located on dev Geoevent C:\OpsServer\GeoEventData folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1231]
This executable is included in the GeoEvent install under the c:\Program Files\ArcGIS\Server\GeoEvent folder. This .exe should not be included in the C:\OpsServer\GeoEventData folder otherwise Ops Server configured machines will have two versions of this executable.

**Comment by conklinbd** [comment]
@elinz. This executable is typically copied multiple times to be used directly with the simulation data. I am not sure why having more then 1 copy is a problem.

**Comment by elinz** [comment]
@pHill5136 This is a problem because the C:\OpsServer\GeoEventData folder is shipped with the Ops Server release, which means it's possible that the build of this .exe that is in the GeoEventData folder would be different then the build that is installed on the server when users perform an Ops Server install. We should only have one GeoEventSimulator.exe installed on a machine. If you need to access it from multiple locations then create an shortcut instead. Assigning back to @pHill5136

**Comment by pHill5136** [comment]
I already deleted this. I think I forgot to send the comment before reassigning.

**Comment by pHill5136** [comment]
@elinz sending back to verify delete.

**Comment by elinz** [comment]
@pHill5136 Thanks. Verified that .exe has been deleted from GeoEventData folder. Closing issue.

**Comment by pHill5136** [comment]
@helyx-rterry @abrowning80 @elinz Has anyone at helyx exported a config from GEE that is still connected to Redland's opsserver. We have a service ISR Mission Reports which is having features deleted a couple minutes after restoring. I suspect an errant GEE service is deleting these.

**Comment by abrowning80** [comment]
@pHill5136 The only people to have done this would have been Rich or myself and neither of us have been play / exporting things from gee in Redlands as far as I know.
