### ISSUE TITLE
Mosaic Dataset CA_CC_Lidar.gdb\s_CA_CC_2010_DTM references local user path

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1232]
Mosaic Dataset data\FoundationOverlays\Elevation\MosaicDatasets\CA_CC_Lidar.gdb\s_CA_CC_2010_DTM contains path to local C:\Users\[user]]AppData\Local

**Comment by elinz** [comment]
Examined one of the raster function properties of one record in mosaic dataset this local path is being used for the "Cache folder" property on the "LAS To Raster" tab.

**Comment by NatalieCampos** [comment]
The C:\Users[user]]AppData\Local path has been removed.

**Comment by elinz** [comment]
@NatalieCampos Issue still exists. Assigning back to you.

**Comment by NatalieCampos** [comment]
Ok Hopefully I have fixed it now.   The path that is being populated is a property that is not being used and is automatically being populated.  I have deleted the local path reference.

**Comment by elinz** [comment]
Verified fixed. Closing issue.
