### ISSUE TITLE
LasCache folder does not contain any data; delete if not needed

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1234]
[FILESERVER]\data\FoundationOverlays\Elevation\LasCache\sig_srs2228_rts0x2_0_cls0x3ef7e_ag3_vf0_dt0_cw5 folder does not contain any data. 

Please delete [FILESERVER]\data\FoundationOverlays\Elevation\LasCache folder if not needed.

**Comment by NatalieCampos** [comment]
@elinz The LasCache folder is an automatically generated folder.  We are not using the cache option but the folder still generates.

**Comment by elinz** [comment]
Nothing to verify as no corrective action is possible. Closing issue.
