### ISSUE TITLE
The Observation Reports for MarkLogic Feature Service is used by GeoEvent Services

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1235]
The Observation Reports for MarkLogic Feature Service is used by GeoEvent Services that are going to be released. This service needs to be released or the GeoEvent Input/Outputs need to be removed.

As a reminder the nsecgee is not a development machine, it is for ready to release GeoEvent content.

Service Item id:bff0a7b237e946b385bc7223d8af5ae4 Map Service
Service Item id:e1786c4738b54473982b7f0b85453643 Feature Service

**Comment by topowright** [comment]
@conklinbd These items have been shared with the demo review folder

https://github.com/Esri/ops-server-config/issues/1024

**Comment by conklinbd** [comment]
@lfunkhouser for you to review and release.

**Comment by conklinbd** [comment]
#1212 depends on this issue.

**Comment by lfunkhouser** [comment]
@conklinbd @topowright Item descriptions say "Various spot reports over California...";however, there is only one and it is in the water by Monterey. Is this "as designed"?

**Comment by lfunkhouser** [comment]
Map service and feature service released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified.
