### ISSUE TITLE
The Observation Reports Feature Service is used by GeoEvent Services

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1236]
The Observation Reports Feature Service is used by GeoEvent Services that are going to be released. This service needs to be released or the GeoEvent Input/Outputs need to be removed.

As a reminder the nsecgee is not a development machine, it is for ready to release GeoEvent content.

Service Item 1be76160f5de45d59f0246161696c10b Map Service
Service Item 5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc Feature Service

**Comment by topowright** [comment]
@conklinbd I have shared with the Demo Review.

**Comment by elinz** [comment]
@conklinbd @topowright Interesting. I had fixed the issues with this service, and was already released but today I see my changes were thrown away.

**Comment by topowright** [comment]
@elinz @conklinbd I think these are the same thing and they have been fixed. 

https://github.com/Esri/ops-server-config/issues/1235

**Comment by conklinbd** [comment]
I have assigned to @lfunkhouser to release

**Comment by conklinbd** [comment]
#1212 depends on this issue

**Comment by lfunkhouser** [comment]
Services released by Demo Military

**Comment by conklinbd** [comment]
Verified
