### ISSUE TITLE
Portal content with external URLs need tag "Internet Required"

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1237]
@lfunkhouser I can run a content report which will flag if the item has an external URL. This should at least catch 90% of the items (I can't check the custom apps).

**Comment by lfunkhouser** [comment]
@joebayles could you add these?

**Comment by joebayles** [comment]
@elinz please send me the report.

**Comment by elinz** [comment]
@joebayles Report sent through email. Reassigning back to you.

**Comment by joebayles** [comment]
Done... the vast majority of these items are EM content that is referencing an AGOL basemap.

Also, found blank Summary, Access and Use Constraints, and Credits fields in several EM items as well.

**Comment by elinz** [comment]
Verified. NOTE: only did a spot check. Closing issue.
