### ISSUE TITLE
Delete VehicleCommander apps from DemoAndScript demo location; these templates already are shipping with Ops Server

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1238]
@ScottCecilio @jrweakland Delete the x64 and x86 versions of VehicleCommander from the demo and script staging location since these templates are already being shipped with Ops Server (i.e. Downloads folder); we need to remove file duplication:

[FILESERVER]\OpsServerStaging\2015_Q4\DemoAndScripts\Military\LandOperations\Data\Applications

**Comment by ScottCecilio** [comment]
@elinz @jrweakland the x64 and x86 versions of VehicleCommander from the demo and script staging location have been deleted.  Please verify.

**Comment by conklinbd** [comment]
@ScottCecilio if you pass an issue to someone else, please assign it to them. 
Changing assignment.

**Comment by elinz** [comment]
Verified both versions of VehicleCommander were deleted from the DemoAndScripts staging folder.
