### ISSUE TITLE
Image Discovery App fails to load

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1240]
404 error on trying to access:
Apps/NationalIntel/ImageDiscovery/widgets/ImageDiscovery/base/Results/base/Analysis/base/Transparency/template/TransparencyWidgetTemplate.html

![10-7-2015 10-24-16 am](https://cloud.githubusercontent.com/assets/3093940/10345319/b9138cfc-6cdd-11e5-9a7c-7d58d5fae4b9.png)

**Comment by nfeuerstein** [comment]
I replaced the missing .html file.

**Comment by ACueva** [comment]
Verified the application is now working.
