### ISSUE TITLE
Javascript viewer on ArcGIS REST endpoint fails to load .css files

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1242]
On all map services, if you click on:

View In: ArcGIS JavaScript

The tundra.css and esri.css will fail to load:

https://SERVERNAME/arcgis/home/js/dojo/dijit/themes/tundra/tundra.css
https://SERVERNAME/arcgis/home/js/esri/css/esri.css

**Comment by conklinbd** [comment]
Is this an issue that has to be fixed for the release?

**Comment by elinz** [comment]
@ACueva @conklinbd Just tested on both our dev server and the test server I set up with fall content and the view in "ArcGIS JavaScript" functionality is working. Map service draws as expected and throws no errors. Back to @ACueva to verify.

**Comment by ACueva** [comment]
@elinz Yes the data loads, except the style sheets are not loading properly. The correct location should be: arcgis/home/js/jsapi/dijit/themes/tundra/tundra.css and /arcgis/home/js/jsapi/esri/css/esri.css

Recommended fix would be go into:
https://SERVERNAME/ags/admin/system/handlers/rest/servicesdirectory
and modify the .css file location

@conklinbd @elinz  Please advise if you'd like me to do this.

**Comment by elinz** [comment]
Modified the paths in the SetServicesDirectoryProps.py script to the following:
https://server.domain/arcgis/jsapi/jsapi/dijit/themes/tundra/tundra.css and 
https://server.domain/arcgis/jsapi/jsapi/esri/css/esri.css

Based on the information provided in the following help topic (although the paths in the doc are not 100% correct):
http://server.arcgis.com/en/portal/latest/administer/linux/connecting-the-arcgis-server-services-directory-to-your-portal.htm

Closing the issue.
