### ISSUE TITLE
Jenkins Build: Dataset path names for data used in CA_CC_Lidar related mosaic dataset too long

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1243]
Encountering copy issue when copying LasCache files because the path is too long...

Shorten folder names and dataset names for all folders/datasets similar to that shown in the screenshot and reset paths in related mosaic datasets
![image](https://cloud.githubusercontent.com/assets/4635490/10346121/624b4e6e-6ce2-11e5-8150-a71827441909.png)

**Comment by NatalieCampos** [comment]
@elinz The files in the LasCache folder are automatically generated files.  I have no control over their naming.  Since we are not using the cache properties you can ignore this folder in the copy.

**Comment by elinz** [comment]
@ACueva Please exclude the folder \\[FILESERVER]\data\FoundationOverlays\Elevation\LasCache from the data copy operation in the Jenkins build server process.

**Comment by ACueva** [comment]
Closed, same issues as #1287
