### ISSUE TITLE
 "Maritime Contact" feature service released, not map service

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1244]
"Maritime Contact" has its feature service released but the map service isn't released.

**Comment by jrweakland** [comment]
id:8ef34c2cf61848c59c55538fa14907d5

@lfunkhouser - ready for your review and release.

**Comment by lfunkhouser** [comment]
map service released by DemoMilitary

**Comment by jrweakland** [comment]
Verified.
