### ISSUE TITLE
Please release associated image for "Maritime Contact" demonstration

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1245]
id=40095e796bcd4fdca6a4fe1108079d3d

**Comment by conklinbd** [comment]
@jfrygeo last week was the cutoff for new content. 
What released item is this related to? We are fixing content for released items only this week.

**Comment by jfrygeo** [comment]
This is the map service for the released feature service of "maritime contact".

Sent from my iPhone

On Oct 9, 2015, at 10:15 AM, Ben Conklin <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://github.com/jfrygeo> last week was the cutoff for new content.
What released item is this related to? We are fixing content for released items only this week.

**Comment by conklinbd** [comment]
Ok, so this is a showstopper then?

**Comment by jrweakland** [comment]
@lfunkhouser - ready for your review and release

**Comment by conklinbd** [comment]
Tracking this as a showstopper since it is needed for released content.

**Comment by lfunkhouser** [comment]
This has been released by DemoMilitary

**Comment by jrweakland** [comment]
Verified.
