### ISSUE TITLE
Released version of "Maritime Threat Tools" does not contain any tools

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1246]
Contained in the "Maritime Threat Tools" application - now renamed "Apps - Maritime Threat Tools" was two tools:

<ln> Farthest on circle
<ln> Visible Range at Sea

now, in the released version, no tools are contained in the app. Is this by design?

@jrweakland @kerryrobinson

**Comment by jfrygeo** [comment]
Please add the two tools (1. Farthest on Circle - Image Service, 2. Visible Range at Sea) into the application.

**Comment by jfrygeo** [comment]
Closing issue... looks like these are for two separate demonstrations. 

<li> 1. web application . https://nsec.esri.com/arcgis/home/item.html?id=c88e3aae0920447d8d81dfe842c168b6 released by DemoMilitary
<li> 2. web application https://nsec.esri.com/arcgis/home/item.html?id=3b7814e0f661472cb0635f39b25fba17 released by DemoNationalSecurity

sorry for confusion

**Comment by kerryrobinson** [comment]
John this is a very simple app that I created just for my Web GIS story map.   Your original app (id=c88e3aae0920447d8d81dfe842c168b6) still has the two tools.
