### ISSUE TITLE
EsriMapsforOffice 3.1 client fails to connect to development server

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1248]
When connecting from a client machine running EM4O 3.1 you are not able to establish a connection to our portal.

Installing EM4O 3.0 client solves this issue.

**Comment by elinz** [comment]
I've installed Esri Maps for Office Portal Resources 3.1 on the dev portal.
@ACueva Please verify that EM4O 3.1 is working now.

**Comment by ACueva** [comment]
Verified with 3.1 client that our dev portal is working now.
