### ISSUE TITLE
Patrol Report Map and Map Tour need to be released

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1249]
Ok. I created a Story Map id:932fd43122d24c28ad408ef4b9387746.
This item and the web map id:13a6ba5d51b1467983cfb3bf0e96b78b will need to be released.

This is used in the Web GIS App Journal. 

@lfunkhouser can you review and release the Story Map and Web Map. I made it quickly so please check it out.

**Comment by lfunkhouser** [comment]
@ACueva Please look at link on image 5 to see if you can fix?

**Comment by kerryrobinson** [comment]
@conklinbd @lfunkhouser @ACueva I was also going to mention image 5, that it contains a link to the AAR html page. I found this useful demonstrating in the past but if it is a hassle to get it onto the Ops Server at this late stage I suggest the link is deleted.

My only other comment is that the descriptions clearly mention Jalalabad/ISAF although it clearly isn't. Probably too difficult to change all of that this late in the game.

**Comment by conklinbd** [comment]
I think the mentions of ISAF and JBAD are OK. If Avi feels like it he could try to update to our scenario names but I don't think it is that important.

**Comment by ACueva** [comment]
I've tried to edit the image 5 url, it's not saving for me.  I'll see if i can manually edit this item.

**Comment by ACueva** [comment]
Image 5 link has been deleted.  Had to modify the item's json file manually.

**Comment by conklinbd** [comment]
Verified that this was released.
