### ISSUE TITLE
WorldElevationCache service has display issues

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1250]
@NatalieCampos I'm seeing elevation differences when loading this image service in ArcGIS Pro.

![10-7-2015 3-42-50 pm](https://cloud.githubusercontent.com/assets/3093940/10353326/5ad1c348-6d0a-11e5-9784-d1bd9cd0b888.png)

**Comment by conklinbd** [comment]
@Acueva I don't think we want to test this in Pro. Does it work in the Scene Viewer?

**Comment by conklinbd** [comment]
I am seeing issues at specific scales in the scene viewer. It appears that the units for the high resolution (lidar) data is incorrect. We need to try and fix this for the release.

**Comment by NatalieCampos** [comment]
I am currently working  on it.@conklinbd

**Comment by lfunkhouser** [comment]
@NatalieCampos Can you post an update on this issue?

**Comment by NatalieCampos** [comment]
The issue seems that the cache itself does not honor the unit conversion raster function.  I am trying to get a confirmatioon from core.  I am currently recooking the cache at the level of the lidar by excluding the the lidar from the mosaic dataset.  When the cache is recooked I will replace the tiles and see if that solves the issue.

**Comment by conklinbd** [comment]
@NatalieCampos is working on this issue and will be republishing the service. The service may need to have a new name in order for the cache changes to be recognized. Should be done by the end of the day.

**Comment by NatalieCampos** [comment]
This issue has been fixed.  The fix required a new Cached elevation mosaic to be made and a small cache over the Monterrey Area to be created.  Portal Item maintains the same description as the previous version.    


![image](https://cloud.githubusercontent.com/assets/5116835/10415183/98dd9608-6fa3-11e5-884a-161a2a68349c.png)

**Comment by ACueva** [comment]
verified as fixed.
