### ISSUE TITLE
Spelling mistakes in What is Web GIS story map

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1251]
There are few spelling mistakes in the What is Web GIS story maps:

@conklinbd can you go ahead and fix these?

- [x] id:47a2a3b4659b41c08e6029353eb7b272 - Web Maps Journal, under 'Web Map', replace 'mashi' with 'mash'
![image](https://cloud.githubusercontent.com/assets/3383476/10365225/b074190e-6db9-11e5-84c5-376bb9f499a7.png)

- [x] id:a0944c6a2b4f4847863af010461c24a5 - Apps Journal, under 'Briefing Book', replace 'pprapred' with 'prepared' and remove the period after 'storm':
![image](https://cloud.githubusercontent.com/assets/3383476/10365249/f402c378-6db9-11e5-874f-4624d67a5de2.png)

**Comment by conklinbd** [comment]
@kerryrobinson I will do that, but I will wait until tomorrow or late this afternoon just to not mess with your presentation.

**Comment by conklinbd** [comment]
@kerryrobinson fixed.
Back to you to Verify.

**Comment by kerryrobinson** [comment]
Verified.
