### ISSUE TITLE
Please release " Mapping and Charting Solution for Server Installation Guide" for Maritime Chart Server

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1253]
Needed for anyone who wants to setup the Maritime Chart Server... This is a link to the documentation on the Esri Website.

c773544bd4654a08a9eaaa3107d35011

**Comment by conklinbd** [comment]
Any new content was due last Friday. 
This week was only for fixing issues to this missed the cutoff.

**Comment by elinz** [comment]
As I recall there are links to web pages created in the Demo and Scripts folder where this software is so having portal items containing the same is not a critical issue.

**Comment by jfrygeo** [comment]
This is item was overlooked in the demo group last week.

John

Sent from my iPhone

On Oct 9, 2015, at 10:13 AM, Ben Conklin <notifications@github.com<mailto:notifications@github.com>> wrote:


Any new content was due last Friday.
This week was only for fixing issues to this missed the cutoff.

**Comment by jrweakland** [comment]
@jfrygeo - this should be in word document in the \\FILESERVER\OpsServerStaging\2015_Q4\Resources folder.
