### ISSUE TITLE
Owner of service definition item "CommunityAddresses" is not the same as the associated hosted service item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1255]
Service Definition item a796a12d014f404593c19cc2f3e3c7e4 "CommunityAddresses" has not been released to ReleasedEManagement. This is associated with hosted feature service item de278fef421f48e5852d38211da7e481.

@jessnoo I'll change ownership of the service definition to ReleasedEManagement. FYI: This item does not have a thumbnail as the other EM service definition items do.

**Comment by elinz** [comment]
@jessnoo Changed ownership.

**Comment by jessnoo** [comment]
@elinz this Service is empty, so it appears that there is no thumbnail for the service definition.  we have not be doing any thumbnails for service definition items.

**Comment by elinz** [comment]
@jessnoo Okay. I did a search of the service definition items owned by ReleasedEMangement and they had thumbnails. Didn't know this service was empty.
