### ISSUE TITLE
Is ownership of web map "Illicit Drug Grows" correct?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1259]
Web Map, a4c628fc4aa04a05ad30fd32613df340,  "Illicit Drug Grows" is owned by DemoIntelligence       

However the two services referenced in the web map are owned by Released accounts (see below); should the web map really be owned by ReleasedIntelligence?

Service, d9c97656cb4e4ba0b7d1ad1d26f1c2a2, Drug Grows, ReleasedIntelligence                                                                                              Service, 4c42ae61d0ab4cca8d4662bc6fff1041, Topographic Basemap, ReleasedOpsServer

**Comment by lfunkhouser** [comment]
The owners are based on which groups they were in.  The services were reviewed for release, but can change owner from Released to Demo owner if @nfeuerstein wants them released as Demo content

**Comment by conklinbd** [comment]
It is fine for a Demo web map to use Released content. There are more factors then just the layers the web map uses.
