### ISSUE TITLE
Released web map "Foundation Data - Terrain Overlays" references unreleased services

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1260]
Web map "Foundation Data - Terrain Overlays" 506ad5fc2bcb423a9ded96180e5cd9f5  is owned by DemoNationalSecurity however it references the following services which are not released and not in the review process:

b9ef7590b9c9440c87ce17c448b38b53, HMMWV_CCM

**Comment by conklinbd** [comment]
This was in #1209

**Comment by conklinbd** [comment]
Closing as duplicate.
