### ISSUE TITLE
Is ownership of web map "SALUTE Reports" correct?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1261]
Web map "SALUTE Reports" owned by ReleasedIntelligence, but has service 5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc   owned by DemoMilitary, so should web map be owned by DemoMiltary?

**Comment by lfunkhouser** [comment]
SALUTE Reports was in the Release Review group under owner @nfeuerstein and was released as ReleasedIntelligence.  The map service was in Demo Review under owner @topowright and released as DemoMilitary
@nfeuerstein @topowright Are these items released under the correct owners?

**Comment by conklinbd** [comment]
I made this a showstopper. It is OK for Demo content to use Released content but the opposite is not good. I assigned to @nfeuerstein to decide.

**Comment by elinz** [comment]
@conklinbd I agree with your statement.

**Comment by nfeuerstein** [comment]
@lfunkhouser Let's make the SALUTE feature service RELEASED content, too.  If I'm remembering correctly, this happened because the service that the SALUTE Reports map used was an unsupported hosted service, so I switched it and grabbed a different SALUTE service.

**Comment by karlterrey** [comment]
@nfeuerstein Do we have anything from MarkLogic saying it is OK to do this?

**Comment by conklinbd** [comment]
@karlterrey this is not MarkLogic's data. This is all Esri created simulation data. 
We provided it to MarkLogic to support the demo.

**Comment by lfunkhouser** [comment]
I've removed MarkLogic from the credits.

@nfeuerstein If this service is going to be released, please update the summary and description so that it doesn't read like demo content.

**Comment by conklinbd** [comment]
Reminder, if you need someone to work on an issue reassign the issue to them.

**Comment by nfeuerstein** [comment]
Updated the summary and description.

**Comment by conklinbd** [comment]
This still needs to be reassigned. id:5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc is still owned by Demo instead of Released user.

**Comment by lfunkhouser** [comment]
Sorry @conklinbd I thought you meant to reassign the issue not the portal item to the person. I was waiting on the issue to be fixed before changing ownership. @joebayles can you check out the edits, please.

**Comment by joebayles** [comment]
@lfunkhouser - minor edits... suggest you rename it Spot Reports (vice Observation Reports), but it's good for release.

**Comment by conklinbd** [comment]
@joebayles reminder to reassign the issue if you are done with it. 
Reassigned to @lfunkhouser

**Comment by lfunkhouser** [comment]
Owner changed to Released Intelligence
@elinz to verify

**Comment by elinz** [comment]
Verified that service 5e8dc9bf8bcd4e2a98bfb7ff9d6b6bdc  is now owned by ReleasedIntelligence. Closing issue.
