### ISSUE TITLE
10 Small Aircraft thumbnail does not display in search results

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1263]
Thumbnail for 10 Small Aircraft image id:79ec58d78b8f42e7871e350abbf79787 does not display in search results list
![image](https://cloud.githubusercontent.com/assets/3800729/10379421/147eab36-6dc3-11e5-8975-1c7773a4057b.png)

**Comment by conklinbd** [comment]
This is typically an issue with the thumbnail size being larger then the required size.

**Comment by ScottCecilio** [comment]
Fixed, please verify.

**Comment by lfunkhouser** [comment]
verified as fixed
