### ISSUE TITLE
Urban Mission Rehearsal

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1264]
id=5f5e48f2cf48451b9fb8e5cecd7979b0
- [x] The description for the web scene says it was built w/ 2015.1, but the template is for 2014.1. Is this discrepancy intentional?
- [x] Bookmarks - some have odd naming conventions
  - [x] "Ingress#" - Maybe "Ingress Route #1"
  - [x] "Target#" - Suggest "Target [directional extent]" i.e. "Target SW Extent"
  - [x] "Egress#" - Maybe "Egress Route #1"

id=115b283d80a742729f751186188fb78d
- [X] The Credits field is empty.

id=115b283d80a742729f751186188fb78d
- [X] Move version from title to summary
- [x] Share with Release Review

**Comment by lfunkhouser** [comment]
I believe the template was certified against 2015.1 and used to make the web scene.

**Comment by jrweakland** [comment]
The 2014.1 version was certified to work with 2015.1

**Comment by conklinbd** [comment]
Issue #1010 depends on this.

**Comment by conklinbd** [comment]
If this item can not be fixed by 1300 it will need to be released with those issues present. @NatalieCampos you other issues are a higher priority then this one.

**Comment by lfunkhouser** [comment]
verified as fixed
