### ISSUE TITLE
Line of Sight GP Service does not exist

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1265]
id=bdb59e3de7904449aa92acb329873b4b

I checked ArcGIS Server manager, no such service exists.
![10-8-2015 4-10-47 pm](https://cloud.githubusercontent.com/assets/3093940/10382292/2b6faa70-6dd7-11e5-95a7-99ef4dca6e8e.png)

**Comment by conklinbd** [comment]
Not sure why this is in the version next milestone, the item is not released.
I am changing the milestone.

**Comment by ACueva** [comment]
@conklinbd I assumed since the item was shared out with the Release Review group and was included in our sprint we were trying to make a push to get the item released.
@lfunkhouser FYI

**Comment by conklinbd** [comment]
Hmmm...I don't see an issue associated with it, the cutoff for new content was last week so I am not sure what this was for. 
Unless @jrweakland has an explanation of why it is need for this release I think this needs to stay as something to deal with for the next release.

**Comment by jrweakland** [comment]
next release is appropriate

**Comment by jrweakland** [comment]
This GP service was created by @kgonzago

**Comment by kgonzago** [comment]
@jrweakland @conklinbd @ACueva That service should not have been created. Python scripts were provided for Line of Sight purely as a guide to how an LOS service is created and referenced in the Elevation Profile Table widget. This is noted in the README.md. I recommend deleting that LOS service.

**Comment by ACueva** [comment]
@kgonzago I've deleted the portal item.  I checked and there was no LOS service on the ArcGIS Server.
