### ISSUE TITLE
Population Density 2011 web app needs more information

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1266]
Is this item supposed to be in Release Review? This item (id:f1ded0d8cbef405582e189c50698dfab) cannot be released without a description and thumbnail.

**Comment by conklinbd** [comment]
If this isn't resolved by 1300 pst this item will not be released with the Ops Server. Upon review of the app I am guessing this item was mistakenly shared with release review.

**Comment by nfeuerstein** [comment]
Removed from Release Review - was definitely shared by mistake.
