### ISSUE TITLE
Imagery Basemap does not zoom in far enough

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/ops-server-config#1267]
Please see the following service. I have applications relying on this data and when I zoom in I have a gap in my Imagery cache.

https://[FILESERVER]/ags/rest/services/Basemaps/Imagery/MapServer

 When zooming over Monterey Regional Airport, I lose the basemap at 1:2,500

**Comment by NatalieCampos** [comment]
@ScottCecilio the cached level of 1:2500 is currently the lowest level the basemap goes down due to cache size issues.  If you need lower levels than that you will need to request it through @conklinbd.

**Comment by conklinbd** [comment]
@ScottCecilio this is extremely late in the process to identify this issue. The caches have not changed in more than 4+ months. Please provide additional justification for why this issue needs to be fixed prior to the release.

**Comment by conklinbd** [comment]
Note if we are going to do anything about this, we need to do it before 1300 pst so please provide justification now.

**Comment by ScottCecilio** [comment]
@conklinbd I have been ok with the cache the way it has been.  However, lastnight I was not able to get the same amount of zoom that I had before.  Don't know if the cache level is corrupted or what but I simply cannot zoom as much as I used to.

**Comment by conklinbd** [comment]
@ScottCecilio nothing has changed with the cache. Unfortunately I do not this this can be addressed today.

**Comment by NatalieCampos** [comment]
@ScottCecilio The imagery basemap has been updated to include L19 (the largest scale) for a small AOI around the airport. Please verify and close this issue if it has been fixed for your needs.
