### ISSUE TITLE
Only 4 of 7 Solutions Geoprocessing Toolboxes are shared with Release Review

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/ops-server-config#1268]
@mfunk @nfeuerstein The following 2.1.0 versions are not in Release Review. Should they be included on this Ops Server release? We are making document links to point to the data and need to know if these should be included
- Capability id:b75b298d780045cd803a8276e25ecb07
- Suitability id:bd7f9b40f5df41f78bc6faf895a14eee
- Operational Graphics id:417f577d5a474a9684e558aba870e84d

**Comment by mfunk** [comment]
**ALL** 7 of the solutions-geoprocessing-tools items should be there. Either they ALL need to be there, or none of them should be there. Is there are reason they aren't???

**Comment by mfunk** [comment]
Better yet @lfunkhouser how do I add them to Release Review? Where is it?

**Comment by conklinbd** [comment]
@lfunkhouser looks like you will need to reassign these items.

**Comment by lfunkhouser** [comment]
Visibility, Data Management, and Patterns are owned by Natalie and in the Release Review group
@mfunk Suitability and Capability 2.1.0 toolboxes (see item ids in issue) are owned by you and not shared with any review group
@nfeuerstein Operational Graphics is owned by you and not shared with any review group

Assigning to @nfeuerstein

**Comment by mfunk** [comment]
Capability and Suitability must have been moved from QA/QC. I put them back into QA/QC.

**Comment by nfeuerstein** [comment]
All 7 should be good to go and in Release Review now.

**Comment by lfunkhouser** [comment]
verified as fixed
