### ISSUE TITLE
Predictive Analysis Web App depends on unreleased content

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1273]
All of this content is in demo review but I am just logging an issue so these don't get missed.

Execute Query GP Service
id:c9e065fe2b3c47d9bc1cec734affe711
Predictive Analysis Demo Map
id:e8effa285e7e4cfcab3b004a3cfc8e55

**Comment by lfunkhouser** [comment]
Both items have been released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified that both items have been released. New issues were created for the services that are not released.
