### ISSUE TITLE
Illicit_Drug_Grows Feature Service does not exist.

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1274]
This service ags/rest/services/Hosted/Illicit_Drug_Grows/FeatureServer/0
is being called from:
ArcGIS for Geospatially Enabling the Intelligence Collector (Map Journal)
id:cf92fbb86028410cbdd84947d7e7a56a

The service does not exist and is causing the aforementioned Map Journal to fail in the Summary Application section.

**Comment by nfeuerstein** [comment]
@ACueva @phil7277 I replaced the summary app in the map journal with the working summary app that is in demo review: f6e165bf688c46daa06048fed1fb43e9
