### ISSUE TITLE
Modify UpdateWebApps.py script to perform search/replace in config_*.json files

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1276]
Web app builder apps have config files for widgets which contain server names and GUIDs. We need to perform search/replace on these files.

File name examples:
config_Basemap Gallery.json (there is a space in the file name)
config_Query Editor.json (there is a space in the file name)

**Comment by elinz** [comment]
@conklinbd The script is already modifying these files. It modifies files with the following search pattern: *.js, *.html, *.json, *.csv, *.erb

Also verified that the server names and guids were updated in web app builder widgets on the "TEM2015 TEST 01" server. Closing issue.

**Comment by conklinbd** [comment]
great news.
