### ISSUE TITLE
Image Observables web app relies on unreleased content

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1277]
Not in Demo or Release Review:
 id:2fed838435ea45df8cbc6e82c0517856 NAIP 2005 to 2014

**Comment by conklinbd** [comment]
This web map:
id:43774ea0de014514917b2167691b494e is in demo review. Maybe we should swap to use it?
@nfeuerstein

**Comment by nfeuerstein** [comment]
Switched the webmap used in Image Observables to one already in demo review: 43774ea0de014514917b2167691b494e

**Comment by conklinbd** [comment]
I want to verify this one.

**Comment by conklinbd** [comment]
Verified.
