### ISSUE TITLE
Predictive Analysis Demo Map uses unreleased service

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1278]
e8effa285e7e4cfcab3b004a3cfc8e55   "Predictive Analysis Demo Map"  used unreleased content:
e7d140d8de9f4fe5a40a9887e866e50a   Country Boundaries Raster Image Service. 
50c15cdd37cd49dcb5caa8e4f6ef4854 Country Boundaries Map Service

Owned by @ircampbell .
@nfeuerstein can you review and release?

**Comment by conklinbd** [comment]
@lfunkhouser I added these to demo review group.

**Comment by nfeuerstein** [comment]
@lfunkhouser I updated the summary and description for the map service and added to Demo Review.

**Comment by lfunkhouser** [comment]
released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified.
