### ISSUE TITLE
Places of Interest Web Map Released but uses demo service

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1280]
b9e9e4c1316c4d2aaae7c63c0f1f0c35   "Places of Interest" Web Map is owned by ReleasedIntel. All of the services are owned by Demo Intel. 
Recommend we reassign this web map to DemoIntel user. 

@nfeuerstein @lfunkhouser

**Comment by lfunkhouser** [comment]
@conklinbd owner changed to DemoIntelligence

**Comment by conklinbd** [comment]
verified.
