### ISSUE TITLE
Invalid MissionReport portal item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1281]
The Military/MissionReport/FeatureServer Service json is associated with the following portal items...
{"itemID":"b0d5bd4b97d34882adfbae9def6cc309","type":"MapServer"},{"itemID":"d78f22ee0b5e454588b9a0883cfd8d22","type":"FeatureServer"}]

However there is a manually created item 7e098cb0d923464ab6089920b20fc70c that references this service. This portal item needs to be deleted.

**Comment by elinz** [comment]
portal item 53e37c5d1d6e4fe3a6970a2879ce4508 also needs to be delete. this was manually created and not associated with the mission report map service.

**Comment by conklinbd** [comment]
I deleted these items and the original service related to issue #1195

**Comment by elinz** [comment]
Verified portal items 7e098cb0d923464ab6089920b20fc70c  and 53e37c5d1d6e4fe3a6970a2879ce4508  have been deleted. Closing issue.
