### ISSUE TITLE
The Test/IncidentHotSpots/GPServer is owned by DemoIntelligence but resides in the AGS Test folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1282]
@conklinbd @lfunkhouser @nfeuerstein Is everyone okay with this?

**Comment by conklinbd** [comment]
This should be corrected.

**Comment by conklinbd** [comment]
My recommendation is to pull it from the release.

**Comment by lfunkhouser** [comment]
This item (id:797e7473926b430fa19788f62b56afe9) will not be released.  Owner changed to @nfeuerstein

**Comment by nfeuerstein** [comment]
Agreed.  Let's pull it.

**Comment by elinz** [comment]
I'll verify since I submitted the issue.

**Comment by elinz** [comment]
Verified that ownership of this service is now @nfeuerstein. Closing issue.
