### ISSUE TITLE
Install Test: InstallIIS.bat, error adding MIME type

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1285]
Server OS:  Windows Server 2012 R2

When running InstallIIS.bat, I get the following error: 

![image](https://cloud.githubusercontent.com/assets/3383476/10416887/1fd23e92-7022-11e5-8dec-abdf8ae72769.png)

This is because the .json MIME type already exists (I double checked).   So this is not critical but might be worth either checking for the exsistance of the MIME type before issuing the command, or warning the user that this error message is OK.

The script continued without problem.

**Comment by elinz** [comment]
@kerryrobinson Added the following note in red to the "Install Internet Information Services (IIS)" section of the install guide:
![image](https://cloud.githubusercontent.com/assets/4635490/10488281/ce2fa980-724c-11e5-9955-46c778d03fd6.png)

**Comment by elinz** [comment]
@kerryrobinson I checked in the install guide change to Esri\ops-server-config v.next. Assigning back to you to verify. If you think this mod to the install guide sufficiently addresses your concern please just close the issue.

**Comment by kerryrobinson** [comment]
Looks good. Just a small spelling error in your text... "mimeMap" instead of "mimiMap".   I'll go ahead and close.

**Comment by elinz** [comment]
@kerryrobinson I'll fix the spelling issue.
