### ISSUE TITLE
Install Test: Copy Files on Data folder doesn't work due to incredibly long filename 

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1287]
CopyData.py failed when copying the R:\OPSServerInstall\Server\Staging\Data folder due to a long file name:

![image](https://cloud.githubusercontent.com/assets/3383476/10417901/e97d5d64-7043-11e5-8f42-f9a13b4c600e.png)

The name was so long Explorer wouldn't let me copy and paste the filename, so here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/3383476/10417927/c53083f4-7044-11e5-90ee-4f5b2f23888c.png)

I deleted the folder on the disk and re-ran the script. I'll manually copy the files back if possible. Not sure if anyone else will see this issue; It will be necessary to keep the file paths as short as possible.

**Comment by ACueva** [comment]
@kerryrobinson I believe this issue might go away when we address this issue. https://github.com/Esri/ops-server-config/issues/1243

**Comment by kerryrobinson** [comment]
@ACueva OK thanks.  Yes it is the same thing, so we can ignore the folder.

**Comment by ACueva** [comment]
Removing the files from the release build included on the USB drive.  In addition, different copy tool is used for install (RoboCopy)

**Comment by elinz** [comment]
@ACueva I removed the contents of the folder FoundationOverlays\Elevation\LasCache\LasCache from the current release build location
