### ISSUE TITLE
Install Test: PublishHostedServices.py didn't work until I gave all users the Publisher role

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1288]
I received an error when running PublishHostedServices.py (the error message was on line 334, and the error code was just 'code').

I realized I was only able to publish this service manually through the Portal once I made the user (Demo Military in this case) a Publisher.  Once i changed all users to have the Publisher role, this script ran successfully.

I'm not sure if this is something that should have been done in a earlier script (PortalContentPost.py?) and didn't succeed, or if this is something missing from the scripts.

**Comment by elinz** [comment]
@kerryrobinson I found this issue when I performed the first test of the fall release. I changed the role of the Demo and Released users to publisher on the dev server; forgot to make the change to the extracted content I shipped to you. This script will work on the final build of Ops Server. Thanks. Assigning back to you to close. Thanks.

**Comment by kerryrobinson** [comment]
@elinz sounds good. closing issue.
