### ISSUE TITLE
Install Test: Running CopyFiles.py on hosted caches... caches already exist

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1289]
When running Copy/files on the CachesHosted folder, i get the message that the dataset already exists (but it is an empty cache):
![image](https://cloud.githubusercontent.com/assets/3383476/10428769/b57d689e-70eb-11e5-9d5f-47be26a8fa10.png)

If i delete the existing version in c:\arcgisserver\directories\arcgiscache, the copy works fine.

**Comment by elinz** [comment]
@kerryrobinson Step #1 in the "Copy hosted service caches" section instructions the user to move the existing hosted cache folders out of the arcgiscache folder before you copy the cache files from the external drive. I'll make the text bold red in the install guide right now and resend to you.

**Comment by kerryrobinson** [comment]
@elinz Aha, i see that now. Completely missed that. Maybe make it in bold or highlight it somehow.  All of these things blur into each other eventually...

**Comment by elinz** [comment]
@kerryrobinson I'll break step #1 into two steps and make the file move bold red.

**Comment by kerryrobinson** [comment]
reopening to track the edit to the document

**Comment by kerryrobinson** [comment]
document fix looks good.
