### ISSUE TITLE
Make final updates to install guide

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1294]
- [x] make sure to include info about possible issue creating initial portal administrator account.
- [x] Update resource spec table.
- [x] Make server name/username/password in script examples and other references consistent.
- [x] Review section "Verify that Geoevent extension is updating feature services" and make necessary edits.

**Comment by conklinbd** [comment]
Assume this is for this upcoming release. Setting milestone.

**Comment by elinz** [comment]
@conklinbd yes, just forgot to set the milestone.

**Comment by elinz** [comment]
Fixed in Esri\ops-server-config v.next. Also included in TEM 2015 build 20151011_0757. Closing issue.
