### ISSUE TITLE
TEM2015 Test 02: Confirm that Hosted/CountIncidentsByLOC wasn't configured as tile service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1301]
The dev server has a folder in the arcgiscache folder for this service. When I published this service to the test machine no cache folder was created for this service. If it's not needed I'll delete the cache folder for this service from the build.

Don't believe having this folder on the Ops Server would cause any problems.

**Comment by lfunkhouser** [comment]
Folder will be deleted from the build and the test server.

**Comment by elinz** [comment]
@nfeuerstein I deleted this cache folder from the test machine. Can you test if this service Hosted/CountIncidentsByLOC is working as expected? If it is, assign the issue back to me and I will delete this cache folder from the TEM2015 build and close this issue. Thanks.

**Comment by elinz** [comment]
I deleted the Hosted_CountIncidentsByLOC from the build folder 20151011_0757\OPSServerInstall\Server\Staging\CachesHosted.
