### ISSUE TITLE
TEM2015: Time Aware template web app doesn't reference Portal JSAPI

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1305]
The Time aware templates web app (used with the NAIP Over Time app (id:645bcc9a7be94e1cbe3541e8767bf7f6) doesn't reference the Portal-hosted version of the jsapi.

In order to work without internet, \SolutionsWeb\Apps\NaiotnalIntel\time-aware-template-master\index.html needs to be modified:

```
17:  <link rel="stylesheet" href="//server.domain.com/arcgis/jsapi/jsapi/dijit/themes/claro/claro.css">
18:  <link rel="stylesheet" href="//server.domain.com/arcgis/jsapi/jsapi/esri/css/esri.css">

94:  <script type="text/javascript" src="//server.domain.com/arcgis/jsapi/jsapi/"></script>
```

This is the first web app i've noticed that does this, not sure if others have the same problem.  Begs the question whether this should be handled in the UpdateWebApps.py script?  (or maybe it was supposed t but didn't work?)

**Comment by conklinbd** [comment]
My guess is that the original app did not have the correct urls. 

@ACueva could probably investigate this issue.

**Comment by elinz** [comment]
FYI: the UpdateWebApps.py is configured to search/replace guids and server names in all .html files. 

@kerryrobinson @conklinbd @ACueva Just examined the \SolutionsWeb\Apps\NationalIntel\time-aware-template-master\index.html file in the TEM2015 release build (20151011_0757) and I find that the server name references do not exist:

![image](https://cloud.githubusercontent.com/assets/4635490/10562455/dc9f87ac-7511-11e5-9b1b-9c9add1dd315.png)

![image](https://cloud.githubusercontent.com/assets/4635490/10562464/61a1cdc0-7512-11e5-9196-f0bd1a01f68a.png)

**Comment by kerryrobinson** [comment]
@elinz correct, the web app wasn't modified to use the server's JSAPI in the first place. 

this is what i  manually replaced them with:
![image](https://cloud.githubusercontent.com/assets/3383476/10582244/cdaab0e6-767e-11e5-8af6-dee696a09d38.png)
![image](https://cloud.githubusercontent.com/assets/3383476/10582250/db1b99f2-767e-11e5-8771-a4de04f284a1.png)

**Comment by elinz** [comment]
@kerryrobinson Understand. Didn't read this close enough.

**Comment by kerryrobinson** [comment]
Ideally index.html gets updated to point to the server before the disk is cut so that your script will make the update.  Probably too late for that though so maybe a note in the install doc to manually update it?

**Comment by elinz** [comment]
This has been corrected on development server and addressed in 2015 4th Quarter Ops Server Patch.
Note: issue related to #1375
