### ISSUE TITLE
web scenes don't seem to import correctly during ops server install

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1309]
web scene seems to be corrupt after installing ops server.  it needs to be manually recreated; i can't find anyway to edit the layers that make up the scene.

**Comment by conklinbd** [comment]
Assigned to @elinz. If you want me to look into this, let me know.

**Comment by elinz** [comment]
@conklinbd If you can take a look at this that would be great. I'm looking into another publishing issue right now.

**Comment by elinz** [comment]
@kerryrobinson Is the web scene in question the one listed in the issue #1322 ?

**Comment by kerryrobinson** [comment]
Yes I believe so.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by conklinbd** [comment]
This was resolved in #1322 so I am closing this issue.
