### ISSUE TITLE
install doc- edits to geoevent section

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1310]
a few updates to geoevent sectin of install doc:

- step 2b should say to copy the contents of the OpsServerInstall\GeoEventData folder
- after importing the GeoEventConfig.xml , step 3eiii, i had to use the url: https://server.domain.com:6443/arcgis instead of https://server.domain.com/ags

**Comment by elinz** [comment]
@kerryrobinson I made the first edit about the OpsServerInstall\GeoEventData folder, but didn't make your second edit; I left as https://server.domain.com/ags as this does work. Maybe something else is wrong in your environment? we can discuss more.

**Comment by elinz** [comment]
@kerryrobinson I'll make a note in the guide that states that that using https://server.domain.com:6443/arcgis is an alternative in case https://server.domain.com/ags does not work.

**Comment by elinz** [comment]
@kerryrobinson I add the change about URLs in red. If you like the change please close the issue.

![image](https://cloud.githubusercontent.com/assets/4635490/10516638/18c526ac-730e-11e5-9d36-fae2f5f2f9ab.png)

**Comment by kerryrobinson** [comment]
looks good.
