### ISSUE TITLE
Is there a simulation file for the Movement data?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1311]
I have GeoEvent working OK but no input for the Movement data.  Is there a simulation file that should be used?

**Comment by conklinbd** [comment]
@kerryrobinson this will be included with the movement demo. 
I am still working on packaging it up.

**Comment by conklinbd** [comment]
I have shared the simulation file with the demo and scripts content. 
DemoAndScripts\Intelligence\MovementAnalysis.

To @lfunkhouser to verify.

**Comment by lfunkhouser** [comment]
Closing. verified as fixed.

**Comment by kerryrobinson** [comment]
Unfortunately this didn't make it into the DemosAndScripts folder on the disks distributed at the TEM.

**Comment by elinz** [comment]
It will be in the 2015 Q4 Patch.
