### ISSUE TITLE
Republish Military/PiracyBySubregion2009to2013 from original source

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1313]
See #1307

**Comment by jfrygeo** [comment]
Republished (overwrite existing service)
<li> item# 765c051ab7d14139bd8dc8857ed2e435
<li>../Military/PiracyBySubregion2009to2013/FeatureServer/

**Comment by elinz** [comment]
Extracted SD files from ArcGIS Server. Verified that "folderName" property in serviceconfiguration.json file references the "Military" folder. Closing issue.
