### ISSUE TITLE
Republish Military/NGASubregions from original source

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1314]
See #1307

**Comment by jfrygeo** [comment]
Republished (overwrite existing service) NGA Subregions:
<li> item: bee2ec5acb7e4c3f9a37c4b37406f8da
<li> Military/NGASubregions/FeatureServer

**Comment by elinz** [comment]
Extracted SD files from ArcGIS Server. Verified that "folderName" property in serviceconfiguration.json file references the "Military" folder. Closing issue.
