### ISSUE TITLE
TEM2015 Test 02: web map "Predictive Analysis Demo Map" references service that was not released

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1315]
Web map dev id: e8effa285e7e4cfcab3b004a3cfc8e55 references elevation service dev id: 93207e73bc804fb897eba2d5ef2b382d that was not released.

**Comment by conklinbd** [comment]
Added to queue for manual extraction

**Comment by elinz** [comment]
@conklinbd Is this queue stored somewhere?

**Comment by conklinbd** [comment]
In github man!

**Comment by elinz** [comment]
@conklinbd So you adding "Added to queue for manual extraction" string to issues so we can search for these?

**Comment by conklinbd** [comment]
Yeah. Simpler than adding a new label.

**Comment by conklinbd** [comment]
This item needs to be released @nfeuerstein 
@lfunkhouser

**Comment by conklinbd** [comment]
Issue #1352 depends on this item

**Comment by nfeuerstein** [comment]
@lfunkhouser tested the elevation layer and then shared with Demo Review.  I'm adding a new issue (after next) to find out why we need two elevation services over the same geography.

**Comment by lfunkhouser** [comment]
Released by DemoIntelligence

**Comment by conklinbd** [comment]
I have verified this and closed it since we have the other open issue for the extraction.
