### ISSUE TITLE
Seaside Initial Population at Risk Assessment Web Map not released

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1316]
This web map (id: 2969122d244048ecad0900278eaa6aa1) is needed for the Tsunami Hits Monterey Coast Briefing Book (id:b851f6a1a2eb4fe4a58fa3145219e0c2), which is released.

**Comment by conklinbd** [comment]
@elinz adding to your queue for manual extraction.

**Comment by elinz** [comment]
Added to queue for manual extraction

**Comment by conklinbd** [comment]
@nfeuerstein this needs to be released today by 1300.
@lfunkhouser

**Comment by conklinbd** [comment]
Issue #1352 depends on this item

**Comment by nfeuerstein** [comment]
@lfunkhouser tested the map and then added to Demo Review group.

**Comment by lfunkhouser** [comment]
Seaside Initial Population at Risk Assessment released by DemoIntelligence

**Comment by conklinbd** [comment]
Verified.
