### ISSUE TITLE
TEM2015 Test 02: Public Information Map Description missing spaces between words

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1318]
The Description text for the Public Information Map, item 4bbe2b10e96c4bb59093496941bf80cf has several missing spaces between words.
![image](https://cloud.githubusercontent.com/assets/3801392/10496686/cf1c3280-7276-11e5-860f-1a72cf3fcd40.png)

**Comment by BobBooth** [comment]
Also missing a space in description of 6e2199d78cb4415db8a8b9105a12cccb  and 6e2199d78cb4415db8a8b9105a12cccb between "to" and "view".
Multiple similar issues in description of b03b5ec0ffeb45829844160c52781a3c.

**Comment by conklinbd** [comment]
Will not fix. These items are taken directly from the EM released content and not modified.
