### ISSUE TITLE
TEM2015 Test 02: Operations Response web mapping app Locate Incident widget fails to pick up rapidly sketched vertices

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1319]
When I digitize a polygon using the Locate Incident widget in the Operations Response web mapping app - d3edfee7294d417a9a9f5f3e67adf98b I find that it doesn't register mouse clicks if I rapidly sketch the polygon. It does register each vertex if I pause between clicks.
![image](https://cloud.githubusercontent.com/assets/3801392/10497126/2215e844-7279-11e5-9387-501e7bf32b2c.png)

**Comment by conklinbd** [comment]
I would consider this a known limit of the template.
