### ISSUE TITLE
TEM2015 Test02:  World Elevation WGS84 has extra raster function attached

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1320]
For the portal item (id:f4511f57cea74617876e39cfa8e23bfa), the Slope RGB2 raster function needs to be removed.  

![image](https://cloud.githubusercontent.com/assets/5116835/10497398/712607ba-727a-11e5-97d2-2589f7773657.png)

**Comment by conklinbd** [comment]
We will not fix this for this release.

**Comment by NatalieCampos** [comment]
The Slope RGB Map2 has been removed from the mosaic dataset.  

![image](https://cloud.githubusercontent.com/assets/5116835/10766580/74c72956-7c95-11e5-8a57-b45087a69deb.png)
