### ISSUE TITLE
TEM2015 Test 02: Coastal Relief Model still points to development server

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1321]
The Coastal Relief Model does not load as it still points to  

/ags/rest/services/NationalIntelligence/CoastalReliefModel/ImageServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

**Comment by elinz** [comment]
@NatalieCampos Please provide more information. When you say "Coastal Relief Model" are you taking about a service, a web map? What's the id of the portal item? When you say "does not load" what are you referring to? If it's a service are you trying to display the service in the portal viewer? 

Tell us how to replicate the issue. This doesn't really tell us anything. Thanks.

**Comment by NatalieCampos** [comment]
- id=8df0127db0854fdf9a96d4c9c4b6bbd4
- by does not load, I mean that it does not load in the web map
![image](https://cloud.githubusercontent.com/assets/5116835/10497917/71231034-727d-11e5-8b78-4832be3bf2b2.png)
- to reproduce click the portal item and add to a new web map

**Comment by conklinbd** [comment]
This issue depends on #1323 being resolved.

**Comment by conklinbd** [comment]
Assigning to @NatalieCampos to retest after the other issue is resolved.

**Comment by NatalieCampos** [comment]
Verified
