### ISSUE TITLE
TEM2015 Test 02: basemap not cached in whole extent of example features

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1324]
Reviewed presentation: ArcGIS for Geospatially Enabling the Intelligence Collector (0555560732ae406495cf5fa55b6bd023), in the Drug Grows section, zoomed in to center of map, lost basemap.  This may just be because it is south of the AOI, but the features straddle the line.
To repro, zoom in where feature data is, lose basemap (the basemap service is at /ags/rest/services/Basemaps/TopographicMap/MapServer).
![image](https://cloud.githubusercontent.com/assets/3801392/10498448/44177cd0-7280-11e5-822c-756b6f814dd7.png)

**Comment by conklinbd** [comment]
This is a known issue. We will not build high resolution caches for the entire AOI.
