### ISSUE TITLE
TEM2015 Test 02: map not displayed, prompted for portal sign-in

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1326]
In Story Map presentation: Reviewed presentation: ArcGIS for Geospatially Enabling the Intelligence Collector (0555560732ae406495cf5fa55b6bd023) on second to last pane, topic is ArcGIS WebApp Builder, prompted for portal login credentials.
![image](https://cloud.githubusercontent.com/assets/3801392/10499032/da79edaa-7282-11e5-88b3-e63017365b3a.png)

**Comment by elinz** [comment]
@BobBooth I believe this is expected behavior if your not already signed into the portal. I don't think you can access web app builder unless you are signed in.

**Comment by BobBooth** [comment]
OK.  I can't seem to sign in to the portal.

**Comment by elinz** [comment]
@BobBooth You need to create an account.

**Comment by BobBooth** [comment]
OK, Seems to work after I do that.
Guess that "log in to the portal" should be part of the instructions for demos (probably are).

**Comment by conklinbd** [comment]
@BobBooth Can you verify that this issue is resolved?

**Comment by BobBooth** [comment]
If it is a requirement to view the presentation that the user be signed it to the portal, then this issue is user error. It behaves as designed.  Just confusing if you're not signed in.
Closing.
