### ISSUE TITLE
TEM2015 Test 02:  Intelligence SIGINT dashboard video widgets not available

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1329]
Downloaded and opened Intelligence/SIGINT dashboard
id:4b66154bc0c54ec08e0f195cfc73651c
Two panels say "The Custom widget VideoWidget is not accessible"
![image](https://cloud.githubusercontent.com/assets/3801392/10500523/a482fbaa-728d-11e5-9132-a8852b90bc42.png)

Other widgets look good.

**Comment by conklinbd** [comment]
It appears that the dashboard has a reference to the AddIn id:D9E73D85E0874CC4A192A6873BE71E3D
The new id for this AddIn is
id:aae674686c5d4564b390fa2ba8afd560

The dashboard config json has an array of ids that need to be updated during the copy process. 
addInIds: [
"D9E73D85E0874CC4A192A6873BE71E3D"
]

**Comment by elinz** [comment]
99.9% sure that they issue is that the publishing script didn't update the GUIDS because the addInIds are stored in uppercase and not lowercase. Looking into modifying update logic to search for both uppercase and lowercase guids.

**Comment by elinz** [comment]
I've updated the PortalContentPost.py, UpdatePortalGUIDs.py, and UpdateWebApps.py scripts to search for uppercase, lowercase versions of the search string as well as the original search string.

**Comment by elinz** [comment]
Fixed in Esri\ops-server-config v.next. Will verify if scripts modifications solved the widget issue when testing Ops Server install on "TEM2015 Test 03" machine.

**Comment by elinz** [comment]
Verified on TEM2015 Test 03 server. Closing issue.

![image](https://cloud.githubusercontent.com/assets/4635490/10562413/ff1e2c86-750f-11e5-8af1-968ff2a68058.png)
