### ISSUE TITLE
TEM2015 Test 02: URL in document links for VCP and Lodgment Planning are not working

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1330]
Noticed that the url in the document links are not working, as in when you click on the url it takes you to a new page, with a 404 error.  Using the dropdown below the thumbnail to "open" also returns a 404.

https://[testserver05]/arcgis/home/item.html?id=18578392acfb40a5b55fabfee4bb65a6  -- vcp
https://[testserver05]/arcgis/home/item.html?id=5edf7000d0c14f8695eca14386f35ab2   -- lodgment

don't know how widespread this problem is, i did not go through checking other document links, i actually only mistakenly discovered this while testing something else.... recommended all document links be checked

**Comment by elinz** [comment]
@dfoll The "Downloads" folder is still copying (it takes hours) to the test server so not all links we work right now. Only EmergencyManagment and Intel are copied right now. In addition I believe @lfunkhouser still needs to rename folders and/or files in the build "Downloads" folder.

**Comment by dfoll** [comment]
check. 

@elinz feel free to close this then if you are confident that it will be fine after the downloads folder is done copying

**Comment by conklinbd** [comment]
Assigned to @dfoll for retesting. Also, I do not consider this a showstopper for the release so even if it doesn't get fixed we will proceed with the release.

**Comment by dfoll** [comment]
these two are working now, however i am seeing this behavior with the visibility and range document link... will open a new issue for that
