### ISSUE TITLE
TEM2015 Test 02: No portal item for Visibility and Range on test server

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1336]
There is no portal item for Visibility and Range on [testserver05].... i'm positive this should exist,as it was just updated. see issue below in regards to it being updated.

#1269

**Comment by elinz** [comment]
@dfoll Please clarify. What is missing? Is it the document link item or application template item?

Application template items for the "Downloads" will not be included in the Ops Server release. As far as document link items I believe that only a document link item for the latest download will be included in the Ops Server release; note this is a document link item for version 4.0.0 of Visibility and Range on the test server. Thanks.

**Comment by lfunkhouser** [comment]
Confirmed with @dfoll it was the template he was referring to and explained that desktop templates won't be released as portal items.  Closing issue.
