### ISSUE TITLE
TEM2015 Test 02: Application "Elevation Profile of Damaged Areas" is missing layers

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1337]
The following layers are missing that are being listed in the Table of Content in the application: 

id:5ba2b7dec99245879efa188b44b5740f
Application LInk: 
arcgis/apps/Elevations/index.html?appid=5ba2b7dec99245879efa188b44b5740f

Layers are missing: 

Damage Assessment - Damage to Buildings
Damage Assessment - Damaged to Areas

I would expect that these layers would be in the application because they are listed in the TOC

**Comment by elinz** [comment]
@topowright These layers exist. The app 5ba2b7dec99245879efa188b44b5740f references the web map e094868a1d274a59959f508c4ea1598a ("Multiple Businesses and Police Station Destroyed").

This web map has the following damage related layers, which do exist:
/ags/rest/services/Hosted/DamageAssessment/FeatureServer/0 (Damage to Buildings) - contains no records.
/ags/rest/services/Hosted/DamageAssessment/FeatureServer/1 (Damage to Bridges) - contains no records.
/ags/rest/services/Hosted/DamageAssessment/FeatureServer/2 (Damaged Areas) - contains records.

Is there something I am missing?

**Comment by conklinbd** [comment]
I think was strictly a performance issue.

**Comment by elinz** [comment]
I looked into this further. The portal item associated with this service Hosted/DamageAssessment/FeatureServer states in the description "You can create an empty hosted feature service from this existing feature service." Therefore it was the intent of the service author that this service was not suppose it have any features.

**Comment by topowright** [comment]
@elinz Based on the above information there are no actions.

**Comment by elinz** [comment]
@topowright I've loaded the features from the service on the dev server into the file geodatabase stored in the .sd file for the associated portal item in the Ops Server build so the damage buildings and damage area feature classes will have features; note the damage bridges feature class didn't have any features on the dev server.
