### ISSUE TITLE
TEM2015 Test 02: Intelligence SIGINT Dashboard missing Video Widget 

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1338]
The Operations dashboard is missing the custom video widget. 

id: 4b66154bc0c54ec08e0f195cfc73651c

Background: 

When this widget was used at UC 2015 it would have to be manually added; however, I do not see this widget as a option in the portal items.

**Comment by elinz** [comment]
@topowright This is a duplicate issue. See #1329. Please close issue.
