### ISSUE TITLE
TEM2015 Test 02: Military Reports Ops Dashboard Failed to Load in Browser

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1339]
id:01d66af31fa54cee96dcb3ab6b3d77fc

![e0ac968c-7345-11e5-9bc5-9956eeb284dd](https://cloud.githubusercontent.com/assets/5739155/10528296/41a237ea-734a-11e5-817c-560678ba893c.png)

**Comment by conklinbd** [comment]
@jrweakland Be careful in your screenshots to not capture internal urls.

**Comment by conklinbd** [comment]
Can't reproduce (think it is a performance issue).

**Comment by jrweakland** [comment]
works
