### ISSUE TITLE
TEM2015 Test 02:Two Farthest on Circle Tools available on Maritime Threat Tools Application  

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1340]
The application Maritime Threat Tools has two buttons inside the application that does the same thing. 

item URL:  apps/webappviewer/index.html?id=f6417c04a63543018b09a77ccd1edc67

id: f6417c04a63543018b09a77ccd1edc67

**Comment by conklinbd** [comment]
I think this is confusing but not an issue for the release. Putting in to the next release.
