### ISSUE TITLE
TEM2015 Test 02: Operation Cobra Strike (Display Only) Does Not Load the Ops Dashboard

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1341]
id:6f4e49320d4a4f15a9556504b287ddbd

![822f84f4-7348-11e5-8cd7-98112afb18ba](https://cloud.githubusercontent.com/assets/5739155/10528286/29c87396-734a-11e5-81a3-c3cb3cae9f4c.png)

**Comment by conklinbd** [comment]
Can't Reproduce. Most like just a performance issue.

**Comment by elinz** [comment]
Tested against the TEM2015 Test 03 server. I can't replicate. Was the ops dashboard from the specific portal installed?

![image](https://cloud.githubusercontent.com/assets/4635490/10562497/c8dd448c-7513-11e5-9f56-3119962767e4.png)

**Comment by jrweakland** [comment]
@elinz - Yes. I downloaded ops dashboard from the specific portal. NOTE: I was using Internet Explorer 11.0.9600.18036
