### ISSUE TITLE
TEM2015 Test 02: Military Reports Feature Layer is Not Available

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1342]
id:ffe4be0233ce4e95a3752464abd37283

![2ad5fc6e-7349-11e5-88e0-ad11b59e66d0](https://cloud.githubusercontent.com/assets/5739155/10528265/093fe97e-734a-11e5-8607-c6e972651280.png)

**Comment by conklinbd** [comment]
This works for me. I think this was just a performance issue.
To retest, if the web map doesn't load the first time just wait 5 seconds and then hit refresh on the browser.

**Comment by jrweakland** [comment]
Works
