### ISSUE TITLE
TEM2015 Test 02: MEDEVAC Requests Fails

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1344]
id:1d230e9956884ff0ba6a60786c6207a8

![9159c674-734d-11e5-89b0-84bdd5bb1a37](https://cloud.githubusercontent.com/assets/5739155/10529252/137d9c22-7351-11e5-894c-c8e6976f0206.png)

**Comment by conklinbd** [comment]
URL in your screenshot.

**Comment by conklinbd** [comment]
Can't reproduce.
