### ISSUE TITLE
TEM2015 Test 02: Wave Watch III Waves and Winds

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1345]
Layer is not drawing in the portal map viewer

id: id=e6ebb3b7d87141b0a10ce8920f4ec5e5

**Comment by elinz** [comment]
@topowright The service associated with this portal service item does exist ( ags/rest/services/Military/WaveWatchIII/ImageServer) and does display in the portal map viewer.

**Comment by conklinbd** [comment]
HMMM. I just looked for this service and it didn't show up.
Must be slow startup time. Maybe it is the same issue as #1343

**Comment by conklinbd** [comment]
This works now, seems to be strictly a performance issue.

**Comment by topowright** [comment]
@conklinbd @elinz I have verified that this service now draws successfully.
