### ISSUE TITLE
TEM2015 Test 02:  Meteorological Service of Canada (MSC) GeoMet Geospatial Web Services

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1346]
id=835d048facb04b52822bb83a24040d3a 

Service does not draw in portal web viewer

**Comment by conklinbd** [comment]
I believe we determined that this is a known limit and does not work.
@elinz and @jrweakland is that correct?

If so we probably shouldn't have released this.

**Comment by conklinbd** [comment]
This wasn't a known issue but unfortunately this external service is outside of our control. 
This can not be "fixed" by us.
