### ISSUE TITLE
TEM2015 Test 02: Monitored Facilities and Suspicious Location widgets show no data

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1350]
Testing What is Web GIS web mapping Application, item 42b2b67c672045388433bacd6e2a6676
On Apps tab, slide 2, the Monitored Facilities and Suspicious Location Frequented widgets are showing no data.
![image](https://cloud.githubusercontent.com/assets/3801392/10529338/e9419ade-7351-11e5-8511-9e154fbfc729.png)

**Comment by conklinbd** [comment]
@BobBooth this was because the movement simulation was not run. This is part of the demo setup step.
