### ISSUE TITLE
TEM2015 Test 02:  Map data does not load "An error occurred while loading the map"

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#1351]
Testing What is Web GIS web mapping Application, item 42b2b67c672045388433bacd6e2a6676
Apps tab, 6th slide, Briefing Book, page 3 of 4 Demographic Data in the affected Zone
Map data does not load "An error occurred while loading the map"
![image](https://cloud.githubusercontent.com/assets/3801392/10529370/30b7c258-7352-11e5-8eb6-612f0760145b.png)

**Comment by elinz** [comment]
The issue is that the web map "Seaside Initial Population at Risk Assessment" (id 2969122d244048ecad0900278eaa6aa1 on dev server) is not released. NOTE: damage assessment feature still won't draw even if web map is released since the hosted feature service is empty on deployed ops servers.

**Comment by elinz** [comment]
Added to queue for manual extraction

**Comment by conklinbd** [comment]
Duplicate of #1316

**Comment by conklinbd** [comment]
Issue #1352 depends on this item
