### ISSUE TITLE
Items for manual extractions

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#1352]
ID from DEV Server:
- [x] id: 2969122d244048ecad0900278eaa6aa1 Seaside Initial Population at Risk Assement Web Map
related to issue #1316 
- [x] id:fda053a2afd5468b8d2fb8ee441012b1 Tsunami Damage Assessment 3D Web Scene
Related to issue #1322 
- [x] id:93207e73bc804fb897eba2d5ef2b382d Elevation Image Service
Related to issue #1315

**Comment by elinz** [comment]
Extracted these items and integrated them into the build OpsServerBuilds\Archive\20151011_0757.

**Comment by elinz** [comment]
I'll verify by publishing to TEM2015 Test 03 server.

**Comment by elinz** [comment]
Still need to extract SD file for Elevation service.

**Comment by elinz** [comment]
Verified all items and service definition files if required were manually extracted.
