### ISSUE TITLE
Online API references in SolutionWeb Apps

### ISSUE THREAD

**Issue by tongeg** [Esri/ops-server-config#1365]
The API is referred to js.arcgis.com in the SolutionWeb applications. (c:\inetpub\wwwroot\SolutionWeb\Apps)
Most of the apps can be edited manually to the Portal API (version 3.13):
env.js -> apiURL = “//<host>/arcgis/jsapi/jsapi”

ImageDiscovery and maybe some more is using 3.14. 
Need to download the newer api version manually for this.

**Comment by ACueva** [comment]
Can confirm this is an issue for disconnected environments.

Web application fails to load due to not being able to hit:

- [ ] dojo.css
- [ ] claro.css
- [ ] esri.css 
- [ ] ResizeHandle.css
- [ ] init.js

**Comment by elinz** [comment]
This has been addressed for non-emergency management apps on our development server as well as in the 2015 4th Quarter Patch.
