### ISSUE TITLE
Image Observables references external resources

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1366]
https://servername/SolutionsWeb/Apps/NationalIntel/ImageObservables/

Web application fails to load due to not being able to hit:

- [ ] dojo.css
- [ ] claro.css
- [ ] esri.css 
- [ ] ResizeHandle.css
- [ ] init.jsWeb application fails to load due to not being able to hit:

**Comment by elinz** [comment]
References 3.14, 3.13, and 3.11.

**Comment by elinz** [comment]
Modified the env.js file to reference the local js api (i.e. /arcgis/jsapi/jsapicompact). Closing issue.
