### ISSUE TITLE
Predictive Analysis references external resources

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1368]
https://servername/SolutionsWeb/Apps/NationalIntel/PredictiveAnalysis/

Web application fails to load due to not being able to hit:

- [ ] dojo.css
- [ ] claro.css
- [ ] esri.css 
- [ ] ResizeHandle.css
- [ ] init.js

**Comment by elinz** [comment]
References 3.13, and 3.11.

**Comment by elinz** [comment]
Modified the following files to reference local js api (i.e. /arcgis/jsapi/jsapicompact):
env.js
widgets\QueryEditor\lib\js\queryEditor\css\QueryEditor.css
widgets\QueryInspector\lib\js\queryEditor\css\QueryEditor.css
