### ISSUE TITLE
CSS path in ArcGIS Server Administrator Directory REST handlers not set correctly

### ISSUE THREAD

**Issue by KSteinicke** [Esri/ops-server-config#1374]
ArcGIS Server Administrator Directory:

*Home* > *system* > *handlers* > *rest* > *servicesdirectory*

**is set to:**
- https://server.fqdn/arcgis/home/js/dojo/dijit/themes/tundra/tundra.css
- https://server.fqdn/arcgis/home/js/esri/css/esri.css

**should be set to:**
- https://server.fqdn/arcgis/home/js/jsapi/dijit/themes/tundra/tundra.css
- https://server.fqdn/arcgis/home/js/jsapi/esri/css/esri.css

**Comment by ACueva** [comment]
Duplicate issue:
https://github.com/Esri/ops-server-config/issues/1242
