### ISSUE TITLE
NAIP Over Time web app points to external JSAPI

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#1375]
Need to update index.html here: C:\inetpub\wwwroot\SolutionsWeb\Apps\NationalIntel\time-aware-template-master to point to Portal's JSAPI. (there are three places in the file to update).

**Comment by elinz** [comment]
References 3.14 and 3.13.

**Comment by NatalieCampos** [comment]
Reassigning to @nfeuerstein

**Comment by elinz** [comment]
@NatalieCampos Reassigning to myself. I'm working on the 2015 Q4 release patch which will include the updates to this app. After patch is finished I will update the app files on the development server.

**Comment by elinz** [comment]
Modified index.html file to reference local js api (i.e. /arcgis/jsapi/jsapicompact). Closing issue.
