### ISSUE TITLE
Predictive Analysis Tools download link is broken

### ISSUE THREAD

**Issue by KSteinicke** [Esri/ops-server-config#1377]
*The folder seems to have been renamed to Intel after the item has been published.*

*Item location is set to* 
- https://server.fqdn/Downloads/Intelligence/PredictiveAnalysisTools1.3.0.zip

*Should be*
- https://server.fqdn/Downloads/Intel/PredictiveAnalysisTools1.3.0.zip

**Comment by elinz** [comment]
This has been addressed in the 2015 4th Quarter Ops Server Patch. Users are instructed to rename the Downloads\Intel folder in the IIS web server to Downloads\Intelligence.
