### ISSUE TITLE
Documentation - Copy enterprise geodatabase datasets (Page 26)

### ISSUE THREAD

**Issue by adgiles** [Esri/ops-server-config#1386]
The example Path for the <sourcefolder> at step 2 is incorrect, it currently reads:

OPSServerInstall\Server\Staging\Caches

should be:

OPSServerInstall\Server\DistributionEntGDBs

**Comment by elinz** [comment]
Made change to Word doc.

**Comment by elinz** [comment]
Fixed in v.next. Closing issue.
