### ISSUE TITLE
Duplicate CrowdSourceReporter folder in IIS SolutionsWeb folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1390]
App exists under NationalIntel folder (SolutionsWeb\Apps\NationalIntel\CrowdSourceReporter). However, this app also exists directly under the SolutionsWeb folder. I'm assuming that the SolutionsWeb\CrowdSourceReporter folder should be deleted.

**Comment by nfeuerstein** [comment]
Deleted SolutionsWeb\CrowdSourceReporter
