### ISSUE TITLE
Need  permissions to update Mission Report GEOFORM and Feature Service. 

### ISSUE THREAD

**Issue by phil7277** [Esri/ops-server-config#1395]
I need to update the existing Mission Report GEOFORM and Feature Service. It is currently owned by Demo Intelligence. I need the ownership of these items transferred to me.

**Comment by nfeuerstein** [comment]
Is this still needed? @phil7277

**Comment by phil7277** [comment]
No I do not. Lyle has now taken this over.


Regards,
Phil

Phil Suarez | ISR/SOF Account Executive
Esri | Defense & Intelligence
8615 Westwood Center Dr. | Vienna, VA. 22180 | USA
T 909-793-2853<tel:909-793-2853> x2829 | M 571-328-6802<tel:571-328-6802>
psuarez@esri.com<mailto:psuarez@esri.com> | www.esri.com<http://www.esri.com/>

**Comment by joebayles** [comment]
@topowright is this still an issue?

**Comment by topowright** [comment]
This issue has been fixed. The issue was in referance to the Domains not working properly. This can now be confirmed in the GeoForm with the following id:4ab19d716e4442daaacf006fdeb52677.

**Comment by topowright** [comment]
This has been fixed and was verified by @Dbarnes1
