### ISSUE TITLE
InstallSettings.bat not honoring breaks when edited in notepad

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1396]
ops-server-config/Install/InstallSettings.bat not honoring page breaks when edited in notepad.

Due to being a disconnected environment having to install another editor is not an acceptable work-around.

Result is having to go through the file and enter breaks manually.

**Comment by elinz** [comment]
InstallSettings.bat file in repo is honoring breaks in notepad. Issue is with the 2015 4th Quarter release of the .bat file. Opening separate issue.
