### ISSUE TITLE
Ops Server installation Guide asks users to delete c:\inetpub

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#1398]
Ops Server installation Guide asks you to:

"IIS – After uninstalling, delete the C:\inetpub folder."
under Uninstall existing software section.

This can be very dangerous as not everyone has a dedicated machine for the Ops Server.  Deleting the content of c:\inetpub could potentially delete all of the user's hosted applications/content.

**Comment by elinz** [comment]
I added above the list of software uninstall steps a NOTE in red:
NOTE: uninstalling Internet Information Services (IIS) is not necessary.

**Comment by elinz** [comment]
Fixed in v.next. Closing issue.
