### ISSUE TITLE
Ops Server Install Guide suggests incorrect paths

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#1399]
On page 25, under **Copy enterprise geodatabase datasets**, Step 2 lists the incorrect source folder:

>... folder path of SDE connection files/file geodatabases (i.e. the OPSServerInstall\Server\Staging\Caches folder on the external drive).

should be:

... folder path of SDE connection files/file geodatabases (i.e. the OPSServerInstall\Server\DistributionEntGDBs folder on the external drive).

**Comment by elinz** [comment]
Closing issue.
