### ISSUE TITLE
Image Shift with Airbus Image Services- Pleiades, SPOT, and TerraSAR-X

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1407]
_From @Nekillims on November 10, 2015 14:50_

I did  a check in a web map of the Pleiades, TerraSAR-X, and SPOT 5 images over Monterey.
Pleiades-  about 5 to 20 Meters difference (measured), azimuth (estimated) 275 deg Image shift relative to base (an image point is x meters west of the object in the basemap)  magnitude of shift varies from image to image, but the direction is fairly consistent.

TerraSAR-X about 100 Meters, azimuth estimated around 275 deg
SPOT about 50 Meters, azimuth estimated about 280 deg

San Diego
Pleiades shifted about 15M  AZ 225 deg
TerraSAR-X  about 30M AZ 90 deg   (estimated)
SPOT  about 20M AZ 90 deg (estimated)

Bottom line:  the images do not register to each other nor do they register to our basemap.  I would like to get these images into the raster team’s hands (via Gerry Kinn).  First because they would like to have them for development, and second because they should have some tools to help diagnose the issue.

Update 6 Nov:
Yesterday as I continued to work on the Pleiades imagery, most of the displacement (Pleiades to image basemap) went away.  At most it was 2 meters or so.  This morning, the displacement is back, but it’s more N-S than E-W and the magnitude is on the order of about 3-4 meters.   Something strange is going on with the service, and it’s not fully repeatable.

_Copied from original issue: ArcGIS/solutions-desktop-templates#167_

**Comment by jrweakland** [comment]
@Nekillims - should this issue be in the desktop templates repo or the ops server config repo?

**Comment by jrweakland** [comment]
_From @lfunkhouser on December 1, 2015 20:5_

@Nekillims Are you using these in a template? If they are not from a template and they are on the development server, please log/transfer this issue to the ops-server-config repo so it can be addressed.

**Comment by elinz** [comment]
@jrweakland Any status update for this issue? It's been labled "In Progess". Thanks.

**Comment by jrweakland** [comment]
@NatalieCampos - These services are under your account on NSEC. Do you plan on releasing them this ops server release?

**Comment by NatalieCampos** [comment]
These services can be released.  They have been fully documented with permissions and all that is neccary for release.

**Comment by NatalieCampos** [comment]
Talked to @jrweakland.  these will be released. Issue is being closed.
