### ISSUE TITLE
NationalIntelligence Image Services Failing to draw after 10.4 update

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1412]
Failed to draw in ArcMap 10.4 but would draw in the Portal.  I did stop the service and restart it in order for the service to draw in ArcMap and it seems to be working fine now.  This issue maybe related to 10.4 server upgrade.  @elinz The errors seem to be on services that are based on mosaic datasets.  We should do some testing to isolate the problems.

**Comment by NatalieCampos** [comment]
The CostalReliefModel also failed to draw and needed to be restarted.  
![image](https://cloud.githubusercontent.com/assets/5116835/13794521/7abf027e-eab9-11e5-8112-a97497df0c8d.png)

**Comment by NatalieCampos** [comment]
The CountrY Boundaries services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.
![image](https://cloud.githubusercontent.com/assets/5116835/13794612/005d9ca6-eaba-11e5-8bda-0cbe74c3ef04.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\DistanceFromAllWeatherRoadsMosaic  services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.
![image](https://cloud.githubusercontent.com/assets/5116835/13794928/c70e8b84-eabb-11e5-9354-b1a770412993.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\DistanceFromForestEdgeMosaic:  services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.

![image](https://cloud.githubusercontent.com/assets/5116835/13795196/e874427c-eabc-11e5-82ed-2a664277ab2c.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\DistanceFromOceanMosaic: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.
![image](https://cloud.githubusercontent.com/assets/5116835/13795389/b41ec96a-eabd-11e5-8660-430dcd989ac4.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\DistanceFromTrailsMosaic: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.

![image](https://cloud.githubusercontent.com/assets/5116835/13795480/49d49728-eabe-11e5-9a89-e37537b53ae7.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\DistanceFromWaterSourcesMosaic:  services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap.

![image](https://cloud.githubusercontent.com/assets/5116835/13795558/c7e5095e-eabe-11e5-98f4-0ab8c4e75e62.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\LandCover: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap
![image](https://cloud.githubusercontent.com/assets/5116835/13795722/b5ea4fb0-eabf-11e5-8a2e-d1d21f509867.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\PopulationDensity: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap


![image](https://cloud.githubusercontent.com/assets/5116835/13796043/b6cfafae-eac1-11e5-8e2b-adc66676f9ac.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\Spot5Pan: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap
![image](https://cloud.githubusercontent.com/assets/5116835/13796117/1f9edd0c-eac2-11e5-8c6c-eccdd0ae08eb.png)

**Comment by NatalieCampos** [comment]
The NationalIntelligence\SpotMS: services failed to draw and needed to be stopped and then restarted to enable viewing in ArcMap

![image](https://cloud.githubusercontent.com/assets/5116835/13796208/aceeb93e-eac2-11e5-9fb4-99cabd608db7.png)

**Comment by NatalieCampos** [comment]
![image](https://cloud.githubusercontent.com/assets/5116835/13796255/f70e1f0a-eac2-11e5-8426-34ece8c63d0c.png)

**Comment by NatalieCampos** [comment]
![image](https://cloud.githubusercontent.com/assets/5116835/13796310/479c5a2c-eac3-11e5-8720-9bc90bbc7064.png)

**Comment by NatalieCampos** [comment]
![image](https://cloud.githubusercontent.com/assets/5116835/13796398/bbf50b8a-eac3-11e5-95a8-91c7244e6657.png)

**Comment by NatalieCampos** [comment]
All of the abover services had to be stopped and restarted in order to be viewed in ArcMap though they were viewable in the portal map (some of them).  I am unsure whether this is a configuration issue or 10.4 or a script issue.  @elinz Please tell me how I can help you test where the issue originates or the stopping and starting should be added to the OpsServer documentation so that customers/distributors know that this is an issue.

**Comment by elinz** [comment]
@NatalieCampos Please check each image service on our production server and see if problem still exists. Thank you.

**Comment by elinz** [comment]
@NatalieCampos Make sure to use ArcMap 10.4.1 since the server and portal were upgraded to 10.4.1.

**Comment by NatalieCampos** [comment]
All services are in working order.
