### ISSUE TITLE
NationalIntelligence\DigitalSurfaceModel: fails to draw

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1413]
The DSM failed to draw as seen in issue #1412.  Upon Stopping and Restarting there seem tp be an issue with the path to the overview data.  The original paths were UNC paths and now they are point to a C: drive.  This issue may have been  caused by the 10.4 upgrade.  This issue was also seen last year at the UC as well as upon return for UC.  

![image](https://cloud.githubusercontent.com/assets/5116835/13794850/5383c24c-eabb-11e5-9087-8e154f46db73.png)

![image](https://cloud.githubusercontent.com/assets/5116835/13794893/8f7874dc-eabb-11e5-9855-4f7041d24b7c.png)

**Comment by elinz** [comment]
@NatalieCampos This wouldn't be caused by an upgrade to 10.4 server.

**Comment by elinz** [comment]
@NatalieCampos The mosaic datasets for last years UC servers were intentionally altered to a local path because of a bug in the repair mosaic dataset paths gp tool which failed to update paths containing certain UNC patterns. The paths in mosaic datasets on the production file server were not altered and therefore would have the original UNC path.

**Comment by NatalieCampos** [comment]
@elinz I have fixed the path issue on this service after we returned for UC.  This service has worked fine since then.  Since the upgrade there seems to be an issue.  I can change the path from C: to a UNC path but it seems that there is a bigger issue in that I should not have to constantly change the paths everytime there is a change to the server.  Please tell me how I can help so that we can isolate what is causing the paths to be changed.

**Comment by NatalieCampos** [comment]
this service has been fixed.  it now draws correctly.
