### ISSUE TITLE
Intel Report Feature Service is Unreachable

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1415]
This goes with issue #1395. The feature service "IntelReports" is unreachable. ../services/Military/IntelReports/FeatureServer/0

**Comment by nfeuerstein** [comment]
@jfrygeo looks like that service was deleted.  I was not the original publisher of that information and wasn't able to find a map package on the ops server to republish the "IntelReports".  @phil7277 did you publish the "IntelReports" service?  This was the description: "A Feature Service with the locations of incidents over the Monterey, CA region based off of the Combined Information Data Network Exchange (CIDNE) database and Intelligence, Surveillance, and Reconnaissance (ISR) Mission Reports for reporting and presenting intelligence information derived from time critical air reconnaissance and sensor imagery"

**Comment by phil7277** [comment]
Team, I have not updated any services or published this service. I am currently in training but can take a look at this once I am done.


Regards,
Phil

Phil Suarez | ISR/SOF Account Executive
Esri | Defense & Intelligence
8615 Westwood Center Dr. | Vienna, VA. 22180 | USA
T 909-793-2853<tel:909-793-2853> x2829 | M 571-328-6802<tel:571-328-6802>
psuarez@esri.com<mailto:psuarez@esri.com> | www.esri.com<http://www.esri.com/>

**Comment by elinz** [comment]
@jfrygeo @phil7277 Retested this service and both layers listed below within this service are now accessible and can be drawn in a web map.
Military/IntelReports/FeatureServer/0
Military/IntelReports/FeatureServer/1

Closing this issue.
