### ISSUE TITLE
Failed to publish/delete an ArcGIS Service

### ISSUE THREAD

**Issue by astha11** [Esri/ops-server-config#1417]
**When I am trying to overwrite an existing service, I get the following error:**
![image](https://cloud.githubusercontent.com/assets/18527264/14598704/7c6815f0-054b-11e6-8488-49bdd63f5e04.png)
![image](https://cloud.githubusercontent.com/assets/18527264/14598753/acbb0a3c-054b-11e6-8e04-1fa12b00c2cb.png)
**It could be that the underlying folder has been corruted. However, I am not able to delete the service either. It says Access is denied.**
![image](https://cloud.githubusercontent.com/assets/18527264/14598891/5bc5f078-054c-11e6-8ac8-73b1347cc08d.png)

Please can someone help me?

**Comment by elinz** [comment]
@astha11 It appears that this issue was created in this GitHub repo by mistake, as it is not related to the use of scripts provided in this repo or in the scope of this repo. You can post questions to https://geonet.esri.com, http://support.esri.com/ or contact Esri Technical Support. Thank you.
