### ISSUE TITLE
Image item "Sample Legacy Intelligence Report" is referenced by a released item, but not released itself

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1438]
The "Sample Legacy Intelligence Report" image item (id:ad4723bfec334906acdf77e4e32fe22a) should be released. It's referenced by the released map journal item "Geospatially Enabling the Intelligence Collector (Map Journal)" (id:cf92fbb86028410cbdd84947d7e7a56a).

**Comment by phil7277** [comment]
@elinz this ID references an image we do not have release doc for. We need to update the release item, and either recreate doc/image, with different entries, or  remove it from the map journal.

**Comment by joebayles** [comment]
Per @phil7277: Delete the service, sir.

**Comment by elinz** [comment]
Portal item ad4723bfec334906acdf77e4e32fe22a has been deleted. Closing issue.
