### ISSUE TITLE
KML: make sure that portal items of type KML and item type "file" can be extracted and published

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1443]

**Comment by elinz** [comment]
In order for this to work, I had to modify the URL_BASED_ITEM_TYPES and FILE_BASED_ITEM_TYPES lists in the portalpy\__init__py file. I removed KML from the URL list, and added it to the FILE list.

**Comment by conklinbd** [comment]
The slight problem with that solution is that you can add KML urls to the Portal.

**Comment by elinz** [comment]
@conklinbd Correct. The functions to publishing items will need to be modified to add additional logic for this unique case where the item type is a member of two different categories (URL and FILE). Searching our production portal for type:KML I only find items of in the category FILE. So for now I was going to commit this change for UC until I have more time to look into the logic to handle both cases.

**Comment by elinz** [comment]
@conklinbd If your okay with my change I will make a pull request to get the change into master.

**Comment by conklinbd** [comment]
@elinz that seems fine.

**Comment by elinz** [comment]
There is an item type called 'KML Collection' that was not documented in the portal sharing api. I added this type to the FILE_BASED_ITEM_TYPES list.
