### ISSUE TITLE
Service Definition item missing for hosted service "High_Intensity_Drug_Trafficking_Areas_(HIDTA)"

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1445]
@ScottCecilio Found that shapefile item d361304339364931bc3bbdf2e2038c1c was used to created this hosted service. The ops server distribution process only supports automatic republishing of hosted services when the source of the service is a service definition portal item. This service will have to be republished.

----------------------------------------------------------------------------------------------------
Hosted Service Item:   Title - "High Intensity Drug Trafficking Areas (HIDTA)"

        id: bb2fdfcd9ba948cead8c2dc32aa6f209  owner: ****    type: Feature Service          service: High_Intensity_Drug_Trafficking_Areas_(HIDTA)/FeatureServer

        Matching Source Item:
*** ERROR: no matching source item found.

**Comment by elinz** [comment]
@ScottCecilio The hosted feature service item "High Intensity Drug Trafficking Areas (HIDTA)"(bb2fdfcd9ba948cead8c2dc32aa6f209) is owned by you. Are there plans to release this service in the current Ops Server release? If yes, then it will need to be republished through ArcMap or ArcGIS Pro. The Ops Server publishing scripts do not support republishing from shapefiles or geodatabases, etc.

If its not going to be released then I'll change the milestone of this issue for post release. Thanks.

**Comment by joebayles** [comment]
@ScottCecilio, what up wit dis?

**Comment by ScottCecilio** [comment]
Items were removed from the Ops Server build as they are no longer needed.
