### ISSUE TITLE
Service Definition exists for hosted service "IncidentsForSentiment/FeatureServer" but service does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1446]
Service definition portal item id de070a8367004796ac1bd24b74023557 exists, but the hosted feature services it creates does not exist.

Probably a case where the hosted service was deleted, but publisher failed to delete the associated service definition item.

If this services does not need to exist, please delete the service definition item; otherwise this service will be published on the user conferences servers.

----------------------------------------------------------------------------------------------------
Source Item:   Title - "IncidentsForSentiment"

        id: de070a8367004796ac1bd24b74023557  owner: ****   type: Service Definition       service: IncidentsForSentiment/FeatureServer

        Matching Hosted Service:
*** ERROR: no matching hosted service found.

**Comment by topowright** [comment]
From my understanding if the issue does not have feedback or resolved in 24 hours we are supposed to delete the service. Do you have a different understanding?

**Comment by conklinbd** [comment]
@topowright that is correct.

**Comment by elinz** [comment]
I deleted the service portal item de070a8367004796ac1bd24b74023557. Closing issue.
