### ISSUE TITLE
Invalid file geodatabase for item "Incidents"

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1449]
Performed a test extract and publish of the portal items from the production portal to a 10.4.1 portal and received the following error during the portal add item operation of the PortalContentPost.py script:

        Publishing item 4665f2260dee4e5e9130be5acfea3b28 (7/29)...
ERROR:portalpy:Error while analyzing File Geodatabase 'Incidents.zip' Unable to extract 'file geodatabase' Invalid File Geodatabase, missing gdbtable or gdbindexes file.
ERROR: Exception on adding/updating item: 4665f2260dee4e5e9130be5acfea3b28

I'm not sure what the purpose of this file geodatabase is. Just FYI, the Ops Server scripts do not support publishing of hosted services from file geodatabases, only service definition portal items.

This item is owned by @phil7277, but assigning to @topowright if you don't mind.

**Comment by topowright** [comment]
I am not sure why this is here, but I think it should be deleted. There is no need to have a zip file of incidents.

**Comment by phil7277** [comment]
@elinz @topowright ; Team , I do not understand the issue on this. This is content in my folder that is not shared for release, BUt information stored to work with. Are we not suppose to have anything on the development portal unless it is finished and releasable? This can be deleted if needed. This is just reference content.

**Comment by elinz** [comment]
@phil7277 It's ok to have this content on the development portal. For "official" releases of Ops Server we would only be extracting portal items for the released/demo accounts, but for UC release we extract portal items for all accounts. If this item is not need for UC then you don't have to perform any corrective action.

**Comment by elinz** [comment]
@topowright @phil7277 Since I don't believe this item will be released in the current Ops Server release, i.e. 2016 4th Quarter, I'm going to close this issue.
