### ISSUE TITLE
Maritime Domain Awereness DIS 2016 400 error

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1456]
id:2bb62fdd2c0041a09fc75ef770251c7c

ERROR: URL issue - code: 400; message: ; url: http://geo.weather.gc.ca/geomet/?lang=E

**Comment by jrweakland** [comment]
@jfrygeo - This came up as an error again in today's output.

**Comment by elinz** [comment]
@jrweakland @jfrygeo There are some URLs that the url check tool will flag as an error. An example is if the url requires a token. I always verify if the reported error is actually an error by pasting the URL in a browser. If not an error, comment this in the GitHub issue and close. On subsequent error reports search GitHub for this id/issue to check if it was already reported and if error is valid.

**Comment by jrweakland** [comment]
John verified that this services works in his web map.
