### ISSUE TITLE
RangeFanFromBearingLimits 10060 error

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1457]
id:b087038cd9e34d40961f2dc1ea73f327

ERROR: URL issue - code: 10060; message: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

This is coming from your rugged 8.

**Comment by jfrygeo** [comment]
@jrweakland I have no clue what this is. The rugged server is currently down. This reference can be deleted.

**Comment by jrweakland** [comment]
@jfrygeo - you will need to remove or delete what you do not want on the portal for UC.

**Comment by jrweakland** [comment]
I deleted the portal item on 06/015/2016
