### ISSUE TITLE
Maritime Boundaries feature service not appearing in Map. The REST endpoint exists, but no data in webmap.

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1460]
item= bf3cca6ca1bb45dd903e3df969156bd0

Service: https://<server name>/Military/MaritimeBoundaries/FeatureServer

**Comment by jrweakland** [comment]
@jfrygeo - I do not own this item.

**Comment by jfrygeo** [comment]
DemoMilitary?

Sent from my iPhone

On Jun 13, 2016, at 1:28 PM, Jim Weakland <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jfrygeo&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=2m02lVTHIn3k2-Zp2qmiQ7R8ZFFfIP-fVrNjG5Tb9SE&s=E0eFgEaDUXYlx7D-4NmRmKiw_haDqtRkOh-I2urpScA&e=> - I do not own this item.

-

**Comment by jrweakland** [comment]
There has not been a military team in over three months. I would suggest @ACueva or @elinz to take a look at it. I believe that this is a service that you created for the new geography.

**Comment by jfrygeo** [comment]
I can republish but seems weird that the data is gone @ACueva

**Comment by jfrygeo** [comment]
@ACueva I tried to republish this feature service and received an ERROR:001369 from ArcMap. "Failed to Create the Service."

**Comment by jfrygeo** [comment]
I did not own the item. The item was transferred to me, then I was able to republish.
