### ISSUE TITLE
add the custom widgets to the build

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#1479]
Currently we have widgets that we have configured manually to work with the WAB that is running off of portal. When the extraction happens these widgets are not grabbed. Should we grab these?

**Comment by elinz** [comment]
@topowright We won't automatically extract any custom widgets from our production portal and include with the Ops Server release. It will be up to you to provide the following:
- Set of widget files that will work with 10.4.1 portal web app builder.
- Instructions on how to "install" these into an Ops Server portal installation

I can include a section in the Ops Server installation guide titled something like "Custom Web App Builder widgets (Optional)" that points to the .pdf or word doc that you write containing the widget installation instructions.

**Comment by ACueva** [comment]
@dfoll FYI

**Comment by topowright** [comment]
@dfoll there is nothing for you to do on this issue. 

I have finished the instructions and placed them in the following folder: 

2016_Q4\OPSServerInstall\WebAppBuilder\Widgets\

@elinz Please verify that the instructions are placed in the correct folder.

**Comment by elinz** [comment]
Instructions and widgets placed in correct folder. Closing issue.
