### ISSUE TITLE
Jenkins build server: update path to ArcGIS Maps for Office Portal Resources installer

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1481]
Product name has been changed from Esri Maps for Office to ArcGIS Maps for Office so we should make appropriate change to build process.

See #1480

**Comment by elinz** [comment]
Lets use the 4.1 (Beta) version for this release.

**Comment by ACueva** [comment]
TODO: verify EM4O is being copied over correctly.

**Comment by elinz** [comment]
@ACueva I verified. Closing issue.
