### ISSUE TITLE
"Maritime Domain Awareness Dashboard" Operation View was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1488]
Item 0845dd9f0ee74d66b504e62804d2c2c6 was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @jfrygeo. If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

@lfunkhouser FYI.

**Comment by jfrygeo** [comment]
@elinz Yes. it should be released. I am currently fixing an issue I came across at the DIS 2016. Once fixed I will push for release @lfunkhouser

**Comment by jfrygeo** [comment]
@elinz item shared to demo review group.

**Comment by jfrygeo** [comment]
Item removed from demo review group. Noticed that geofenced items are not updating. @pHill5136 In the dashboard (https://"portal"/arcgis/home/item.html?id=0845dd9f0ee74d66b504e62804d2c2c6), the geofenced items are not showing up. There are filters set on the shipping data that should populate lists in the dashboards. It looks like the geoevent service here https://"geoevent Server":6143/geoevent/manager/newService.html?service=ba3d006f-25f8-487d-8696-28e224f4a451&mode=view-edit is not calculating items in geofences. Can you take a look at this?

**Comment by pHill5136** [comment]
@jfrygeo is this affecting the ship position service?

**Comment by jfrygeo** [comment]
The ship position feature service is used with a few geofences in the "MaritimeOps-ShipPosition" GeoEvent service. When ships move into a certain region ("Area to be Avoided", "shipping lanes", "Proximity Alert,") a field calculator writes to a field and then in the dashboard, a list populates. The "Proximity Alert" feature service is created from military vessels and then the output is used as a geofence, too.

**Comment by jfrygeo** [comment]
republished "Proximity alert" feature service (https://"portal"/arcgis/home/item.html?id=478cbdd6f965408f9094ec5b33f0114d). The buffer is not being created.

**Comment by jfrygeo** [comment]
@elinz could you transfer ownership of the "Maritime Boundaries" feature and map service so I can republish? I want to try and see if republishing the service could make the geofences work again. 

- https://"portal"/arcgis/home/item.html?id=aa2c139f19f54f9ca92f6fce564aea1f

- https://"portal"/arcgis/home/item.html?id=bf3cca6ca1bb45dd903e3df969156bd0

**Comment by elinz** [comment]
@ACueva can you please change ownership? Thanks

-------- Original message --------
From: John Fry
Date:09/09/2016 11:54 AM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz , Mention
Subject: Re: [Esri/ops-server-config] "Maritime Domain Awareness Dashboard" Operation View was previously released; should be this year? (#1488)


@elinz<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_elinz&d=DQMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=2ZpT4vzBgD3Uq0Qu1_1lvg&m=-zoWcgCUtCZhPduv425QuCAZuQWah-xYipDfjU-Nu84&s=CFax3SS2Co87HM0IJ2bjRecMU8kR1cT8RBeiU-oOY7M&e=> could you transfer ownership of the "Maritime Boundaries" feature and map service so I can republish? I want to try and see if republishing the service could make the geofences work again.

  *   https://"portal"/arcgis/home/item.html?id=aa2c139f19f54f9ca92f6fce564aea1f

  *   https://"portal"/arcgis/home/item.html?id=bf3cca6ca1bb45dd903e3df969156bd0

-

**Comment by jfrygeo** [comment]
Republished Maritime Boundaries map/feature service. Will see if dashboard is updating with geofenced items.

**Comment by pHill5136** [comment]
@jfrygeo I have it writing out to proximity buffers. I turned off the delete features in the output because features were getting deleted every 20 seconds because the datetime coming in from the simulation is stale. Can you verify whether the proximity buffers are working now?

**Comment by jfrygeo** [comment]
@phil7277 Good work. Geofences working, shipping updating. 

@elinz please release the following components of this demonstration:

-Maritime Boundaries map service-aa2c139f19f54f9ca92f6fce564aea1f
-Maritime Domain Awareness Web Map - 995d354c59694c01bbd1ff877441526a
-Maritime Domain Awareness Dashboard - 0845dd9f0ee74d66b504e62804d2c2c6
-ProximityAlert FS- 478cbdd6f965408f9094ec5b33f0114d
-ProximityAlert MS- 5463afdb5cb8475689997dd07eb0d57b

**Comment by elinz** [comment]
- [ ] Maritime Boundaries map service-aa2c139f19f54f9ca92f6fce564aea1f
- [ ] Maritime Domain Awareness Web Map - 995d354c59694c01bbd1ff877441526a
- [ ] Maritime Domain Awareness Dashboard - 0845dd9f0ee74d66b504e62804d2c2c6
- [ ] ProximityAlert FS- 478cbdd6f965408f9094ec5b33f0114d
- [ ] ProximityAlert MS- 5463afdb5cb8475689997dd07eb0d57b

**Comment by elinz** [comment]
NOTE: ownership of Maritime Boundaries feature service item bf3cca6ca1bb45dd903e3df969156bd0 associated with map service item aa2c139f19f54f9ca92f6fce564aea1f had been previously changed to DemoMilitary.

Changed ownership of the specified items to DemoMilitary. Closing this issue.
