### ISSUE TITLE
"Proximity Alert" feature service was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1489]
Item 478cbdd6f965408f9094ec5b33f0114d was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @jfrygeo. If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

@lfunkhouser FYI.

**Comment by jfrygeo** [comment]
@elinz  Yes. it should be released. I am currently fixing an issue I came across at the DIS 2016. Once fixed I will push for release @lfunkhouser

**Comment by jfrygeo** [comment]
@elinz item shared to demo review group.

**Comment by elinz** [comment]
Item was released; now owned by DemoMilitary. Closing issue.
