### ISSUE TITLE
"Proximity Alert" map service was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1490]
Item 5463afdb5cb8475689997dd07eb0d57b was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @jfrygeo. If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

This map service is associated with feature service issue #1489 

@lfunkhouser FYI

**Comment by jfrygeo** [comment]
@elinz Yes. it should be released. I am currently fixing an issue I came across at the DIS 2016. Once fixed I will push for release @lfunkhouser

**Comment by jfrygeo** [comment]
@elinz item shared to demo review group.

**Comment by elinz** [comment]
Item has been released. Now owned by DemoMilitary. Closing issue.
