### ISSUE TITLE
"Farthest On Circle" geoprocessing service was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1491]
Item 779c8029eac24a129ce95a8f4caa8301 was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @jfrygeo. If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

@lfunkhouser FYI

**Comment by jfrygeo** [comment]
@elinz Yes. it should be released. I am currently fixing an issue I came across at the DIS 2016. Once fixed I will push for release @lfunkhouser

**Comment by jfrygeo** [comment]
@elinz @ACueva When I try to access the URL for the "farthest on circle" gp service:

https://"Server"/ags/rest/services/Military/FarthestOnCircle/GPServer

I get : 
"Could not access any GIS Server machines. Please contact your system administrator."

I tried to republish, and got:

ERROR 001369: Failed to publish the service.

**Comment by jfrygeo** [comment]
Failed to initialize server object 'Military/FarthestOnCircle': 0x80070057: Can not open file \\SERVER\arcgisserver_directories\arcgisoutput\Military\FarthestOnCircle_GPServer\Military_FarthestOnCircle\results.msd. The system cannot find the path specified. Probable cause: The file is inaccessible to Server. 

I am going to delete and republish the service.

**Comment by jfrygeo** [comment]
Could not delete service:

ERROR: code:500, Could not undeploy services from one or more machines. 'Server machine 'https://SERVER:6443/arcgis/admin' returned an error. 'C:\Program Files\ArcGIS\Server\framework\runtime\ejbs\Military\FarthestOnCircle.GPServer\Recycling (Access is denied)''. Internal server error.

**Comment by elinz** [comment]
@jfrygeo Let me try deleting the service.

**Comment by elinz** [comment]
@jfrygeo I was able to delete the gp service, however, the associated map service was not automatically deleted. I'm trying to delete that now.

**Comment by elinz** [comment]
@jfrygeo ArcMap and Server Manager do not provide the ability to delete a map service associated with a gp service, however, the server "admin" REST api does. The map service was successfully deleted. Closing issue.

**Comment by jfrygeo** [comment]
@elinz Failed to publish this service. 

- Failed to construct instance of service 'Military/FarthestOnCircle.GPServer'. The toolbox did not load: \\SERVER\arcgisserver_directories\arcgissystem\arcgisinput\Military\FarthestOnCircle.GPServer\extracted\v101\FarthestOnCircle.tbx

-Failed to initialize server object 'Military/FarthestOnCircle': 0x80004005: The toolbox did not load: \\SERVER\arcgisserver_directories\arcgissystem\arcgisinput\Military\FarthestOnCircle.GPServer\extracted\v101\FarthestOnCircle.tbx 

-InitToolbox Failed

-The toolbox did not load: \\SERVER\arcgisserver_directories\arcgissystem\arcgisinput\Military\FarthestOnCircle.GPServer\extracted\v101\FarthestOnCircle.tbx

-Error executing tool. PublishServiceDefinition Job ID: je540c7817f7a4acf834b38ea0cb65823 : ERROR 001369: Failed to create the service. Failed to execute (Publish Service Definition).

-Failed to create the service.: ERROR: Service failed to start, Internal server error.

-Core server call to create service failed (/admin/createService).

**Comment by jfrygeo** [comment]
Changed name of the GP service and publishing worked...

**Comment by jfrygeo** [comment]
Delete protection was enabled on the "Farthest On Circle" GP service. Could have thrown the error above.

**Comment by jfrygeo** [comment]
Please release the "Farthest On Circle" tool:

Farthest On Circle - 37a5ccb48c72434eb0354668bab2526c

You can test in this application: 

https://"PORTAL"/arcgis/apps/webappbuilder/index.html?id=71d30f4be37b4dc3adb95bbb92da4841

**Comment by elinz** [comment]
@jfrygeo Doesn't changing the name of the gp service cause problems? Since any apps released reference the previous named gp service?

**Comment by jfrygeo** [comment]
I can try and republish with the same name, but I keep getting errors.

**Comment by jfrygeo** [comment]
Republished successfully with same name. Please release. Associated with #1549

**Comment by elinz** [comment]
@jfrygeo I released the item dc83412ba2c84da9a8006fa2666a606b (Military/FarthestOnCircle.GPServer). The item is owned by DemoMilitary.
