### ISSUE TITLE
"Maritime Domain Awareness" web map was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1492]
Item 995d354c59694c01bbd1ff877441526a was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @jfrygeo. If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

@lfunkhouser FYI

**Comment by jfrygeo** [comment]
@elinz Yes. it should be released. I am currently fixing an issue I came across at the DIS 2016. Once fixed I will push for release @lfunkhouser

**Comment by jfrygeo** [comment]
@elinz WebMap shared with "DemoReview" group. Please change ownership for release

**Comment by elinz** [comment]
@jfrygeo I will close the issue when the item has been released.

**Comment by elinz** [comment]
Item has been released. Now owned by DemoMilitary. Closing issue.
