### ISSUE TITLE
"Mission Report" web mapping application was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1493]
Item c48bdb0b6d2f4dfea70f39b048a3ceb7 was released in 2015 Q4 and owned by DemoMilitary. Currently, item is owned by @conklinbd . If this item needs to be included in current release the it needs to go through release process (limited process if still going to be owned by a demo account).

@lfunkhouser FYI.

**Comment by joebayles** [comment]
@ScottCecilio do you still want this on the Ops Server?

**Comment by ScottCecilio** [comment]
Yes I would like to keep this as it is being used with demonstrations for Land Ops as well as the AF demo.

**Comment by joebayles** [comment]
@nfeuerstein assigning you because it's release-related at this point... @lfunkhouser FYI

**Comment by topowright** [comment]
This item (c48bdb0b6d2f4dfea70f39b048a3ceb7) owned by @conklinbd  can be deleted. The released version of this app has the following id: 4ab19d716e4442daaacf006fdeb52677

**Comment by topowright** [comment]
I will delete this app.

**Comment by topowright** [comment]
I have pushed this item to demointelligence

**Comment by topowright** [comment]
@elinz please verify.

**Comment by elinz** [comment]
@joebayles @topowright I verified that is item is now owed by DemoIntelligence. I'm closing this issue. Thanks.
