### ISSUE TITLE
"Visibility And Range" document link was previously released; should be this year?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1494]
Item 5e3361273fd04fcb8088cec71f659905 was released in 2015 Q4 and owned by ReleasedMilitary. Currently, item is owned by @topowright. If this item needs to be included in current release then it needs to go through release process.

NOTE: "Military" folder in document link URL also needs to be changed to "ArcGISforDefense".

@lfunkhouser FYI.

**Comment by topowright** [comment]
@elinz  This item is now owned by releasedmilitary. Please verify

**Comment by elinz** [comment]
@topowright I verified that is item is now owned by ReleasedMilitary. I'm closing this issue. Thank you.
