### ISSUE TITLE
All template document links need to be reviewed

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1495]
This is a team effort task:

- Ensure that lastest version of each template has a document link portal item.
- If new version of template was created since last Ops Server release then update existing link item to reflect new template.
- Any references to "Military" or "Intelligence" folder in the document link URL needs to be changed to "ArcGISforDefense"

NOTE: All templates that existed in the ArcGISforMilitary or ArcGISforIntelligence folder will be moved into a folder called "ArcGISforDefense" on the Ops Server release USB drive.

NOTE: URL should be in the form of:
https://"server"/Downloads/ArcGISforDefense/"template_name.zip"
where:
"server" is the fully qualified name of our production portal.
"template_name.zip" is the actual name of the template zip file.

**Comment by mfunk** [comment]
If there are any that are missing Document links I'll volunteer to add as many as I can.

**Comment by mfunk** [comment]
Eric will give me access to template folder on server, I will compare list of template ZIPs to document links and see what needs to be created.

**Comment by mfunk** [comment]
the plan:
1) Starting by getting a list of all template ZIP files on the server into Excel (211 ZIP files)
2) Filter the list by the latest version (there are multiple versions of the templates listed -- 75 ZIP files )
3) List to portal search for "type:Document" (ouch .... only 35 matches)
4) Check each item in step 3 and add the document link to Excel document
5) Look at the difference between latest version and document links, this will be the **working list**
6) Add **working list** to this Issue

**Comment by elinz** [comment]
@mfunk Thank you

**Comment by mfunk** [comment]
**WORKING LIST**

THE FOLLOWING NEED FULL DOCUMENT LINK **CREATED**:

- [ ] CompoundMap5.0.0.zip
- [ ] CoordinateConversionArcGISPro1.0.1.zip
- [ ] CoordinateConversionArcMap1.0.1.zip
- [ ] CoordinateConversionWAB1.0.0.zip
- [ ] DistanceAndDirectionArcGISPro1.0.0.zip
- [ ] DistanceAndDirectionArcMap1.0.0.zip
- [ ] HelicopterLandingZone_4.0.0.zip
- [ ] ImageChangeDetection2.0.1.zip
- [ ] ImageryBasemap3.0.0.zip
- [ ] ImageryCatalog_Web_1.0.0.zip
- [ ] IncidentAnalysis5.0.0.zip
- [ ] MilitaryAspectsofTerrain_1.0.0.zip
- [ ] PatrolDataCapture3.0.2.zip
- [ ] PointofOriginDetection5.0.1.zip
- [ ] PredictiveAnalysisWeb1.1.0.zip
- [ ] RangeCards2.0.0.zip
- [ ] ScannedMapsBasemap3.0.0.zip
- [ ] Situation_Awareness_1.0.0.zip
- [ ] SunPositionAnalysis_1.0.0.zip
- [ ] TimeSpanAnalysis2.0.0.zip
- [ ] VisibilityArcGISPro1.0.0.zip
- [ ] VisibilityArcMap1.0.0.zip



THE FOLLOWING HAVE LINKS BUT NEED TO BE **UPDATED**:

- [ ] BeachLanding4.0.0.zip
	- This has a document link that  points to another portal item, not the ZIP
- [ ] ClearingOperations5.0.1.zip
	- Current link points to v4.0.0
- [ ] DistancetoAssets2.0.1.zip
	- Current link points to v2.0.0
- [ ] GeoMessageSimulator1.0.0Windows-x64.zip
	- Need to add links (in Description) to other template distributions.
	- GeoMessageSimulator1.0.0Linux-x64.zip
	- GeoMessageSimulator1.0.0Linux-x86.zip
	- GeoMessageSimulator1.0.0Windows-x86.zip
- [ ] GeonamesLocator4.1.1.zip
	- Current link points to v4.0.0
- [ ] LodgmentPlanning5.0.0.zip
	- Current link uses tiny url, not required link from Eric's comments above.
- [ ] NationalSecurityBasemaps2.0.1.zip
	- Current link points to v2.0.0
- [ ] PredictiveAnalysisAddIn1.3.1.zip
	- Current link points to PredictiveAnalysisTools1.3.0.zip
- [ ] RangeDomeAnalysis3.0.0.zip
	- Current link points to v2.0.0
- [ ] SolutionsGeoprocessingToolbox2.2.0.zip
	- Current link points to v2.1.0
- [ ] VehicleCommander4.1.1Windows-x64.zip
	- Need to add links (in Description) to other template distributions.
	- VehicleCommander4.1.1Linux-x64.zip
	- VehicleCommander4.1.1Linux-x86.zip
	- VehicleCommander4.1.1Windows-x86.zip
- [ ] VisibilityAndRange5.0.0.zip
	- Current link points to v4.0.0

**Comment by mfunk** [comment]
HOW TO ADD A NEW LINK (Adapted from deleted page in OneNote 2016):

**How to Create a Document Link**

To create a document link for the NSEC TEM 2016 RELEASE:

1. Log into the server
1. Go to **My Content**
1. Select **Add Item** >> **From the web**
1. Select **Document** in the next dialog
	1. **URL:** This is the URL to the template on the server (https://"server"/Downloads/ArcGISforDefense/"template_name.zip")
	1. **Title:** This is the title of the template (Do not use version numbers)
	1. **Tags:** Control the filter behavior in the gallery.


1.  Select **Add Item**. This creates the blank Document link page which you will edit to add the remaining items below.
1.  Click thumbnail to change image. below the current thumbnail (probably a world map).
	2.  click Browse... and navigate to the thumbnail you want to use. Your thumbnail should be a 286 pixels wide by 190 pixels high (different than the instructions on the Upload Thumbnail prompt) Portable Network Graphic (PNG).
	3.  Once you have selected your thumbnail, click Open and OK.
1. Add an item **Summary**. This is a short description of the template. In it, you should list the specific technology and version (i.e. "compatible with ArcGIS Pro 1.1").
1. Add an item **Description**. This text should be similar to the Overview text on the documentation page. After that, there is required text. They are:
	1. **Required Software**: The text is "See Online Help for details." Ensure that the words "Online Help" link to the documentation page (link to the Solutions Page for the template).
	2. **Download**: The text is "*Click on the icon above.*"
	3. **Support**: The text is:

` "If you need support, please contact **Esri Support Services**. If you'd like to get help from other military community members, post your question on the Defense and Intelligence Forum on **GeoNet**. If you have a general question or comment about this solution, feel free to post them in the comments section on this page." `

Where "Esri Support Services" links to *https://my.esri.com/welcome?source=my-support*
and "GeoNet" links to *https://geonet.esri.com/community/defense-and-intelligence*

1. Add **Access and Use Constraints**. This is not data permissions or credits. Contact @karlterrey  for any questions, but the stock verbiage is:

`The information presented in this ArcGIS Pro Project template is based on standard Esri Commercial off-the-Shelf (COTS) technologies and commercial data. All scenario data is notional.`

1. Adjust the item properties. This includes:
	1. Item URL - Should already be set, but ensure it links to the tiny URL (http://esriurl.com/…)
	2. Tags - Add additional tags as necessary, but should only correspond to items in the gallery filter (http://solutions.arcgis.com/gallery/#s=0).
	3. Credits - Credit Esri and any additional credits necessary (from data permissions).
1. Save the item by clicking **Save**.
1. **Share** the Document Link item with **Everyone** by:
	1. Clicking **Share** >> **Everyone** >> **OK**.

**Comment by mfunk** [comment]
Starting on **CompoundMap5.0.0.zip**

**Comment by mfunk** [comment]
Starting on ** ImageChangeDetection2.0.1.zip**

**Comment by mfunk** [comment]
Starting on **CoordinateConversionArcGISPro1.0.1.zip**

**Comment by mfunk** [comment]
Starting on **DistanceAndDirectionArcGISPro1.0.0.zip** and **DistanceAndDirectionArcMap1.0.0.zip**.

These will go into ONE Document link with internal links to the separate downloads.

**Comment by mfunk** [comment]
Starting on ** VisibilityArcGISPro1.0.0.zip** and **VisibilityArcMap1.0.0.zip**.

These will go into ONE Document link with internal links to the separate downloads.

**Comment by mfunk** [comment]
Starting on **CrossCountryMobility_3.0.0.zip**

**Comment by mfunk** [comment]
Starting on **HelicopterLandingZone_4.0.0.zip**.

**Comment by Dbarnes1** [comment]
@mfunk Starting on **ImageryBasemap3.0.0.zip**

**Comment by mfunk** [comment]
Starting on **IncidentAnalysis5.0.0.zip**.

**Comment by elinz** [comment]
@mfunk Finished with GeonamesLocator4.1.1.zip

**Comment by mfunk** [comment]
Starting on **MilitaryAspectsofTerrain_1.0.0.zip**.

**Comment by mfunk** [comment]
Starting on **PointofOriginDetection5.0.1.zip**.

**Comment by Dbarnes1** [comment]
@mfunk starting on **PredictiveAnalysisWeb1.1.0.zip**

**Comment by mfunk** [comment]
Starting on **RangeCards2.0.0.zip**.

**Comment by Dbarnes1** [comment]
@mfunk @dfoll already created **PredictiveAnalysisWeb1.1.0**, I'm marking it as complete.

**Comment by mfunk** [comment]
Starting on **ScannedMapsBasemap3.0.0.zip**.

**Comment by mfunk** [comment]
Starting on **SunPositionAnalysis_1.0.0.zip**.

**Comment by mfunk** [comment]
Starting on **TimeSpanAnalysis2.0.0.zip**.

**Comment by lfunkhouser** [comment]
@mfunk There are 2 Compound Map doc links. One for previous version 4.0.0 exists id=1ebce832b268418aa2adda47ba766586 - this could be updated for the new version instead of creating an additional item, id=37c6d44fdb9f41c98dad95a0d42fb91e for version 5.0.0. Which one do you want to use/release?

**Comment by mfunk** [comment]
@lfunkhouser @ACueva @elinz 

All of the document links that needed to be CREATED are done.

Next is to update existing ones. For that I either need someone to assign them to me or give me permissions to edit them directly.

**Comment by mfunk** [comment]
@lfunkhouser I cannot see 1ebce832b268418aa2adda47ba766586:

![image](https://cloud.githubusercontent.com/assets/3093182/18401782/14e345a0-7691-11e6-81f7-9f3e4495cc75.png)

**Comment by mfunk** [comment]
@lfunkhouser @ACueva @elinz 

I've got permissions and have moved all of my Document links to **ReleasedMilitary**.

**Comment by mfunk** [comment]
Starting on **SolutionsGeoprocessingToolbox2.2.0.zip**.

**Comment by mfunk** [comment]
Starting on **DistancetoAssets2.0.1.zip**.

**Comment by mfunk** [comment]
Starting on **ClearingOperations5.0.1.zip**.

**Comment by mfunk** [comment]
Starting on **BeachLanding4.0.0.zip** owned by *ReleasedMilitary*.

@lfunkhouser can you delete or unshare your Document link to Beach Landing so we don't confuse it with the "fixed" one?

**Comment by mfunk** [comment]
Starting on **GeoMessageSimulator1.0.0Windows-x64.zip**.

**Comment by Dbarnes1** [comment]
@mfunk starting on **LodgmentPlanning5.0.0.zip**

**Comment by mfunk** [comment]
Starting on **VehicleCommander4.1.1Windows-x64.zip**.

**Comment by Dbarnes1** [comment]
Fixed **LodgmentPlanning5.0.0.zip** There is a document link for this template that is owned by @lfunkhouser, can you remove/hide this?

**Comment by Dbarnes1** [comment]
@mfunk starting on **NationalSecurityBasemaps2.0.1.zip**

**Comment by Dbarnes1** [comment]
@mfunk starting on **RangeDomeAnalysis3.0.0.zip**

**Comment by Dbarnes1** [comment]
@mfunk starting on **VehicleCommander4.1.1Windows-x64.zip**

**Comment by mfunk** [comment]
@Dbarnes1 Negative.... I'm already on Vehicle Commander....

**Comment by mfunk** [comment]
@topowright it seems there is only one **Visibility and Range** document link. I'm going to update it and send it to *ReleasedMilitary*.

Starting on **VisibilityAndRange5.0.0.zip**.

**Comment by mfunk** [comment]
@lfunkhouser Done with updating the document links.

**Comment by lfunkhouser** [comment]
The beach landing template owned by lfunkhouser is not intended to be released. The one owned by ReleasedMilitary should be the item that gets updated if needed.

**Comment by lfunkhouser** [comment]
@mfunk Compound Map points to v4.0.0 not 5.0.0, @elinz do we still have time to fix this?

**Comment by elinz** [comment]
@lfunkhouser Go ahead and make the change. Let me know when it’s done and also if we can close out this issue.

thanks

**Comment by elinz** [comment]
There was one last edit that @lfunkhouser wanted to do. I'm not sure if this was completed, but we are now in the Jenkins build phase so I'm closing this issue.
