### ISSUE TITLE
Please release Panga Boat Smuggling story map application demo

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1498]
This demo is part of the UC 2016 presentation for Maritime Big Data.

Panga Boat Story Map

Panga Boat Intelligence FS- 93b2bcccc17c486e92720f1059a8f1a2 
Panga Boat Intelligence MS - f83dc1f4959e4f4f85fc1e688c05160b
Panga Boat Photograph 1 - 6bc0234bc77c4828a28746b8f51a0fe3
Panga Boat Photograph 2 - b31a3859e24c4542b6546010a05b7723
Panga Boat Smuggling WebMap -55e63ff71694417e8cef863ffe7f7122
Panga Boat Smuggling Web App - 9342dd42160943aa9c2e76fa021d7c96

**Comment by elinz** [comment]
- [ ] Panga Boat Intelligence FS- 93b2bcccc17c486e92720f1059a8f1a2, change owner to DemoMilitary. 
Panga Boat Intelligence MS - f83dc1f4959e4f4f85fc1e688c05160b, change owner to DemoMilitary.
Panga Boat Photograph 1 - 6bc0234bc77c4828a28746b8f51a0fe3, change owner to DemoMilitary.
Panga Boat Photograph 2 - b31a3859e24c4542b6546010a05b7723, change owner to DemoMilitary.
Panga Boat Smuggling WebMap -55e63ff71694417e8cef863ffe7f7122, change owner to DemoMilitary.
Panga Boat Smuggling Web App - 9342dd42160943aa9c2e76fa021d7c96, change owner to DemoMilitary.

**Comment by elinz** [comment]
@jfrygeo All 6 items requested to be released have been released, i.e. ownership has been changed to DemoMilitary; also unshared with Demo Review group. 

Please verify and then close this issue. Thanks.

**Comment by jfrygeo** [comment]
Verified.
