### ISSUE TITLE
Military Overlay related services exists without portal items; assume author wanted them deleted

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1504]
@Dbarnes1 I'm assuming these services are yours as I can't verify ownership. Since the portal items don't exist anymore, I'm assuming your intent was to delete these services. Please confirm and I will delete these services. Thanks.

ERROR: Service "Military//MilitaryOverlay.MapServer" is associated with a portal item (850a7321fe724f429d1a0ba20c287c61; MapServer) that does not exist.

ERROR: Service "Military//MilitaryOverlay.MapServer" is associated with a portal item (202d58f08fda48f8a8cf96104a8dd4bb; FeatureServer) that does not exist.

ERROR: Service "Military//Military_Overlay_Pro1dot3.MapServer" is associated with a portal item (105b5550645b4a45adaa48918385f5c9; MapServer) that does not exist.

ERROR: Service "Military//Military_Overlay_Pro1dot3.MapServer" is associated with a portal item (145dc4fd81df4e40aa6ad7b574ecb7e8; FeatureServer) that does not exist.

**Comment by Dbarnes1** [comment]
@elinz confirmed, you can go ahead and delete these services. They will need to be manually published once the ops server is distributed anyway. Thanks

**Comment by elinz** [comment]
I deleted MilitaryOverlay service, but having problems deleting the Military_Overlay_Pro1dot3 service, with error that another administrative process is trying to configure the server. I will attempt to delete the service at a later time.

**Comment by elinz** [comment]
I was able to delete the service Military\Military_Overlay_Pro1dot3. Issue was probably fixed during server restart. Closing this issue.
