### ISSUE TITLE
Need to sync and change ownership of ExecuteQuery/GPServer

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1507]
I republished the service ExecuteQuery/GPServer to our production server (c0d5b5d7c4b94b189ff3146567349cb4 ) but there exists a DemoIntelligence owner serviced item for this gp service (c9e065fe2b3c47d9bc1cec734affe711)   "Execute Query GP Service"                                                                                         

I need to change ownership of this service item to DemoIntelligence and edit the service json to point the service to the item c9e065fe2b3c47d9bc1cec734affe711.

**Comment by elinz** [comment]
- Ownership of item c0d5b5d7c4b94b189ff3146567349cb4 was changed to @dfoll and he updated the description, summary, etc for this item.
-  I delete the item c9e065fe2b3c47d9bc1cec734affe711.
- I changed ownership of item c0d5b5d7c4b94b189ff3146567349cb4 to DemoIntelligence.

Closing issue.

**Comment by elinz** [comment]
@dfoll I also changed ownership of the AnalyzeQueryFactors portal item be1e530f006f4a2b9f10036058d042f4 to DemoIntelligence.

**Comment by dfoll** [comment]
@elinz sounds good, thanks
