### ISSUE TITLE
Web Mapping App "Foundation Data Journal" references a web map item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1508]
Web map app 5cd903df8c234d9584f77bad9be47222 owned by DemoNationalSecurity...

ERROR: References web map item that does not exist: fd0831d938eb426da87e25ae54ad7234

@nfeuerstein Do you know who was the author of this app?

**Comment by nfeuerstein** [comment]
This is the one that Kerry made for last year's TEM.

**Comment by elinz** [comment]
@nfeuerstein Thanks.

**Comment by elinz** [comment]
Discussed issue with @kerryrobinson. If the app opens and each "tab" of the story app works then the missing web map item is not an issue. Tested web map app and missing web map item appears not to be a problem. Closing issue.
