### ISSUE TITLE
Please Release "Maritime Domain Awareness Dashboard" demo content for TEM

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1513]
@lfunkhouser @elinz The Maritime Domain Awareness Dashboard was previously released presentation that was used during 2016 UC DIS presentation. There were some issues with the shipping information not updating in the dashboard. These items were already released once and had been updating when a simulation file was set. 

The issue with them not updating is that if you are running the GeoEvent simulator with sample AIS simulation file from a local client machine, only one location would update in the Operations Dashboard. However, if you run the GeoEvent Simulator from the GEE server, locations get updated in the dashboard. 

-Sample CSV file
<li> AIS Ship Traffic Simulation CSV - Run on the GeoEvent server with Port 5566
https://"portal"/arcgis/home/item.html?id=6b11665dc1924f6898a48a31a1f9ff15

-Dashboard
<li>"Maritime Domain Awareness" Operations Dashboard

-Web Map
<li> "Maritime Domain Awareness" web map. 
https://"portal"/arcgis/home/item.html?id=995d354c59694c01bbd1ff877441526a

-Feature Services

<b>Proximity Hazard</b>-created when there is a military vessel reported 
https://"server"/ags/rest/services/Military/ProximityAlert/FeatureServer

<b>Shipping</b> Shipping feature service which is updated from the simulation file. 
https://"portal"/arcgis/home/item.html?id=620d14d3602049ae979130fafca37ff3

-Geoevent Services
<b>  Input </b>- MaritimeOps-Ship-Position-tcp-text-in (Receive Text from a TCP Socket)
<b> GeoEvent Service</b> -MaritimeOps-ShipPosition
<b> Output</b> - MaritimeOps-Ship-Position-fs-out
<b> Output</b> - MaritimeOps-Proximity-Alert-fs-out

**Comment by elinz** [comment]
- Sample CSV File: 6b11665dc1924f6898a48a31a1f9ff15 - Already owned by DemoMilitary, updated 08 Sept 2016.

- [ ] "Maritime Domain Awareness" Operations Dashboard - I'm assuming it's 0845dd9f0ee74d66b504e62804d2c2c6, owned by @jfrygeo needs to be released as owner DemoMilitary

- [ ] "Maritime Domain Awareness" web map - 995d354c59694c01bbd1ff877441526a, owned by @jfrygeo  needs to be released as owner DemoMilitary.

- [ ] Proximity Alert Map Service: 5463afdb5cb8475689997dd07eb0d57b, owned by @jfrygeo, needs to be released as owner DemoMilitary.

- [ ] Proximity Alert Feature Service: 478cbdd6f965408f9094ec5b33f0114d, owned by @jfrygeo , needs to be released as owner DemoMilitary.

- Ship position map service: 87c6d0c38f3647f3b460b477323e516fm, owned by DemoMilitary already, updated Aug 2, 2016

- Ship position feature service: 620d14d3602049ae979130fafca37ff3, owned by DemoMilitary already, updated Aug 2, 2016

**Comment by elinz** [comment]
@jfrygeo @lfunkhouser I will take care of this.

**Comment by elinz** [comment]
@jfrygeo Based on #1488 I am not changing ownership of any of these items to DemoMilitary yet.

**Comment by elinz** [comment]
@jfrygeo What is the status? Is all content ready to go? I know you were having a problem with #1488 . Thanks.

**Comment by jfrygeo** [comment]
All good to go for release. Please close out #1488 #1489 #1490 #1492 #1528

**Comment by elinz** [comment]
Closing this issue. Items have been released. Ownership changed to DemoMilitary.
