### ISSUE TITLE
Confirm latest PA Web installers are being used in the ops server scripts

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1515]
Making sure the latest PA Web .dlls are being used in the ops server script(s). I believe the services are good already, and because the services are good already, the .sd files should be of no concern, but making sure the .dlls needed for those services are installed with the ops server script(s). If you need if the most recent version of PA Web .zip is attached, the setup.exe is inside this .zip in the "Web Services Installer" folder.
[PredictiveAnalysisWeb1.1.0.zip](https://github.com/Esri/ops-server-config/files/462791/PredictiveAnalysisWeb1.1.0.zip)

**Comment by dfoll** [comment]
@ACueva

**Comment by elinz** [comment]
@dfoll @ACueva I am only including the ESRI.ArcGIS.GPAT.Web.Install.msi and setup.exe from the .zip file you referenced. I've already copied these files into our staging location for the software installer piece of the Ops Server release. 

@dfoll Close issue whenever you are ready.

**Comment by dfoll** [comment]
exactly what i was hoping to hear. thanks @elinz
