### ISSUE TITLE
Cannot overwrite existing service. Possible due to ownership of services.

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1518]
Need to republish some services that GEE is using as geofences. Cannot republish services possibly due to ownership of the services. These services were published as the user "DemoMilitary" and now do not have rights as a publisher to overwrite the services. 
![republishing](https://cloud.githubusercontent.com/assets/5074686/18395524/b6cd12f6-768c-11e6-8a39-4bfc1505ef47.JPG)

**Comment by elinz** [comment]
@jfrygeo You shouldn't attempt to overwrite a service you don't own. So what are the names of the services? You didn't mention it in the issue.

**Comment by elinz** [comment]
@ACueva Assigning to you as I have to head out in a few minutes. Thanks.

**Comment by jfrygeo** [comment]
I own the service. - "Proximity Alert"

**Comment by jfrygeo** [comment]
When the opsserver scripts published the content, it was published under "DemoMilitary." The services were transferred over to me so I could attempt to republish. Getting the error above when I try to republish the service.

**Comment by jfrygeo** [comment]
I was able to republish the service after the service restart. Service is here https://"server"/ags/rest/services/Military/ProximityAlert/FeatureServer
