### ISSUE TITLE
No Spatiotemporal Big Data Stores available in GeoEvent

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1519]
![nostbdsavailable](https://cloud.githubusercontent.com/assets/5074686/18400467/07456ce4-76a4-11e6-994f-9007ce541ef8.JPG)

Typically, the list of registered ArcGIS Server connections usually appears in this dialog.

**Comment by ACueva** [comment]
Had to re-validate the data store.  Looks like it came back up. @jfrygeo assigning it back to you to close if issue has been resolved.
![9-9-2016 3-12-06 pm](https://cloud.githubusercontent.com/assets/3093940/18404522/d68fdbe2-769f-11e6-9ff5-947fea5193c9.jpg)

**Comment by jfrygeo** [comment]
I was able to create a spatiotemporal big data store using the "default" connection as it was the only one that was showing up.

**Comment by elinz** [comment]
@ACueva @jfrygeo The "default" data store entry should not have been used for the Spatiotemporal Big Data Stores "connection". I had created the data store "OpsServer-Portal-SpatioTemporal" and assigned to the Big Data stores in the past for this purpose. I just registered the "OpsServer-Portal-SpatioTemporal" data store and now it shows up in the list of big data store connections. But haven't selected it yet because we need to see what is the impact.

**Comment by elinz** [comment]
@jfrygeo @ACueva I went ahead and changed the connection to use "OpsServer-Portal-SpatioTemporal" data store. Going to talk to geoevent team to see if there is any problem changing the connection after the big data store data sources have been created.

**Comment by jfrygeo** [comment]
I haven't loaded any data yet. I can delete the current map/feature services and create new ones with the "OpsServer-Portal-SpatioTemporal" connection.

**Comment by jfrygeo** [comment]
Created map services/feature services with the "OpsServer-Portal-SpatioTemporal" connection.

**Comment by elinz** [comment]
@jfrygeo Talking with the geoevent team it does not appear that the Big Data Store data sources store the "alias" of the data store connection that was used in the Manage Spatiotemporal Big Data Stores. If you think it's safer to delete and recreate the new data sources now that I changed it to use "OpsServer-Portal-SpatioTemporal" connection please feel free.

**Comment by elinz** [comment]
@jfrygeo ok. Thanks. I will go ahead and close this issue.
