### ISSUE TITLE
Foundation Data Journal: References web map item that does not exist

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#1521]
item id:5cd903df8c235d9584f77bad9be47222

is missing a web map. id:4d0831d928eb426da87e25ae54ad7234

**Comment by elinz** [comment]
id is 5cd903df8c23**_4_**d9584f77bad9be47222.

Discussed issue with @kerryrobinson. If the app opens and each "tab" of the story app works then the missing web map item is not an issue. Tested web map app and missing web map item appears not to be a problem. Closing issue.
