### ISSUE TITLE
Geoevent folder data store that points to c:\data no longer exists

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1524]
Up until a week or so ago we had a folder data store on the Geoevent server that referenced the folder C:\Data. This data store does not exist any more.

Not sure what's going on here. Can you look into this please?

**Comment by pHill5136** [comment]
@elinz Not sure why this was deleted or how/ by whom??? I looked at an older config and the c:/data path is paired with a data store named 'Data'. I restored the data store in GEE.

**Comment by elinz** [comment]
@pHill5136 I verified that is was fixed. I'm closing the issue. Thank you.
