### ISSUE TITLE
Service Military\Mil2525CWeb map service does not have a service definition file

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1526]
Without a service definition file this non-hosted service can't be published to an Ops Server. Based on the name of the service, I'm assuming this has military symbology so it was published from Pro as a non-hosted service so it will need to be manually published by people setting an Ops Server

@Dbarnes1 Will this service be a part of this Ops Server Release? If yes, are you creating the documentation and whatever else is needed to manually publish this service for this release? Thanks.

**Comment by Dbarnes1** [comment]
@elinz I just deleted this service and the associated portal items, so it should be gone now. The documentation I've included goes over how to publish services from Pro from scratch, as that workflow will be easier than re-pointing their data to existing services.

**Comment by elinz** [comment]
@Dbarnes1 Thanks. I will close this issue.
