### ISSUE TITLE
"Mission Report" Geoform web map app does not open

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1527]
item 4ab19d716e4442daaacf006fdeb52677 Mission Report throws the following error when it's opened:

Unable to create map: Form layer does not exist. Please configure the application and set the layer.

Note: this app is being consumed by the "Geospatially Enabled the Intelligtence Collector (Map Journal)" web map app (story map) - cf92fbb86028410cbdd84947d7e7a56a

**Comment by topowright** [comment]
@elinz I have finished my work and turn back on the service. This should be working now. Please verify.

**Comment by elinz** [comment]
@topowright I verified that this is now working. I am closing issue. Thank you.
