### ISSUE TITLE
"Maritime Domain Awareness" web map references URL that I can't access

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1528]
web map 995d354c59694c01bbd1ff877441526a references the url...
http://geo.weather.gc.ca/geomet/?lang=E

When I access this url I receive an error that this site can't be reached.

**Comment by jfrygeo** [comment]
I can see the information from that WMS service in a web map. When trying to access this URL from a browser:

https://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities

You cannot reach it, but adding the WMS url in a web map the information shows up properly. 

Please test URL in a web map and close issue. Very similar to issue #1529

**Comment by elinz** [comment]
@jfrygeo Tried to add new wms service using this url ( https://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities) in a web map and received the following error:

"The WMS service, https://geo.weather.gc.ca/geomet/?lang=E, cannot be added to the map. It is either not available or you have entered an invalid URL for the type of layer you want to reference."

**Comment by elinz** [comment]
@jfrygeo Haven't been able to add the WMS url to a web map. Each attempt has thrown errors. I'm going to go ahead and close this issue since you have been able to get this to work.
