### ISSUE TITLE
"Meteorological Service of Canada (MSC) GeoMet Geospatial Web Services" WMS url doesn't respond

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1529]
WMS service item 14808ff0a2f94601a02711d78f824ae9 references the url...
https://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities

When I access is a browser I receive an error that that the site can't be reached.

**Comment by jfrygeo** [comment]
I am able to see the WMS layer in a web map for the item Meteorological Service of Canada (MSC) GeoMet Geospatial Web Services:

https://"Portal"/arcgis/home/item.html?id=14808ff0a2f94601a02711d78f824ae9


Please verify service works in a web map.

**Comment by elinz** [comment]
@jfrygeo I will close this issue. Thanks.
