### ISSUE TITLE
"SpatialTemporalBDS" folder data store is not needed

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1535]
The "SpatioTemporalBDS" folder data store references the folder c:\data\SpatioTemporalBDS. There is already a data store named "Data" which references the C:\data folder so creating a separate data store entry for the SpatioTemporalBDS subfolder is unnecessary. Probably when you created the "SpatioTemporalBDS" data store entry the "Data" was didn't exist. For some reason it was deleted I think sometime last week.

You can leave this SpatioTemporalBDS data store and I'll modify the install instructions or if you want to have a cleaner installation then you can delete this but then you will have to republish some geoevent services so they reference the "Data" data store. Just let me know what you want to do.

**Comment by jfrygeo** [comment]
I think @ACueva  created this folder ("GeoeventServer"\SpatioTemporalBDS\Shipping) so I am able to drop some AIS data into it. Lets keep this as I just transferred some csvs there.

**Comment by elinz** [comment]
@jfrygeo Having the folder C:\data\SpatioTemporalBDS\Shipping isn't a problem it's that we have an unneeded data store called "SpatioTemporalBDS". The "Data" data store references the C:\data folder so there is no need to create other data store entries that reference sub folders to the C:\data folder.

**Comment by elinz** [comment]
@jfrygeo Closing this issue.
