### ISSUE TITLE
Duplicate Items on Portal / Please delete the following

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1536]
The following items have been released:

Panga Boat Intelligence FS- 93b2bcccc17c486e92720f1059a8f1a2
Panga Boat Intelligence MS - f83dc1f4959e4f4f85fc1e688c05160b
Panga Boat Photograph 1 - 6bc0234bc77c4828a28746b8f51a0fe3
Panga Boat Photograph 2 - b31a3859e24c4542b6546010a05b7723
Panga Boat Smuggling WebMap -55e63ff71694417e8cef863ffe7f7122
Panga Boat Smuggling Web App - 9342dd42160943aa9c2e76fa021d7c96

Original content located here (owned by user @KenHarrigan ). This user helped me at the 2016 DIS to create content. Now the content is released, so the following can be deleted:

- Panga Boat Smuggling - 288c9305f2024c138f6a62bf5d0e7593
- Estimated Departure Region -edd2973b115e4c95a8c2dccb7630cc71
- Panga Boat Locations  web map- e862816421f443b489d24a4c4254dcdb
- Panga_Boat_Ranges web map - 2bb1f05bb9d54c2ea2615c7c92d0645c
- Historic Smuggling Route FS - cd6de56aa82a4fe38ac5e7558f8af548
- Historic Maritime Drug Smuggling Routes - cd172aa6ea77463487fa62c52b5a3147

**Comment by elinz** [comment]
- [ ] Panga Boat Smuggling - 288c9305f2024c138f6a62bf5d0e7593
- [ ] Estimated Departure Region -edd2973b115e4c95a8c2dccb7630cc71
- [ ] Panga Boat Locations web map- e862816421f443b489d24a4c4254dcdb
- [ ] Panga_Boat_Ranges web map - 2bb1f05bb9d54c2ea2615c7c92d0645c
- [ ] Historic Smuggling Route FS - cd6de56aa82a4fe38ac5e7558f8af548
- [ ] Historic Maritime Drug Smuggling Routes - cd172aa6ea77463487fa62c52b5a3147

**Comment by elinz** [comment]
@jfrygeo Done. Deleting this content. Closing issue.
