### ISSUE TITLE
Please share hosted feature services from the BDS user

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1537]
@elinz Can you share the following feature and map services so I can use them in a web application. It is not letting me share them. 

-AISHistoric FS - 6eaba7e4813c4dc9a85927d6a9ef44b9
-AISHistoric MS - 3fa6248067ca4fca8dca79b51b4b31fb
-AISHistoricSOGMin - a8373a48c8754829af429681a1dd3eae

**Comment by elinz** [comment]
@jfrygeo I have shared these items with Everyone.

**Comment by elinz** [comment]
@jfrygeo Just making sure. Did you write up instructions on how to republish these services as these services can't be automatically republished. Thanks.

**Comment by elinz** [comment]
Closing issue.
