### ISSUE TITLE
What items in GeoEvent will users need to recreate for connectors to BDS?

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1542]
When users deploy the OpsServer, what items will they need to recreate in GeoEvent? I am trying to decided what to tell users to set up in the documentation.

-BigData store connection in registered Arcgis Servers?
-Input connector  - (looking at a registered folder)?
-Spatiotemporal hosted features and map services (Spatiotemporal big data store tab)?
-output connector - (looking at Spatiotemporal hosted features and map services)?
-Geoevent services?

**Comment by elinz** [comment]
@jfrygeo Anything having to do with Big Data you will have to tell them to do because we don't install Big Data Store as part of the Ops Server.

**Comment by jfrygeo** [comment]
Will do
