### ISSUE TITLE
Intel web apps don't have any portal items and will be removed from release

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1543]
@nfeuerstein @dfoll FYI: The following web apps under SolutionsWeb\Apps\NationalIntel do not have any portal items that reference them so I'm removing them from the SolutionsWeb\Apps\NationalIntel folder so they won't be copied into the release:

- PredictiveAnalysisWeb-UC2016
- StoryMap-Cascade-1.0.2
- Survey123Community-master
- Test

**Comment by elinz** [comment]
@nfeuerstein @dfoll I've moved them to the folder c:\EricL\TEM2016Release\SolutionsWeb_files_removed_from_release\Apps\NationalIntel on the server. Closing issue.

**Comment by elinz** [comment]
@nfeuerstein @dfoll Same issue with PredictiveAnalysis-SharingQueries; moving this out of the SolutionsWeb folder.

**Comment by dfoll** [comment]
i only know about the two PA web apps, both are directly my fault... didn't think to delete them from the solutionsweb folder when i no longer wanted the items... apologies

**Comment by elinz** [comment]
@dfoll The only PA web app that will be included in the release is SolutionsWeb\Apps\NationalIntel\PredictiveAnalysisWeb1.1.0RCtest since it's the only one that was released.

**Comment by dfoll** [comment]
@elinz awesome, that is exactly what i intended
