### ISSUE TITLE
Will "PredictiveAnalysis" web app be released?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1544]
@dfoll Will the web app SolutionsWeb\Apps\NationalIntel\PredictiveAnalysis be released? The associated portal item is owned by you. If it's not going to be released that please remove this app folder from the SolutionsWeb\Apps\NationalIntel so it's not shipped with the release. Alternatively, I can remove to another location on the server so it's not included, but you'll have a backup of this files. Thank you.

**Comment by elinz** [comment]
@dfoll Haven't heard back and it's after the content cutoff so I'm going to move this app outside SolutionsWeb\Apps\NationalIntel. Moved to the following folder on the server:
C:\EricL\TEM2016Release\SolutionsWeb_files_removed_from_release\Apps\NationalIntel

Closing this issue.

**Comment by dfoll** [comment]
@elinz i know it's after the fact, but for what it's worth, that was the correct move...the one owned by me was not intended to be released, as i mentioned on the other issue, that was just a lack of thinking on my part, and didn't think about removing it from solutionsweb
