### ISSUE TITLE
Will "PredictiveAnalysisAntiSmuggling" web app be released?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1545]
@nfeuerstein  Will the web app SolutionsWeb\Apps\NationalIntel\PredictiveAnalysisAntiSmuggling be released? The associated portal item is owned by you. If it's not going to be released that please remove this app folder from the SolutionsWeb\Apps\NationalIntel so it's not shipped with the release. Alternatively, I can remove to another location on the server so it's not included, but you'll have a backup of this files. Thank you.

**Comment by nfeuerstein** [comment]
Deleted.
