### ISSUE TITLE
Will "MilitaryOverlayPlanning" web app be released?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1547]
@kerryrobinson  Will the web app SolutionsWeb\Apps\Military\MilitaryOverlayPlanning be released? The associated portal item is owned by you. If it's not going to be released that please remove this app folder from the SolutionsWeb\Apps\Military so it's not shipped with the release. Alternatively, I can remove to another location on the server so it's not included, but you'll have a backup of this files. Thank you.

**Comment by kerryrobinson** [comment]
@elinz No this will not be released. Can you move it to another folder?

**Comment by elinz** [comment]
@kerryrobinson I have moved to c:\EricL\TEM2016Release\SolutionsWeb_files_removed_from_release\Apps\Military on the server. Closing issue.
