### ISSUE TITLE
Will "MilitarySymbologyWeb" web app be released?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1548]
@joebayles Will the web app SolutionsWeb\Apps\Military\MilitarySymbologyWeb be released? The associated portal item is owned by you. If it's not going to be released that please remove this app folder from the SolutionsWeb\Apps\Military so it's not shipped with the release. Alternatively, I can remove to another location on the server so it's not included, but you'll have a backup of this files. Thank you.

**Comment by joebayles** [comment]
Assigning to @Dbarnes1 because I think this is his item that I just worked on.

**Comment by Dbarnes1** [comment]
@elinz this web app is referencing feature layers that no longer exist. I think that this web app can be deleted.

**Comment by elinz** [comment]
@joebayles @Dbarnes1 Moved this app to the following folder on the server so it's not going to be a part of this release:
c:\EricL\TEM2016Release\SolutionsWeb_files_removed_from_release\Apps\Military
