### ISSUE TITLE
Please Release "Maritime Threat Awareness Web Application" portion of Maritime Big Data Demo

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#1549]
Feature and Map Services. These, I think will need to be created.

-AISHistoric FS - 6eaba7e4813c4dc9a85927d6a9ef44b9
-AISHistoric MS - 3fa6248067ca4fca8dca79b51b4b31fb
-AISHistoricSOGMin - a8373a48c8754829af429681a1dd3eae

We can release these:
-Maritime Threat Awareness- Web Map - b66101dbbf78459ea48f0df4cb6bbb94
-Maritime Threat Awareness Web Application - 71d30f4be37b4dc3adb95bbb92da4841

**Comment by elinz** [comment]
@jfrygeo Looks like the apps are being updated to use the newly published farthest on circle gp tool. Going to wait to release this until the apps are updated.

**Comment by jfrygeo** [comment]
Please release.

**Comment by elinz** [comment]
@jfrygeo I released the following items. They are now owned by DemoMilitary.
-Maritime Threat Awareness- Web Map - b66101dbbf78459ea48f0df4cb6bbb94
-Maritime Threat Awareness Web Application - 71d30f4be37b4dc3adb95bbb92da4841
