### ISSUE TITLE
Instructions for re-creating Air 2C stream services need to be written

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1556]
Stream services won't be automatically created during the Ops server publishing so a pdf document needs to be written with instructions on how to create the stream services necessary for the AirC2 demo.

This pdf should be placed in the OPSServerReleases\2016_Q4\DemoAndScripts\DemoAndScripts

Note that the geoevent stream service "entries" will exist in the Ops Server geoevent configuration, but the underlying stream service won't exist in ArcGIS Server so you will also need to instruct the user on how to delete the existing stream service references in Geoevent manager.

**Comment by joebayles** [comment]
Assigning back to @elinz to decide if this is enough.

http://solutions.arcgis.com/defense/templates/air-c2-cop/get-started/setup-simulator/

**Comment by elinz** [comment]
@joebayles @adgiles That page doesn't show you how to create stream services. I did find stream service creation mentioned here http://solutions.arcgis.com/defense/templates/air-c2-cop/get-started/setup-outputs/

For Ops Server release was there suppose to be any simulators? I don't find any of the .csv's mentioned in your referenced topic http://solutions.arcgis.com/defense/templates/air-c2-cop/get-started/setup-simulator/ on the Ops Server.

FYI.  Not all gee service names mentioned in these doc pages match the names on Ops Server.

The doc needs to be written in context to the Ops Server. i.e. I've set up an Ops Server based on this release and now what are the things I need to do to get AirC2 works on the Ops Server.

**Comment by elinz** [comment]
@joebayles @adgiles I did find the .csv's. thanks.

**Comment by elinz** [comment]
@joebayles @adgiles The instruction doc can be placed in the 2016_Q4\DemoAndScripts\Military\AirC2 folder I created. I will send the full path in an email.

**Comment by elinz** [comment]
@joebayles @adgiles This doc is being written by @pHill5136

**Comment by elinz** [comment]
Merged all the additional setup instructions into a single .pdf file and copied to the DemoAndScripts\Military\AirC2 folder in the final release. Closing issue.
