### ISSUE TITLE
Image Observables Document Link Broken on Test Portal

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/ops-server-config#1564]
I'm getting an error when trying to download Image Observables on the test portal, it looks like the zip might be missing from the proper folder. 

https://{testportal}.esri.com/arcgis/home/item.html?id=ffa524689f384d2a9546ec4dc33f0ca4

**Comment by elinz** [comment]
@Dbarnes1 The URL is incorrect. The "Intelligence" folder wasn't changed to "ArcGISDefense". I'll edit the extracted content in the release folder to change the URL in json file for this item. Thanks.

**Comment by elinz** [comment]
@Dbarnes1 I corrected the URL on the development portal. Re-extracted this item and integrated into the final release folder structure. Closing this issue.
