### ISSUE TITLE
Intervisibility widget in Air Plan (next) pointing to a gp service that does not exist

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1565]
On the testing portal, the "AirC2 - Air Plan (Next 24) - App Template" item [testing server]/item.html?id=3f2ec82c26d740228a88ae5a0d750d08 has an intervisibility widget that uses the viewshed gp service, which does not exist on the testing server.

**Comment by elinz** [comment]
- [ ] Military\AirC2_2D_AirPlanNext24\widgets\Geoprocessing\Intervisibility.json - this is pointing to incorrect location of gp service.
- [ ] Military\AirC2_2D_AirPlanNext24\widgets\Viewshed\Widget.js - this is pointing to incorrect location of gp service.

**Comment by elinz** [comment]
Closing issue.
