### ISSUE TITLE
Intervisibility widget in Air Plan (Live) pointing to a gp service that does not exist

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1566]
On the testing portal, the "AirC2 - Air Plan (Live) - App Template" item [testing server]/item.html?id=11df1e803eed40389cddbf0703944371 has an intervisibility widget that uses the viewshed gp service, which does not exist on the testing server.

**Comment by elinz** [comment]
This viewshed_gp service exists on our development portal/server and is owned by @topowright and was not released and was not extracted for this release.

**Comment by elinz** [comment]
@dfoll I've released this portal item and integrated into the final release. Closing this issue.
