### ISSUE TITLE
Current Operations (MultiDisplay) give an warning message that data sources are not accessible

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1567]
On the testing server, when  opening the Current Operations (MultiDisplay) item.html?id=59ec3b3e65f344f2922c6f68eaf0c142 gives an warning message that data sources are not accessible, however no data sources are listed in the box.

**Comment by elinz** [comment]
@dfoll This operations view references the service Military\AirC2_MilitaryAirTracks\MapServer which must be published manually. This service along with Military\AirC2_LandInstallations\MapServer won't be created on the test server. Instructions will be provided to instruct users on how to create these services; however, these instructions may have to be provided after the USB drives are made.

**Comment by dfoll** [comment]
got it!
