### ISSUE TITLE
"AirC2-StreamServiceOut-CivilianAirTracks" feature layer does not add to a webmap

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#1568]
Item "AirC2-StreamServiceOut-CivilianAirTracks" item.html?id=6b57a2da8e98493080a03f31fa29be99 does not add to a map, message "The layer, AirC2-StreamServiceOut-CivilianAirTracks, cannot be added to the map." when trying to add to a new map

**Comment by elinz** [comment]
@dfoll Stream services have to be manually created and may not be recreated on the test server. Instructions will be provided to instruct users on how to create these services; however, these instructions may have to be provided after the USB drives are made.

**Comment by dfoll** [comment]
got it....sorry for over creating issues. i'll ask about ones that seem funny before creating excess issues
