### ISSUE TITLE
Current Operations (Single Display) item has issues

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#1573]
Current Operations (Single Display) (Operations View) owned by Demonstration: <link removed>10b05c86371f46568a1623dbacec8f86
* [ ] No Description
* [ ] No Summary
* [ ] No Credits
* Open in Browser, opens, interacting with app... a little. Again, not sure what I should be doing here, or what I can do here.

Had several Connectivity Issues:
==================================================================
Operations Dashboard can no longer access some resources used by the operation view. Please check your network connection or contact the publisher Demo Demonstration.
x Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: da440349938947d8815e4fe4e963429f
<link removed>
Could not access service. Either the service is not available, has been deleted, or it does not support secured access (HTTPS/SSL).
 <link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: 61ab5eedba644d6c812d6a849615b4b3
<link removed>
Could not access service. Either the service is not available, has been deleted, or it does not support secured access (HTTPS/SSL).
<link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: d26c502c8e204403ab409cb4de312797
<link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: e7eb02ad70b145fa9d8d40396f9a9a6f
<link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: dd75b088db8448bb81be7d0c39c31f22
<link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: 258362e7168f4d279e405446f1dae16d
<link removed>
Could not access item. Either you do not have access to the item or it has been deleted. Operations Dashboard used the service url instead.
Item id: ac61ccc9ba8c4ed8a60557ac7105fc6c
<link removed>
Item or service could not be accessed when opening the map.
<link removed>/8453829fc1e64ac49d30459833fcf086

Comment

**Comment by elinz** [comment]
@mfunk For items owned by Demonstration, we really aren't worried about the description, credits and summary. The only error I receive when I open this operations view is "The following data sources are not accessible", this ops view references the service Military/AirC2_MilitaryAirTracks/MapServer which has to be published manually by users. Instructions for publishing this service are being written and will be provided in the Ops Server release, therefore this service will exist at some point on a deployed Ops Server, so I will close this issue. Thank you.
