### ISSUE TITLE
Current Operations (MultiDisplay) (Operations View) item has issues

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#1574]
Current Operations (MutliDisplay) (Operations View) owned by Demonstration: 59ec3b3e65f344f2922c6f68eaf0c142
* [ ] No description
* [ ] No credits
* [ ] No summary
* Opening item downloads Operations Dashboard, Sign in to TEM2016, message pops up in Ops Dashboard "Warning. The following data sources are not accessible <empty list>".
* Operations Dashboard is open and can interact with some of the stuff on the map. Not sure what to expect here.

**Comment by elinz** [comment]
@mfunk For items owned by Demonstration, we really aren't worried about the description, credits and summary. As far as the error "The following data sources are not accessible", this ops view references the service Military/AirC2_MilitaryAirTracks/MapServer which has to be published manually by users. Instructions for publishing this service are being written and will be provided in the Ops Server release, therefore this service will exist at some point on a deployed Ops Server, so I will close this issue. Thanks.
