### ISSUE TITLE
Current Operations (Beta) (Web Mapping Application) item has issues

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#1575]
Current Operations (Beta) (Web Mapping Application) owned by Demonstration: 7a6d842a52cd4dedb5a6b9141cd6ff5a
* [ ] No description
* [ ] No credits
* [ ] No summary
* Opens Web App Ops View, click around and stuff seems to work.

**Comment by elinz** [comment]
@mfunk For items owned by Demonstration, we really aren't worried about the description, credits and summary. I will close this issue. Thank you.
