### ISSUE TITLE
Error for portal item: Maritime Contacts Web Map for Geoform or ArcGIS for Collector

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1577]
The following portal item (id=45a50df9d8554cec99d3b4e1101f1624) has a layer that does not load.  

![image](https://cloud.githubusercontent.com/assets/5116835/18726931/71ff69ee-7ffb-11e6-93fc-5174263ac87b.png)

**Comment by ACueva** [comment]
Maritime Boundary and Shipping Fairways, Lanes, and Zones layers point to Feature Service layers that do not exit.  This issue transferred over from our production environment.

**Comment by elinz** [comment]
@NatalieCampos @ACueva The service Military/MaritimeBoundaries/FeatureServer does exist however the web map references layer 28 (Maritime Boundary) and layer 39 (Shipping Fairways, Lanes, and Zones) do not. 

Shipping Fairways, Lanes, and Zones is layer 0
Maritime Boundaries is layer 1

Let me see if I can edit the json file for this data in the released set of files.

**Comment by elinz** [comment]
layer 28 (Maritime Boundary) -> layer 1
layer 39 (Shipping Fairways, Lanes, and Zones) -> layer 0

**Comment by elinz** [comment]
@NatalieCampos @ACueva On the production portal I edited the webmap json to correct the feature service layer ids and then extracted the item and integrated the item files into the final release. I also edited the webmap json on the test portal to simulate how the corrected item will behavior. Closing this issue.

FYI @jfrygeo I think the service must have been republished with a different layer order.
