### ISSUE TITLE
Error: Maritime Chart Service Application does not load

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1579]
The following web application does not load (id=c6678443d0644be19408f16fa73a7e04)

**Comment by ACueva** [comment]
Verified as bug.  This item is looking for an application on another internal server that does not exist.

**Comment by ACueva** [comment]
@elinz How do you want to handle broken items?  Delete them, leave them?

**Comment by elinz** [comment]
@NatalieCampos @ACueva I believe this is an external service to host the host, that I think is just currently down. This is not an issue we have to fix. Closing this issue.
