### ISSUE TITLE
Error: Video Widget Addin is unable to download or open

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#1580]
The video widget addin is unusable.  Portal item(id=39138693205c4817a582597eaf70d525)

![image](https://cloud.githubusercontent.com/assets/5116835/18727975/13c9e58e-8000-11e6-8c1e-5292bfcf55fc.png)

**Comment by ACueva** [comment]
Same behaviour exists on internal production environment.  If you click on:

> Source code posted here.

It gives you the option to download the source code.
