### ISSUE TITLE
Predictive Analysis Tools on ArcGIS.com is listed as Web App

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#177]
The Predictive Analysis Tools on ArcGIS.com are listed as a Web Mapping Application under Arcgisonline_defense:
http://www.arcgis.com/home/item.html?id=90d9d9e8bb9e4228b75ec73ea394f5e4

It should be of type Document Link. Assigned to @ACueva to fix at next update.

**Comment by conklinbd** [comment]
I am removing from this milestone. This issue should also be logged for the solution website, instead of the Ops Server.
