### ISSUE TITLE
Canvas and Imagery Basemap need to have 2 layers

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#181]
Both the Canvas Basemap and the Imagery with Reference Overlay basemaps should have 2 layers. They should have an overview layer and a base layer. There are several utilities to make these basemaps.

**Comment by nfeuerstein** [comment]
Completed on nsec: https://nsec.esri.com/arcgis/home/item.html?id=f16515ad822b4f20810633969f4eb6ef and https://nsec.esri.com/arcgis/home/item.html?id=c404e47e4d8a4cabb2896ecff89829f1
