### ISSUE TITLE
Remove SolutionsWeb Applications that are no longer needed

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#284]
Currently there are web applications in the c:\inetpub\wwwroot\SolutionsWeb\Apps folder that should no longer be accessed using the direct URL to the application. i.e. http://hostname/SolutionsWeb/Apps/Templates/StoryTellingAccordion/

We need to find these deprecated items and not include them in future releases.

**Comment by conklinbd** [comment]
I am closing this issue since it is not valid for the new dev server..
