### ISSUE TITLE
Add a geocode service

### ISSUE THREAD

**Issue by jeffbaranyi** [Esri/ops-server-config#367]
Geocoding is a critical task for Emergency Management agencies.  They need to locate things by address all the time (shelters, resources, incidents, etc).  Can we get a geocode service added to the ops-server post TEM?  We should be able to get data from Virginia and/or Esri Data and Maps.

**Comment by conklinbd** [comment]
@nfeuerstein  this is resolved correct?

**Comment by nfeuerstein** [comment]
We have place names (GNIS Name), MGRS, and Long/Lat geocode services on NSEC, thus far.  Still need an address geocode service (aside from the Esri World Geocoder).

**Comment by conklinbd** [comment]
The Address based locator does not need to be fixed for this release. I am closing this issue and we will open a new one for incorporating the community address locator if the EM team is unable to do it for this release (it is in their plans).
