### ISSUE TITLE
Geoevent adapters missing

### ISSUE THREAD

**Issue by richgale** [Esri/ops-server-config#497]
Missing adapters causing issues with "inputs"

AFM_UDP_In
Status: Error - Stopping Stream 'AFM_UDP_In' because the Adapter is not available.

buoy-regexText-in
Status: Error - Stopping Stream 'buoy-regexText-in' because the Adapter is not available.

metar-regexText-in
Status: Error - Stopping Stream 'metar-regexText-in' because the Adapter is not available.

twitter-in
Status: Error - Stopping Stream 'twitter-in' because the Adapter is not available.,Stopping Stream 'twitter-in' because the Transport is not available.

SeismicEventsIn
Status: Error - Address already in use : Bind

symbolid-tcp-text-in
Status: Error - Address already in use : Bind

**Comment by iamlaksh1** [comment]
@pHill5136  - I am facing similar adapters missing issue on Azure event hub connectors. Any clue to debug/fix?
