### ISSUE TITLE
LandOps demo content folder structure confusing

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#508]
Recommend not zipping up files for individual demos as it causes a lot of sub-folders.

**Comment by jrweakland** [comment]
@lfunkhouser - this is a consistency issue in my opinion.

**Comment by elinz** [comment]
@jrweakland Why is this assigned to the Release Team? Isn't this an issue for the product teams to define the demo folder structure and ensure demos are structured based on the define structure? Thanks.

**Comment by jrweakland** [comment]
@elinz - It would be better for the Release Team to define the folder structure and have the content teams place the content in the correct folders. This would assist the international distributors with locating content.

**Comment by ScottCecilio** [comment]
I have redesigned this presentation and have organized the folders to be more clear. Request this be closed.

**Comment by conklinbd** [comment]
Closed
