### ISSUE TITLE
Duplicate files in LandOps "3 Planning" demo

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#520]
\\disldb\DemoAndScripts\LandOps\Demo Folders\3 Planning contains "a ArcGIS Pro.zip" file. Extracting a find

Duplicates and temp folder of "Range Dome Analysis" and thumbnails in a ArcGIS Pro\a ArcGIS Pro\Index folder; in C:\BackupNo\a ArcGIS Pro\a ArcGIS Pro\data\Index.

Find duplicate files of "GeoINT_Import.xml" _1.xml and _2.xml.

Not a complete list of issues, just happened to extract and poke around.

The RangeDomeAnalysis.gdb is 2 GB. Do we really need this amount of data?

**Comment by ScottCecilio** [comment]
I have removed the old Pro presentation from the \disldb\DemoAndScripts\LandOps\Demo Folders\3 Planning folder location.  I have replaced it with the updated Pro demo that was used at FedGIS 2015 (\\disldb\DemoAndScripts\LandOps\3 Planning\Intelligence_Analysis).  This is more of a quick fix as this demo has everything the previous one had but is built to be focused around the Intelligence Analysis section.  I will be updating the entire Land Operations demonstration come the next release of OpsServer around the TEM.
