### ISSUE TITLE
Demo and scripts - Folders for templates require numbering

### ISSUE THREAD

**Issue by richgale** [Esri/ops-server-config#522]
Similar to LandOps, the following folders need to have the same structure. Each template or demo needs to have a number assigned to it (i.e. 1 Opertional Environment, 2 Intelligence Analysis, etc..)  
This will help ordering, referencing the content from script and finding the relevant item.  

DomOps:
EmergencyManagement:
Intel:
LawEnforcement:
MaritimeOps:

**Comment by jrweakland** [comment]
@joebayles @nfeuerstein @lfunkhouser - I would like to meet about this issue.

**Comment by conklinbd** [comment]
@jrweakland and @lfunkhouser I have added this to our product owner meeting agenda. We don't need an issue to track this, since we are changing the packaging for this content for next release.
