### ISSUE TITLE
Land Ops - Include script/demos from USMC presentation?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#527]
I know this is last mniute, but is it possible to include the demos or at least the script used for the USMC presentation on the TEM disk? (the demos Lyle showed at the Sprint Review on Friday)

If we can at least include the script so others can understand a good workflow to use that would be great.

**Comment by jrweakland** [comment]
This demonstration is being updated for the 2015 FedGIS and did not make the cutoff for the 2014 Q4 Ops Server release.
