### ISSUE TITLE
The Richmond Imagery Map Service is not caching on demand

### ISSUE THREAD

**Issue by jeffbaranyi** [Esri/ops-server-config#552]
For https://afmiedev.esri.com/arcgis/home/item.html?id=f78aa7ec24e148e58ef7cfcc27cafed5

It doesn't seem to be caching on demand now.  This was working yesterday.  We didn't cache all the way down to 1:1000 figuring we could build up cache in the areas we need it.  I think the right settings are applied but its not working.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
