### ISSUE TITLE
Image Observables web app does not reference local geometry and printTask services

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#560]
@nfeuerstein Note: milestone set for next Ops Server release.

The commonConfig.js file located under \\afmiedev\SolutionsWeb\Apps\Templates\ImageObservables references arcgisonline geometry and printTask services. The Ops Server does have these services so we should reference the Ops Server services.

Until we have a world geocode service on Ops Server #367, you can still reference external service.

**Comment by nfeuerstein** [comment]
Does not apply to NSEC.  Closing.
