### ISSUE TITLE
Iranian Election Violence web app does not reference local geometry service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#561]
@nfeuerstein Note: milestone set for next Ops Server release.

The index.html file located under \\afmiedev\SolutionsWeb\Apps\IranianElectionViolence references arcgisonline geometry service. The Ops Server does have this service so we should reference the Ops Server service.

**Comment by nfeuerstein** [comment]
Does not apply to NSEC.  Closing.
