### ISSUE TITLE
Remove backup copy of Roads (Infrastructure.sde\RoadNetworkFD\Roads_original)

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#563]
Looks like this feature class isn't needed, as the RoadNet network dataset uses the Roads and RoadNet_Junctions feature classes. Delete the Roads_original feature class.

I will be deleting the Road_original feature class in the extracted file geodatabase.

**Comment by conklinbd** [comment]
I am closing this issue since it is not valid for the new geography.
