### ISSUE TITLE
CopyData.py not copying all datasets in CurrentOperations.sde\InternallyDisplacedPersons FeatureDataset

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#565]
Here are the contents of the SDE feature dataset...
![image](https://cloud.githubusercontent.com/assets/4635490/4579728/a46376f4-4fcf-11e4-8288-b9c2e90efe74.png)

Here are the contents of the extract file geodatabase feature dataset...
![image](https://cloud.githubusercontent.com/assets/4635490/4579741/c2a95976-4fcf-11e4-9d85-f18ade66f5bf.png)

For now I'll have to manually copy this feature dataset from the SDE database.Double-check after executing the CopyData.py script to copy from distribution fgdbs to enterprise on Ops Server if this feature dataset is fully copied; if not I will have to investigate the issue for this milestone.

**Comment by conklinbd** [comment]
I am closing this issue since it is not valid for the new geography.
