### ISSUE TITLE
Shelters item text needs edits

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#569]
The Shelters item (https://afmiedev.esri.com/arcgis/home/item.html?id=992c302826c04408906c26cdcb5a1863) text needs edits.

Summary:
Spreadsheet of shelters to be opened in the event of an emergency at the Richmond International Raceway. Mapped using the Esri Maps for Office add-in for Microsoft Excel.
Description:
Spreadsheet of shelters to be opened in the event of an emergency at Richmond International Raceway. Shelters have been mapped using the Esri Maps for Office add-in for Microsoft Excel.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
