### ISSUE TITLE
Shelter Routing item text needs edits

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#570]
The Shelter Routing (https://afmiedev.esri.com/arcgis/home/item.html?id=1bd245336a0c46f681abb747c4937637) text needs edits.

Summary
Web map for National Security Demo that illustrates how to use the "Find Nearest" online analysis service.  
Description
Web map for the National Security Demo that illustrates how to use the "Find Nearest" online analysis service.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
