### ISSUE TITLE
Incident Planning for Richmond International Raceway September Race item needs edits

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#571]
The Incident Planning for Richmond International Raceway September Race (https://afmiedev.esri.com/arcgis/home/item.html?id=3169470f687e424daf81d6cb2f439df3) portal item text needs edits.

Description:
A Briefing Book for Command to use when briefing emergency response personnel and for Incident Planning for Richmond International Raceway September Race.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
