### ISSUE TITLE
Typo in Title Page of Incident Planning for Richmond International Raceway September Race 

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#572]
The Incident Planning for Richmond International Raceway September Race Briefing Book (https://afmiedev.esri.com/SolutionsWeb/Apps/Templates/BriefingBook/?bookId=3169470f687e424daf81d6cb2f439df3) has a typo on the subtitle of the Title page.
"Septemer" should be "September".

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
