### ISSUE TITLE
Raceway Information Map for Fans portal item text needs update

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#573]
The Raceway Information Map for Fans portal item (https://afmiedev.esri.com/arcgis/home/item.html?id=f186df709cf445bc9da71d452ffbc46a) text needs update
Summary:
A Mapping Application to assist fans to find amenities and navigate the raceway complex on race day! Part of National Security demo.  
Description:
A Mapping Application to assist fans to find amenities and navigate the raceway complex on race day! Part of National Security demo.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
