### ISSUE TITLE
Raceday Operations Dashboard text needs update

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#574]
The Raceday Operations Dashboard portal item (https://afmiedev.esri.com/arcgis/home/item.html?id=18d3a5d24d8c4028854a45a9ed4e10f2) text needs to be updated.
Summary:
An Operations Dashboard for Fire/Rescue to use when managing incidents on race day.
Description:
An Operations Dashboard for Fire/Rescue to use when managing incidents on race day.

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
