### ISSUE TITLE
Raceway Operations Dashboard source data has "Amphitheatre" misspelled

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#575]
The Raceway Operations Dashboard source data has "Amphitheatre" misspelled as "Ampitheatre", this shows up in one of the “Incidents” shown in the Raceway Operations Dashboard. It is in the “Full Address” field, which makes me suspect that it is also misspelled in the geocoding reference data feature service/feature class..

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
