### ISSUE TITLE
Raceday Operations Dashboard - Mobile portal item text needs update

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#576]
The Raceday Operations Dashboard - Mobile (https://afmiedev.esri.com/arcgis/home/item.html?id=84e6f39a706e440983a97f1fad98cc9a) portal item text needs update:

Summary:
A Mobile Operations Dashboard for Fire/Rescue to use when managing incidents on race day.

Description:
A Mobile Operations Dashboard for Fire/Rescue to use when managing incidents on race day.
The title of the item should also be changed to "Race Day Operations Dashboard - Mobile "

**Comment by conklinbd** [comment]
Since we will recreate this content on NSEC, I am closing this issue.
