### ISSUE TITLE
Strikegroup Post-Deployment Report has a broken link

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#589]
@jfrygeo: @karlterrey discovered a broken link pointing to https://dtcrugmo05.esri.com/SolutionsWeb/Resources/NavyCCIR/KiloSub.html
![10-13-2014 9-42-35 am](https://cloud.githubusercontent.com/assets/3093940/4616861/fb902672-52f7-11e4-9121-c6e2c3b99496.png)

**Comment by ACueva** [comment]
Have no idea why it shows this unassigned by me.  Reassigning back to John.

**Comment by jfrygeo** [comment]
Try to create a new service to fix this issue but encountering issues. #597

**Comment by jrweakland** [comment]
@jfrygeo - please verify and close if appropriate. Added to backlog: https://app.asana.com/0/23169951437136/31304190918348

**Comment by conklinbd** [comment]
This is OBE for the new geography so I am closing.
