### ISSUE TITLE
Failed to publish service to afmiedev.esri.com

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#597]
When trying to resolve the github issue #589 by republishing the service I am getting an error that "the server's publishing job didn't succeed. 
![publish1](https://cloud.githubusercontent.com/assets/5074686/4629572/b5bcf9fa-53a5-11e4-86b9-a265f8954ecf.JPG)

![publish](https://cloud.githubusercontent.com/assets/5074686/4629510/0bf4e860-53a5-11e4-80e0-d51a7257df26.JPG)

Received this error 10/13/14 prior to restart of AGS and after. Tried to publish a new service and received the same error.

**Comment by jfrygeo** [comment]
@elinz . Tried to create a new service with a different name and received errors. 

![ccirafmiedev](https://cloud.githubusercontent.com/assets/5074686/6232486/454f7d20-b69a-11e4-951f-dcf3f50ddcd2.PNG)

**Comment by elinz** [comment]
@jfrygeo The managed database (ArcGIS Data Store) wasn't validating. I stopped and restarted the data store and now it validates. Try republishing now.
