### ISSUE TITLE
Storytelling apps on Try-It Live have incorrect urls for javascript resources

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#599]
For some reason the Try It live version of almost all of our apps have the incorrect urls for the css resources. 

These are incorrect for multiple reasons. They point to wrong location and they are not protocol neutral.

http://land-ops.maps.arcgis.com/home/js/dojo/dijit/themes/tundra/tundra.css
http://land-ops.maps.arcgis.com/home/js/esri/css/esri.css

//js.arcgis.com/3.8/js/dojo/dijit/themes/tundra/tundra.css
//js.arcgis.com/3.8/js/esri/css/esri.css

**Comment by ACueva** [comment]
This was the reason:
http://blogs.esri.com/esri/arcgis/2014/10/06/arcgis-api-for-javascript-version-3-11-released/
