### ISSUE TITLE
Range Fans By Feature tool needs inputs that are not packaged with the template

### ISSUE THREAD

**Issue by dfoll** [Esri/ops-server-config#617]
Range Fans By Feature tool needs inputs that are not packaged with the template

Open the tool, select an input, but nothing that is packaged with the template that can be used as input centers has the appropriate fields for this tool. 

![image](https://cloud.githubusercontent.com/assets/5322669/4653464/124366e2-54ae-11e4-890d-07e4af2ad886.png)

![image](https://cloud.githubusercontent.com/assets/5322669/4653473/2886c4e4-54ae-11e4-92ae-4adc4a8938dd.png)

**Comment by joebayles** [comment]
This issue was moved to ArcGIS/solutions-templates#8
