### ISSUE TITLE
Data Store can't be created by Ops Server installer

### ISSUE THREAD

**Issue by garys-esri** [Esri/ops-server-config#628]
Run through the Ops Server installer through the step where an ArcGIS Data Store is supposed to be created. Use an admin user, and Run As Administrator. The Data Store is not created, and an error message is printed:

> Error encountered: Current user doesn't have permission to perform this task. Please retry as the data store owner or Windows Administrator. If you are already member of Windows Administrators group, please try "Run as Administrator".

Instead, the Data Store should be created and no error message should appear.

**Comment by elinz** [comment]
@garys-esri Can't replicate issue. This may have been an issue in earlier builds if the OS account was not explicitly a member of the local administrators group. Recommend this issue be closed; if issue is encountered again we can reopen.

**Comment by garys-esri** [comment]
I haven't gone through the Ops Server install in ages, so I couldn't tell you if the issue still exists. If you're not seeing it, then most likely it was either a special case on the machine I used or an issue that was resolved in a subsequent build. I'm fine if you close this issue.

**Comment by elinz** [comment]
Thanks @garys-esri I will close the issue.
