### ISSUE TITLE
Ops Server install guide: highlight when it's necessary to follow instructions in command prompt

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#630]
Make it really obvious when instructions need to be followed in the command prompt.   i.e. big red letters.

**Comment by conklinbd** [comment]
@elinz do you plan to address this release or should we move to next?

**Comment by elinz** [comment]
@conklinbd @kerryrobinson I made the changes to the install guide first thing this morning. I have been making some other changes to the doc so I haven't check in the changes and closed the issue yet; which I will do today.

**Comment by elinz** [comment]
Fixed in Esri\ops-server-config v.next. Closing issue.

**Comment by kerryrobinson** [comment]
Wait, don't i need to verify before closing as per Chris' email?  I'll review the doc now.

**Comment by elinz** [comment]
@kerryrobinson I was debating on this. Unless the fix is trivial then you don't have to reassign. I thought it was trival. But I will reopen and assign to you to verify.

**Comment by elinz** [comment]
@kerryrobinson to verify.

**Comment by kerryrobinson** [comment]
@elinz no problem.  I've just checked the doc and I endorse your closing.  I didn't know about the 'trivial' clause.    

Closing issue.

**Comment by csmoore** [comment]
Sorry - I missed this in the flood of notifications....trivial is somewhat subjective so I apologize ...but is meant to mean a really small/simple/easy-to-see change ( ex: a one-line change in a web readme.md ) and before you close you should still try to paste in a screenshot or easily viewable link so it is immediately obvious to the originator - so they don't need to go finding/downloading a binary file (ex: gdb/word doc/etc.) just to see the change.

Github tip for those who may not have noticed this - you can easily paste screenshots/images directly into issues with menu copy/paste (or short cut: apple/ctrl-v)
