### ISSUE TITLE
Feature services aren't updated by GeoEvent Extension

### ISSUE THREAD

**Issue by garys-esri** [Esri/ops-server-config#632]
I'm following the 2014 Q4 Ops Server installation guide. I'm on page 46 (marked as page 45) and trying to verify that the GeoEvent Extension is updating feature services. It is not updating them. The simulators are running, and the GeoEvent Extension manager page is showing inputs and outputs on the services, but neither the Operations/FriendlyOperations service nor the Operations/FriendlySituation services has any features in it. I checked the logs for GeoEvent Extension and ArcGIS for Server and couldn't find any clues when running just the FriendlyOperations simulator. I don't understand why GeoEvent Extension would say it is writing outputs if those outputs are not actually written to the feature service.

**Comment by yehiahassan** [comment]
@pHill5136 my system has a really high specs where restarting the server and reaching the point where all outputs are in stopped state takes about 5-10 minutes, and I start the output connectors manually and it turns green successfully; so, I don't have a problem in this regards despite that I have to start them manually every restart time.

As of stopping the connectors update after a while, I also don't have this problem.

My problem is restarting the windows service for GeoEvent which would be either manually or by restarting the machine will directly stops output connectors updates despite that it showing green live status and this is for all update feature connectors; recreating the connector solves with the same parameters solves the problem till the next GeoEvent service restart, where I'll have to re-create the connector again.

**Comment by pHill5136** [comment]
I haven't not noticed that in my environment yet, but I suspect that it is related to the other issues we have been having.  I will attempt to replicate this today.  We have one of the GEE developers working on these issues and we have given him full access to our servers to diagnose (so far that has been the biggest impediment to troubleshooting the issue).

One thing from your side that may help is if you post this issue to the sp-geoevent alias.  If the GEE developers -who watch the alias pretty closely -  see that other people are having the same issues, it might expedite a solution.

-Patrick

**Comment by jrweakland** [comment]
@pHill5136 - added to the backlog: https://app.asana.com/0/22926133759983/31304190918340

**Comment by conklinbd** [comment]
This was resolved with the GEE Patch. Closing and updating Asana.
