### ISSUE TITLE
Install Guide- Post Copy Ops Server Data procedures: Prompt user to install Desktop & spelling error

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#636]
The Post Copy Ops Server Data procedures step (page 22) involves copying a Feature Class and Feature Dataset, so ArcGIS Desktop is required.  

- [ ] Prompt the user to install ArcGIS Desktop before the Post Copy Ops Server Data Procedures step.

- [ ] Also "InternallyDisplayedPersons" should be changed to "InternallyDisplacedPersons"

**Comment by elinz** [comment]
@kerryrobinson at least so far, for the Fall 2015 release, it looks like we won't need to perform any Post-copy data procedures.

**Comment by conklinbd** [comment]
In this case I think we can close this issue.

**Comment by kerryrobinson** [comment]
I'd like to confirm this in the latest install gide before closing.

**Comment by elinz** [comment]
@kerryrobinson @conklinbd I'll be confirming whether we need to perform any Post-copy data procedures during the stabilization and testing phases the next couple of weeks.

**Comment by elinz** [comment]
@kerryrobinson @conklinbd This step is not necessary with this release. I've removed this section from the installation guide.

**Comment by elinz** [comment]
Fixed in Esri\ops-server-config v.next. Closing issue.
