### ISSUE TITLE
Japanese installation - Web Adaptor - ArcGIS Server admin disabled

### ISSUE THREAD

**Issue by cpitman-gis** [Esri/ops-server-config#653]
Not sure if this is intentional,

When running InstallOpsServer.bat, the WebAdaptor for "ags" (ArcGIS Server 10.3 final) does not have admin enabled. 

This means the tests that people installing after this script don't quite work.

This was fixed manually afterwards, by reconfiguring the webadaptor for "ags".

**Comment by conklinbd** [comment]
Since we can't reproduce on English Locale we are not going to fix.
