### ISSUE TITLE
Simulation files need to be reviewed prior to moving to the NSEC GEE server

### ISSUE THREAD

**Issue by jrweakland** [Esri/ops-server-config#683]
@elinz copied a new build of the Message Simulator exe to the NSECGEE server (i.e. C:\MessageSimulator\MessageSimulator). He also created the OS Scheduled task and left it in a disabled state. He didn’t copy over any of the message files from the last Ops Server release, because he wanted someone to review all the files before we deploy message files to the new geography GEE server (NSECGEE), but everything else for the Message Simulator is now on the server.

**Comment by jrweakland** [comment]
@pHill5136 - added to backlog: https://app.asana.com/0/22926133759983/31304190918338

**Comment by jrweakland** [comment]
@pHill5136 - has the been any movement on this issue?

**Comment by conklinbd** [comment]
@pHill5136 My impression is that this issue is resolved.

**Comment by jrweakland** [comment]
:+1: Agreed.

**Comment by pHill5136** [comment]
@ScottCecilio  reviewed the land ops sim files for friendly equipment and hostile equipment over monterey airport area.
