### ISSUE TITLE
SPOTREPs not being updated... missing GEE service?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#696]
I was looking into why SPOT reports weren't being updated. This seems unrelated to the other issue with features being updated by GEE (#632).  

I see the the SPOTREPAdd output in GEE, but no Service to go with it. I notice the same thing on AFMIEDEVGEP.esri.com, so it's not an issue with the OpsServer install. 

So either there is a service using the SPOTREPAdd which is broken, or we need to add back in the LO_SPOTREP  service.  (or it was removed for a reason?)

**Comment by jrweakland** [comment]
@pHill5136 - added to the backlog at: https://app.asana.com/0/22926133759983/31304190918335

**Comment by conklinbd** [comment]
This is no longer valid with the move to the new geography.
