### ISSUE TITLE
GEE:  Geofences need to be updated and re-syncronized after OpsServer Install

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#697]
I just realized that none of my geofences were syncronized with the server. I had to go into each one and double check the values (some of them were pointing to the wrong feature class), and then synchronize each one.

Now i can use them to recreate the geofence processing that is missing  from some of the services (Sensor Tracks, SPOT REP, maybe others).

I notice that none of the geofences are syncrhonized on AFMIEDEVGEP either.

**Comment by jrweakland** [comment]
@kerryrobinson - could you please send @pHill5136 the old 10.2.2 config file?

**Comment by kerryrobinson** [comment]
I sent this to @pHill5136 on January 13th, responding to this thread.

**Comment by conklinbd** [comment]
This was caused by an issue resolved in the GEE patch. We will be recreateing the Geofences for the new geography so closing this issue.
