### ISSUE TITLE
Released Strike Group Post Deployment Report Application - unavailable

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#699]
http://www.arcgis.com/home/item.html?id=f04a074c702348a7919289bc38252cde

**Comment by jfrygeo** [comment]
http://esrifederal.maps.arcgis.com/home/item.html?id=f04a074c702348a7919289bc38252cde

**Comment by conklinbd** [comment]
@ACueva Same with this one.

**Comment by ACueva** [comment]
Fixed issue of item pointing to afmcloud and not arcgis.com org.
