### ISSUE TITLE
changing the basemaps cause the basemap to zooms out to full extent 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#702]
Changing the basemaps when zoomed in causes the portal map viewer to zooms out to full extent of the new basemap.  This behavior is seen in the following basemap:
-oceans
- imagery
- streets
- terrain
- topo

**Comment by conklinbd** [comment]
Ask the SP alias or support to see if they know the cause. Also look at the "extent" for those basemaps and compare it to the ones where the zoom doesn't happen.

**Comment by NatalieCampos** [comment]
The extent for the Imagey, Streets, Terrain, Oceans, and Topo basemap has been fixed.  Basemaps no longer zoom out when a different basemap has been changed.

**Comment by conklinbd** [comment]
:+1:
