### ISSUE TITLE
Change Detection:  PreProcessing- Set up template and explore your data

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#703]
1.	 Step 1 gives the following error. 
 
![image](https://cloud.githubusercontent.com/assets/5116835/5884135/51c6c580-a30e-11e4-8e89-f68f82f240dd.png)

**Comment by csmoore** [comment]
Sounds like this (and all the issues from #703 - #718 ) might be the result of just the initial/sanity/configuration test - we might want to do a first sanity pass using an alternate method - like a text/word doc or combine into a single issue.

But a tip for everyone doing templates - if possible, try to sanity test your Pro template project deployment **on a second machine** before handing off to testing. We have seen a lot of deployment issues (such as hardcoded Pro project settings, other unexpected configurations after unpackaging, etc.) that you don't necessarily catch if you open the .ppkx on the same machine.

**Comment by helyx-amcmillan** [comment]
Tested on two machines before it was sent for testing and this worked - Step one should just be some text with a 'next step' button so not sure how this can not work, step two the same, step 3 should automatically open the pre-processing map, and step 4 should just open an 'add data' dialogue box. Have changed step 4 to a manual 'add data' step based on testing. 

As a wider point it looks like your task file may be pointing back to an older version. Have also re-referenced the toolbox again this morning, re-tested on three machines and seems to work. But still not convinced I've completely got to the bottom of it.

**Comment by NatalieCampos** [comment]
Error is no longer present.
