### ISSUE TITLE
Change Detection: Calibrate Imagery 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#704]
Step 1. Calibrate imagery throws the following error.  Previous version the "tool failed" description was  red.  This needs to be cleaned up and reference to that tool removed.  
![image](https://cloud.githubusercontent.com/assets/5116835/5884322/bfe7fe6a-a310-11e4-93a7-831e078f8123.png)
r.

**Comment by helyx-amcmillan** [comment]
Tested on two different machines and worked before sent for testing - the task file should reference tools and scripts that are embedded within the project - not sure why this is still referencing back to there. Have recreated the toolbox and re-pointed references again to see if it re-emerges. tested on three different machines and seems to work.

**Comment by NatalieCampos** [comment]
Calibrate Imagery tool fails when run from tasks.  
 Start Time: Thu Jan 29 11:20:08 2015
Running script DNtoReflectance...
Failed script DNtoReflectance...
Traceback (most recent call last):  File "C:\Users\nata7004\Documents\ArcGIS\Packages\ChangeDetectionProject\p1\ChangeDetectionTools.tbx#DNtoReflectance_ChangeDetection.py", line 12, in <module>ImportError: No module named 'DNtoReflectance'
Failed to execute (DNtoReflectance).
Failed at Thu Jan 29 11:20:08 2015 (Elapsed Time: 0.01 seconds)
3.	Tool also fails when run from Project Folder.
Start Time: Thu Jan 29 12:54:29 2015
Running script DNtoReflectance...
Failed script DNtoReflectance...
Traceback (most recent call last):  File "C:\Users\nata7004\Documents\ArcGIS\Packages\ChangeDetectionProject\p1\ChangeDetectionTools.tbx#DNtoReflectance_ChangeDetection.py", line 12, in <module>ImportError: No module named 'DNtoReflectance'
Failed to execute (DNtoReflectance).
Failed at Thu Jan 29 12:54:29 2015 (Elapsed Time: 0.01 seconds)

**Comment by helyx-amcmillan** [comment]
Ok so this is because if you design the toolbox with embedded scripts, the referenced scripts don't get packaged with the project. Have taken out embedded scripts, and put back in a reference to the tools within the folder. We were having some issues with this method before though so need to test again.

**Comment by helyx-amcmillan** [comment]
Just tested - now it's going back to an old bug. When I try to package the project, it tries to create a file that is >2GB in size and then fails. Absolutely no idea why this is. All I have changed is the reference in the tool to the script.

**Comment by helyx-amcmillan** [comment]
We've traced this back to a hard coded path in one of the scripts. The package seemed to follow this path and try to package up all associated data in the folder. One to watch out for!

**Comment by NatalieCampos** [comment]
Tool runs as expected on most recent build test2.ppk.  Whatever was done to get this tool to run needs to be maintained in further iterations of the project so as to not have to constantly revisit and test each piece.
