### ISSUE TITLE
Change Detection:  Cloud mask imagery

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#705]
Step 1.  There is an error upon opening.  This step was skipped. 
![image](https://cloud.githubusercontent.com/assets/5116835/5884410/e0450044-a311-11e4-8546-002a246bbe07.png)

**Comment by NatalieCampos** [comment]
**ACCA cloud masking tool fails.**  
Start Time: Thu Jan 29 14:12:26 2015
Running script ACCACloudMask...
Failed script ACCACloudMask...
Traceback (most recent call last):  File "C:\Users\nata7004\Documents\ArcGIS\Packages\ChangeDetectionProject\p1\ChangeDetectionTools.tbx#ACCACloudMask_ChangeDetection.py", line 38, in <module>ImportError: No module named 'ACCACloudDetector'
Failed to execute (ACCACloudMask).
Failed at Thu Jan 29 14:12:26 2015 (Elapsed Time: 0.17 seconds)
**ACCA cloud masking tool fails from project folder.** 
Start Time: Thu Jan 29 14:16:47 2015
Running script ACCACloudMask...
Failed script ACCACloudMask...
Traceback (most recent call last):  File "C:\Users\nata7004\Documents\ArcGIS\Packages\ChangeDetectionProject\p1\ChangeDetectionTools.tbx#ACCACloudMask_ChangeDetection.py", line 38, in <module>ImportError: No module named 'ACCACloudDetector'
Failed to execute (ACCACloudMask).
Failed at Thu Jan 29 14:16:47 2015 (Elapsed Time: 0.15 seconds)

**Comment by helyx-amcmillan** [comment]
Same as Landsat DN to Reflectance - if you design the toolbox with embedded scripts, the referenced scripts don't get packaged with the project. Have taken out embedded scripts, and put back in a reference to the tools within the folder. We were having some issues with this method before though so need to test again.

**Comment by NatalieCampos** [comment]
The tool fails still in most recent build test2.ppk.  Tool fails when called from tasks but works when separately run from the tool box.  Below is the error when the tool is called from tasks.  

Start Time: Fri Jan 30 10:51:41 2015
Running script ACCACloudMask...
Reflectance Calculated for Band 2
Reflectance Calculated for Band 3
Reflectance Calculated for Band 4
Reflectance Calculated for Band 5
Reflectance Calculated for Band 6
Creating Gap Mask
First pass underway
Failed script ACCACloudMask...
Traceback (most recent call last):
  File "C:\Users\nata7004\Documents\ArcGIS\Packages\test2\p1\ACCACloudDetector_ArcInterface.py", line 79, in <module>
    Filter6Thresh)
  File "C:\Users\nata7004\Documents\ArcGIS\Packages\test2\p1\ACCACloudDetector.py", line 243, in ACCACloudDetector
    TempMin=Band6clouds.min()
  File "c:\program files\arcgis pro\bin\Python\lib\site-packages

**Comment by helyx-amcmillan** [comment]
Haven't been able to replicate this one - ours runs every time from both tasks and tools. Need to have a look with screen sharing possibly?

**Comment by NatalieCampos** [comment]
Anneley
Can you send me a meeting invite?  I can get on early in the morning (my time) so we can work through this issue.  Have you tested it on a different computer to see if it is a packaging problem?

**Comment by helyx-amcmillan** [comment]
I get a similar error to you if I put in TOA Reflectance bands as the input (say LT50220392005250GNC01_B1_TOA_Reflectance.tif), but then classify the data type as Digital Numbers (This should be Reflectance). Is it possible that the input bands did not match the data type selection when you were running it through the task?

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#21
