### ISSUE TITLE
Change Detection: Cloud masking imagery - Applying cloud mask

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#706]
Error upon opening step.  
![image](https://cloud.githubusercontent.com/assets/5116835/5884439/44fa584a-a312-11e4-9be2-3433c4c64754.png)
Unknow what tool to run with the tool as none of the tools in the Landsat tool box correspond to the naming convention in the error or have a similar dialogue.  
![image](https://cloud.githubusercontent.com/assets/5116835/5884462/a1f56e04-a312-11e4-9ee9-0a94439a1d49.png)

**Comment by helyx-amcmillan** [comment]
Should be fixed

**Comment by NatalieCampos** [comment]
Unable to test/verify this step until ACCA cloud mask issue is resolved fixed.  Issue #705

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#20
