### ISSUE TITLE
Change detection: Landsat toolbox tools need tool decription

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#707]
The following tools need tool description

1.  ACCA Cloud Mask
2. Landsat 7 Gap Filler
3.  LTL Cloud Mask

**Comment by helyx-amcmillan** [comment]
Tool description written for ACCA cloud mask. Landsat 7 gap Filler and LTK Cloud Mask taken out of project as not referenced in task.

**Comment by NatalieCampos** [comment]
Tools in the pro project are still missing tool documentation.  See dialogs for each tool.  

Example 1.  
![image](https://cloud.githubusercontent.com/assets/5116835/5968130/fd9c0924-a7c8-11e4-9c37-a4819a933391.png)
Example2.  

![image](https://cloud.githubusercontent.com/assets/5116835/5968135/16e75d34-a7c9-11e4-9983-f09fa4a7344b.png)

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#19
