### ISSUE TITLE
Change Detection PIF tool does not run 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#710]
The PIF model does not run.  Attempted the same as above.  I tried calculating stats to get it to run and that didn’t work.  
![image](https://cloud.githubusercontent.com/assets/5116835/5885396/b856cd88-a320-11e4-9452-629b34db2c06.png)

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#17
