### ISSUE TITLE
Indices NDWI

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#712]
There is no NDWI raster function associated with this step.  
![image](https://cloud.githubusercontent.com/assets/5116835/5885525/df07f940-a323-11e4-9cb0-7cebd44f7b51.png)

**Comment by helyx-amcmillan** [comment]
it is in my project under the 'Project' category of raster functions. I wasn't aware that this didn't persist when packaged - What is the best way to save a raster function in with the project?

**Comment by NatalieCampos** [comment]
This is bug.  It has been logged.    When you create a new Pro project there is a 'Project' folder in the Raster Functions pane.  This would be location of where project specific raster functions should be store.  Note: you can also copy out of box raster functions like NDVI to this location.
![image](https://cloud.githubusercontent.com/assets/5116835/5949342/776395f6-a701-11e4-93f7-f27c6a757402.png)
When the project is packaged the Raster Function pane no longer has this folder.
![image](https://cloud.githubusercontent.com/assets/5116835/5949401/2fbbfb84-a702-11e4-9559-5f23d58b3a12.png)

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#16
