### ISSUE TITLE
Change detection: Iso cluster Step 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#714]
Unable to completet the Register step without previous steps added to tasks.  A link file needs to be previously created with directions.
![image](https://cloud.githubusercontent.com/assets/5116835/5890147/81219504-a402-11e4-982d-49c79b232dd3.png)

**Comment by helyx-amcmillan** [comment]
This is an optional field - It works for me without creating the link file. I think the link file is for images that are very separated from each other, which our images aren't.

**Comment by NatalieCampos** [comment]
Yes, the tool works for me.  I think directions would have helped so that the user would know that it is an optional step.  I looked into what the tool does and it puts a temp geotransformation on the input image.  The image is resampled in the process.  Because the two images used are already so closely aligned, I would (as the user) rather skip this step rather than have the image resampled.
