### ISSUE TITLE
Change Detection Maximum Likelihood Create Signatues step

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#715]
Unable to create the signatures in step 9.  I tried in both 10.3 and Pro.  Error is below.
![image](https://cloud.githubusercontent.com/assets/5116835/5890170/aa19c732-a403-11e4-9abd-e932e2d6a1c3.png)

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#15
