### ISSUE TITLE
Unable to create segmentation raster in MLC task

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#716]
Unable to create segmentation raster in MLC task.  
![image](https://cloud.githubusercontent.com/assets/5116835/5890176/fd174c48-a403-11e4-9f20-e5771b52d5d5.png)

**Comment by helyx-amcmillan** [comment]
This step has been taken out because it is only an input to the 'train ML Classifier' tool which itself has been removed. The 'train ML Classifier' tool cannot use Pro created training samples yet - So I'm just using the normal ML Classification routing using training samples.

**Comment by dfoll** [comment]
@NatalieCampos @helyx-amcmillan  is the "train ML Classifier" tool ever going to go back in? if so we should leave this open (and attach appropriate information about anything that was logged against Pro about it not working).

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#14
