### ISSUE TITLE
The QC task cause the Pro app to crash on step 2

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#718]
The QC task cause the Pro app to crash on step 2 after creating the validation points.  The error report was sent in.

**Comment by helyx-amcmillan** [comment]
Have re-built. One of the automated tasks was causing it to crash. There is still a small issue in that the 'Add Field' step should have a blank 'Field Domain' section, however it keeps getting pre-populated with 'CIMPATH=world/new_group_layer8.xml'. Need to log as bug.

**Comment by dfoll** [comment]
@helyx-amcmillan @NatalieCampos  can we get the information included here about the separate bug that was logged

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#12
