### ISSUE TITLE
Suggestion to Release Ops Server (Including Content) via BOX

### ISSUE THREAD

**Issue by richgale** [Esri/ops-server-config#719]
As part of the European Defence Team, I'm increasingly being asked for copied of the Ops Server by European Distributors after the Disc has been given out or shipped as part of a main event release i.e TEM.

My suggestion would be for the Solutions team to package the full Ops Server including content and place it on "Box". 
You can use 7zip to span the content across multiple 100mb files, which would help Distributors download the whole release. Plus you could put items like the map caches in a separate archives, for those users which already have a recent basemaps and don't require the tiles again. 
Having the Ops server on "Box" would not only allow distributor to access the latest release without having create a USB disc shipped to them, but you would be able to see who is accessing and download the content via the "Box" alerts. 

Thanks R

**Comment by conklinbd** [comment]
We tried this and unfortunately it doesn't work. Box sync just fails to properly pull in all the files and it fails without warning so we can't even tell if it had a problem.
