### ISSUE TITLE
Blank fields in embedded task tools sometimes reference invalid path

### ISSUE THREAD

**Issue by helyx-amcmillan** [Esri/ops-server-config#721]
For instance in the 'add field' tool the 'Domain' section should be blank, however automatically populates with 'CIMPATH=world/new_group_layer8.xml'

**Comment by NatalieCampos** [comment]
Where was this bug logged? with what team? more information needed.

**Comment by dfoll** [comment]
This issue was moved to ArcGIS/solutions-templates#11
