### ISSUE TITLE
Some GEE services need to be updated to use GeoFences again

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#723]
In the 10.2.2 version of Ops Server, GeoFences were created for Monitored Areas and NAI/TAI's.   These were used to raise alerts on reports and tracks entering/existing these areas, shown in the ISR Watchkeeper Dashbaord.

Some services were recreated for the 10.3 version but didn't include the logic to use the geofences.  I have recreated these for SPOTREP and SensorTracks and think that at least these two should be added back to the Ops Server (not necessarily for the 2014_Q4 patch, but at least the next release).  Using these geofences makes for a great GeoEnrichment demo and to show the capabilities of GEE.

I've exported the configs for these two services, if you'd like me to send them. Here are screenshots for reference:

SensorTracks:
![image](https://cloud.githubusercontent.com/assets/3383476/5960500/c2130a38-a7cd-11e4-877e-197712b61f7b.png)

SPOTREP:
![image](https://cloud.githubusercontent.com/assets/3383476/5960520/028f3820-a7ce-11e4-9a4d-e2caf40ebc38.png)

**Comment by jrweakland** [comment]
@pHill5136 - please take a look at this in a future sprint. Added to backlog: https://app.asana.com/0/22926133759983/31304190918329

**Comment by jrweakland** [comment]
@pHill5136 - has this been resolved yet?

**Comment by conklinbd** [comment]
Some have been modified to include geofences. We are not completely replicating all the old services so I am closing this.
