### ISSUE TITLE
RoadNetworkTasks GP tool -  point, line and area barriers are mandatory inputs in WAB

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/ops-server-config#724]
I used the Geoprocessing Widget in Web AppBuilder (Dev Edition) to add the RoadNetworkTasks GP tool.   This tool was written so that point, line and area barriers are required parameters of the model, so when running the tool in WAB, you must sketch these in order to solve the route.

 I've looked at the GP model and see why they are required inputs, because the AddLocations tool needs to be run sequentially, each time adding in the new Input Location (stops, barriers, etc).  But I'm wondering if there is any way to re-engineer this GP task so that these parameters aren't required?  It's a great GP tool to show in WAB, but those required inputs make it clunky.

I have noticed that when running the tool in desktop, those parameters are not required (or can be empty).

**Comment by conklinbd** [comment]
@kerryrobinson did you look at the Directions with Barriers widget we built for Web App Builder in our Solutions Web App Builder widgets repository?

**Comment by kerryrobinson** [comment]
No, I haven't...  but I will now.  Thanks for pointing it out.

**Comment by jrweakland** [comment]
@kerryrobinson - have you had a chance to check this out yet?

**Comment by kerryrobinson** [comment]
@jrweakland not yet... once I am done with travel in 2 week's time I plan on trying the new widget.

**Comment by conklinbd** [comment]
I am closing this question as answered.
