### ISSUE TITLE
CD:Preprocessing - Step 3 open Preprocessing map

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#725]
The CD project opens with the preprocessing map open already.  Step 3, however, is to open the preprocessed map. Either have the map closed when the project is opended (preference) or deleted step 3

**Comment by helyx-amcmillan** [comment]
Accidentally saved the project with the map open while testing. Will try to remember to close it next time I package a test file.

**Comment by NatalieCampos** [comment]
issue is not seen on the most recent build test2.ppk.
