### ISSUE TITLE
Predictive Analysis Drug Grows - map package corrupt 

### ISSUE THREAD

**Issue by richgale** [Esri/ops-server-config#726]
Predictive Analysis Drug Grows map package is corrupt within the demo and scripts and on the Shipped USB disc.
\\disldb\DemoAndScripts\Intel\PredictiveAnalysisDemos\DrugGrows\Data\PredictiveAnalysis_DrugGrows.mpk

**Comment by conklinbd** [comment]
I am closing this issue since it is not valid for the new geography.
