### ISSUE TITLE
Unable to delete an ArcGIS Pro project/template from Portal for ArcGIS

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#733]
@dfoll uploaded an ArcGIS Pro template under his name.  He was unable to delete this file.

I tried to delete the file as well with no success.

This occurred on NSEC production server.

**Comment by conklinbd** [comment]
@ACueva have you contacted anyone from the Portal team to try to get this resolved.

**Comment by ACueva** [comment]
@conklinbd I have not.  I will do so right away.

**Comment by elinz** [comment]
@ACueva Contact the same two people in the email I sent you this morning.

**Comment by ACueva** [comment]
This is issue was cause by the portal item having the Delete Protection set to "on" in the portal item settings.
