### ISSUE TITLE
UrlChecker.py script enhancements

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#737]
- [x] Add ability to filter urls from UrlChecker.py script - Having the ability to run the Url Checker script and filter urls pointing to a server would beneficial to figure out what try it live applications are being referenced by our solutions pages.
- [x] Check local links: local links e.g. `<a href="/military/land-operations/templates/vc/workflows/template-workflow-page/">`
- [x] Ignore Links in HTML comment blocks
- [x] Links that do not have `a href` (erb links) [example of bad link not caught](https://github.com/joebayles/arcgis-solutions-website/blob/standdown/source/military/index.html.erb#L20)
- [x] PeP8 + Pylint clean-up.

**Comment by ACueva** [comment]
@csmoore FYI

**Comment by csmoore** [comment]
We will probably need to make this a little smarter with local links like: `<a href="/military/land-operations/templates/vc/workflows/template-workflow-page/">` since these links could likely be in error also.  

I'm going to change the issue title to "URL checker enhancements" & we can just capture & track these in this issue

**Comment by ACueva** [comment]
First item marked resolved.  This same feature can be accomplished by setting Verbose=True and simply sorting the csv file that is returned.

**Comment by ACueva** [comment]
Checked the Ignore Links in HTML comment blocks section of code.  It does function as intended.

**Comment by ACueva** [comment]
Confirmed script now catches links that do not have a href in them.

**Comment by ACueva** [comment]
@csmoore Changes have been made.  Please review changes. https://github.com/ACueva/ops-server-config/blob/master/SupportFiles/UrlChecker.py

**Comment by csmoore** [comment]
Tested from PR #743 & looks good.  Additional/new issues noted in #742
