### ISSUE TITLE
Beach Landing 10.1 does not contain documentation on how to use the template.

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#739]
The beach landing 10.1 template does not contain documentation on how to use the template on http://www.esri.com/apps/products/download/index.cfm?fuseaction=download.main&downloadid=1597 and it is seen as reference on http://www.arcgis.com/home/item.html?id=df54647727614aa79c93016ec659689f. Because it is disseminated as a map package it is harder to package documentation.

**Comment by jfrygeo** [comment]
Created zip files of the template with the standard "documentation" and "maps" folders. By having it as zip file, the tool works successfully on 10.1, 10.2, and 10.3. Pushing to @jrweakland for review and release on Esri Downloads website.

**Comment by joebayles** [comment]
@jfrygeo This looks like it should have been opened in the https://github.com/ArcGIS/solutions-templates repository instead.
