### ISSUE TITLE
Group application template onto portal 10.3.1

### ISSUE THREAD

**Issue by phil7277** [Esri/ops-server-config#744]
I am having an issue trying to deploy the crowdsource reporter group application template on to portal 10.3.1. After sharing the crowdsource reporter group application template to the group nsec gallery template, it should be available as an application selection for sharing the group. Instead all gallery application templates are no longer visible when I share the group, and the crowd source reporter application is not an option as a gallery application template.

**Comment by conklinbd** [comment]
@ACueva Can you help Phil together put together an sp- email to see if we can find a resolution to this issue?

**Comment by ACueva** [comment]
@conklinbd Will do.

**Comment by ACueva** [comment]
@conklinbd I contacted the Portal team directly.  I'll give them some time, if not I'll send out the SP e-mail.

**Comment by ACueva** [comment]
@conklinbd Just and FYI that the Portal team is looking into this issue,

**Comment by conklinbd** [comment]
@ACueva can you get an update on this issue?

**Comment by conklinbd** [comment]
@ACueva @elinz @phil7277 @jrweakland 
I have figured out the root cause of this issue. 
The folder we have the application deployed to has the name /apps/. This folder seems to be some kind of keyword for the Portal so it has a problem parsing out the correct path. 

When I move the application out of this folder it works. 
@ACueva - Can you communicate this to the Portal team since it is a Portal bug and not a bug with the crowd source app.

We will need to rename our folder to work around this issue. I would like to do this soon, just so we don't have to many app urls to update. 

I think we could just call the folder app instead of apps.

**Comment by conklinbd** [comment]
@ACueva there actually seems to be more problems with using a custom-crowd sourced application. When I try to use it, it adds /arcgis/ to the url. 
Maybe we can just let them know that we can not make this work at all.

**Comment by conklinbd** [comment]
I am going to place these applications in the Portal apps directory as a workaround, for now. We still want to keep this issue open so we can restore it to this location for a future release.

**Comment by conklinbd** [comment]
That is complete. Someone had already placed them in that directory (maybe it was me?) I just registered the apps and set their thumbnails. I did not test thoroughly.

**Comment by phil7277** [comment]
@conklinbd The gallery application template still does not work. I receive the following area when trying to share the group using the crowd source reporter:
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.

I think the application still needs to be published.

**Comment by conklinbd** [comment]
@phil7277 try again. Just missed an element when I edited the url.

**Comment by phil7277** [comment]
@conklinbd, I tried it again, it throws a different error:
Page not found
Type: Status Report
Message: /arcgis/apps/CrowdSourceReporter/index.html
Description: http.404:/arcgis/apps/CrowdSourceReporter/index.html

I have added you to the group I was trying to share:
Operations Center Reports

**Comment by conklinbd** [comment]
Ok. This is now fixed for real. The app only works in the share dialog. You can't launch the app by just searching for it on the portal. 
@ACueva can you go ahead and paste the urls for the devtopia issues in her.

**Comment by ACueva** [comment]
•	Make a Gallery Application: Preview and Publish template open invalid URL – fixed installed into 10.4 awaiting verification once the home app builds are turned back on
https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/3683
•	Make a Gallery Application: If one of the applications in the group has thumbnail = null none of the applications are displayed in the selection dialog
https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/3682 – fixed installed into 10.4 awaiting verification once the home app builds are turned back on

**Comment by ACueva** [comment]
These issues have been marked fixed in daily builds of ArcGIS Portal.  Added verify label as I should verify these items truly are fixed at next stable Portal version.

**Comment by phil7277** [comment]
This issue has been resolved and the gallery applications have successfully been deployed to the NSEC portal.
