### ISSUE TITLE
Services published to incorrect folder on Development Server

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#746]
There were 2 new folders created on the Ops Server. 
https://nsec.esri.com/ags/rest/services/Whitby
https://nsec.esri.com/ags/rest/services/Movement

We do not want to create new folders on the server for any services. Please publish to an existing folder. Also, I don't think the Whitby services are required any more so they can just be deleted.

**Comment by conklinbd** [comment]
https://nsec.esri.com/ags/rest/services/Movement has been removed. Just waiting on Whitby to be removed.

**Comment by topowright** [comment]
@conklinbd These services and folder has been removed.
