### ISSUE TITLE
CrowdSource Manager and CrowdSourceReporter apps do not follow the naming convention for app deployment

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#747]
The crowd source manager app and crowd source reporter app do not currently follow the naming conventions for custom application deployment.

onenote:http://devinfo/SiteDirectory/DefenseAndIntelligence/Procedures/TeamNotebook/Team%20Notebook/Development%20Servers.one#Deploying%20Custom%20Web%20Apps%20to%20the%20NSEC%20Portal&section-id={48F5CD8C-C860-4A68-B2E4-59B094141220}&page-id={B80B50C9-DD64-423C-9639-EEE4EB31F936}&end

**Comment by conklinbd** [comment]
@phil7277 I noticed that you fixed this on the folder, but not the item. The items urls still point to the old name.

**Comment by phil7277** [comment]
Fixed the items URL to point to the correct name.
