### ISSUE TITLE
Validated that you have access to github issues

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#749]
@Esri/arcgis-defense-team 

Respond to this post with your github ID and your real world name to help us validate that you have access to Github and know where the ops-server-config is. 

___Admin Note___ This is for the UC 2015/Ops Server kickoff with the National Security Solutions team.

**Comment by kerryrobinson** [comment]
@kerryrobinson  Kerry Robinson

**Comment by oevans** [comment]
Hi Ben — I’m oevans on GitHub, but I’m unsure as to why I need access to this repo.  ??  Is it a case of mistaken identity or a typo?

Owen Evans | Solution Engineer
National Government Sector - Emerging Markets
Esri | 8615 Westwood Center Dr. | Vienna, VA 22182 | USA
703-506-9515, ext. 8135 | OEvans@esri.com | esri.com

From: Ben Conklin
Reply-To: Esri/ops-server-config
Date: Monday, April 20, 2015 at 2:17 PM
To: Esri/ops-server-config
Cc: Owen Evans
Subject: [ops-server-config] Validated that you have access to github issues (#749)


@Esri/arcgis-defense-team<https://github.com/orgs/Esri/teams/arcgis-defense-team>

Respond to this post with your github ID and your real world name to help us validate that you have access to Github and know where the ops-server-config is.

**Comment by csmoore** [comment]
Validated (Hopefully this wasn't a trick to see who is checking email - & deduct "participation points")

**Comment by jfrygeo** [comment]
validated.

**Comment by tedrick** [comment]
tedrick - James Tedrick

**Comment by tsmedley-kh06** [comment]
tsmedley-kh06

Tom Smedley

**Comment by abouffard** [comment]
abouffard - Andy Bouffard

**Comment by lfunkhouser** [comment]
lfunkhouser
Lorraine Funkhouser

**Comment by pHill5136** [comment]
pHill5136 Patrick Hill

**Comment by joebayles** [comment]
joebayles - Joe Bayles
:us:

**Comment by garys-esri** [comment]
@garys-esri Gary Sheppard

**Comment by NatalieCampos** [comment]
NatalieCampos

**Comment by mfunk** [comment]
MFunk

**Comment by ircampbell** [comment]
ircampbell - Ian Campbell

**Comment by jrweakland** [comment]
@jrweakland
James Weakland

**Comment by eWells** [comment]
eWells

**Comment by MaryClawson** [comment]
MaryClawson

Mary

**Comment by dfoll** [comment]
dfoll - Derek Foll

**Comment by nfeuerstein** [comment]
nfeuerstein - Natalie Feuerstein

**Comment by ACueva** [comment]
@acueva 

Avi Cueva

**Comment by BobBooth** [comment]
@BobBooth
Bob Booth

**Comment by elinz** [comment]
elinz - Eric Linz

**Comment by ScottCecilio** [comment]
@ScottCecilio - Scott Cecilio

**Comment by swang2013** [comment]
swang2013 - Stella Wang

**Comment by nvc-tvv** [comment]
@nvc-tvv Vyacheslav Tomilin

**Comment by knu2xs** [comment]
@knu2xs

Joel McCune

**Comment by yehiahassan** [comment]
@yehiahassan - Yehia Hassan

**Comment by slavickd** [comment]
Slavickd
Dan Slavick

**Comment by cpitman-gis** [comment]
cpitman-gis Craig

**Comment by jscott11** [comment]
@jscott11 Janette Scott

**Comment by jeffbaranyi** [comment]
@jeffbaranyi Jeff Baranyi

**Comment by jofraley** [comment]
@jofraley Jo Fraley

**Comment by conklinbd** [comment]
I am closing this issue. Several team members were not part of the defense team. We will rectify that.
