### ISSUE TITLE
Publish Maritime Incident Feature Service

### ISSUE THREAD

**Issue by csmoore** [Esri/ops-server-config#750]
Needed For Mil Team #2 Demo

**Comment by csmoore** [comment]
@jfrygeo @joebayles @BobBooth - this is the basis for all the other demos so should be completed first (high priority)

**Comment by elinz** [comment]
@jfrygeo  @joebayles @BobBooth This should be captured in Asana and not GitHub. Use GitHub to log issues, use Asana to log work to do.

**Comment by conklinbd** [comment]
:+1:
