### ISSUE TITLE
exercise - Maritime Security Template - crashes ArcGIS Pro 1.1 of previous builds

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#751]
Template was created on build 3068, was using a much older build.

https://nsec.esri.com/arcgis/home/item.html?id=fef1d6ec3c124a26bd9af452ce29ddc5

**Comment by ACueva** [comment]
@jfrygeo This appears to be related to a template.  I'd probably log the issue here:
https://github.com/ArcGIS/solutions-templates

Normally I'd move it for you, for the purposes of the exercise you might want to make sure you can create the issue in the repo I linked above.

**Comment by csmoore** [comment]
Self-assigning this to move & address the fix/workaround

**Comment by csmoore** [comment]
Moved: https://github.com/ArcGIS/solutions-templates/issues/60

(I watched/helped John create this issue so this is also my fault it was put in the wrong repo)
