### ISSUE TITLE
DemoAndScripts Folder vice OpsServerStaging\Demos on DISLDB

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/ops-server-config#752]
If the correct location to store demos and scripts is \\disldb\OpsServerStaging\Demos, then what is supposed to be stored here: \\disldb\DemoAndScripts

**Comment by elinz** [comment]
The share \\disldb\DemoAndScripts was used for the last Ops Server release and references the \\disldb\OpsServerStaging\2014_Q4\DemoAndScripts folder. I've deleted the \\disldb\DemoAndScripts share but not the underlying folder as over the last couple of months I've noticed that people have been updating files in \\disldb\OpsServerStaging\2014_Q4\DemoAndScripts and people can use these files as a starting point for their demos. But the only files that will be shipped in Ops Server releases are files in the \\disldb\OpsServerStaging\Demos folder.

**Comment by mfunk** [comment]
@elinz @nfeuerstein Been using the \disldb\DemoAndScripts for our Exercise today.
What should be be using now?

**Comment by conklinbd** [comment]
\disldb\OpsServerStaging\Demos

**Comment by elinz** [comment]
@mfunk People were instructed to use \\disldb\OpsServerStaging\Demos. Never instructed to use the \\disldb\DemoAndScripts folder.

**Comment by conklinbd** [comment]
This question has been answered.
