### ISSUE TITLE
Maritime Security Feature Layer Issues

### ISSUE THREAD

**Issue by joebayles** [Esri/ops-server-config#753]
- [ ] Layer has _Others_ and _Other_ (which is further divided into Theft). Suggest removing _Others_
 - [x] Suggest adding symbology to the [Maritime Security Feature Layer](https://nsec.esri.com/ags/rest/services/Military/MaritimeSecurityCollections/FeatureServer/0?token=_2Gre5BnpDUZblHyFHmwYyPbgdx_7WghhzpUdiZYErr0GqlUzrzdI5tQjc2WBObunlAs7kM9J-qNiXBoheoqEoVM_cX59rI-BN2DqBmgOtVNFwKU_AxvEDTso5gJbTjEz6Mn1bRn2vXYk67KWr_JrwKO8Ly0YNcTbvQUaD6DXWQ), something like this:

![image](https://cloud.githubusercontent.com/assets/5016557/7257528/43c520ac-e80b-11e4-96f9-7941f473d468.png)
![image](https://cloud.githubusercontent.com/assets/5016557/7257559/8059acc2-e80b-11e4-85f7-e8f4ed01da8f.png)

**Comment by conklinbd** [comment]
@jfrygeo is this issue for data we will include in the Ops Server release? If not please delete.
