### ISSUE TITLE
DigitalTerrainModel has not descripton, tags, credits, restrictions, etc.

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#754]
DigitalTerrainModel has not descripton, tags, credits, restrictions, etc.

https://nsec.esri.com/arcgis/home/item.html?id=65a20bd89184442a86448a99a6ecd1f8

Would like to use this for demo, but don't know if I can.

**Comment by nfeuerstein** [comment]
Assigned to @NatalieCampos as she created the service.

**Comment by NatalieCampos** [comment]
This was a demo service for the kickoff.It has since been removed as the NSEC world elevation service is currently being built.
