### ISSUE TITLE
Basemaps do not show up when zoomed in to southern California

### ISSUE THREAD

**Issue by garys-esri** [Esri/ops-server-config#755]
Zoom in to southern California, for example Redlands, and the basemaps do not display. You have to zoom out several levels to get it to display. Instead, it should display at all levels since this is our "new geography" area of interest.

**Comment by conklinbd** [comment]
@garys-esri Please refer to following web map for areas that have high resolution caches. 
https://nsec.esri.com/arcgis/home/webmap/viewer.html?webmap=31a38062b3194689989bfa4eddc64b15
