### ISSUE TITLE
Error message when trying to use Esri Maps for Office

### ISSUE THREAD

**Issue by fred3792** [Esri/ops-server-config#756]
When I try to add a map in excel, I get an error message.
![4-21-2015 10-47-31 am](https://cloud.githubusercontent.com/assets/9387234/7258885/31e6ac94-e814-11e4-9f59-f7f96858ca6f.jpg)

**Comment by conklinbd** [comment]
I can not reproduce this issue with Office 2013 and Esri Maps for Office 3.0. Please ensure you have the latest software installed.
