### ISSUE TITLE
ModelGeography_WFL is empty, no Descrip, Credits, etc.

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#760]
I was pointed to the ModelGeography_WFL service on NSEC to use for admin boundaries for new geography. But there are no features in it.

ArcMap 10.3.1 Build 4959:
1. Open ArcMap
2. Add Data from ArcGIS Portal (connection to https://nsec.esri.com/arcgis/home  as matt2542)
3. Search for "ModelGeography_WFL"
4. Add the feature service to map (ModelGeography_WFL layer contains City Boundary sub layer, no features are added to the map)
5. Right click on City Boundary and Open Attribute Table

![image](https://cloud.githubusercontent.com/assets/3093182/7302106/dfa383d8-e99b-11e4-8352-bb27abe93b4a.png)

Open the item on NSEC portal and item is missing:
* Summary
* Description
* Access and Use Constraints
* Tags
* Credits

![image](https://cloud.githubusercontent.com/assets/3093182/7302145/282f8728-e99c-11e4-975f-6bf1b3e8eecf.png)

**Comment by conklinbd** [comment]
I have republished this service. Something must have gone wrong during the upgrade process. This service is a temporary service, I assume the foundation services will include the admin boundaries as a permanent layer.

**Comment by conklinbd** [comment]
Nevermind...there seems to be a larger issue with the service definition also. I will delete my temporary copy and wait for someone to publish the authoritative source.

**Comment by mfunk** [comment]
@nfeuerstein @conklinbd Who is publishing the authoritative source for the model geography AOI. Should be ultra-urgent top priority. I'm guessing most people publishing data will want to use that as a boundary or intersect (like me). Since servers are not back up again (per Eric) this morning (4/24/2015) could we have said author have something up early next week?

**Comment by nfeuerstein** [comment]
@mfunk @conklinbd - I started preparing this last week.  I'll finish it up today.

**Comment by nfeuerstein** [comment]
Or....I'll finish it up when the servers are back up.
