### ISSUE TITLE
Tags show incorrect seach terms 

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#761]
For:
* AFMI Gallery Templates
* AFMI Web Application Templates

![tags](https://cloud.githubusercontent.com/assets/5074686/7319721/7672aef0-ea65-11e4-8f5d-ceed27af7394.PNG)

**Comment by elinz** [comment]
@jfrygeo Need more information. What is the specific issue? I'm assuming the tags having [ and \ characters. Is this issue encountered on a Ops Server that you have deployed using the ops-server-config scripts? Or did you find this on the development portal? and is this issue on the current NSEC portal or the previous AFMIEDEV portal? Thanks.

**Comment by jfrygeo** [comment]
Happen
