### ISSUE TITLE
utds database needs to be deleted from nsec

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#763]
The utds gdb needs to be deleted from the nsec server.  The utds gdb has been replaced with a tds database that contains the data from utds, ltds, and rtds.

**Comment by elinz** [comment]
I will delete this enterprise geodatabase when I get back into the office next Tuesday.

-------- Original message --------
From: Natalie Campos
Date:05/08/2015 1:35 PM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: [ops-server-config] utds database needs to be deleted from nsec (#763)


The utds gdb needs to be deleted from the nsec server. The utds gdb has been replaced with a tds database that contains the data from utds, ltds, and rtds.

**Comment by elinz** [comment]
@NatalieCampos I'm assuming I can also delete the rtds database since the new tds should contain the contents of the rtds database?

**Comment by conklinbd** [comment]
@elinz you can delete all the databases that no longer have connection files shared. I removed the databases we no longer need.

**Comment by elinz** [comment]
@conklinbd Great. Thank you.

**Comment by elinz** [comment]
Deleted all PosgreSQL geodatabases except for: currentoperations, military, tds, and workflow.
