### ISSUE TITLE
Weather related services are not following best practices

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#764]
The Weather related services are not following the best practice guidelines.
Conventions for services are listed in the Team Onenote under Development Servers.

The Weather Services are not named with CamelCase. They are using under_scores.
Additionally, there are a large # of services with only 1 layer. It is best to minimize the # of services and just configure the layers in your web map. 

Additionally, the services are served up as map service layers and I would expect them to be Image Service Layers. Is there a specific reason they do not work as Image Service Layers?

**Comment by abrowning80** [comment]
Sorry for this, will address post tomorrows meeting

Layers are served  as map services and not image services due to not being able to apply cartography to an image service at present. Could also serve as an image layer so that user is able to get to the underlying data if so desired.

**Comment by conklinbd** [comment]
This was resolved.
