### ISSUE TITLE
Slope RGB raster function does not display properly for dataset not in Web Mercator

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#765]
The slope RGB raster function does not display properly for datasets not in web mercator.  The raster function needs to be fixed.  

Raster function in WGS 84
![image](https://cloud.githubusercontent.com/assets/5116835/7638391/31e43708-fa29-11e4-96b0-fa92d556204c.png)
Raster function in Web Mercator
![image](https://cloud.githubusercontent.com/assets/5116835/7638410/5060eca8-fa29-11e4-8310-5c6988e75ab0.png)

**Comment by conklinbd** [comment]
@NatalieCampos I thought that they added an automatic Z value calculation to the slope function. Is that not set or is it not working correctly?

**Comment by NatalieCampos** [comment]
The issue is not related to the slope raster function itself.  That issue was fixed.  The issue is how the slope calculation is converted to an 8 bit rgb image(display purposes only not for analytic use).  I need to ask rajinder/cody for an updated raster function.  But i wanted to get the services up and running first.

**Comment by NatalieCampos** [comment]
This is a know issue and it will not be fixed prior to the Sept cut off date.  @lfunkhouser @nfeuerstein Please move to future release.

**Comment by elinz** [comment]
@NatalieCampos It appears that this is still an issue with our World Elevation WGS84 service. Can you please see if this can be fixed for our current Ops Server release? Thanks.

**Comment by NatalieCampos** [comment]
this  can not be fixed at this time.  The colorized version uses slope that is not  appropriate  for wgs 84.  this  results in the bug.  This raster function is included because it is part of the World Elevation Service functions.  Should this raster function be  removed @lfunkhouser @nfeuerstein ?  Or should this issue be closed as a known defect.

**Comment by Dbarnes1** [comment]
remove from mosaic and have @jrweakland verify.

**Comment by NatalieCampos** [comment]
the slope rgb raster function has been removed from all relevant elevation services.
