### ISSUE TITLE
Behavior when clicking on a featured map is not what expected on nsec portal.

### ISSUE THREAD

**Issue by MaryClawson** [Esri/ops-server-config#766]
When I am at the nsec portal home page, when I click on a featured map, I expect to go to the web map or the description page if the featured item is a template.  So for example when I click on the Model Geography New, I go to a web map.  However, when I click on the Vehicle Check Point or the Observation Post, it immediately downloads and I don't get to either the description nor does it open a web map.@nfeuerstein

![nsce home page](https://cloud.githubusercontent.com/assets/5453541/7639361/1742c23c-fa30-11e4-8873-c49762059a96.png)

**Comment by nfeuerstein** [comment]
That is how featured content works.  If the featured item is a web map, it opens the web map when clicked.  If its a zip file, it downloads the zip file when clicked.  If its a layer, it opens the layer in a web map when clicked.  Its as designed.

**Comment by MaryClawson** [comment]
Maybe if that's how it works, it would be better not to put a template on the home page of Featured Maps and Apps.  If I am primarily a portal user, getting a download without any additional feedback is unexpected and not useful.
