### ISSUE TITLE
Receiving "client tried to access password-protected page" error when trying to run GP Service in WAB.

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#767]
Published a GP service and made it public. 
https://nsec.esri.com/ags/rest/services/Military/FarthestOnCircle/GPServer

The GP service uses a raster, which is also shared publicly. 
https://nsec.esri.com/ags/rest/services/Military/WaterMask/ImageServer

When trying to use it in Web App Builder getting this error:
![gperrors](https://cloud.githubusercontent.com/assets/5074686/7709886/0bf32d48-fe2e-11e4-80e7-32292b56301f.PNG)

Server logs indicate:
Error executing tool. Farthest On Circle Job ID: je3ba58e547054ecdb223bf5f2d15d8e1 : ERROR 999999: Error executing function. Client tried to access password-protected page without proper authorization. Failed to execute (Image Service Mask). Failed to execute (Farthest On Circle). Failed to execute (Farthest On Circle).

**Comment by jrweakland** [comment]
@elinz and @jfrygeo  - I think this is from the issues with the Portal today.

**Comment by jfrygeo** [comment]
working with support to with this issue.

**Comment by jfrygeo** [comment]
Working with support to deal with this issue of having an image service in a GP service. Esri Case #01688405

**Comment by jfrygeo** [comment]
same as issue #777 - closing issue
