### ISSUE TITLE
AGS Services do not have an associated portal item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#770]
- [x] Test//VCPTemplate1022.MapServer
ERROR: Service "Test//VCPTemplate1022.MapServer" is associated with a portal item (81eff6f669a04c8cbc4c5716e0877ce0; MapServer) that does not exist.
ERROR: Service "Test//VCPTemplate1022.MapServer" is associated with a portal item (e0edff8be4ca48dda539c6350d35087d; FeatureServer) that does not exist.
@nfeuerstein issue still exists as of 04 June 2015.

- [x] NationalIntelligence//RoadFeatures.MapServer
       Service "NationalIntelligence//RoadFeatures.MapServer" has an associated item (e2d9b54c044c446e876b61123c947ff3; MapServer)
ERROR: Service "NationalIntelligence//RoadFeatures.MapServer" is associated with a portal item (cf51c5a4a673438e8385645b206d3730; FeatureServer) that does not exist.
@nfeuerstein issue still exists as of 04 June 2015.

- [x] NationalIntelligence//RailroadOverlay.MapServer
ERROR: Service "NationalIntelligence//RailroadOverlay.MapServer" is associated with a portal item (0a66d57e6c1a4c3eb7cdaee3089b3220; MapServer) that does not exist.
@nfeuerstein issue still exists as of 04 June 2015.

- [x] NationalIntelligence//RoadsOverlay.MapServer
ERROR: Service "NationalIntelligence//RoadsOverlay.MapServer" is associated with a portal item (8a9706f2f80e45358b0c53d971689c12; MapServer) that does not exist.
@nfeuerstein issue still exists as of 04 June 2015.

- [x] NationalIntelligence//RailroadFeatures.MapServer
       Service "NationalIntelligence//RailroadFeatures.MapServer" has an associated item (7d346efdeff2422792a7c4baca38c6e1; MapServer)
ERROR: Service "NationalIntelligence//RailroadFeatures.MapServer" is associated with a portal item (ff370904894d423b9c701956dcb036cc; FeatureServer) that does not exist.
@nfeuerstein issue still exists as of 04 June 2015.

- [x] NationalIntelligence//NAIP.ImageServer
ERROR: Service "NationalIntelligence//NAIP.ImageServer" is associated with a portal item (72c2075063704407b99d954ed199baa5; ImageServer) that does not exist.
@nfeuerstein New issue as of 04 June 2015.

**Comment by elinz** [comment]
@nfeuerstein Reran report 04 June 2015. Marked still exists issues and one new issue.

**Comment by nfeuerstein** [comment]
@jrweakland - I think this has to do with the Vehicle Checkpoint template:
Test//VCPTemplate1022.MapServer
ERROR: Service "Test//VCPTemplate1022.MapServer" is associated with a portal item (81eff6f669a04c8cbc4c5716e0877ce0; MapServer) that does not exist.
ERROR: Service "Test//VCPTemplate1022.MapServer" is associated with a portal item (e0edff8be4ca48dda539c6350d35087d; FeatureServer) that does not exist.

**Comment by nfeuerstein** [comment]
all other issues have been remedied

**Comment by elinz** [comment]
@jrweakland Okay for me to delete the Test//VCPTemplate1022.MapServer service? Since both the map service portal item and feature service portal item for this service do not exist, I'm assuming that the publisher wanted to delete this service, but did not delete it probably (i.e. delete the portal items instead of deleting the service from AGS connection.

**Comment by jrweakland** [comment]
@elinz - please delete the test service.

**Comment by elinz** [comment]
@jrweakland I deleted the Test//VCPTemplate1022.MapServer service. Closing issue.
