### ISSUE TITLE
AGS Services do not have an associated portal item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#771]
- [x] Military//MAOW_freshOpI.MapServer
ERROR: Service "Military//MAOW_freshOpI.MapServer" is associated with a portal item (1b3095841b214d86b5495e4d72c94818; MapServer) that does not exist.
@jrweakland @abrowning80 Issue still exists as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//MAOW_Weather_OpImpact.MapServer
ERROR: Service "Military//MAOW_Weather_OpImpact.MapServer" is associated with a portal item (fef1ad48ccb74d6f91ad8fd4bb252c93; MapServer) that does not exist.
@jrweakland @abrowning80 Issue still exists as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Weather_Cloud_Cover.MapServer
ERROR: Service "Military//Weather_Cloud_Cover.MapServer" is associated with a portal item (5fb84c1cc2bb4fd2ab5a1045afc0e596; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//MAOWTemplate_publish_Just_Weather.MapServer
ERROR: Service "Military//MAOWTemplate_publish_Just_Weather.MapServer" is associated with a portal item (0c16ccebc7864ab7a8841a6b89684cce; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Weather_Heat_Index.MapServer
ERROR: Service "Military//Weather_Heat_Index.MapServer" is associated with a portal item (6f9cb8ef60d348efae00ed2af7535310; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Op_Impact_Air_Visibility.MapServer
ERROR: Service "Military//Op_Impact_Air_Visibility.MapServer" is associated with a portal item (6d98347cb6c24ebea36f3cfd155de6ed; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Op_Impact_Air_Cloud_Ceiling.MapServer
ERROR: Service "Military//Op_Impact_Air_Cloud_Ceiling.MapServer" is associated with a portal item (950e9ba529714a1888fa25c10261de65; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//MAOW_freshOpI2.MapServer
ERROR: Service "Military//MAOW_freshOpI2.MapServer" is associated with a portal item (b4130e0015f34acd806a81b296522696; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Weather_Cloud_Ceiling.MapServer
ERROR: Service "Military//Weather_Cloud_Ceiling.MapServer" is associated with a portal item (8c06a420090a4e0a906460efafda498e; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Op_Impact_Air_Temperature.MapServer
ERROR: Service "Military//Op_Impact_Air_Temperature.MapServer" is associated with a portal item (6629e79b532b422190ab946292070483; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Weather_WindChill.MapServer
ERROR: Service "Military//Weather_WindChill.MapServer" is associated with a portal item (617c6c847b154c818dee0498b3a37417; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//MAOWTemplateF.MapServer
ERROR: Service "Military//MAOWTemplateF.MapServer" is associated with a portal item (0ac1ff27366a453893a37d7ef3c268f7; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015.

- [x] Military//Op_Impact_Windspeed.MapServer
ERROR: Service "Military//Op_Impact_Windspeed.MapServer" is associated with a portal item (f0e980db600743639fd1b1b7959ac362; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 (Also service name should not have underscores).

- [x] Military//Weather_Relative_Humidity.MapServer
ERROR: Service "Military//Weather_Relative_Humidity.MapServer" is associated with a portal item (d81754d14441482692ed5b05566fdb8a; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 07:40 PST (Also service name should not have underscores).

- [x] Military//Op_Impact_Bridge_Crossing_Wind.MapServer
ERROR: Service "Military//Op_Impact_Bridge_Crossing_Wind.MapServer" is associated with a portal item (ecbc4a92deea40e4a81fccdf287259ff; MapServer) that does not exist.
@jrweakland @abrowning80 New issue as of 04 June 2015 07:40 PST (Also service name should not have underscores).

**Comment by elinz** [comment]
@jrweakland @abrowning80 Reran report today 04 June 2015. The previous issues still exist and there are many more issues identified in today's report. If the service meant to be deleted then please make sure you delete the service through ArcGIS Desktop (for non-hosted services). If you try and delete through portal (i.e. delete the portal service item) then only the service item is deleted...it won't deleted the service. NOTE: service names should not have underscores. Please republish (overwrite) any of the services with underscores in them. It's important to have this fixed immediately otherwise any web maps or other resources built on the currently named services will have incorrect references. The release team has been instructed to "get serious" about these issues and we will been to "seek and destroy".

**Comment by abrowning80** [comment]
@jrweakland @elinz Should all be sorted now.  Sorry for the delay.

**Comment by elinz** [comment]
@jrweakland @abrowning80 Reran to verify corrections. Found two new issues. See checklist above. Thank you.

**Comment by abrowning80** [comment]
@jrweakland @elinz Have resolved those 2 as well so should be all good now.  I will start rebuilding things correctly next week all being well.

**Comment by elinz** [comment]
@jrweakland @abrowning80 Thanks. Reran report and the military services are "clean".

**Comment by elinz** [comment]
@jrweakland @abrowning80 Reran report again today 10 June, 2015 and military services are "clean". Will close this issue; I'll reopen if issue is encountered again in the future.
