### ISSUE TITLE
Southwest Asia Climate Briefing needs layers set in Web Maps

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#774]
A released version of the Southwest Asia Climate Briefing (http://www.arcgis.com/apps/StorytellingTextLegend/index.html?appid=b71d46f69bb046938f0b91ac130a4e3e) displays the first layer in the web maps for each of the parameters. For example, Diurnal Temperature Range, Frost Days, Precipitation, etc. all display the layer for temperature.

Looks like after the Ops-Server is deployed the web maps default to the top layer in the web maps, when that layer should be turned off, and the correct layer turned on. 

Three examples below of the layer appearing under each tab.
![swasia1](https://cloud.githubusercontent.com/assets/5074686/7861440/2cfadf1c-051e-11e5-99a2-25a6d1789a83.PNG)
![swasia2](https://cloud.githubusercontent.com/assets/5074686/7861441/2cfd1610-051e-11e5-9f4d-0bae3a68ec36.PNG)
![swasia3](https://cloud.githubusercontent.com/assets/5074686/7861442/2d309440-051e-11e5-8661-60d8c9dfc8ac.PNG)

How to fix the web maps - 
1. Go to the web map for each variable in the web application.
2. Turn off temperature, turn on the correct layer
3. Save web map

The picture shows that temperature appears on top and it is turned on by default when the ops server gets deployed. 
![swasia4](https://cloud.githubusercontent.com/assets/5074686/7861439/2cfa892c-051e-11e5-8ff6-edce98a67843.PNG)

**Comment by jfrygeo** [comment]
@ACueva

**Comment by ACueva** [comment]
Issue has been fixed on the try it live server.  The application now works properly.
http://arcgisforintel.maps.arcgis.com/apps/StorytellingTextLegend/index.html?appid=945b9bec781b444baffc1de307bfbc48

Reassigned to @jfrygeo as this needs to be fixed for future releases.

**Comment by conklinbd** [comment]
@jfrygeo is this even a valid issue anymore?

**Comment by jfrygeo** [comment]
no. fixed on solution pages here:http://arcgisforintel.maps.arcgis.com/apps/StorytellingTextLegend/index.html?appid=945b9bec781b444baffc1de307bfbc48
