### ISSUE TITLE
ArcGIS IED-Incident Geoform Web Application item on AGOL has broken link

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#775]
http://www.arcgis.com/home/item.html?id=6e641c88c3544560ad180c20e61b8db9

Web Application is pointing to http://afmcloud.esri.com/arcgis/apps/GeoForm/index.html?appid=6e641c88c3544560ad180c20e61b8db9&webmap=4c0156c16b654a82b664247763e3848c

is gives a "500 internal server" error. 
@ACueva, @nfeuerstein

**Comment by conklinbd** [comment]
This is not tied to the ops server release, this is an issue with the try-it live server.
