### ISSUE TITLE
ArcGIS IED Incident Summary Summary Viewer AGOL item has broken link

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#776]
http://arcgis.com/home/item.html?id=fe276874bc4d4bc8acbcd80efa69e749 

= item

Web application

http://afmcloud.esri.com/arcgis/apps/SummaryViewer/index.html?appid=fe276874bc4d4bc8acbcd80efa69e749

@ACueva @nfeuerstein

**Comment by conklinbd** [comment]
This is not tied to the release of Ops Server, this is an issue with the current try it live content.
