### ISSUE TITLE
World elevation mosaic datasets reference invalid paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#778]
Location of elevation data folders has changed, but paths in the mosaic datasets were not updated.

Elevation source data was moved to folder FoundationOverlays\Elevation\SourceData but mosaic datasets (for example d_WorldElevationWGS84) reference  FoundationOverlays\Elevation.

Also this mosaic dataset references a non-UNC path location.

Please review all elevation mosaic datasets and fix as required.

**Comment by NatalieCampos** [comment]
This issue has been resolved.
