### ISSUE TITLE
no data values creates holes in scene viewer

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/ops-server-config#779]
No data values in an elevation mosaic causes drop outs when not able to connect to AGOL.  See below.  It is estimated to be fixed by Portal version 10.4.

![image](https://cloud.githubusercontent.com/assets/5116835/8015701/ba2b2848-0b8f-11e5-8242-e1bd1b475621.png)

**Comment by jrweakland** [comment]
@NatalieCampos - Please add the appropriate tags for this issues. I started to add the tags and realized that you should complete them so that the tags are accurate and complete. Sorry...

**Comment by NatalieCampos** [comment]
This issue has been fixed with the inclusion of the "dummy" raster for the current version of the elevation cache.  The inclusion of the "dummy" raster with values of 0 overcomes the limitation of the nodata values.  The inclusion of the dummy raster will need to be reassessed if the cache is ever rebuilt.
