### ISSUE TITLE
Places of Interest services are incorrectly published to the ArcGIS Server root folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#781]
No ArcGIS Server services should exist in the root folder. All services should be published to a folder. Please republish the following services:
CommericalPlacesOfInterest
GovernmentPlacesOfInterest
HospitalsPlacesOfInterest
MilitaryPlacesOfInterest
MiscellaneousPlacesOfInterest
ReligiousPlacesOfInterest
SchoolsPlacesOfInterest
UtilitiesPlacesOfInterest

**Comment by elinz** [comment]
@Nekillims It is really necessary to publish all POI as separate services as opposed to creating a single POI service with multiple layers (commerical, government, etc)?. Having each as a separate service is going to use more server resources then necessary. Thanks.

**Comment by conklinbd** [comment]
@Nekillims this needs to be resolved in 3 days or we will have to delete the service. We don't want people to start to use these services in their maps and apps.

**Comment by elinz** [comment]
Verified and closed.
