### ISSUE TITLE
Service does not have service definition file (Military)

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#784]
The following services do not have a service definition file in the ArcGIS Server configuration store and will need to be re-published. Without an .sd file, the service won't be published on any Ops Servers.
 
- [ ] Military//LineOfSight.GPServer

**Comment by elinz** [comment]
@kgonzago This service is owned by you. If it's needed for UC then it will need to be republished for the .sd file to be stored in the ArcGIS Server config-store/directories.

**Comment by conklinbd** [comment]
I assume this is not needed for UC. Changing milestone.

**Comment by kgonzago** [comment]
@elinz: @ACueva republished the GP service - https://app.asana.com/0/23019535413942/28389452384457/f

**Comment by elinz** [comment]
@kgonzago I looked into this a bit further. While the .sd file does exist on the server the .sd file states that the service exists in the root folder and not in the Military folder, therefore when the sd extract script compares the services on the server and the .sd files to see if a .sd files exist for this service it can't find it since the .sd file is incorrect. The service needs to be republished from scratch to the Military folder.

**Comment by elinz** [comment]
@kgonzago Reopened as the issue is not fixed.

**Comment by jrweakland** [comment]
@kgonzago - please look at eric's comment and republish when you have a chance.

**Comment by kgonzago** [comment]
@elinz @jrweakland The LOS service will need to be removed since it is considered a "test" service. Please refer to conversation from this Asana task: https://app.asana.com/0/23019535413942/28389452384457

**Comment by conklinbd** [comment]
I deleted.
