### ISSUE TITLE
Service does not have service definition file (Intelligence)

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#785]
The following services do not have a service definition file in the ArcGIS Server configuration store and will need to be re-published. Without an .sd file, the service won't be published on any Ops Servers.

- [ ] NationalIntelligence//ExecuteQuery.GPServer

**Comment by ACueva** [comment]
This is @kAilshie 's Predictive Analysis service.  We have to manually publish it as part of the installation process.  It wouldn't run properly anyways unless the .dlls were installed prior to publishing.

**Comment by kAilshie** [comment]
There is an SD file in the folder the dlls get installed to but @ACueva is right, we will probably need to install and publish this manually.

**Comment by elinz** [comment]
@kAilshie Yes, by publishing the service manually the .sd file will be retained on the nsec server and the service will be automatically published when we set up an Ops Server.

**Comment by kAilshie** [comment]
@elinz Can you provide some instruction on what I need to do to verify that the issue is resolved?  The service has been republished many times but I'm not sure if the .sd file has been moved to the config store or not.

**Comment by ACueva** [comment]
I'm working with @kAilshie to resolve this issue.

**Comment by elinz** [comment]
@ACueva Just need to publish the service to the dev server and it will save the .sd file in the ArcGIS Server maintained folder, which is where we pull the file from.

**Comment by elinz** [comment]
@ACueva @kAilshie I verify by running the GetSDFiles.py script. I ran this morning and it now finds an .sd file for the ExecuteQuery gp service. There are multiple .sd files for this service, but the one that the script will pull from the server is the latest, which in this case is dated July 7th 15:02, is this correct?

**Comment by ACueva** [comment]
They should all be identical as no changes have been made the the .sd file.  Your choice as to which one you want to pull.

**Comment by elinz** [comment]
The won't be all identical as the service was published to different locations (the folder location is stored in the .sd file). We should be good using the .sd file with the latest stamp. I'm closing this issue.
