### ISSUE TITLE
When publishing, getting error "Another administrative operation is currently accessing the store. Please try again later."

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#786]
![administrativestore](https://cloud.githubusercontent.com/assets/5074686/8291722/694be256-18f9-11e5-8952-af3a151f45ba.PNG)

**Comment by elinz** [comment]
@jfrygeo Please provide more information. Were you trying to overwrite an existing service? Publishing a new service? What is the folder\service name\service type of the service.

**Comment by jfrygeo** [comment]
Received message 2 times:
1st time was publishing a new service - https://nsec.esri.com/ags/rest/services/Military/MaritimeBoundaries/FeatureServer
the second time was overwriting that service. 

However, I went to the manager, saw the service was already started and brought the service into a web map - no problem.

**Comment by elinz** [comment]
FYI: generally speaking when you receive an "...administrative operations is currently accessing..." or similar error, don't perform any other operations on this service...it probably won't succeed and most likely make the situation worse.

**Comment by conklinbd** [comment]
@jfrygeo we think this issue has been resolved with a change to the permission level for the ArcGIS Server account on the NSEC Server. I am closing this as resolved. 
Reopen if you encounter this issue again.
