### ISSUE TITLE
Very large (>3GB) Service Definition files; is source data in AGS registered folder?

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#787]
@ScottCecilio @jrweakland You have two hosted services, Change_2005_2014 and DetectedChangeNorthernMonterey in which the associated service definition items on the portal (ids 8a06515adeab459d9eb502f8125f5c0e and 8f30babc48194ffab1d585a409199d92) are over 3GBs in size. These are very large and will impact the performance of publishing these services to target Ops Servers. Is the underlying source data for these services stored in the ArcGIS registered data folder or enterprise databases?

**Comment by jrweakland** [comment]
@elinz - My guess is that the underlying data was copied to the server instead of stored in the data store or enterprise database. @ScottCecilio - Please verify my statement and, if necessary, add the data to the enterprise database.

**Comment by elinz** [comment]
@jrweakland No the data was copied into the .sd file during the publishing process because the data was not stored in the registered data folder; @ScottCecilio is already taking care of this issue by copied the data into the registered data folder and republishing the services. Thanks.

**Comment by jrweakland** [comment]
:+1:

**Comment by elinz** [comment]
Verified fixed; closing this issue.
