### ISSUE TITLE
Hosted service item exists (Incidents), but hosted service does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#788]
Hosted feature service portal item "Incidents" (id:a79e118ff51e493abed58823ea7f8be7) exists in nsec portal, but the actual service does not exist.

NOTE: if you delete this portal item, make sure to delete the associated service definition item id:d1a5948e01294466be95abf9eebea0ae.

**Comment by ScottCecilio** [comment]
I saw this as well when looking at incidents for use with Land Ops.  I created a subset (1,999 features) of the incidents and created a service including just the features and not the CIDNE database symbology.  Feel free to use instead.

**Comment by conklinbd** [comment]
@j-sullivan If this is not fixed by 1700 this will not work at UC. @nfeuerstein FYI in case you are needing this.

**Comment by nfeuerstein** [comment]
@j-sullivan You can delete your Incident feature service referenced above unless there is something about it that is unique to your needs.  We have a feature service from the incidents you moved to the new geography here: https://nsec.esri.com/arcgis/home/item.html?id=03d78feda64d4eaea74c4d6a37512329

**Comment by conklinbd** [comment]
@j-sullivan is this still an issue?

**Comment by conklinbd** [comment]
Based on the lack of activity on this item. I am going to delete the item at 1100 today. If you think this is in error please respond by then.  Items like this cause us problems in QA/QC and have the potential to cause other problems as individuals reuse this content in their demo's/presentations.

**Comment by elinz** [comment]
FYI: Looks like there are no resources that are referencing a service named "Incidents".

**Comment by conklinbd** [comment]
Service definition deleted @j-sullivan 
This is a simple fix so no verification needed.
