### ISSUE TITLE
Hosted service Basemap_AOIs/FeatureServer does not have a service definition item.

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#789]
The hosted service Basemap_AOIs (feature service) item exists id:8946afd181f649c58c2dc0ef6f5d1a77 but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

**Comment by NatalieCampos** [comment]
This hosted service has been republished via ArcMap creating the necessary service definition.

**Comment by elinz** [comment]
@NatalieCampos I re-ran report and a service definition item does not exist on the portal for this hosted service. Reopening the issue.

**Comment by elinz** [comment]
@NatalieCampos Please ignore.
