### ISSUE TITLE
Hosted service dKPhG/FeatureServer does not have a service definition item.

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#790]
The hosted service dKPhG (feature service) item exists id:482f45d9d51f4c1ca154b457d661377bbut does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

**Comment by garys-esri** [comment]
I don't know who created that service and its associated map and apps, but it wasn't me. They all have "DELETE ME!!!" in the item text, and that's exactly what I will do.

You might want to verify that your scripts aren't mistakenly changing ownership of items.

**Comment by elinz** [comment]
@garys-esri No scripts are changing ownership of items.
