### ISSUE TITLE
Service Definition item (MAoWDataTest1) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#796]
Hosted service MAoWDataTest/MapServer no longer exists, but associated service definition item exists; please delete the following item:

id: 3273f53fe1fd4f6cae6df9834f5b78f3  
type: Service Definition       
service: MAoWDataTest/MapServer

**Comment by jrweakland** [comment]
@elinz - I deleted the service definition. Please verify and close issue.

**Comment by elinz** [comment]
Verified service definition item was deleted; closing issue.
