### ISSUE TITLE
Web Map "Movement Editing For GeoEvent Testing" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#797]
Item id 79ae73df02b84a5a8e8cb6db34d70fa3 references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/22
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/21
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/20
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/19
https://nsec.esri.com/ags/rest/services/Hosted/SignificantLocations/FeatureServer/0

**Comment by conklinbd** [comment]
Deleted Item
