### ISSUE TITLE
Web Map "Volunteer Location Tracking" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#798]
Item id 65856bc98cc640d883f00cdf1dfc6b39 references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/22
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/21
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/20
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/19
https://nsec.esri.com/ags/rest/services/Hosted/SignificantLocations/FeatureServer/0

**Comment by conklinbd** [comment]
Deleted Item
