### ISSUE TITLE
Web Map "Model Geography New" references URLs external to NSEC server/portal site

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#799]
Item id 2cbbc834f48e45f2ad645c261c1a26ba references the following URLs that are external to NSEC server/portal site:
https://afmiedev.esri.com/ags/rest/services/test/NewGeography/FeatureServer/0
https://afmiedev.esri.com/ags/rest/services/test/NewGeography/FeatureServer/1
https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer

**Comment by conklinbd** [comment]
Deleted. This should have been replaced by authoritative layers by now.
