### ISSUE TITLE
Web Map "Movement Pattern" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#800]
Item id b8f09773673d4d7aaf9d1748c646a98c references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/SignificantLocations/FeatureServer/0
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/524
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/523
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/522
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/521
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/520
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/519
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/518
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/517
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/516
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/515
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/512
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/514
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/513
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/511
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/510
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/507
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/506
https://nsec.esri.com/ags/rest/services/NationalIntelligence/Movement/FeatureServer/505

**Comment by conklinbd** [comment]
Deleted Item
