### ISSUE TITLE
Web Map "Model Geography" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#801]
Item id b39c3bbdf13e4f829f78dc9c2ab6e96a references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/2
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/1
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/0

Also references service external to NSEC server/portal site:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer

**Comment by conklinbd** [comment]
Deleted, no longer needed
