### ISSUE TITLE
Web Map "WeatherTemp" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#803]
Item id 645aadb7d17c45eeab6c6c0e765fcaa4   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/MAOWTemplateF/MapServer

**Comment by abrowning80** [comment]
@elinz Web Map removed so please close the issue.

**Comment by elinz** [comment]
Verified that web map was deleted. Closing issue.
