### ISSUE TITLE
Web Map "Field_Reports" references URLs external to NSEC server/portal site

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#804]
Item id 917f6353ed564e2bbf481c5a8d26a25d   references the following URLs that are external to NSEC server/portal site:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer

All the operational layers within the web map references services on the NSEC server, so I would expect the basemap layer to reference the applicable basemap service on the NSEC server.

**Comment by conklinbd** [comment]
@erikreid  is this needed for UC? If so you need to fix your basemap by 1700.

**Comment by erikreid** [comment]
Removed from NSEC. is not needed for UC.
