### ISSUE TITLE
Web Map "Maritime Security Collections" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#806]
Item id 2a026ef7abd44145a61c293aa293fa53   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/MaritimeSecurityCollections/FeatureServer/0

NOTE: this web map is referenced in the following operation views:
0e93dc8bd2ee4e2397fd8c60f887c1f3   "Maritime Security Dashboard - Multidisplay"
b5b437f7d65442a6b9ef6d52c0997b16   "Maritime Security Dashboard"

**Comment by joebayles** [comment]
Pretty sure this was for the training class that @conklinbd gave... right @jfrygeo?

**Comment by joebayles** [comment]
Deleted.
