### ISSUE TITLE
Web Map "Maritime Security Collections" (2nd) references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#807]
Item id baca87986fe444ee9b669ac2722e7eeb   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/MaritimeSecurityCollections/FeatureServer/0

**Comment by joebayles** [comment]
Same as https://github.com/Esri/ops-server-config/issues/806.

**Comment by elinz** [comment]
Same issue, different Web Map. There are two web maps with the same name.

**Comment by joebayles** [comment]
Deleted.
