### ISSUE TITLE
Web Map "ISR Mission Report Test" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#809]
Item id 55929b9e5a52459db6cb0cb655a38c6b   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Test/ISRMissionReportTest/FeatureServer/0

NOTE: this web map is referenced in the following operation view:
8d54e3b1266c4f40b57dc7d3143b9688   "ISR Mission Report Dashboard Test"

**Comment by topowright** [comment]
This webmap has been deleted
