### ISSUE TITLE
Web Map "Elevation Test Maps" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#811]
Item id 9d4dc007131247db9cef7d3abb3aade9   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/SignificantEvents/FeatureServer/0

NOTE: this web map is referenced by the web mapping application 73b4fe7ed79345b9ba082128c266bd63   "Elevation Test Maps App".

**Comment by MaryClawson** [comment]
Web map deleted.
