### ISSUE TITLE
Web Map "Key Locations" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#813]
Item id 510dc088cc734d24b481673abb0d5758   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/Area_of_Interest_for_Caching/FeatureServer/0

Also this web map references the following Imagery service twice:
https://nsec.esri.com/ags/rest/services/Basemaps/Imagery/MapServer

**Comment by MaryClawson** [comment]
Web map deleted.
