### ISSUE TITLE
Web Map "ModelGeography-Copy" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#815]
Item id 3d6625c890ba41bcbb016f38124f8da3   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/2
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/1
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/0

**Comment by elinz** [comment]
This is Patrick S. issue. We are currently trying to get him access to the Esri GitHub org.

**Comment by pshowalter** [comment]
This web map has been deleted due to it being obe.
