### ISSUE TITLE
Web Map "Large Event Facilities" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#816]
Item id 8b0370575f2f45d2992d6a675272781d   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/2
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/1
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/0

Also references basemap on external site:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer

**Comment by elinz** [comment]
This is Patrick S. issue. We are currently trying to get him access to the Esri GitHub org.

**Comment by pshowalter** [comment]
This web map has been deleted due to it being obe.
