### ISSUE TITLE
Web Map "Stadiums" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#817]
Item id 24c240741c4c4955b8ff64d2b5ab0471   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/2
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/1
https://nsec.esri.com/ags/rest/services/Hosted/ModelGeography_WFL/FeatureServer/0

Also basemap references external URL. If all your operational layers are on nsec I would expect your basemap would also point to NSEC basemap.

**Comment by elinz** [comment]
This is Patrick S.'s issue. Waiting for him to accept invitation to Esri org.

**Comment by pshowalter** [comment]
These web maps were deleted as obe.
