### ISSUE TITLE
Web Map "Monterey Airport (Compound Map)" references URLs external to NSEC server/portal site

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#820]
Item id 46193871c5c247d2b60b22be0b3e8947   references the following URLs that are external to NSEC server/portal site:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer

All operational layers reference services on the NSEC server/portal so I would expect that the basemap service should also reference the applicable basemap service on NSEC.

**Comment by ScottCecilio** [comment]
This Web Map has had the basemap pointed to: https://nsec.esri.com/ags/rest/services/Basemaps/Imagery/MapServer

**Comment by ScottCecilio** [comment]
I changed the basemap to point to the NSEC Imagery Basemap.
![compoundmap](https://cloud.githubusercontent.com/assets/6999909/8489493/da2d02c8-20e9-11e5-8ca8-32aadaebb679.PNG)
