### ISSUE TITLE
Web Map "Monterey Airport (Enemy Situation)" references URLs external to NSEC server/portal site

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#821]
Item id 4aa5c7731971478f8afeddb1a923dac9   references the following URLs that are external to NSEC server/portal site:
https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer

All operational layers reference services on the NSEC server/portal so I would expect that the basemap service should also reference the applicable basemap service on NSEC.

**Comment by ScottCecilio** [comment]
This Web Map has had the basemap pointed to: https://nsec.esri.com/ags/rest/services/Basemaps/Imagery/MapServer

**Comment by elinz** [comment]
@ScottCecilio You just edited the basemap to point to the nsec imagery basemap? Or you says it always was pointed to the nsec basemap?

**Comment by ScottCecilio** [comment]
I changed the basemap to point to the NSEC Imagery Basemap.  
![enemysituation](https://cloud.githubusercontent.com/assets/6999909/8489482/af840364-20e9-11e5-853a-c66bd95a75ac.PNG)
