### ISSUE TITLE
Web Map "Geonames Demo" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#822]
Item id 43d300b5bbff41a48191e88e71641715   references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/CommercialPlacesOfInterest/MapServer
https://nsec.esri.com/ags/rest/services/SchoolsPlacesOfInterest/FeatureServer/0

**Comment by conklinbd** [comment]
Since this has not been resolved, I assume it is not needed for UC.

**Comment by ACueva** [comment]
Item 43d300b5bbff41a48191e88e71641715 does not exist. Closing.
