### ISSUE TITLE
Trying to overwrite existing service causes administration error:"Another administrative operation is currently accessing the store. Please try again later."

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ops-server-config#826]
When trying to overwrite "MaritimeBoundaries" feature service, I received this error message.

**Comment by conklinbd** [comment]
@jrweakland I believe this was incorrectly assigned to this milestone.

**Comment by jrweakland** [comment]
@jfrygeo - can you try again and see if the service can be overwritten?

**Comment by jfrygeo** [comment]
tried to republish ca. 9/1/2015, but got same errors.

**Comment by jfrygeo** [comment]
Logged with support ticket #01688405
