### ISSUE TITLE
Web Map "CRU Climate Data Map" references a service in the AGS "Test" folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#828]
The web map id 62a27df4c4ca49e5b7b9638810ed6a98 references the following service which is located in the AGS "Test" folder:

Service: 0a637deb8cd64d81947e822d5261eee7   
Name: Climate Southwest Asia
Owner: john6807@AVWORLD         
URL:   https://nsec.esri.com/ags/rest/services/Test/ClimateSwAsia/MapServer   

Services published to the AGS "Test" folder are meant to be temporary services and be deleted. Did you really intend to create a web map that references a test service?

**Comment by mfunk** [comment]
Yes. I'm trying to test build some webmaps based on services. Is there a time limit when I need to remove test services?

**Comment by mfunk** [comment]
Deleting it anyway.

**Comment by jfrygeo** [comment]
I am not sure what this is. This could be deleted.

John

Sent from my iPhone

On Oct 23, 2015, at 6:22 PM, Eric Linz <notifications@github.com<mailto:notifications@github.com>> wrote:


The web map id 62a27df4c4ca49e5b7b9638810ed6a98 references the following service which is located in the AGS "Test" folder:

Service: 0a637deb8cd64d81947e822d5261eee7

Name: Climate Southwest Asia
Owner: @jfrygeo<https://github.com/jfrygeo>

URL: https://[dev server]/ags/rest/services/Test/ClimateSwAsia/MapServer

Services published to the AGS "Test" folder are meant to be temporary services and be deleted. Did you really intend to create a web map that references a test service?
