### ISSUE TITLE
Jenkins build server: PostgreSQL installer is not being copied

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#829]
After build process completes the following folder is empty:
OPSServerInstall\Software\Database\PostgreSQL_9.2.2

Please compare with an Ops Server release and make changes accordingly.

**Comment by ACueva** [comment]
Items manually copied to the UC build.  Changes have been made to build scripts, will test on next build.

**Comment by ACueva** [comment]
9.2.2 folder is still empty. PostgreSQL_9.3.5 is being populated with the installers.  I will need to delete the 9.2.2 folder from copy source and or batch file that is creating the folder structure.

**Comment by ACueva** [comment]
Database is being copied.
