### ISSUE TITLE
Jenkins build server: MessageSimulator and related software not being copied

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#830]
The following folder is empty after a build:
OPSServerInstall\Software\MessageSimulator

It should contain a MessageSimulator folder with the message simulator files.
It should contain the TCPListner folder with the appropriate files.
It should contain the UDPDump folder with the appropriate files.

**Comment by elinz** [comment]
@ACueva After the July 3rd build of Ops Server found that the MessageSimulator, TCPListner, and UDPDump software are being copied to the wrong folder.
Currently copied to:
OPSServerInstall\Geoevent\MessageSimulator\MessageSimulator
OPSServerInstall\Geoevent\MessageSimulator\TCPListner
OPSServerInstall\Geoevent\MessageSimulator\UDPDump

Should be copied to:
OPSServerInstall\Software\MessageSimulator\MessageSimulator
OPSServerInstall\Software\MessageSimulator\TCPListner
OPSServerInstall\Software\MessageSimulator\UDPDump

**Comment by ACueva** [comment]
Changes made.  Verify at next release.

**Comment by ACueva** [comment]
Verified.

**Comment by elinz** [comment]
I have also verified fix in build 20151002_1949.
