### ISSUE TITLE
Jenkins build server: OPSServerInstall\Software\OpsDashboardUtility is not being copied

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#831]
The following folder is missing content:

OPSServerInstall\Software\OpsDashboardUtility

It should contain a Certificate folder and our teams' certificate.
It should also contain the OperationsDashboardUtility.exe and all other related files.

See an exist Ops Server release for an example.

**Comment by ACueva** [comment]
Fixed. To be verified next Jenkins build.

**Comment by elinz** [comment]
Verified. Closing issue.

**Comment by elinz** [comment]
I also verified in build 20151002_1949.
