### ISSUE TITLE
Jenkins build server: copying solution downloads to incorrect location

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#832]
After the build process completed found that the OPSServerInstall\WebApps folder

Contains an "Intel" and "Military" folder which contain all the .zip files from our download site (I think stored somewhere on \\metro). The OPSServerInstall\WebApps folder should only contain the files and folders located in the development server's IIS "SolutionsWeb" folder.

**Comment by ACueva** [comment]
I put these folders in this location for future use.  These templates in zip format can be linked as portal doc link items from its own web server.  I believe this came out of one of the meetings we had regarding how to provide content to people who do not have internet access.
Looping in @joebayles and @lfunkhouser for guidance.

**Comment by joebayles** [comment]
Our templates do need to make it onto the Ops Server, but I don't know what the process is to get there. I thought they were extracted from the NSEC portal in the Released groups or user names?

**Comment by elinz** [comment]
@ACueva modify the build process to create a folder called "Downloads" under OPSServerInstall\WebApps and copy the Military and Intel folders to this Downloads folder instead of having Military and Intel folder directly under WebApps folder.

**Comment by ACueva** [comment]
Downloads folder now exists in the OPSServerInstall\WebApps\ folder.

Verified this is working.

**Comment by elinz** [comment]
I also verified in 20151002_1949.
