### ISSUE TITLE
Jenkins build server: OPSServerInstall\Server\Staging\Caches contains .site folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#834]
After build process the folder OPSServerInstall\Server\Staging\Caches contains the .site folder from our development server. We should not copy this folder to the build. If left in the build and someone copies this with the cache to their target server it will overwrite their Ops Server and may corrupt their server.

**Comment by ACueva** [comment]
Modified ant script.  .site folder no longer gets included with the cache.
Verifying next jenkins build.

**Comment by ACueva** [comment]
Verified

**Comment by elinz** [comment]
I also verified fixed in build 20151002_1949.
