### ISSUE TITLE
Hosted service CA_Measles_17APR2015/FeatureServer does not have a service definition item.

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#835]
The hosted service "California Measles Outbreak" item exists id:406fb20818ca4b1081b6cfa7fdc93305 but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: this hosted feature service was published from a .csv file and not from ArcGIS Desktop or ArcGIS Pro, which means that this service will not be published to any of the UC servers.

**Comment by mfunk** [comment]
I am building a demonstration for "Collaboration and Reporting Using Portal for ArcGIS" that shows Smart Mapping and non-address geocoding using a CSV file, and how it can be used in building web maps and apps.

Should I be using a different server?

**Comment by elinz** [comment]
Should you use a different server? Not necessarily. By using a CSV file and publishing a hosted service from it means that the service won't be automatically published during the Ops Server installation. This service would have to be manually published from the csv item that it on portal.

**Comment by mfunk** [comment]
The first step in the demo is me showing the audience how to publish a CSV to Portal as a hosted service. Afterwards I use the hosted feature service in other maps and apps.

**Comment by elinz** [comment]
This will be okay.
