### ISSUE TITLE
Jenkins build server: modify to copy Esri Maps for Office portal resources

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#838]
Create the following folder structure in the output build:
OPSServerInstall\Software\EsriMapsForOffice\WebContent

Copy source from:
OpsServerBuilds\Archive\ESRI Software\EsriMapsForOffice

**Comment by ACueva** [comment]
Made changes to Jenkins build. Verified.

Changes in folder structure made here:
https://github.com/elinz/ops-server-config/pull/2

**Comment by elinz** [comment]
I also verified in build 20151002_1949.
