### ISSUE TITLE
Jenkins build server: SolutionsWeb folder should be copied to OPSServerInstall\WebApps\SolutionsWeb folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#839]
Modify build process so contents of development server SolutionsWeb folder is copied to OPSServerInstall\WebApps\SolutionsWeb folder instead of directly under the OPSServerInstall\WebApps.

**Comment by elinz** [comment]
@ACueva Correction to my comments above. Under the WebApps folder should be a folder named "wwwroot". 

OPSServerInstall\WebApps\wwwroot
OPSServerInstall\WebApps\wwwroot\SolutionsWeb
OPSServerInstall\WebApps\wwwroot\Downloads\Military
OPSServerInstall\WebApps\wwwroot\Downloads\Intel

Look at 2014_Q4 release for example.

**Comment by ACueva** [comment]
Pull request submitted to address this issue:

https://github.com/elinz/ops-server-config/pull/2
