### ISSUE TITLE
Can't re-publish MAOWData map service on Ops Server

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#842]
@abrowning80 @jrweakland Need help figuring out this issue. Was this service just a test service? I see that the portal item summary and description is set to "q" (also there is an Image service of the same name, so maybe this was just a test/temp service that was meant to be deleted).

Using the ops-server-config repo scripts to publish non-hosted services to an Ops Server I receive the following error when running PublishToOpsServer.py script:

        *ERROR encountered:
        Error Info:
        ERROR 001487: Failed to update the published service with the server-side data location. Please see the server's log for more details.
ERROR 001369: Failed to create the service.
Failed to execute (Publish Service Definition).
Failed.
ERROR: the server's publishing job didn't succeed.
Failed to execute (UploadServiceDefinition).

Looking at the ArcGIS Server logs I find the following:

SEVERE	Jul 5, 2015, 7:58:10 AM	Error executing tool. PublishServiceDefinition Job ID: j8f2750dd38784e369f47003456b211c8 : ERROR 001487: Failed to update the published service with the server-side data location. Please see the server's log for more details. ERROR 001369: Failed to create the service. Failed to execute (Publish Service Definition).	System/PublishingTools.GPServer
SEVERE	Jul 5, 2015, 7:58:10 AM	Failed to create the service.: Xml Parsing failed. Reason:End tag 'ServiceURL' does not match the start tag 'DatasetName'. Linepos:84 Source:MAOWDataMosaic Dataset<MosaicMethod>ByAttribute</MosaicMethod><LockImageID></LockImageID><TileOrderField>StdTime</TileOrderField><TileOrderBase>0</TileOrderBase><MosaicOperator>First</MosaicOperator><SortAscending>FALSE</SortAscending><ViewPointX>0.0</ViewPointX><ViewPointY>0.0</ViewPointY>None75OpImpactUAVCloudCeilingDisplays impact of cloud cover on Unmanned Aerial Vehicles (UAVs)OpImpactUAVCloudCeilingDisplays impact of cloud cover on Unmanned Aerial Vehicles (UAVs)Statistics and Histogram FunctionAssociates/adds statistics and histograms.UNKNOWNRasterStatisticsHistogramsRaster_2015115_113326_154Raster Function TemplateA raster function template.Remap FunctionRemaps pixel values using user-defined pixel ranges or an external table.UNKNOWNRasterInputRangesNoDataRangesOutputValuesTableUseTableAllowUnmatchedInputFieldOutputFieldInputMaxFieldRemapTableTypeRaster Function TemplateA raster function template.Local FunctionPerforms operations.UNKNOWNOperationExtentTypeCellsizeTypeRastersOperation_2015224_245_85650falseExtentType_2015224_245_8560falseCellsizeType_2015224_245_8560falseRasters_2015224_245_856Raster Function TemplateA raster function template.Local FunctionPerforms operations.UNKNOWNOperationExtentTypeMAOWDataMosaic Dataset<MosaicMethod>ByAttribute</MosaicMethod><LockImageID></LockImageID><TileOrderField>StdTime</TileOrderField><TileOrderBase>0</TileOrderBase><MosaicOperator>First</MosaicOperator><SortAscending>FALSE</SortAscending><ViewPointX>0.0</ViewPointX><ViewPointY>0.0</ViewPointY>None75OpImpactUAVCloudCeilingDisplays impact of cloud cover on Unmanned Aerial Vehicles (UAVs)OpImpactUAVCloudCeilingDisplays impact of cloud cover on Unmanned Aerial Vehicles (UAVs)Statistics and Histogram FunctionAssociates/adds statistics and histograms.UNKNOWNRasterStatisticsHistogramsRaster_2015115_113326_154Raster Function TemplateA raster function template.Remap FunctionRemaps pixel values using user-defined pixel ranges or an external table.UNKNOWNRasterInputRangesNoDataRangesOutputValuesTableUseTableAllowUnmatchedInputFieldOutputFieldInputMaxFieldRemapTableTypeRaster Function TemplateA raster function template.Local FunctionPerforms operations.UNKNOWNOperationExtentTypeCellsizeTypeRastersOperation_2015224_245_85650falseExtentType_2015224_245_8560falseCellsizeType_2015224_245_8560falseRasters_2015224_245_856Raster Function TemplateA raster function template.Local FunctionPerforms operations.UNKNOWNOperationExtentType	System/PublishingTools.GPServer
SEVERE	Jul 5, 2015, 7:58:10 AM	Failed processing the gis-resource in the service definition.	System/PublishingTools.GPServer
SEVERE	Jul 5, 2015, 7:58:10 AM	Updating the server data path for layer Op Impact UAV Cloud Ceiling failed. Attempted server path was DATABASE=C:\OpsServer\Data\MAOW\Geodatabase\MAOWData.gdb. Please verify the path exists on the server.	System/PublishingTools.GPServer

**Comment by jrweakland** [comment]
@elinz and @abrowning80 - I believe that this service was a test and not a "final" product.

**Comment by elinz** [comment]
@abrowning80 Please verify so we can't delete this service if it was just a test. Thank you.

**Comment by abrowning80** [comment]
@elinz this service was originally just for a test and a presentation but it is the one that I am now hoping to use for UC but can't re publish to it at present.  Sorry for delay in reply was not quite sure what I was going to aim to do for UC.

**Comment by jrweakland** [comment]
@abrowning80 and @joebayles - please delete or move to next milestone if not needed for 2015 UC.

**Comment by abrowning80** [comment]
@elinz  This was a test service but wasn't used for UC, Am hoping that once i have final sign off of my MAOW v2 stuff then I will be updating all this to use it as the final service.  Please close this issue

**Comment by elinz** [comment]
Closing issue for now.
