### ISSUE TITLE
Image Discovery app not loading on NSECMINI07

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/ops-server-config#844]
The Image Discovery app IS working as expected on NSEC: https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/ImageDiscovery/

It is NOT loading on NSECMINI07: https://nsecmini07.esri.com/SolutionsWeb/Apps/NationalIntel/ImageDiscovery/

**Comment by conklinbd** [comment]
@elinz I had to change a setting in the config.js 
It currently says isWebTier: true.

I changed it to isWebTier: false and this seems to have corrected the issue.
I also signed in to the portal, this might have been related.

We will need to make this change for all web app builder apps.

**Comment by conklinbd** [comment]
@nfeuerstein please verify and close.

**Comment by nfeuerstein** [comment]
Once I deleted my browser cache, it loaded.  Closing the issue.  @NatalieCampos - it should be up now.
