### ISSUE TITLE
CopyData.py is not repairing Mosaic Dataset paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#845]
Could be an issue with file permissions. For the Trial UC server I used robocopy to copy the "Data" folder instead of RichCopy or the CopyData.py script.

Copy a small set of data containing mosaic datasets in file geodatabases using other methods of file copy and run the repair code block.

**Comment by elinz** [comment]
This is an issue with the Repair Mosaic Dataset Paths geoprocessing tool; search/replace not working if UNC path and path starts with "n" (maybe other characters such as "t").

**Comment by conklinbd** [comment]
@elinz is this issue fixed? Are you using 10.4 to "preprocess" the mosaics before distributing?

**Comment by elinz** [comment]
@conklinbd @ACueva The issue in the GP has been fixed in 10.4. For preparing the ops server release we will be running the  script ops-server-config\Publish\Server\RepairMosaicDatasets.py (new script to allow users to set "search" and "replace" paths) on a machine with 10.4 Desktop. Today I will be performing another test with the latest desktop build to confirm that this fix is still working.

**Comment by elinz** [comment]
@conklinbd For the Fall release we ran the ops-server-config\Publish\Server\RepairMosaicDatasets.py script using a daily build of 10.4. Moving this to version - after next since our plan is to use 10.4 for the Spring release and I would like to verify this on 10.4 ArcGIS Server.

**Comment by elinz** [comment]
Retested the ops-server-config\Publish\Server\RepairMosaicDatasets.py script on ArcGIS Server 10.4.1 which executes the out of the box RepairMosaicDatasets gp tool and it is working correctly. In the Ops Server Installation Guide I instruct people to use robocopy, and CopyGDBs.py  instead of the CopyData.py script so I'm going to close this issue.
