### ISSUE TITLE
Engagement Area template Error 500: Item does not have a file

### ISSUE THREAD

**Issue by BobBooth** [Esri/ops-server-config#846]
The Engagement Area template at: 
https://nsecmini07.esri.com/arcgis/home/item.html?id=189691eccf1b47a2afa220d02e7c0483 
is shared with Everybody but not released yet. 
When I click the download link for it I get:
Error
Item does not have a file.
Error: 500

I know it isn’t released, which might be why it didn’t get an item, but someone might want to use it.
My other item, the Control Measures LPKX downloads correctly.

**Comment by elinz** [comment]
@BobBooth It has a portal item; it just doesn't have the associated file. Does the associated item on the dev portal have the file?

**Comment by BobBooth** [comment]
@elinz  - yes, NSEC has an item for it.

**Comment by elinz** [comment]
@BobBooth Check with your product lead if this is really needed for UC. If not, change the milestone to version after next.

**Comment by conklinbd** [comment]
@elinz this is an issue for UC. All of the Pro project templates have this issue. There is no file associated with the time.

**Comment by elinz** [comment]
@conklinbd Roger that.

**Comment by elinz** [comment]
Added fix to https://github.com/elinz/ops-server-config/tree/v.next repo. Extract portal content from dev server and verified that .aptx files are being downloaded from "Project Template" items. Closing issue.
