### ISSUE TITLE
Web Map "POI Test Map" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#848]
Item id fd34995f3b214d6e8498c0109a15d229 references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/PointsOfInterestFeatureService/MapServer

**Comment by conklinbd** [comment]
SInce this has not been resolved, I assume it is not needed for UC.

**Comment by ACueva** [comment]
Item fd34995f3b214d6e8498c0109a15d229 no longer exists on the portal. Closing issue.
