### ISSUE TITLE
IntelFoundation enterprise geodatabase contains raster datasets and mosaic dataset

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#850]
The IntelFoundation enterprise geodatabase contains the following raster datasets and mosaic dataset:
intelfoundation.sde.DistanceFromAllWeatherRoadsClip
intelfoundation.sde.DistanceFromFairWeatherRoadsClip
intelfoundation.sde.DistanceFromForestEdgeClip
intelfoundation.sde.DistanceFromGovernmentStudy
intelfoundation.sde.DistanceFromMajorRoadsStudy
intelfoundation.sde.DistanceFromOceanClip
intelfoundation.sde.DistanceFromSettlementsStudy
intelfoundation.sde.DistanceFromTest
intelfoundation.sde.DistanceFromTrailsClip
intelfoundation.sde.DistanceFromValuableResourcesStudy
intelfoundation.sde.DistanceFromWaterSourceClip
intelfoundation.sde.DistanceFromWaterStudy
intelfoundation.sde.SpeedModelClip
intelfoundation.sde.LandCover (mosaic dataset)

Team guidance is not to store mosaic datasets and raster datasets within an enterprise geodatabase; instead store mosaic dataset in file geodatabase and raster datasets as files.

Having the raster data in an enterprise geodatabase is having a significant time impact on the Ops Server build process and setting up an Ops Server. The time to copy the IntelFoundation enterprise geodatabase to file geodatabase (which is used as the distribution format) is around 8-10 hours. Which means the ops server build process is running around 24 hours.

The data needs to be moved to file based geodatabase/files and any affected services will need to be republished (with overwrite option).

**Comment by nfeuerstein** [comment]
We need to move our raster/mosaic datasets - "distance from" and Land Cover - from the SDE to a FGDB. 

@kAilshie @ircampbell  - I have created a FGDB here: \\nsecdata\data\DerivedLayers\PredictiveAnalysis.gdb that we can use for the Distance From rasters.

@dfoll - it would make sense to have the FGDB for LandCover created here: \\nsecdata\data\FoundationOverlays\LandCover

**Comment by elinz** [comment]
@nfeuerstein @kAilshie @ircampbell @dfoll I already have the IntelFoundation enterprise copied to a file geodatabase. I can copy this file geodatabase as both the \nsecdata\data\DerivedLayers\PredictiveAnalysis.gdb and nsecdata\data\FoundationOverlays\LandCover then you can just delete what you don't need.

Just let me know and I can start this process for you guys.

**Comment by nfeuerstein** [comment]
That would be great Eric!  Thank you.

**Comment by elinz** [comment]
I will start this right now; I'll let you know when it's done.

**Comment by nfeuerstein** [comment]
:+1:

**Comment by elinz** [comment]
Copying IntelFoundation.gdb to \\nsecdata\data\DerivedLayers folder. After it's copied we can rename and delete what you don't need.

**Comment by elinz** [comment]
- Raster datasets now exist in \\nsecdata\data\DerivedLayers\PredictiveAnalysis.gdb (NOTE: there is a "SpeedModelClip" raster dataset in this fgdb. Don't know if this is also used by Predictive Analysis or should be located elsewhere). I've deleted this data from the IntelFoundation enterprise geodatabase.

- The "LandCover" mosaic dataset now exists in \\nsecdata\data\FoundationOverlays\LandCover\LandCover.gdb (NOTE: there was already a "LandCover" mosaic dataset in \\nsecdata\data\FoundationOverlays\LandCover\NLCD\NLCD.gdb and references the same data. So the \\nsecdata\data\FoundationOverlays\LandCover folder, which I created, could probably be deleted. I'll leave that up to your team in case the properties of the mosaic dataset were actually different and you need the two mosaic datasets). I've deleted this data from the IntelFoundation enterprise geodatabase.

- Any services that reference this data needs to be republished to point to the new data locations.

**Comment by conklinbd** [comment]
@nfeuerstein and @dfoll  are these going to be republished by 1700 today?

**Comment by nfeuerstein** [comment]
KIan is starting to publish services now for the "distance from" services.  @dfoll what about Landcover?
