### ISSUE TITLE
Add silent install functionality to Predictive Analysis installer

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#852]
@kAilshie - We're going to try to streamline the process of installing the necessary dlls using your installer.  If we had the ability to install silently this would help us a lot.

Basic functionality needed:

- [ ] Flag for install location. i.e. (setup.exe -d c:\directory)
- [ ] Flag for install silently. (usually -s)

**Comment by elinz** [comment]
@kAilshie What's the status of creating the silent installer? I need to add the installation of the Predictive Analysis tools to the Ops Server installation with the next week or so. Thanks.

**Comment by kAilshie** [comment]
Last I spoke about this was with @ACueva before the UC.  We discussed that the installer was made as a microsoft installer project.  This link shows some options that I believe are for running it silently:  https://support.microsoft.com/en-us/kb/227091

I have not verified that the command line options work for the PA web installer but I believe it would look something like this: **msiexec.exe /i "C:\PAInstaller.msi" /qn**.  @ACueva , I know we talked a while back about this but have you by chance tested to see if this works on any of the server machines?  If not, I could try to squeeze a test in today but if I am unable to I will be out of the office for the rest of the week.

**Comment by conklinbd** [comment]
@kAilshie this issue is still assigned to you. Can you please confirm this works or assign to @ACueva

**Comment by conklinbd** [comment]
Moving to after next. We already install this.

**Comment by kAilshie** [comment]
@conklinbd  @ACueva  I am not in the office and will not be able to address this until monday, since this is going to the next milestone will it be ok that it waits until then?

**Comment by elinz** [comment]
@kAilshie Closing this issue. As I recall, the installer has all the functionality I need. If necessary we can reopen at a later date.
