### ISSUE TITLE
Predictive Analysis Execute Query if published to root folder

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#854]
@nfeuerstein, @dfoll - FYI

@kAilshie and I were able to identify the issue that was causing the Predictive Analysis gp service to fail.  When the service is published to a sub-folder i.e. NationalInteligence, it fails.
We were able to publish it to the root ArcGIS Server directory and were able to get the gp service to work.

**Comment by kAilshie** [comment]
One thing I'd like to note is that currently this issue is only affecting the nsec and nsecmini machines.  On the other installations I have performed I am able to publish to a server sub folder without any issues.

**Comment by jrweakland** [comment]
@elinz + @ACueva - This there any resolution to this issue?

**Comment by conklinbd** [comment]
I think we need to treat this as a known issue for the Ops Server, we can't fix for this release and the impact is monor.
