### ISSUE TITLE
Service "Hosted//Ebola_Outbreak.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#855]
@nfeuerstein Believe this was a service that Sarah S. published, don't know for sure since the portal item was deleted and the ownership is determined by portal item. Can't assign to Sarah and it looks like she does not have access to GitHub...we are checking. If this service as meant to be deleted you as a portal admin will be able to see the service and delete through AGS connection.

ERROR: Service "Hosted//Ebola_Outbreak.MapServer" is associated with a portal item (cf99f0d389464018b1054df2e7a789cc; MapServer) that does not exist.

Most likely cause, publisher intent was to delete the service, but the hosted service was deleted incorrectly. To delete a hosted service, you delete the portal item. If you delete the service through an AGS connection the service will be deleted, but the portal item remain.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
