### ISSUE TITLE
Hosted service Cumulative_Num_Cases_Ebola_Districts/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#858]
The hosted service "Districts Reporting Ebola Cases in West Africa" item exists id:32cfc69cbedf45078a6ee67e11bdf9c6but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
