### ISSUE TITLE
Hosted service Ebola_Burial_Teams/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#859]
The hosted service "Ebola Burial Teams" item exists id:37af79a219614f899d12cf5564a13dba but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
