### ISSUE TITLE
Hosted service ebola_outbreaks/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#860]
The hosted service "Ebola Outbreaks in West Africa" item exists id:45d4ccf4653d45c0ab4479d12a39e21b but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by elinz** [comment]
@sschwoppe I see an "ebola_outbreaks" service published to the AGS root folder. Was the intention to publish this as a hosted service?

**Comment by sschwoppe** [comment]
@elinz I deleted the item and republished.

**Comment by elinz** [comment]
@sschwoppe The service wasn't deleted. Make sure when you delete a non-hosted service you delete through the AGS connection, which will delete the service and the portal items. If you delete by deleting the portal items, only the portal items are deleted and not the service. It will appear that the service was deleted because ownership is control by the portal item, so if the item is deleted it removes your access to the service. I've deleted the service.

FYI. To delete a hosted service, you have to delete the portal item which will delete the portal item and the service.

**Comment by sschwoppe** [comment]
@elinz Okay.  I thought deleting the portal item would be enough.  Which folder do I need to use to publish items?

**Comment by elinz** [comment]
@sschwoppe If you are publishing a hosted service you won't actually be able to choose the folder. It will automatically be published to the "Hosted" folder. If you are publishing a hosted service from ArcGIS Desktop you will need to select the "My Hosted Services" connection when prompted for a connection. If you are publishing from ArcGIS Pro, all services are published as hosted so you won't have to select a folder.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
