### ISSUE TITLE
Hosted service Liberia_Border_Crossings/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#861]
The hosted service "Liberia Border Crossings" item exists id:df32b0c4a281487b8a4d9716d6a6a9aa but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
