### ISSUE TITLE
Hosted service Field_Reports_Daraa_Syria/FeatureServer does not have a service definition item 

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#862]
The hosted service "Field Reports Dar'a, Syria" item exists id:0fb9789ba3e6491b947da72e8c79c0c5 but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
