### ISSUE TITLE
Hosted service Damage_Assessment_in_Daraa_Syria/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#863]
The hosted service "Damage Assessment in Dar'a Syria" item exists id:abafa1c91d5349548b7fb65c10ffd194 but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by jrweakland** [comment]
@sschwoppe

**Comment by elinz** [comment]
@jrweakland Thanks Jim. We couldn't assign to proper person until her account was added to the Esri org. I'm reassigning now.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
