### ISSUE TITLE
Hosted service Ebola_Healthcare_Facilities_in_Western_Africa/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#864]
The hosted service "Ebola Healthcare Facilities in Western Africa" item exists id:eb718f3470b94946ad3814f3887092fc but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Service owned by Sarah S.

**Comment by conklinbd** [comment]
This was fixed as part of the release process I assisted @nfeuerstein with.
