### ISSUE TITLE
Hosted service Ebola_Cases/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#865]
The hosted service "Ebola Cases" item exists id:376ff64becf1408ea7cfaffdddf531f7 but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

**Comment by mfunk** [comment]
This hosted feature service is created from importing a CSV to Portal as part of the first demo in Collaboration and Reporting. This CSV and service will be deleted before each dry run of the demo.
