### ISSUE TITLE
Hosted service Country_Boundaries/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#866]
The hosted service "Country Boundaries" item exists id:a7fc5565cd264a92b7397311310c719c but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

**Comment by mfunk** [comment]
This hosted feature service is created from importing a zipped Shapefile to Portal as part of the first demo in Collaboration and Reporting. This SHP and service will be deleted before each dry run of the demo.
