### ISSUE TITLE
Web Map "OppImpactCCMTemp" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#869]
Item id 549db75cf51645a69a837facd2dd580f references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/MAOWData/MapServer

**Comment by abrowning80** [comment]
@elinz This is connected to the service I was trying to publish that Avi has just got to work.  Am going to work on it now and tomorrow so should be resolved asap.  This is the same for all the other errors.

**Comment by jrweakland** [comment]
:+1:

**Comment by abrowning80** [comment]
@elinz  issue resolved so issue can be closed thanks

**Comment by elinz** [comment]
Verified. Closing issue.
