### ISSUE TITLE
Map Server item MAOWData exists without actually map service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#870]
Map service item 11489191107f4b7c868a2e6c46985fa5 exists for service https://nsec.esri.com/ags/rest/services/Military/MAOWData/MapServer , but the service doesn't actually exist.

It's possible that the user didn't delete the service correct. For non-hosted services, you must delete the service through the ArcGIS Server connection, which will delete the service and the associated portal items.

Delete the portal item.

**Comment by jrweakland** [comment]
@elinz - The ArcGIS for Server connection from ArcMap (for example) can delete this service correctly, right?

**Comment by elinz** [comment]
@jrweakland @abrowning80 Aidan ran into a problem while deleting the service through AGS connection; I was able to delete the remnants of the delete attempt through the AGS connection.

The following item can safely be deleted through portal now that this item is not associated with the service:
https://nsec.esri.com/arcgis/home/item.html?id=11489191107f4b7c868a2e6c46985fa5

**Comment by abrowning80** [comment]
@elinz Item has been deleted issue can now be closed.

**Comment by elinz** [comment]
Verified. Closing issue.
