### ISSUE TITLE
Web Map "OpImpactADTemp" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#873]
Item id c1cdc2168f524e33b0b422a5e31ec938references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Military/MAOWData/MapServer

**Comment by abrowning80** [comment]
@elinz  Issue resolved layers have been fixed, can now be closed.

**Comment by elinz** [comment]
Verified. Closing issue.
