### ISSUE TITLE
Web Map "Monterey Airport (Overview)" references services/layers that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#875]
Item id e9afca99ffa14bf0b064df6631210f60 references the following services/layers that do not exist:
https://nsec.esri.com/ags/rest/services/Hosted/CountIncidentsByLOC/MapServer

**Comment by jrweakland** [comment]
If I remember correctly, this is a result from testing by @ScottCecilio. If so, please delete Scott.

**Comment by ScottCecilio** [comment]
This is a needed WebMap that just needed the layer to be re-pointed.  This is very much needed for my LandOpS presentation and the layer has been re-pointed.
