### ISSUE TITLE
Can't create Web Mapping App from scratch

### ISSUE THREAD

**Issue by mfunk** [Esri/ops-server-config#877]
This isn't a huge problem as there is a simple workaround, but something that needs to be noted. I'm not able to create a Web Mapping App from scratch in [dev server]. At the step to configure the app I get a 404 error. The item is created, but cannot open or configure it. Here's what I'm doing:

1) Open *My Content*
2) *Create* >> *App* >> *Using a Template*
3) Select *Story Map Journal* (page 4) in New Web Mapping Application, and click *Next*
5) Give it a title, Tags, and Description, and click *Done*
6) **Server Error: 404 - File or directory not found.**

@mfunk Deleted screenshot. contained internal server name.

7) click Back button on browser, which brings you back to My Content
8) Click the Web Mapping Application which was created
9) Item page opens, click *Configure App*, and you get the same error. This happens if you try to *Open* too.

The work around seems to be that you should start with an existing web map open already, then Share it as a Story Map Journal item.

**Comment by conklinbd** [comment]
This is known issue with Portal 10.3.1 and is planned for fix in 10.4

**Comment by jrweakland** [comment]
@mfunk - please check when we start to use 10.4 on NSEC.

**Comment by mfunk** [comment]
Tested this today with the Story Map Tour (as Story Map Journal is deprecated). Had a few warnings about creating map tour point feature service, but eventually it worked and basic map service is now done.
