### ISSUE TITLE
Service "Military//OperationalWeather.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#878]
ERROR: Service "Military//OperationalWeather.MapServer" is associated with a portal item (0d540103554243d09ed5df2443022ce5; MapServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by conklinbd** [comment]
@abrowning80  this may be your issue.

**Comment by abrowning80** [comment]
@elinz all deleted now so should be clean

**Comment by elinz** [comment]
Verified. Closing issue.
