### ISSUE TITLE
Service "NationalIntelligence//LanguagesInUkraineByOblast.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#879]
Service "NationalIntelligence//LanguagesInUkraineByOblast.MapServer" is associated with a portal item (aa4cbc7a6d3b4eabaa53dfa03728da79; MapServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by jrweakland** [comment]
@CraigCleveland

**Comment by CraigCleveland** [comment]
@elinz @jrweakland This service has been deleted. I believe it was "leftover" from initial publishing attempts, which were all failing, so I subsequently went the hosted route which work successfully.

**Comment by nfeuerstein** [comment]
Confirmed service was deleted.
