### ISSUE TITLE
Hosted service LanguagesInCrimeaTiles/MapServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#880]
The hosted service "Languages in Crimea (Tile Service)" item exists 93f8ddef0a5a462e8730940234b13b9c but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Owned by Craig C. but looks like he doesn't have GitHub account or has account but no access to Esri org.

**Comment by jrweakland** [comment]
@CraigCleveland

**Comment by CraigCleveland** [comment]
@elinz @jrweakland Ditto to previous comment.  Will re-work the web maps as a workaround for this release.

**Comment by elinz** [comment]
@CraigCleveland FYI: Re-ran report and the hosted service item still exists. Without service definition portal item, the service won't be published during stand-up of Ops Server. Options are to republish the hosted service so service definition item is uploaded to portal or delete this hosted service. Thanks.

**Comment by CraigCleveland** [comment]
@elinz see my comment on previous thread for full details.  Short version is I plan to utilize only feature services...

**Comment by elinz** [comment]
@CraigCleveland Please delete the hosted LanguagesInCrimeaTiles/MapServer map service. Thanks.

**Comment by CraigCleveland** [comment]
@elinz - deleted.

**Comment by elinz** [comment]
@CraigCleveland hosted service LanguagesInCrimeaTiles.MapServer service and portal item 93f8ddef0a5a462e8730940234b13b9c still exist. Let me know and I can delete this for you.

**Comment by CraigCleveland** [comment]
@elinz they should be gone now.  The previous delete failed for some reason...
