### ISSUE TITLE
NSEC Portal Searching for Key words

### ISSUE THREAD

**Issue by pshowalter** [Esri/ops-server-config#882]
I did search on nsec portal for "maot", and "Military Aspects of Terrain" using "Search All Content" it returned:
https://nsec.esri.com/arcgis/home/item.html?id=bfd513dd62d345bcb07a13aaf3a1e1fc which is a Web Map titled "MaOT Product", (also returned the tag libraries).   
It should have also returned:
https://nsec.esri.com/arcgis/home/item.html?id=87f169b7dd324279b2a1bc49ea33706c which is the ArcGIS Pro Template for MAoT.

**Comment by elinz** [comment]
Not a bug. You have to check "Show ArcGIS Desktop Content" on the left side of the search results page:
![image](https://cloud.githubusercontent.com/assets/4635490/8648939/14659724-291a-11e5-8071-7249dd6dffe0.png)

**Comment by jrweakland** [comment]
:+1:
