### ISSUE TITLE
Apps built with Web AppBuilder dev edition (v1.3) are not loading

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/ops-server-config#883]
Apps built with Web AppBuilder dev edition (v1.3) (grabbed 1.3 off metro) and they are not loading when deployed to nsec (they work find within web appbuilder:

Image Observables: https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/ImageObservables/

It seems that https://nsec.esri.com/ is appended to the URL - GET https://nsec.esri.com/https://nsec.esri.com/sharing/generateToken?f=json&callback=dojo_request_script_callbacks.dojo_request_script0

**Comment by conklinbd** [comment]
@NatalieCampos is this problem resolved with the version you got from Previn?

**Comment by conklinbd** [comment]
I can resolve the url issue. Not sure if there are more issues:
Give this a try:
https://nsec.esri.com/SolutionsWeb/Apps/NationalIntel/ImageObservablesTest/

**Comment by nfeuerstein** [comment]
It loaded!  But, now its doing some weird stuff with widget placement.  I'm going to try installing the latest build from devtopia that Campos sent out and see if that resolves anything. (T-1)

**Comment by conklinbd** [comment]
@nfeurstein I think this was resolved with a more recent build Can you confirm?

**Comment by nfeuerstein** [comment]
Resolved.
