### ISSUE TITLE
Service "Test//Climate.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#884]
ERROR: Service "Test//Climate.MapServer" is associated with a portal item (96bf1c94e296460382e9299accf4b1fa; MapServer) that does not exist.

Most likely cause is that publisher deleted the service incorrectly. Non-hosted service should be deleted through an AGS connection in desktop and not by deleting the portal service item.

If this service was truly meant to be deleted, let me know and I can delete this service.(important as if it's not deleted then service will be published to UC machines utilizing memory that can be used for required services.

**Comment by abrowning80** [comment]
@jrweakland @joebayles This one is nothing to do with me sorry

**Comment by joebayles** [comment]
@elinz delete this service please.

**Comment by elinz** [comment]
Checked today and this service no longer exists. Closing issue.
