### ISSUE TITLE
Service "NationalIntelligence//DistanceFromAllWeatherRoads.ImageServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#885]
ERROR: Service "NationalIntelligence//DistanceFromAllWeatherRoads.ImageServer" is associated with a portal item (de31d9e33744495db60a10aaa19f208d; ImageServer) that does not exist.

Most likely cause is that publisher deleted the service incorrectly. Non-hosted service should be deleted through an AGS connection in desktop and not by deleting the portal service item.

If this service was truly meant to be deleted, let me know and I can delete this service.(important as if it's not deleted then service will be published to UC machines utilizing memory that can be used for required services.

**Comment by joebayles** [comment]
@elinz delete this service please.

**Comment by dfoll** [comment]
this can be marked as closed, but i will leave that to @elinz  since he has been reassigned. the service in question here that was missing a portal item was no longer needed and was just deleted incorrectly. I watched eric delete this service. so even as this is being written, it no longer exists

**Comment by joebayles** [comment]
Roger! :+1:

**Comment by elinz** [comment]
@joebayles @dfoll This service still exists. I will delete.

**Comment by elinz** [comment]
@joebayles @dfoll Service has been deleted.
