### ISSUE TITLE
Service "Test//ClimateSwAsia.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#886]
ERROR: Service "Test//ClimateSwAsia.MapServer" is associated with a portal item (0a637deb8cd64d81947e822d5261eee7; MapServer) that does not exist.

Most likely cause is that publisher deleted the service incorrectly. Non-hosted service should be deleted through an AGS connection in desktop and not by deleting the portal service item.

If this service was truly meant to be deleted, let me know and I can delete this service.(important as if it's not deleted then service will be published to UC machines utilizing memory that can be used for required services.

@jrweakland Should this be assigned to Aidan?

**Comment by abrowning80** [comment]
@jrweakland @joebayles This one is nothing to do with me sorry

**Comment by joebayles** [comment]
@elinz delete these please.

**Comment by elinz** [comment]
I deleted this service.
