### ISSUE TITLE
SD file does not exist for service Military//OperationalWeatherAB.MapServer

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#887]
The SD files for this service does not exist in the ArcGIS Server maintained system folders and therefore will not be published to the UC servers.

If this service is need for UC please re-publish and I can re-verify if the .sd file was uploaded to server.

**Comment by abrowning80** [comment]
No am going to delete this.

**Comment by abrowning80** [comment]
@elinz  Issue resolved can now be closed.

**Comment by elinz** [comment]
Verified that this service no longer exists, therefore the .sd file is no longer necessary. Closing issue.
