### ISSUE TITLE
"Data\Sustainment" folder contains web applications

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#891]
The following folder contains web application files:
\\nsecdata\data\Sustainment\WebApps

Web applications should only be stored in the shared "SolutionsWeb" folder.

**Comment by jrweakland** [comment]
These might be from @abrowning80 and @joebayles preparing for UC.

**Comment by abrowning80** [comment]
@elinz  Issue resolved as have deleted the folder as was stuff for UC but is no longer relevant. Issue can now be closed.

**Comment by elinz** [comment]
Verified that folder data\Sustainment no longer exists. Closing issue.
