### ISSUE TITLE
Some thumbnails are not being transferred during republishing of hosted services

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#893]
For examples:
![image](https://cloud.githubusercontent.com/assets/4635490/8650819/1ca03b1e-292a-11e5-90cf-e5b5f8342447.png)

NOTE: noticed that export and tracking properties are not available on this item.

**Comment by jrweakland** [comment]
@elinz - I have noticed that sometimes when I create a service I get something similar to the image. But if I refresh the page, the item displays as expected. Think that might be related?

**Comment by elinz** [comment]
@jrweakland Investigating this issue right now.

**Comment by elinz** [comment]
Published hosted services several times and the problem with thumbnails is not a consistent problem. Believe this could be a timing/resource issue. I have put delays before each of the code blocks that perform transfer of item information and sharing properties and based on the testing so far this looks like it may have solved the issue. Closing issue for now. If we find the issue has cropped up again I'll reopen the issue.

**Comment by elinz** [comment]
Fixed in Esri\ops-server-config v.next.
