### ISSUE TITLE
Critical Facility feature class has null values in all of the attributes when published to destination machine.

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#894]
Critical Facility feature class has null values in all of the attributes when published to destination machine.

All fields have valid values on NSEC server but when viewed on the destination machines the field values are null.

https://nsecmini01.esri.com/ags/rest/services/NationalIntelligence/KeyLocations/FeatureServer/2/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=*&returnGeometry=false&maxAllowableOffset=&geometryPrecision=&outSR=&gdbVersion=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=&resultOffset=&resultRecordCount=&f=html

**Comment by conklinbd** [comment]
This seems to be a problem with the Service definition file. @topowright we need you to regenerate the SD file so we can republish to all the servers. Make sure you keep the service name the same name. If you have an .mpk already created we can create the SD file for you.

**Comment by topowright** [comment]
@conklinbd I have created a Map Package of the data. Should I place this data in the "FoundationOverlays" folder in our shared file store?

**Comment by topowright** [comment]
@conklinbd I have placed these files in the KeyLocations folder on the shared server under Foundation Overlays

**Comment by conklinbd** [comment]
@topowright I had to recreate the SD file. The one you provided did not have feature access enabled. Additionally, the layer order was changed because a group layer was added. For future work we should use immutable IDs. 

The SD file is created and published on mini01. Need to publish to all other servers.

**Comment by conklinbd** [comment]
This has been published to all the UC machines.
