### ISSUE TITLE
Validate Ops Server GeoEvent config

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#895]
We need to verify the Ops Server GeoEvent Config prior to applying it to all machines.

**Comment by conklinbd** [comment]
I have validated the movement demo services and they are good.

**Comment by conklinbd** [comment]
@pHill5136

**Comment by conklinbd** [comment]
https://nsecmini01.esri.com:6143/geoevent/manager/index.html

**Comment by pHill5136** [comment]
@jfrygeo Addin this to opsserver for tracking.
please test your GEE services and dashboards on the nsecmini01 server

https://nsecmini01.esri.com:6143/geoevent/manager/index.html

**Comment by jfrygeo** [comment]
I have validated:
<li>Shipping feature service updating with local GEE simulator
<li>Fences seem to working in Dashboard
<li> Updates coming through in Dashboard
<li> Monitor is acting appropriately

**Comment by conklinbd** [comment]
@pHill5136 so is this complete?

**Comment by pHill5136** [comment]
Juat waiting on Aidan to get Sustainment stuff. Everything else looks good.

**Comment by conklinbd** [comment]
We can't wait for that. They will just need to deploy the sustainment stuff if they get it working. 

Let's just go ahead and deploy this to all the server. 
@elinz

**Comment by elinz** [comment]
@conklinbd I deployed GEE config to all the other machines last night and this morning.
