### ISSUE TITLE
NAIP mosaic dataset references invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#896]
Data\FoundationOverlays\OrthophotoBase\NAIP\NAIPClip.gdb\NAIP mosaic dataset references the following paths which do not exist (in addition paths should reference UNC path):
E:\Data\Esri\NewGeography\NAIPClip.gdb
E:\Data\Esri\NewGeography\NAIPClip.Overviews\MosaicDataset.Overviews

I'm correcting the path on the UC machines.

**Comment by conklinbd** [comment]
@NatalieCampos can you take a look at this issue and fix if still required. .

**Comment by NatalieCampos** [comment]
@Ben @lorraine
I am in the portal training today but I can look at it at the end of the day.  But I think that might be past the cutoff.

Sent from my iPhone

On Sep 30, 2015, at 8:43 AM, Ben Conklin <notifications@github.com<mailto:notifications@github.com>> wrote:


@NatalieCampos<https://github.com/NatalieCampos> can you take a look at this issue and fix if still required. .

**Comment by NatalieCampos** [comment]
I have repaired the item paths from E:\Data\Esri\NewGeography\ to Data\FoundationOverlays\OrthophotoBase\NAIP\.  
@nfeuerstein  @ScottCecilio 
I am confused about which NAIP imagery is being released the clipped in the Mosaic dataset or the orignial Mr.Sid files in the NAIP folder.  Should the original Mr.SID images be removed in favor of the clipped  NAIP images?  Also I noticed that the clipped images are stored in the NAIP.gdb.  It is not best practice to store raster imagery inside the gdb as it results in slower read times.

**Comment by conklinbd** [comment]
@NatalieCampos can you look and see which images are used in released image services and remove  any that aren't used (you can tell if it is released if the owner is not an individual person).

**Comment by Lorraine** [comment]
I think I might be copied on this exchange by mistake. 

Lorraine Reinsch

Please excuse my phone's auto-correct.

**Comment by conklinbd** [comment]
@NatalieCampos I removed your incorrect mentions from the comment you made. Be more careful with your mentions and make sure you reference the correct person.

**Comment by NatalieCampos** [comment]
@elinz The original issue of incorrect data paths has been fixed.  Please close this issue after the data is reviewed.  

@conklinbd None of the NAIP is currently being released. Currently, @nfeuerstein owns NAIP image service and several web maps associated with it.  No data will be removed at this time.

**Comment by elinz** [comment]
@NatalieCampos Looks like something is wrong with this mosaic dataset. If you navigate to the NAIPClip.gdb in ArcMap Catalog tree you will see AMD_MosaicDataset_ANA and AMD_MosaicDataset_STS. Datasets that start with "AMD" are supposed to be hidden tables that uses can't interact with.

**Comment by NatalieCampos** [comment]
@nfeuerstein Can you address the AMD_MosaicDataset_ANA and AMD_MosaicDataset_STS issues?

**Comment by Lorraine** [comment]
Yeah, I still shouldn't be on this chain...

Lorraine Reinsch

Please excuse my phone's auto-correct.

**Comment by ACueva** [comment]
@Lorraine, my apologies, we're not able to remove you from this issue.  if you click on "Unsubscribe" on the right hand panel you will stop getting notifications.  Sorry!

**Comment by conklinbd** [comment]
@NatalieCampos can you please look in to this issue.

**Comment by elinz** [comment]
@NatalieCampos Please tell me what you have done to fix this issue as the mosaic dataset in question Data\FoundationOverlays\OrthophotoBase\NAIP\NAIPClip.gdb no longer exists. Did you delete and create a new mosaic dataset \\[FILESERVER]\data\FoundationOverlays\OrthophotoBase\NAIP\NAIP.gdb\NAIP ?

**Comment by conklinbd** [comment]
@elinz that is what was done.

**Comment by NatalieCampos** [comment]
Well the NaipClip.gdb has been renamed to NAIP.gdb.  the NAIPClip Mosaic dataset was deleted and a new NAIP mosaic dataset was created.  The reason the new NAIP mosaic dataset was created was because I was unable to reset the path for the overviews.  The overviews were stuck being generated in some other location and I had no ability to correct the path.

**Comment by elinz** [comment]
Verified mosaic dataset are referencing UNC paths and AMD_MosaicDataset_ANA and AMD_MosaicDataset_STS "hidden" tables are no longer being listed in Catalog.
