### ISSUE TITLE
MAoW mosaic dataset references invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#897]
Mosaic dataset on data file server Data\MAoW\Geodatabase\MaowTest.gdb\MAoWTest has data paths which reference local path instead of UNC; also contains references to raster datasets which do not exist.

**Comment by abrowning80** [comment]
@elinz  Issue resolved as data has been delted can now be closed.

**Comment by elinz** [comment]
Verified that file geodatabase Data\MAoW\Geodatabase\MaowTest.gdb no longer exists. Closing issue.
