### ISSUE TITLE
OperationalWind mosaic dataset reference invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#899]
Mosaic dataset on data file server Data\MAoW\Geodatabase\OperationalWeather.gdb\OperationalWind references local paths instead of UNC paths.

**Comment by abrowning80** [comment]
@elinz  Issue resolved can now be closed.

**Comment by elinz** [comment]
Verified that mosaic dataset paths now reference UNC path. Closing issue.
