### ISSUE TITLE
MAOWData mosaic dataset references invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#900]
Mosaic dataset on data file server Data\MAoW07072015\Geodatabase\MAoWData.gdb\MAOWData references local paths instead of UNC paths.

**Comment by abrowning80** [comment]
Data now deleted so issue can e closed.

**Comment by elinz** [comment]
Verified that folder Data\MAoW07072015 no longer exists. Closing issue.
