### ISSUE TITLE
MAOWWind mosaic dataset references invalid dataset paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#901]
Mosaic dataset on data file server Data\MAoW07072015\Geodatabase\MAoWData.gdb\MAOWWind reference local path instead of UNC paths; in addition references paths that do not exist.

**Comment by jrweakland** [comment]
@joebayles

**Comment by abrowning80** [comment]
This is legacy data that has been deleted so issue can be closed.

**Comment by elinz** [comment]
Verified that folder Data\MAoW07072015 no longer exists. Closing issue.
