### ISSUE TITLE
OperationalData mosaic dataset references invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#902]
Mosaic data on data file server Data\MAoW07072015\Geodatabase\OperationalWeather.gdb\OperationalData references local paths instead of UNC paths; also references paths that do not exist.

**Comment by jrweakland** [comment]
@joebayles

**Comment by abrowning80** [comment]
Data is legacy data and has been deleted so issue can be closed.

**Comment by elinz** [comment]
Verified that folder Data\MAoW07072015 no longer exists. Closing issue.
