### ISSUE TITLE
OperationalWind mosaic dataset references invalid data paths

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#903]
Mosaic dataset on data file server Data\MAoW07072015\Geodatabase\OperationalWeather.gdb\OperationalWind references local paths instead of UNC paths; in addition, references paths that do not exists.

**Comment by jrweakland** [comment]
@joebayles

**Comment by abrowning80** [comment]
@elinz @jrweakland This should now all be sorted once I republish what I have got, need to try in next 24hrs

**Comment by jrweakland** [comment]
:+1:

**Comment by abrowning80** [comment]
This is all legacy data now and has been deleted so issue can be closed.

**Comment by elinz** [comment]
Verified that Data\MAoW07072015 folder no longer exists. Closing issue.
