### ISSUE TITLE
Data coming from Mark Logic comes in as all Null

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#904]
Data coming from Mark Logic through GeoEvent comes over with correct location on the map; however, no attributes are populated @conklinbd @pHill5136

**Comment by conklinbd** [comment]
I just spoke to @pHill5136 about this and he said we are waiting on MarkLogic for them so send us more attribute values in their message.

**Comment by pHill5136** [comment]
I got confirmation from Dave Grant that he will be working on this tomorrow. He is finishing up another request today.

**Comment by topowright** [comment]
@conklinbd @pHill5136 Is this a schema problem? If so can we identify this? They have 885 records right now that are the same records that we have in our database. I would think those points would populate properly and they are also coming over as Null. That is why I think this is a schema issue

**Comment by topowright** [comment]
Here is a link to the service that we are populating

https://nsec.esri.com/ags/rest/services/NationalIntelligence/ObservationReportsML/FeatureServer

**Comment by pHill5136** [comment]
The call to the obi rest endpoint does not return all of the attributes. The only attribute that is returned that maps to ArcGIS is geometry. Dave has to program their service to return the other fields.  They exist in the obi db the rest endpoint just doesn't pass them back when a rest query occurs. Once he has those fields returned we might have to modify the incoming geoevent definition to match the names that he returns.

**Comment by topowright** [comment]
Dave Grant and I will discuss the updates that we need from Mark Logic tomorrow morning.

**Comment by conklinbd** [comment]
@topowright is there progress on this?

**Comment by pHill5136** [comment]
Just tested this. All attributes are coming over. I had to change the incoming geoevent definition for a few of the attributes to match the names of attribute fields as they are returned by obi.

**Comment by pHill5136** [comment]
I checked that observation reports are now receiving attributes. All is working now.

**Comment by topowright** [comment]
@pHill5136 The service is not adding any features at this point. I have test this multiple times and seen no features being added.

**Comment by topowright** [comment]
@conklinbd @pHill5136 This is now working great.
