### ISSUE TITLE
Observation Reports updated or created in ArcGIS are not being updated in Mark Logic

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#905]
Due to Global ID conflicts data created in ArcGIS cannot be added to Mark Logic. if it is added to Mark Logic there will be a ping pong affect. @conklinbd @pHill5136.

**Comment by conklinbd** [comment]
@topowright does this issue need to be addressed for UC?

**Comment by topowright** [comment]
@conklinbd @jrweakland 
Looking at testing a new solution where we would not use GlobalIDs, but trackIDs instead.

**Comment by jrweakland** [comment]
@nfeuerstein - I am including you since this has been tagged with AFI.

**Comment by conklinbd** [comment]
@topowright does this need to be addressed for the Ops Server release?

**Comment by topowright** [comment]
@conklinbd This needs to be addressed at the next release

**Comment by jrweakland** [comment]
@topowright - Just to verify... Does this need to be addressed in the next (October 2015) or after.next release (February 2016) of the Ops Server?

**Comment by pHill5136** [comment]
I think we are having issues here because of recent changes on the ml side. Probably require some development on both sides. I am working with the developer at ml to resolve the issue.

**Comment by conklinbd** [comment]
@phill5136 please provide an update on the status of this issue.

**Comment by topowright** [comment]
@conklinbd @pHill5136 Currently there might be an issue with the GeoEvent definition, which might be the reason why we cannot push content into Mark Logic

**Comment by conklinbd** [comment]
Is this being actively worked on? Can this be resolved by 10/9?

**Comment by pHill5136** [comment]
@topowright @conklinbd This issue has been resolved. Writes from ArcGIS toML and from ML to ArcGIS are both functioning. Sending back to lyle to validate.

**Comment by topowright** [comment]
@pHill5136 Was not able to validate that we were able to write features into Mark Logic. I am changing the version of the release to reflect the same status as this issue: 

https://github.com/Esri/ops-server-config/issues/939
