### ISSUE TITLE
Message Simulation directory is a mix of old and new simulations

### ISSUE THREAD

**Issue by conklinbd** [Esri/ops-server-config#906]
The Message Simulation folder seems to be a mix of old and new simulation files. We need to clean it up to only be the current valid simulation files and the batch script for launching the simulation needs to be updated.

**Comment by conklinbd** [comment]
@pHill5136 this needs to be done today.

**Comment by pHill5136** [comment]
This is complete. Eric will put the new batch on the UC servers.

**Comment by elinz** [comment]
@conklinbd @pHill5136 I copied the C:\MessageSimulator\Messages folder and C:\MessageSimulator\messages_simulation.bat file to all the other UC machines approx. 16:00 Pacific today 14 July.
