### ISSUE TITLE
Users need to republish hosted services with the "missing" service properties

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#914]
Need to investigate why some properties on hosted services published during Ops Server installation for UC didn't have the same editing properties (edit, sync, export, etc) as the source hosted services. I believe that after the hosted service was originally published, the owner of the service modified these properties on the portal item, which means these properties are not stored in the service definition file uploaded to portal.

I will test after UC and confirm.

**Comment by conklinbd** [comment]
@elinz - I think you have researched this now and it isn't a user error. I am changing the label to release team since this is something you will need to address, possibly using ArcREST.

**Comment by elinz** [comment]
@conklinbd Fixed in #1312 (note: without ArcREST). Closing issue.
