### ISSUE TITLE
Crowd Source Reporter Gallery Template

### ISSUE THREAD

**Issue by phil7277** [Esri/ops-server-config#916]
The Crowd Source Reporter app was used to create an Operations Center Reporter group application template. The Ops Server copies made to the mini servers, does not honor the group share into the application resulting in the following error message when trying to access the operations center report:

"Configured group is invalid or no items have been shared with this group yet."

![screenshot 14](https://cloud.githubusercontent.com/assets/6224090/8729496/9d158696-2bb9-11e5-81e9-4d337c48c696.jpg)

**Comment by conklinbd** [comment]
Please provide a link to the item for the app or the group id.

**Comment by conklinbd** [comment]
@elinz 
This looks like an issue with the GUID replacement logic. The group id for this app is stored in the data for the item. 
https://nsecmini05.esri.com/arcgis/sharing/content/items/cddb71c5da4b4397a062c2ed8ad0cfee/data

This group is the same id as the original group id from the portal. We will need to add logic in the future to change the group id in the item data with the new id for the groups. 

@phil7277 This can not be fixed for UC. You need to manually recreate this app on any servers you are accessing. 
https://nsecmini05.esri.com/arcgis/home/group.html?owner=phil7277&title=Operations%20Center%20Reports

Share using the app. 
If @phil7277 had tested this when the test server was up and running we might have been able to address this.

**Comment by phil7277** [comment]
I have recreated the application on nsecmini01, 02 and 03. In order to support UC Demoes, I ill be recreating the app on 
nsecmini04.esri.com
nsecmini07.esri.com
nseclt08.esri.com
nseclt09.esri.com

I will not update the backup servers in order to troubleshoot this issue. The link to the item is: https://nsecmini05.esri.com/arcgis/apps/CrowdsourceReporter/index.html?appid=cddb71c5da4b4397a062c2ed8ad0cfee

**Comment by conklinbd** [comment]
I created a new issue for post UC to fix the publishing scripts.

#917

**Comment by conklinbd** [comment]
@phil7277 Once you have manually resolved this issue on the Tower, Workshop and Demo Theater machines you can close the issue.

**Comment by phil7277** [comment]
Operations Center Reporter has been recreated on all machines with the exception of the back up servers:
nsecmini05.esri.com
nsecmini06.esri.com

**Comment by elinz** [comment]
@phil7277 Can you please recreate on the backup servers 05 and 06? Without making these same fixes on the backup servers, the backup servers won't be useful if we actually need to use these backup machines since the fixes won't be applied. Thanks.

**Comment by phil7277** [comment]
@elinz, I recreated the Gallery App on the Backup Servers 05 and 06. Great point! Thanks.
