### ISSUE TITLE
Access to content shared to "Everyone", not accessible through current "User" role permissions

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/ops-server-config#918]
The Intel Support to Operations - Map Journal, associated web maps, applications, and layers are all shared with "Everyone".  However, when a user with a "User" role tries to access the applications, and webmaps they are not granted permission.  Due to this maps and applications are not opening for the user. @phil7277, @elinz , @jrweakland 

https://[dev server]/arcgis/home/item.html?id=e8f3b790b2844e6f924bf615a7136a42

**Comment by conklinbd** [comment]
@ScottCecilio can you provide the links for the apps that are not opening? I am not having any issue accessing, even if I set myself to a user role. 

Is there a specific user that is having trouble accessing? We can troubleshoot it with them.

**Comment by phil7277** [comment]
@conklinbd The links for the apps that were not opening up are:
Crowd Source Reporter App: https://nsec.esri.com/arcgis/home/item.html?id=29013195a6aa480c8bc3d1c34dbea5f0

Map Journal: https://nsec.esri.com/arcgis/apps/GeoForm/index.html?appid=c48bdb0b6d2f4dfea70f39b048a3ceb7 

Operations Dashboard:
https://nsec.esri.com/arcgis/apps/dashboard/index.html#/d6f09cebdbad474a8c6cad9e94609222

The personnel that could not access the content were Jamon and Tom S.  Eric changed there permissions from User to DTC and it cleared up the issue specifically for them.

**Comment by conklinbd** [comment]
Ok. Changing the role for the individual user is the only option for now. We can look into this in more detail after UC.

**Comment by conklinbd** [comment]
I don't think this is an issue we need to resolve for the Ops Server release.
