### ISSUE TITLE
Missing cached Imagery

### ISSUE THREAD

**Issue by ScottCecilio** [Esri/ops-server-config#919]
Please see the following service.  I have applications relying on this data and when I zoom in I have a gap in my Imagery cache.

https://nsec.esri.com/ags/rest/services/Basemaps/Imagery/MapServer

**Comment by elinz** [comment]
@ScottCecilio Please provide coordinate where issue occurs.

**Comment by ScottCecilio** [comment]
When zooming slowly I lose the basemap at 1:9,028.  The basemap reappears at 1:4,514

**Comment by ACueva** [comment]
@NatalieCampos, @nfeuerstein is on vacation this week, is this something you could take a look at?

**Comment by NatalieCampos** [comment]
This seems to be a rest/soap issue as the 1:4k  scale is visiblle  in ArcMap but not portal. Per @ACueva I will recache the 1:4k  scale and see if that fixes it

In ArcMap
![image](https://cloud.githubusercontent.com/assets/5116835/9049193/43ab99f8-39f4-11e5-81f3-57d0121a5863.png)

**Comment by conklinbd** [comment]
@NatalieCampos This is because ArcMap will always grab another level of data if there are cache tiles missing. Testing form ArcMap is not reliable if you are using the service. 

If you view the cache file directly you will see the missing tiles.

**Comment by NatalieCampos** [comment]
@ScottCecilio I have updated the imagery cache.  Can you please verify and close if completed.

**Comment by ScottCecilio** [comment]
I was able to verify that the cache is now visible in the affected scales.  Thanks for the fix.
