### ISSUE TITLE
Digital Surface Model  Elevation service not working

### ISSUE THREAD

**Issue by Nekillims** [Esri/ops-server-config#921]
View service returns a checkerboard pattern.  No elevation values returned when inspecting elevation posts.  Suspect invalid paths.

![digital surface model screen](https://cloud.githubusercontent.com/assets/11337235/8994117/67d49714-36d7-11e5-9879-633869758df5.JPG)

**Comment by NatalieCampos** [comment]
The error is the service is related to a data path issue. I haverepathed them so they can be used now.  @elinz  What is the correct UNC path for the mosaic datasets?  

The original paths were:  \\nsecdata\Data\FoundationOverlays\Elevation
The new(broken) paths are:  C:\OpsServer\Data\FoundationOverlays\Elevation

**Comment by NatalieCampos** [comment]
the DSM has been fixed and updated. @Nekillims can you please verify and close this issue
