### ISSUE TITLE
Profile Web App Template points to ArcGIS Online Elevation Service

### ISSUE THREAD

**Issue by Nekillims** [Esri/ops-server-config#923]
Profile web app template points to ArcGIS Online elevation data and profile does not agree with elevation data viewed in map display.
![elevation profiles screen](https://cloud.githubusercontent.com/assets/11337235/8994878/fc0cb78c-36db-11e5-8248-693e7a44dea0.JPG)

 Need a version of the template that allows user to select elevation source.

**Comment by jrweakland** [comment]
@kgonzago - not sure if this is in your lane.

**Comment by kgonzago** [comment]
@jrweakland @Nekillims this profile template and WebApp Builder profile widget uses the same elevation service from ArcGIS Online. Is the issue where the features on the map and elevation profile are out of sync? or there isn't a way to supply another elevation profile service?

**Comment by Nekillims** [comment]
@kgonzago @jrweakland   The map display (with shaded relief) points to the NSEC elevation services, but the profile is hardcoded to point to ArcGIS Online.  It is possible that some of our distributor or customer deployments may only have access to the Portal.  That would be problematic for installation and configuration.  Plus, in our case we have high res elevation data (Lidar) that is not used in the profile.

**Comment by kgonzago** [comment]
@Nekillims I'll reach out to you next week to gather more info to properly address issue/enhancement.

**Comment by joebayles** [comment]
@kgonzago is this still an issue?

**Comment by kgonzago** [comment]
@joebayles I reached out to @Nekillims but never got a response. Both widget and template are configurable to allow users to supply their own custom elevation profile service. This issue can be closed.

**Comment by jrweakland** [comment]
Nekillims is Sandy Milliken - so I understand why you did not get a response.

**Comment by joebayles** [comment]
Closing based on feeback from @kgonzago.
