### ISSUE TITLE
World Elevation Cache Disappears at scales larger than ~ 1:600,000

### ISSUE THREAD

**Issue by Nekillims** [Esri/ops-server-config#924]
Might be an issue if someone need a shaded relief display at medium to large scale outide our primary AOI.  Visibility range indicates it should be visible at all view scales
![world elevation cache screen](https://cloud.githubusercontent.com/assets/11337235/8995463/98604920-36df-11e5-820a-76dac00bfc42.jpg)

**Comment by Nekillims** [comment]
![world elevation cache screen](https://cloud.githubusercontent.com/assets/11337235/8995519/e7e5f0da-36df-11e5-80b5-83d589e10047.jpg)

**Comment by Nekillims** [comment]
![world elevation cache screen](https://cloud.githubusercontent.com/assets/11337235/8995599/83f6abd6-36e0-11e5-9088-6dbd14369b55.jpg)

**Comment by conklinbd** [comment]
@NatalieCampos Is the Elevation Cache meant for visualization or just for use as the base elevation in the scene viewer?

**Comment by NatalieCampos** [comment]
@conklinbd  The "cached" part of the cached elevation service is meant to be an elevation for scene and Pro. Visualization is possible by unchecking the **Enable cache view
** on the context menu in ArcMap and Pro. 

![image](https://cloud.githubusercontent.com/assets/5116835/8996416/98d4d8b6-36cc-11e5-948b-d9a0a2b4f288.png)

 I am unable to view the cached elevation service dynamically in a webmap and so the WGS84 service should be used.  Also the cached service is in web mercator.  Below is the full global extent of the cached service dynamically displayed within ArcMap.  
![image](https://cloud.githubusercontent.com/assets/5116835/8996593/eb6e8f76-36cd-11e5-84de-470a79c4a249.png)


As for the cache itself, it was only cached to the extent of greater California.  The no data with no internet issue required a dummy raster to be placed into the mosaic that is viewable at all scales.  This greatly increased the size of the cache and so the cache itself was not built out to a global scale.

**Comment by jrweakland** [comment]
@Nekillims - please close this issue when appropriate

**Comment by Nekillims** [comment]
@jrweakland I'm not entirely comprehending this thread.
"I am unable to view the cached elevation service dynamically in a webmap and so the WGS84 service should be used. Also the cached service is in web mercator. Below is the full global extent of the cached service dynamically displayed within ArcMap."  Does this mean it can only be used in ArcMap and Pro but not a web map?  If so, the documentation/description should reflect this.  BTW I tried it again in a web map and couldn't get it to display at all.

**Comment by conklinbd** [comment]
@NatalieCampos could you discuss this with @Nekillims  and make sure the item description is updated to make it clear how this service should be used.

**Comment by Nekillims** [comment]
I talked with @NatalieCampos.  @conklinbd  The intent is that this is a dynamic service for the desktop but is not viewable in a web map with this version of Portal.  It may be viewable in a future release.  The service description needs to be updated with a statement that this is only for desktop consumption.  I do not have edit access to the Item description to make this description update.

**Comment by NatalieCampos** [comment]
Updated usage language was added to the portal description.

**Comment by Nekillims** [comment]
Updated description is fine
