### ISSUE TITLE
GEE - Creating Output - Update MarkLogic Feature Service

### ISSUE THREAD

**Issue by topowright** [Esri/ops-server-config#939]
@pHill5136 Could we drop the use of a track id for this output extension being that the schema currently does not match this configuration?

**Comment by pHill5136** [comment]
@topowright The output relies on a trackid for updating features. If trackid exists it updates if it does not exist it adds a feature. In a strictly add feature scenario trackids are not required. I would have to look at the output I created. I think I wrote it for update only, but there should be a way to modify the transport to support either update or add a feature when the connector is configured.

**Comment by elinz** [comment]
@jrweakland Can you please review and set appropriate labels, milestone and assignee? Thank you.

**Comment by jrweakland** [comment]
@pHill5136 - Is this something that can be completed today? Or will we need to push it back until February?

**Comment by jrweakland** [comment]
@topowright @pHill5136 @elinz - This will wait until the v.after next milestone.

**Comment by pHill5136** [comment]
Verified that we can push a feature to MLOBI.

**Comment by topowright** [comment]
This is no longer an issue
