### ISSUE TITLE
Jenkins build server: Copy Predictive Analysis install files to Software\PredictiveAnalysis folder

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#941]
The ops server install process has been modified to run the predictive analysis installer. Please modify the Jenkins build server to copy the Predictive Analysis web installer files (i.e. ESRI.ArcGIS.GPAT.Web.Installer.msi and setup.exe) to the OPSServerInstall\Software\PredictiveAnalysis folder.

**Comment by ACueva** [comment]
Changes made, verify at next build.

**Comment by ACueva** [comment]
verified.
