### ISSUE TITLE
Create ArcGIS Server Site fails at 10.4

### ISSUE THREAD

**Issue by ACueva** [Esri/ops-server-config#942]
![image](https://cloud.githubusercontent.com/assets/3093940/9454244/5a4884d2-4a75-11e5-976c-2b3c08d1780f.png)

**Comment by elinz** [comment]
Based on the error message you may have remnants of an earlier ArcGIS Server build. Make sure you have uninstalled any previous server software and delete any remaining folders.

-------- Original message --------
From: Avi Cueva
Date:08/24/2015 3:33 PM (GMT-08:00)
To: Esri/ops-server-config
Cc: Eric Linz
Subject: [ops-server-config] Create ArcGIS Server Site fails at 10.4 (#942)


[image]<https://cloud.githubusercontent.com/assets/3093940/9454244/5a4884d2-4a75-11e5-976c-2b3c08d1780f.png>

**Comment by elinz** [comment]
@ACueva Just ran the ops server installation on a new VM (Win Server 2012 R2) using ArcGIS Server 10.4 daily build 5305 and the create site was successfully created and I can log into server manager afterward. Recommend this issue be closed.
