### ISSUE TITLE
Hosted service MotorcadeRoute/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#949]
The hosted service "MotorcadeRoute" item exists 6e2d88b599da481cb967a0f9430ea9f9 but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by CraigCleveland** [comment]
@elinz it doesn't appear I'm going to be able to get data permissions for the main focal point of this demonstration, hence I'm not going to clean this up and have simply deleted it.
