### ISSUE TITLE
Hosted service MyaDrive/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#957]
The hosted service "MyaDrive" item exists 2004ae5aefd14c0fb7e545a3f50aa1dc but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

@nfeuerstein @jrweakland Item owned by Daniel Hagens, but looks like he doesn't have a GitHub account or his account does not have access to our Esri repos.

**Comment by dhagens** [comment]
This service was added for working with the map tools in Ops Dashboard.  There is no need for this to be published to Ops Server at this time.  Do I need to do anything else at this point to resolve anything?

**Comment by jrweakland** [comment]
@elinz - your guidance would be appreciated.

**Comment by elinz** [comment]
@dhagens Please delete the hosted service MyaDrive/FeatureServer by deleting the portal item 2004ae5aefd14c0fb7e545a3f50aa1dc. Let me know and I can delete this for you.

**Comment by dhagens** [comment]
It has been deleted.

**Comment by elinz** [comment]
@dhagens Thank you. Closing issue.
