### ISSUE TITLE
Hosted service Ebola_Outbreaks/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#958]
The hosted service "Ebola_Outbreaks" item exists bfba972dc62d4a4d982e496016ad5eb7 but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by mfunk** [comment]
Deleted.
