### ISSUE TITLE
Hosted service Districts/MapServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#959]
The hosted service "Districts" item exists 7400e51dde3547f59867747e5fa8a32e but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by nfeuerstein** [comment]
Service deleted.
