### ISSUE TITLE
Hosted service targetdeck/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#960]
The hosted service "targetdeck" item exists 4938aca35d9d4b36b37455a610f9f30a but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by jrweakland** [comment]
@phil7277 - see https://github.com/Esri/ops-server-config/issues/994 for additional information. These issues are related.

**Comment by phil7277** [comment]
No need to have this feature service copied over for release. This was a test feature layer working with some content from ClearTerra LocateXT. I have deleted the feature layer.
