### ISSUE TITLE
Service Definition item (IncidentHotSpots) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#961]
Hosted service IncidentHotSpots/MapServer does not exist, but associated service definition item "IncidentHotSpots" e7ac0db53cb0496f9607c591e0bb2ef6 exists; please delete the following item; otherwise the hosted service will be published to ops servers.

**Comment by ScottCecilio** [comment]
Item "IncidentHotSpots" e7ac0db53cb0496f9607c591e0bb2ef6" has been deleted
