### ISSUE TITLE
Service Definition item (IncidentHotSpots) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#962]
Hosted service Map/MapServer does not exist, but associated service definition item "IncidentHotSpots" 019ef1d8880749269c26e44e490f4f5a exists; please delete the following item; otherwise the hosted service will be published to ops servers.

**Comment by ScottCecilio** [comment]
Item item "IncidentHotSpots" 019ef1d8880749269c26e44e490f4f5a has been deleted
