### ISSUE TITLE
Service Definition item (CompoundMap) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#963]
Hosted service CompoundMap/FeatureServer does not exist, but associated service definition item "CompoundMap" 84f165cbc7404302b1597c3116d6d1f2 exists; please delete the following item; otherwise the hosted service will be published to ops servers.

**Comment by ScottCecilio** [comment]
I believe that there is an associated feature service that was simply renamed to "Monterey Airport Compound Map".  I have renamed the Service Definition for clarity.

**Comment by jrweakland** [comment]
@elinz - Is there an additional issue that needs to be resolved by @ScottCecilio?

**Comment by elinz** [comment]
@ScottCecilio @jrweakland The fixes described above actually didn't fix the problem.

- [ ] The "Monterey Airport Compound Map" service definition item (84f165cbc7404302b1597c3116d6d1f2 ) needs to be deleted. Renaming the SD item title to match the hosted service item doesn't solve anything as what's important is the service name captured in the SD file, which in this case is "CompoundMap".

- [ ] The hosted service MonterreyAirportCompoundMap_WFL/FeatureServer needs to be republished so that the SD item for this service is uploaded to the portal.

**Comment by ScottCecilio** [comment]
Working on this, I'm on travel bear with me.

**Comment by elinz** [comment]
Talked to @ScottCecilio this afternoon. We are looking in this issue, but need to reassess in the morning.

**Comment by ScottCecilio** [comment]
@elinz @jrweakland Does the issue "https://github.com/Esri/ops-server-config/issues/1131" relate to this as well?  If so, I believe that this is no longer an issue and can be closed.

**Comment by elinz** [comment]
@ScottCecilio @jrweakland I verified that the service definition item 84f165cbc7404302b1597c3116d6d1f2 was deleted; also verified that the service MonterreyAirportCompoundMap_WFL/FeatureServer was republished. Closing issue.
