### ISSUE TITLE
Web map "Social_Cultural_Leisure_Monterey" referencing external basemap 

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#966]
Web map "Social_Cultural_Landuse_Monterey" (id: 6bc1727e44e74ac4816e94ead3d1e29d) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by eogden** [comment]
The basemap has now been changed to reference one on NSEC.

**Comment by eogden** [comment]
@elinz  @nfeuerstein could you please check that I have resolved this issue correctly and close it?

**Comment by elinz** [comment]
Verified issue was fixed. Closing issue.
