### ISSUE TITLE
Web map "Social_Cultural_Structures_Monterey" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#967]
Web map "Social_Cultural_Structures_Monterey" (id: 93fa586351ac4d5f8881ba800bb94c64) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by eogden** [comment]
The basemap has now been changed to reference one on NSEC.

**Comment by eogden** [comment]
@elinz  @nfeuerstein could you please check that I have resolved this issue correctly and close it?

**Comment by elinz** [comment]
Verified issue was fixed. Closing issue.
