### ISSUE TITLE
Web map "Social_Cultural_Tourism_Historic_Monterey" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#968]
Web map "Social_Cultural_Tourism_Historic_Monterey" (id: 97c3a378442043648c37a51c0d69a848) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by eogden** [comment]
The basemap has now been changed to reference one on NSEC.

**Comment by eogden** [comment]
@elinz  @nfeuerstein could you please check that I have resolved this issue correctly and close it?

**Comment by elinz** [comment]
Verified issue was fixed. Closing issue.
