### ISSUE TITLE
Web map "Social_Cultural_Areas_Monterey" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#969]
Web map "Social_Cultural_Areas_Monterey" (id: 9584bd0a9ac94a05b05afb0cbdf5c666) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by eogden** [comment]
The basemap has now been changed to reference one on NSEC.

**Comment by eogden** [comment]
@elinz  @nfeuerstein could you please check that I have resolved this issue correctly and close it?

**Comment by elinz** [comment]
Verified issue was fixed. Closing issue.
