### ISSUE TITLE
Web map "MyaDrive" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#970]
Web map "MyaDrive" (id: 6172bd7ba5fa4530a3e3c0be135289ce) is referencing an ArcGIS online basemap https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer and https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
@dhagens - We are getting the Ops Server ready for the upcoming release and need to get this fixes as soon as possible. Thanks.

**Comment by elinz** [comment]
Verified. Closing issue.
