### ISSUE TITLE
Web map "Concealment" references an external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#971]
Web map "Concealment" (id: e0003df7ff6f4c02b91743b3bcf0b7d9) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
