### ISSUE TITLE
Web map "Monterey Bay Foundation Data" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#972]
Web map "Monterey Bay Foundation Data" (id: f987b8c5862d45c6ad8b91cb09ef5d26) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
