### ISSUE TITLE
Web map "Artillery Deployment Location Analysis" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#973]
Web map "Artillery Deployment Location Analysis" (id: 6be4ecc1f7cf4e0ca12cd195c0ac142a) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
