### ISSUE TITLE
Web map "Cover from Flat Trajectory Weapons" reference external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#974]
Web map "Cover from Flat Trajectory Weapons"  (id: 72bfee9edda94254a21115399c76d266) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
