### ISSUE TITLE
Web map "Drop Zone Analysis" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#975]
Web map "Drop Zone Analysis" (id: d7951616773440d09e6fdf03219c908e) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
