### ISSUE TITLE
Web map "Helicopter Landing Zone Analysis After Mudslides" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#977]
Web map "Helicopter Landing Zone Analysis After Mudslides" (id: 2090f8268b174d16862ce128684a6c3a) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
