### ISSUE TITLE
Web map "Modified Combined Obstacle Overlay" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#978]
Web map "Modified Combined Obstacle Overlay" (id: fcf95c15f30c4f3b9170b116de3be1bc) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Changed basemap to NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
