### ISSUE TITLE
Web map "Road Conditions After Storm" references external basemap

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#979]
Web map "Road Conditions After Storm"  (id: 8b44f401e60e4abdbd2ebef663b1a3b2) is referencing an ArcGIS online basemap http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer.

If the operation layers of a web map reference a service on the dev server then the basemap should be a service on the dev server also.

**Comment by jrweakland** [comment]
Fixed. Topographic basemap is now from NSEC.

**Comment by elinz** [comment]
Verified. Closing issue.
