### ISSUE TITLE
Web map "Predictive Analysis Test Map 2" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#980]
Web map "Predictive Analysis Test Map 2" (id: 34dc3152548841c68b8007210fefe0b8) references the following services that do not exist:
NationalIntelligence/DistanceFromValuableResources/ImageServer 
NationalIntelligence/DistanceFromSettlements/ImageServer  
NationalIntelligence/DistanceFromGovernment/ImageServer 
NationalIntelligence/DistanceFromMajorRoads/ImageServer

**Comment by kAilshie** [comment]
I deleted the web map

**Comment by ACueva** [comment]
Verified
