### ISSUE TITLE
Web map "Test Map 2" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#981]
Web map "Test Map 2" (id: fa0cf0457f7d4f4c9debfbe6f8656ee5) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromMajorRoads/ImageServer

**Comment by kAilshie** [comment]
I deleted the web map

**Comment by ACueva** [comment]
Verified.
