### ISSUE TITLE
Web map "Predictive Analysis Test Map" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#985]
Web map "Predictive Analysis Test Map" (id: 55451ab5c76b46eda06675a72b30bec1) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromValuableResources/ImageServer 
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromMajorRoads/ImageServer  
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromSettlements/ImageServer
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromGovernment/ImageServer

**Comment by nfeuerstein** [comment]
Web map deleted.
