### ISSUE TITLE
Dark Gray Basemap draws on top of raster layers in a web map

### ISSUE THREAD

**Issue by kAilshie** [Esri/ops-server-config#986]
I was creating a web map that contained many image service layers and when I changed from the default basemap to the dark gray basemap all my layers became hidden.  This does not happen when I change to any of the other basemaps.

**Comment by nfeuerstein** [comment]
Added to backlog: https://app.asana.com/0/22897918293134/54312512723512

**Comment by NatalieCampos** [comment]
This has been fixed.  Assigning to @ACueva for verification and explanation of the issue.

**Comment by ACueva** [comment]
FYI @kAilshie. Long story short, I goofed when I created this basemap.  I had swapped the base layer with overlay layer.  I manually edited the json config for this web map.

**Comment by kAilshie** [comment]
@ACueva @NatalieCampos and FYI to others that stumble across this... Working with Avi we found out that the web app-builder basemap gallery widget caches all the basemap layer configurations. Since the application was built before the basemap fix I also had to go into my web application and update the basemap gallery widget's configuration to fix this in my app.

**Comment by kerryrobinson** [comment]
@elinz I also had to fix this manually on my Ops Server.  I don't think it was included in the Patch...but it should be noted as something that needs to be fixed (if there is another patch or another announcement to the group who have Ops Servers).
