### ISSUE TITLE
Service "NationalIntelligence//SignificantActivity.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#987]
Service "NationalIntelligence//SignificantActivity.MapServer" is associated with a portal item (03d78feda64d4eaea74c4d6a37512329; FeatureServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by dfoll** [comment]
@elinz this service can be deleted. assigning issue back to @elinz as it is my understanding that he has to be the one to actually make the deletion

**Comment by elinz** [comment]
@dfoll I deleted the NationalIntelligence//SignificantActivity service. Closing issue.
