### ISSUE TITLE
Service "NationalIntelligence//DistanceFromWaterSourceMosaic.ImageServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#988]
Service "NationalIntelligence//DistanceFromWaterSourceMosaic.ImageServer" is associated with a portal item (197cacd838e3496e9dc784219fb3565c; ImageServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by nfeuerstein** [comment]
Service deleted.
