### ISSUE TITLE
Service "NationalIntelligence//LinesOfCommunicationOverlay.MapServer" is associated with a portal item that does not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#993]
Service "NationalIntelligence//LinesOfCommunicationOverlay.MapServer" is associated with a portal item (7ab01386cad14f1f9f0adba709aabe6c; MapServer) that does not exist.

Most likely cause of issue, publisher intended to delete the non-hosted service, but deleted it by deleting the portal item(s). The correct way to delete a non-hosted service is to delete it through the AGS connection which will delete both the service and the associated portal items.

**Comment by nfeuerstein** [comment]
Service Deleted.
