### ISSUE TITLE
Hosted service targetdeck/FeatureServer was published from CSV file

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#994]
The hosted service "targetdeck" item (4938aca35d9d4b36b37455a610f9f30a) was published from a CSV file and won't be published during the Ops Server publishing process.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

**Comment by jrweakland** [comment]
@phil7277 - Looks like you will need to add the CSV file to a ArcMap map document or a ArcGIS Pro project and publish the "targetdeck" item.

**Comment by phil7277** [comment]
No need to have this feature service copied over for release. This was a test feature layer working with some content from ClearTerra LocateXT. I have deleted the feature layer!
