### ISSUE TITLE
Web map "SustainmentReportingWebMap" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#996]
Web map "SustainmentReportingWebMap" (id: dbb2e4817bde467b9f336196590f925e   ) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/MontereyBoundaries/FeatureServer/2
https://nsec.esri.com/ags/rest/services/NationalIntelligence/MontereyBoundaries/FeatureServer/1
https://nsec.esri.com/ags/rest/services/NationalIntelligence/MontereyBoundaries/FeatureServer/0

**Comment by abrowning80** [comment]
@elinz -  Have had a look at this issues and have added in the District Boundaries layer which was the only one that I could find published on NSEC and saved it under my folder as SustainmentReportingWebmap2.  Please can you confirm that you are happy with this and if so close the issue.

**Comment by elinz** [comment]
@abrowning80 @jrweakland SustainmentReportingWebmap2 web map looks good, but is there a reason why you didn't fix the original web map dbb2e4817bde467b9f336196590f925e? Generally speaking, fixing the original resource is usually the best course of action. The problem here is that there could be other resources, such as web apps that reference the original web map which won't work correctly. Can you please fix the original web map?

**Comment by abrowning80** [comment]
@elinz @jrweakland, @helyx-rterry is the owner of "SustainmentReportingWebMap" so is going to delete it as it is no longer needed.  This should resolve the issue.

**Comment by elinz** [comment]
@abrowning80 @jrweakland Reassigning issue to @helyx-rterry

**Comment by conklinbd** [comment]
I will take this issue and delete the specific web map.

**Comment by conklinbd** [comment]
This maps was deleted so I have closed this issue.
