### ISSUE TITLE
Web map "Distance From Water" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#997]
Web map "Distance From Water" (id: 6214c50aa89b43a0ac842ac2bb1ba7eb) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromWater/MapServer

**Comment by CraigCleveland** [comment]
@elinz I have no idea how this one particular service would have been deleted?  My guess is someone had an "oops" moment.  I'll republish today so we can put this one to bed.

**Comment by CraigCleveland** [comment]
@elinz republished and web map fixed.  Should be good to go!

**Comment by elinz** [comment]
Verified fixed.

**Comment by elinz** [comment]
@CraigCleveland This is still an issue with this service. The service exists without a portal item. According to the service json it's supposed to be associated with item d4269c5dbf01495c8ae181952895e9ed which does not exist. If you can create a portal item I'll edit the service json to re-associated with this new portal item.

**Comment by CraigCleveland** [comment]
@elinz - done.  Here is the Portal item - https://nsec.esri.com/arcgis/home/item.html?id=002451cd86134f7fa8b9394174142242  Can you please coordinate with @nfeuerstein as she took this Sudan related content from me as she is preparing for the release.  My assumption is she'd like to have this item next to the other Sudan related items.  Thanks.

**Comment by elinz** [comment]
@CraigCleveland I've associated the service with the portal item and changed ownership to @nfeuerstein. Item exists in the root folder. Closing issue. Thanks for creating the new item.
