### ISSUE TITLE
Web map "P. A. web map test" references services that do not exist

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#999]
Web map "P. A. web map test" (id: a7cfc145dfe44c468c98ca750a4cdd5f) references the following services that do not exist:
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromMajorRoads/ImageServer
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromGovernment/ImageServer
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromSettlements/ImageServer
https://nsec.esri.com/ags/rest/services/NationalIntelligence/DistanceFromValuableResources/ImageServer

**Comment by mfunk** [comment]
@elinz I don't have a P.A. web map test in my NSEC content. Something get orphaned? If it is "web map test" it can probably be deleted.

**Comment by mfunk** [comment]
Closing as this item (https://nsec.esri.com/arcgis/home/item.html?id=a7cfc145dfe44c468c98ca750a4cdd5f) does not exist as of 9/23/2015:

![image](https://cloud.githubusercontent.com/assets/3093182/10047203/d747e3e8-61c1-11e5-8437-1b8fe2ad9c89.png)
